### ISSUE TITLE
Failed to generate bitmap from Font (DEFEDIT-1436)

### ISSUE THREAD

**Issue by britzl** [defold/defold#3902]
Bjrn Ritzl:
{quote}En av Puzzles devs (Tarek Karray) rkar ut fr det hr. Ngon id om vad det kan bero p. Lsningen brukar vara att starta om datorn och sedan se till s att Defold startar frst. Skumt...{quote}

Tarek Karray:
{quote}It doesnt happen every time I launch the editor. But it happens about 2 times a week. If its too much trouble Ill just live with it.{quote}
2018-09-10 11:58:54 (Mats.Gisselson)
We need more info to diagnose the cause. PR with added logging:
(LINK REMOVED)
2018-09-10 12:14:16 (Mats.Gisselson)
Logging has been merged into editor-dev and dev.
2018-09-13 10:47:57 (Mats.Gisselson)
Exception info from the log:
{code}
2018-09-13 07:50:54.332 137648 [clojure-agent-send-off-pool-5] ERROR editor.font - {:line 381, :msg "Failed to generate bitmap from Font. "}
java.lang.NullPointerException: null
	at sun.font.FontDesignMetrics.getDefaultFrc(FontDesignMetrics.java:157)
	at sun.font.FontDesignMetrics.getMetrics(FontDesignMetrics.java:250)
	at java.awt.Component.getFontMetrics(Component.java:3099)
	at editor.pipeline.fontc$font_metrics.invokeStatic(fontc.clj:341)
	at editor.pipeline.fontc$compile_ttf_bitmap.invokeStatic(fontc.clj:377)
	at editor.pipeline.fontc$compile_font.invokeStatic(fontc.clj:582)
	at editor.pipeline.font_gen$generate.invokeStatic(font_gen.clj:16)
	at editor.font$make_font_map.invokeStatic(font.clj:360)
	at editor.font$build_font.invokeStatic(font.clj:395)
	at editor.font$build_font.invoke(font.clj:394)
	at editor.pipeline$build_BANG_$fn__17424.invoke(pipeline.clj:178)
	at clojure.core$map$fn__4785.invoke(core.clj:2646)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.RT.seq(RT.java:521)
	at clojure.core$seq__4357.invokeStatic(core.clj:137)
	at clojure.core$dorun.invokeStatic(core.clj:3024)
	at clojure.core$doall.invokeStatic(core.clj:3039)
	at editor.pipeline$batched_pmap$fn__17417.invoke(pipeline.clj:153)
	at clojure.core$pmap$fn__6970$fn__6971.invoke(core.clj:6736)
	at clojure.core$binding_conveyor_fn$fn__4676.invoke(core.clj:1938)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
{code}

Looks like this JDK bug: (LINK REMOVED)Possibly we can obtain font metrics by some other means and avoid involving {{getDefaultFrc()}} at all?

**Comment by AGulev** [comment]
outdated
no repro
