### ISSUE TITLE
Please clarify the installation instructions for `waf`

### ISSUE THREAD

**Issue by mtnygard** [defold/defold#4797]
**Describe the bug (REQUIRED)**

Build instructions in `README.md` indicate that [waf](waf.io) is required to build. However, it appears that the current release version of `waf`, version 2.0.20 does not properly build the engine.

**To Reproduce (REQUIRED)**
1. Download [waf 2.0.20](https://waf.io/waf-2.0.20), copy the resulting executable into tmp/dynamo_home/ext/bin/waf
2. Clean the repository
3. Run `./scripts/build.py build_engine`
4. Observe the following build error (on Ubuntu 18.04)

```
Building dlib for x86_64-linux
[exec] python /home/mtnygard/work/defold/tmp/dynamo_home/ext/bin/waf --prefix=/home/mtnygard/work/defold/tmp/dynamo_home distclean configure build install --platform=x86_64-linux
Waf: The wscript in '/home/mtnygard/work/defold/engine/dlib' is unreadable
Traceback (most recent call last):
  File "/home/mtnygard/work/defold/tmp/dynamo_home/ext/bin/.waf-2.0.20-36f5354d605298f6a89c09e0c7ef6c1d/waflib/Scripting.py", line 102, in waf_entry_point
    set_main_module(wscript)
  File "/home/mtnygard/work/defold/tmp/dynamo_home/ext/bin/.waf-2.0.20-36f5354d605298f6a89c09e0c7ef6c1d/waflib/Scripting.py", line 142, in set_main_module
    Context.g_module=Context.load_module(file_path)
  File "/home/mtnygard/work/defold/tmp/dynamo_home/ext/bin/.waf-2.0.20-36f5354d605298f6a89c09e0c7ef6c1d/waflib/Context.py", line 362, in load_module
    exec(compile(code,path,'exec'),module.__dict__)
  File "/home/mtnygard/work/defold/engine/dlib/wscript", line 9, in <module>
    import Options
ImportError: No module named Options
None
Traceback (most recent call last):
  File "./scripts/build.py", line 1917, in <module>
    f()
  File "./scripts/build.py", line 889, in build_engine
    self._build_engine_lib(args, lib, host, skip_tests = skip_tests)
  File "./scripts/build.py", line 859, in _build_engine_lib
    run.env_command(self._form_env(), args + plf_args + self.waf_options + skip_build_tests, cwd = cwd)
  File "/home/mtnygard/work/defold/build_tools/run.py", line 63, in env_command
    return _exec_command(args, shell = False, stdout = None, env = env, **kwargs)
  File "/home/mtnygard/work/defold/build_tools/run.py", line 41, in _exec_command
    raise ExecException(process.returncode, output)
run.ExecException
```

**Expected behavior (REQUIRED)**
Expected result is a clean build of the engine

**Defold version (REQUIRED):**
  - Version [e.g. 1.2.155]

**Platforms (REQUIRED):**
 - Platforms: Linux
 - OS: Ubuntu 18.04
 - Device: WSL

**Additional context (OPTIONAL):**
The oldest tag of `waf` in their repo is 1.6.8. I have tried that version of `waf`, resulting in a slightly different error, but again due to a missing module in waf itself:

```
Waf: The wscript in '/home/mtnygard/work/defold/engine/dlib' is unreadable
Traceback (most recent call last):
  File "/home/mtnygard/work/defold/tmp/dynamo_home/ext/bin/.waf-1.6.8-05de7f8cc72bffb80f47dde89119173b/waflib/Scripting.py", line 85, in waf_entry_point
    set_main_module(Context.run_dir+os.sep+Context.WSCRIPT_FILE)
  File "/home/mtnygard/work/defold/tmp/dynamo_home/ext/bin/.waf-1.6.8-05de7f8cc72bffb80f47dde89119173b/waflib/Scripting.py", line 108, in set_main_module
    Context.g_module=Context.load_module(file_path)
  File "/home/mtnygard/work/defold/tmp/dynamo_home/ext/bin/.waf-1.6.8-05de7f8cc72bffb80f47dde89119173b/waflib/extras/compat15.py", line 88, in load_module
    ret=rev(path)
  File "/home/mtnygard/work/defold/tmp/dynamo_home/ext/bin/.waf-1.6.8-05de7f8cc72bffb80f47dde89119173b/waflib/Context.py", line 265, in load_module
    exec(compile(code,path,'exec'),module.__dict__)
  File "/home/mtnygard/work/defold/engine/dlib/wscript", line 11, in <module>
    import waf_dynamo
  File "/home/mtnygard/work/defold/build_tools/waf_dynamo.py", line 5, in <module>
    from TaskGen import extension, taskgen, feature, after, before
ImportError: cannot import name taskgen
None
Traceback (most recent call last):
  File "./scripts/build.py", line 1917, in <module>
    f()
  File "./scripts/build.py", line 889, in build_engine
    self._build_engine_lib(args, lib, host, skip_tests = skip_tests)
  File "./scripts/build.py", line 859, in _build_engine_lib
    run.env_command(self._form_env(), args + plf_args + self.waf_options + skip_build_tests, cwd = cwd)
  File "/home/mtnygard/work/defold/build_tools/run.py", line 63, in env_command
    return _exec_command(args, shell = False, stdout = None, env = env, **kwargs)
  File "/home/mtnygard/work/defold/build_tools/run.py", line 41, in _exec_command
    raise ExecException(process.returncode, output)
run.ExecException
```

**Comment by mtnygard** [comment]
I have also noticed that `scripts/build.py` refers to waf version 1.5.9, but cannot find a download of that version.

**Comment by mtnygard** [comment]
Aha, I now see that I needed to run `./scripts/build.py install_ext --package-path ./packages`

This is mentioned in the page about installing SDKs, so I inferred that it was only necessary to build for iOS or Android.

**Comment by britzl** [comment]
Ah, yes, you should always run install_ext one before building for a platform.

**Comment by britzl** [comment]
I've read the setup instructions again and I find them to be pretty clear:

* https://github.com/defold/defold/blob/dev/README_BUILD.md#install-packages-and-sdks
* https://github.com/defold/defold/blob/dev/editor/README.md#setup

What made you think it was only needed for Android and iOS? How can we clarify that it is needed for all platforms?

**Comment by mtnygard** [comment]
If I may suggest, split the section currently listed as "Install packages and SDKs" into two sections, even though the "Install packages" portion will be short. 

Second, the example command line for install packages shows `https://path.to/packages` which leaves the reader wondering "what is _my_ path to packages?" The example would be clearer if it indicates that the packages are already in the clone of the repo.

**Comment by britzl** [comment]
@mtnygard what's your take on these changes? https://github.com/defold/defold/pull/4809
