### ISSUE TITLE
Cycle detected on node type editor.code.script/ScriptNode

### ISSUE THREAD

**Issue by iovorobiev** [defold/defold#4893]
### Expected behaviour
The game builds successfully
### Actual behaviour
java.lang.AssertionError: Assert failed: Cycle detected on node type editor.code.script/ScriptNode and output :build-targets
(not (contains? (:in-production evaluation-context) [node-id label]))
### Steps to reproduce
I don't have any particular steps. I am trying to build from the editor (ctrl+ b), At some point, I started to get this error, even though I didn't touch anything apart from my lua modules.
I am able to bundle windows application successfully (if I choose bundle instead of build).

I am aware of issue [ #121](https://github.com/defold/editor2-issues/issues/121) but my problem doesn't seem to be related to collections.
<hr/>

<table>
<tr><td>Build time</td><td>2020-06-09T06:32:34.184948</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>77864a400bc9028a176a63308e7a82507577c351</td></tr>
<tr><td>Defold engine sha</td><td>4ebe7a1d548eae2398717ed46f9d7d1b103d5503</td></tr>
<tr><td>Defold version</td><td>1.2.169</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"f067cde7127d4351af857529055af111"'>f067cde7127d4351af857529055af111</a></td></tr>
<tr><td>GPU</td><td>GeForce RTX 2060/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 431.65</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by AGulev** [comment]
It seems like someone in your code you `require` lua file that `require` the first file and you have an infinite loop (it's possible that you have the third file in the middle)

**Comment by iovorobiev** [comment]
@AGulev thanks, it is working now. Is it possible to make this error more informative? The way it asks to create a github issue is a bit misleading towards thinking it is the editor's bug

**Comment by britzl** [comment]
```
internal.node$mark_in_production.invokeStatic.class java.lang.AssertionError: Assert failed: Cycle detected on node type editor.code.script/ScriptNode and output :build-targets
(not (contains? (:in-production evaluation-context) [node-id label]))
    at internal.node$mark_in_production.invokeStatic(node.clj:1320)
    at editor.code.script$ScriptNode$behavior$build_targets.invokeStatic(script.clj:528)
    at editor.code.script$ScriptNode$behavior$build_targets.invoke(script.clj:528)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:283)
    at internal.node$pull_input_values$fn.invoke(node.clj:1160)
    at clojure.core$mapv$fn.invoke(core.clj:6912)
    at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
    at clojure.core$reduce.invokeStatic(core.clj:6827)
    at clojure.core$mapv.invokeStatic(core.clj:6903)
    at internal.node$pull_input_values.invokeStatic(node.clj:1161)
    at editor.code.script$ScriptNode$behavior$build_targets$fn.invoke(script.clj:528)
    at internal.node$trace_expr$fn.invoke(node.clj:35)
    at internal.node$trace_expr.invokeStatic(node.clj:35)
    at editor.code.script$ScriptNode$behavior$build_targets.invokeStatic(script.clj:528)
    at editor.code.script$ScriptNode$behavior$build_targets.invoke(script.clj:528)
```

**Comment by britzl** [comment]
Closed via https://github.com/defold/defold/pull/7262
