### ISSUE TITLE
game.project, game.input_binding etc. all are blank in the editor

### ISSUE THREAD

**Issue by Lynext** [defold/defold#4898]
**Describe the bug (REQUIRED)**
game.project, game.input_binding etc. all are just blank.

**To Reproduce (REQUIRED)**
1. Set your Windows language to Turkish
2. Open any Defold project
3. Open game.project
4. It should be blank now. Check the logs for the exception.

**Expected behavior (REQUIRED)**
To see project settings etc.

**Defold version (REQUIRED):**
  - Version 1.2.169

**Platforms (REQUIRED):**
 - Platforms: Any
 - OS: Windows 10
 - Device: Personal Computer

**Minimal repro case project (OPTIONAL):**
You can try it on the example project "Side scroller tutorial"

**Logs (OPTIONAL):**
java.lang.IllegalArgumentException: No matching field found: getİtems for class javafx.scene.control.MenuButton
	at clojure.lang.Reflector.getInstanceField(Reflector.java:397)
	at clojure.lang.Reflector.invokeNoArgInstanceMember(Reflector.java:440)
	at cljfx.fx.menu_button$get_items__1975.invokeStatic(menu_button.clj:16)
	at cljfx.fx.menu_button$get_items__1975.invoke(menu_button.clj:16)
	at cljfx.mutator$observable_list$set_all_BANG___28953.invoke(mutator.clj:61)
	at cljfx.mutator$observable_list$fn__28955.invoke(mutator.clj:66)
	at cljfx.mutator$fn__28902$G__28849__28913.invoke(mutator.clj:13)
	at cljfx.prop$assign_BANG_.invokeStatic(prop.clj:36)
	at cljfx.composite$create_composite_component.invokeStatic(composite.clj:38)
	at cljfx.composite$create_composite_component.invoke(composite.clj:25)
	at cljfx.lifecycle$fn__29176$G__29146__29185.invoke(lifecycle.clj:17)
	at cljfx.lifecycle$create_dynamic_component.invokeStatic(lifecycle.clj:32)
	at cljfx.lifecycle$reify__29221.create(lifecycle.clj:36)
	at cljfx.lifecycle$wrap_dynamic_fn$fn__29235.invoke(lifecycle.clj:76)
	at cljfx.lifecycle$fn__29176$G__29146__29185.invoke(lifecycle.clj:17)
	at cljfx.lifecycle$create_dynamic_component.invokeStatic(lifecycle.clj:32)
	at cljfx.lifecycle$reify__29221.create(lifecycle.clj:36)
	at cljfx.lifecycle$wrap_extra_props$fn__29355.invoke(lifecycle.clj:348)
	at cljfx.lifecycle$fn__29176$G__29146__29185.invoke(lifecycle.clj:17)
	at cljfx.lifecycle$wrap_many$fn__29311$fn__29315$fn__29316.invoke(lifecycle.clj:279)
	at clojure.core$update.invokeStatic(core.clj:6196)
	at cljfx.lifecycle$wrap_many$fn__29311$fn__29315.invoke(lifecycle.clj:278)
	at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
	at clojure.core$reduce.invokeStatic(core.clj:6827)
	at cljfx.lifecycle$wrap_many$fn__29311.invoke(lifecycle.clj:277)
	at cljfx.lifecycle$fn__29176$G__29146__29185.invoke(lifecycle.clj:17)
	at cljfx.composite$create_props$fn__29588.invoke(composite.clj:21)
	at clojure.lang.PersistentArrayMap.kvreduce(PersistentArrayMap.java:377)
	at clojure.core$fn__8422.invokeStatic(core.clj:6845)
	at clojure.core$fn__8422.invoke(core.clj:6830)
	at clojure.core.protocols$fn__8152$G__8147__8161.invoke(protocols.clj:175)
	at clojure.core$reduce_kv.invokeStatic(core.clj:6856)
	at cljfx.composite$create_props.invokeStatic(composite.clj:15)
	at cljfx.composite$create_composite_component.invokeStatic(composite.clj:27)
	at cljfx.composite$create_composite_component.invoke(composite.clj:25)
	at cljfx.lifecycle$fn__29176$G__29146__29185.invoke(lifecycle.clj:17)
	at cljfx.lifecycle$create_dynamic_component.invokeStatic(lifecycle.clj:32)
	at cljfx.lifecycle$reify__29221.create(lifecycle.clj:36)
	at cljfx.lifecycle$wrap_extra_props$fn__29355.invoke(lifecycle.clj:348)
	at cljfx.lifecycle$fn__29176$G__29146__29185.invoke(lifecycle.clj:17)
	at cljfx.lifecycle$wrap_many$fn__29311$fn__29315$fn__29316.invoke(lifecycle.clj:279)
	at clojure.core$update.invokeStatic(core.clj:6196)
	at cljfx.lifecycle$wrap_many$fn__29311$fn__29315.invoke(lifecycle.clj:278)
	at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
	at clojure.core$reduce.invokeStatic(core.clj:6827)
	at cljfx.lifecycle$wrap_many$fn__29311.invoke(lifecycle.clj:277)
	at cljfx.lifecycle$fn__29176$G__29146__29185.invoke(lifecycle.clj:17)
	at cljfx.lifecycle$props_on$reify__29402$fn__29403.invoke(lifecycle.clj:393)
	at clojure.lang.PersistentArrayMap.kvreduce(PersistentArrayMap.java:377)
	at clojure.core$fn__8422.invokeStatic(core.clj:6845)
	at clojure.core$fn__8422.invoke(core.clj:6830)
	at clojure.core.protocols$fn__8152$G__8147__8161.invoke(protocols.clj:175)
	at clojure.core$reduce_kv.invokeStatic(core.clj:6856)
	at cljfx.lifecycle$props_on$reify__29402.create(lifecycle.clj:388)
	at cljfx.lifecycle$make_ext_with_props$reify__29423.create(lifecycle.clj:412)
	at cljfx.lifecycle$create_dynamic_component.invokeStatic(lifecycle.clj:32)
	at cljfx.lifecycle$reify__29221.create(lifecycle.clj:36)
	at cljfx.lifecycle$wrap_dynamic_fn$fn__29235.invoke(lifecycle.clj:76)
	at cljfx.lifecycle$fn__29176$G__29146__29185.invoke(lifecycle.clj:17)
	at cljfx.lifecycle$create_dynamic_component.invokeStatic(lifecycle.clj:32)
	at cljfx.lifecycle$reify__29221.create(lifecycle.clj:36)
	at cljfx.lifecycle$fn__29225.invokeStatic(lifecycle.clj:58)
	at cljfx.lifecycle$fn__29225.invoke(lifecycle.clj:56)
	at cljfx.lifecycle$fn__29176$G__29146__29185.invoke(lifecycle.clj:17)
	at cljfx.lifecycle$wrap_map_desc$fn__29439.invoke(lifecycle.clj:446)
	at cljfx.lifecycle$fn__29176$G__29146__29185.invoke(lifecycle.clj:17)
	at editor.fxui$wrap_dedupe_desc$reify__30806.create(fxui.clj:173)
	at cljfx.renderer$render_component.invokeStatic(renderer.clj:57)
	at cljfx.renderer$create$fn__30667.invoke(renderer.clj:75)
	at cljfx.renderer$perform_render$fn__30618.invoke(renderer.clj:23)
	at cljfx.renderer$perform_render.invokeStatic(renderer.clj:22)
	at cljfx.renderer$request_render$fn__30644$fn__30648.invoke(renderer.clj:44)
	at cljfx.renderer$request_render$fn__30644.invoke(renderer.clj:44)
	at clojure.lang.AFn.run(AFn.java:22)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at com.sun.glass.ui.win.WinApplication._enterNestedEventLoopImpl(Native Method)
	at com.sun.glass.ui.win.WinApplication._enterNestedEventLoop(WinApplication.java:201)
	at com.sun.glass.ui.Application.enterNestedEventLoop(Application.java:509)
	at com.sun.glass.ui.EventLoop.enter(EventLoop.java:107)
	at com.sun.javafx.tk.quantum.QuantumToolkit.enterNestedEventLoop(QuantumToolkit.java:635)
	at javafx.application.Platform.enterNestedEventLoop(Platform.java:291)
	at editor.fxui$mount_renderer_and_await_result_BANG_.invokeStatic(fxui.clj:216)
	at editor.fxui$show_dialog_and_await_result_BANG_.invokeStatic(fxui.clj:221)
	at editor.dialogs$make_unexpected_error_dialog.invokeStatic(dialogs.clj:361)
	at editor.boot$notify_user$fn__89773.invoke(boot.clj:68)
	at editor.ui$do_run_now$fn__12592.invoke(ui.clj:308)
	at clojure.lang.AFn.run(AFn.java:22)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Workaround (OPTIONAL):**
I couldn't find any. Maybe it will work if you change your Windows' language.

**Screenshots (OPTIONAL):**
https://i.imgur.com/6S7NXcR.png

**Additional context (OPTIONAL):**
My windows is in Turkish language and when I looked at the logs I saw

"java.lang.IllegalArgumentException: No matching field found: getİtems for class javafx.scene.control.MenuButton"

In my language, capital i is not I but İ. I think that the "getItems" function is somehow called like getİtems, so the error occurs.

**Comment by matgis-king** [comment]
A fix has been merged and should reach you shortly.
