### ISSUE TITLE
Windows firewall causes occasional timeout

### ISSUE THREAD

**Issue by sunbeam60** [defold/defold#4928]
### Expected behaviour
* Build project
* Run project

### Actual behaviour
* Build project
* Project starts
* Windows firewall dialog appears
* Game crashes

### Steps to reproduce
* Build a new project
* Await new executable project
* Windows firewall opens to ask for permissions for private and public networks
* Built executable crashes/times out, presumably awaiting approval from the Windows firewall dialog.

<hr/>

<table>
<tr><td>Build time</td><td>2020-06-17T10:06:38.299614</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>e5389d28eab7bfdc5b8edccad637aadcd2832a29</td></tr>
<tr><td>Defold engine sha</td><td>4ebe7a1d548eae2398717ed46f9d7d1b103d5503</td></tr>
<tr><td>Defold version</td><td>1.2.169</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"a4eaf40ce7cb4d038d934b239c4fd9cb"'>a4eaf40ce7cb4d038d934b239c4fd9cb</a></td></tr>
<tr><td>GPU</td><td>Intel(R) UHD Graphics 620</td></tr>
<tr><td>GPU Driver</td><td>4.5.0 - Build 26.20.100.7637</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by JCash** [comment]
The engine should produce a `_crash.dmp` file that I'd like to see.
Also, are you using the vanilla engine, or are you using native extensions?

**Comment by sunbeam60** [comment]
No native extensions, it's a super simple test project. 

Where do I find the _crash.dmp file? I've had a look around, but it doesn't seem to be in the obvious locations and doing a full disk search for *_crash.dmp reveals nothing.

Perhaps I should be clearer ... the newly built exe starts up, but doesn't refresh (hangs) and the editor shows a time-out message. 

![image](https://user-images.githubusercontent.com/17337714/85026453-9b689f80-b170-11ea-99bf-50389efff47c.png)

Then when I close the hung exe, Windows error reporting (you know the one; the most useless crash reporting tool in the world) kicks in.

**Comment by ttblue1972** [comment]
I get the same issue.. reported here.
https://forum.defold.com/t/java-net-sockettimeoutexception-connect-timed-out/65461
I click Dismiss and then press F5.. usually after about 4-5 attempts it will run.

The game window does open but is white and windows says it is not responding.

I have a tower PC and two laptops that I have tried Defold on all the same error. All run Windows.
Attached is a new log file with timeout message.

[editor2.2020-06-26.log](https://github.com/defold/defold/files/4835517/editor2.2020-06-26.log)

**Comment by JCash** [comment]
Note, from the editor2 log from @ttblue1972 :

```
java.net.SocketTimeoutException: connect timed out
	at java.base/java.net.PlainSocketImpl.waitForConnect(Native Method)
	at java.base/java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:107)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
	at java.base/java.net.Socket.connect(Socket.java:591)
	at editor.debugging.mobdebug$try_connect_BANG_.invokeStatic(mobdebug.clj:328)
	at editor.debugging.mobdebug$connect_BANG_$fn__43028.invoke(mobdebug.clj:333)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

Which is a duplicate of #5471

**Comment by JCash** [comment]
> respond quickly enough to the debugger attaching.

@sunbeam60 Do you start the project with or without the debugger? (debugger isn't mentioned in the repro steps).

**Comment by sunbeam60** [comment]
This was with debugger attaching - apologies that the repro steps weren’t clear. 

I don’t have current access to the machine this happens on (Surface Pro 5) as it was left in the office at start of pandemic, so will be hard to verify a possible fix. It doesn’t happen on my much more powerful home computer.

**Comment by AGulev** [comment]
## Issue summary

The report says that on Windows, starting a freshly built project with the debugger could hang while Windows Firewall showed its permission dialog. The editor then timed out trying to attach to the game, sometimes more often on slower machines or under high CPU load.

## Status

Possibly outdated/fixed

## Evidence

- In the issue comments, a maintainer identified `#4928` as a duplicate of [#5471](https://github.com/defold/defold/issues/5471), which is closed.
- Current debugger connection code in `editor/src/clj/editor/debugging/mobdebug.clj:151` retries connection up to 50 times with `Thread/sleep 200`, giving roughly 10 seconds total retry time instead of the older 2 second window.
- Current `try-connect!` in `editor/src/clj/editor/debugging/mobdebug.clj:144` catches `java.lang.Exception`, not only `ConnectException`, which matches the historical `SocketTimeoutException` symptom discussed in the issue thread.
- Git history shows two relevant fixes landed after the report: `2242344ee7` (`DEFEDIT-5471: Debug connection fix`) and `5db88a9bad` (`Increase debugger connect timeout from 2 to 10 seconds (#6031)`).
- The editor now routes debugger connection failures through an explicit error handler in `editor/src/clj/editor/debug_view.clj:507`, instead of relying on the older behavior seen in the 2020-2021 reports.

## Why I think it is possibly already fixed

The original report lines up closely with the later `SocketTimeoutException` debugger-attach issue that Defold tracked separately as `#5471`. The repo contains the follow-up fix for that duplicate and then an additional timeout increase from about 2 seconds to about 10 seconds, which directly addresses the "slow machine / temporary stall while attaching" failure mode described in the comments.

I do not see current code or tests proving the exact Windows Firewall dialog scenario end-to-end, and the GitHub issue itself is still open. But based on the duplicate link, the closed follow-up issue, and the concrete debugger connection changes now present in `mobdebug.clj`, this looks more like an outdated report than an actively unfixed bug.
