### ISSUE TITLE
Error opening main.collection

### ISSUE THREAD

**Issue by aitorCerecetoGlovoApp** [defold/defold#4958]
### Expected behaviour
Open main.collection
### Actual behaviour
Error 
### Steps to reproduce
- Open Project
- Open main.collection
<hr/>

<table>
<tr><td>Build time</td><td>2020-06-22T13:03:26.602841</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>c907611b80aaec1c2bd1f4490699c0be3b250f87</td></tr>
<tr><td>Defold engine sha</td><td>5791ee6d96b87e50eee5acd70abaa4026fefef28</td></tr>
<tr><td>Defold version</td><td>1.2.170</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"f681b3a9633c40feb5aefee7aeda1477"'>f681b3a9633c40feb5aefee7aeda1477</a></td></tr>
<tr><td>GPU</td><td>Mesa Intel(R) UHD Graphics 620 (WHL GT2)</td></tr>
<tr><td>GPU Driver</td><td>OpenGL ES-CM 1.1 Mesa 20.0.4</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>5.4.0-7634-generic</td></tr>
<table>

**Comment by britzl** [comment]
class jogamp.opengl.es1.GLES1Impl cannot be cast to class com.jogamp.opengl.GL2ES2

**Comment by britzl** [comment]
Please try: https://defold.com/manuals/linux/#q-why-does-the-defold-editor-crash-when-i-try-to-create-a-new-project-or-open-an-existing-one

**Comment by aitorCerecetoGlovoApp** [comment]
Same for both options when using export:
`  java.lang.ClassCastException: class jogamp.opengl.es1.GLES1Impl cannot be cast to class com.jogamp.opengl.GL2ES2 (jogamp.opengl.es1.GLES1Impl and com.jogamp.opengl.GL2ES2 are in unnamed module of loader 'app') `

**Comment by britzl** [comment]
> Max GLES[23] profile version: 3.2

What if you try:

```
$ export MESA_GL_VERSION_OVERRIDE=3.2
$ ./Defold
```

**Comment by aitorCerecetoGlovoApp** [comment]
Same as before.
This happens when trying to access `main.collection` 
Here's the stacktrace
```
2020-07-21 15:29:07.936 ERROR default    editor.error-reporting - {:line 110}
java.lang.ClassCastException: class jogamp.opengl.es1.GLES1Impl cannot be cast to class com.jogamp.opengl.GL2ES2 (jogamp.opengl.es1.GLES1Impl and com.jogamp.opengl.GL2ES2 are in unnamed module of loader 'app')
	at editor.gl$gl_clear.invokeStatic(gl.clj:191)
	at editor.scene$render_BANG_.invokeStatic(scene.clj:273)
	at editor.scene$update_image_view_BANG_$fn__41751.invoke(scene.clj:1158)
	at editor.scene$update_image_view_BANG_.invokeStatic(scene.clj:1155)
	at editor.scene$update_image_view_BANG_.invoke(scene.clj:1127)
	at editor.scene$refresh_scene_view_BANG_.invokeStatic(scene.clj:842)
	at editor.app_view$refresh_scene_views_BANG_$fn__46922.invoke(app_view.clj:1366)
	at editor.app_view$refresh_scene_views_BANG_.invokeStatic(app_view.clj:1366)
	at editor.app_view$open_resource$fn__46987.invoke(app_view.clj:1576)
	at clojure.lang.AFn.run(AFn.java:22)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
	at java.base/java.lang.Thread.run(Thread.java:834)

```

**Comment by aitorCerecetoGlovoApp** [comment]
Weird, using 2.1 fixed it.

This can be closed, many thanks!

**Comment by britzl** [comment]
Good to hear that it is working now! I thought you had tried that already!
