### ISSUE TITLE
Error on Building Side scroller tutorial 

### ISSUE THREAD

**Issue by LaurentOngaro** [defold/defold#5025]
### Expected behaviour

Run the project

### Actual behaviour
Following Error when clicking on the "build and run" link of the readme.md file of the tutorial

```
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: Could not initialize class com.dynamo.bob.TexcLibrary
java.lang.NoClassDefFoundError: Could not initialize class com.dynamo.bob.TexcLibrary
```

### Steps to reproduce
Create a new projet from tutorial 
select Side scroller tutorial (First one)
clic on the "build and run" link of the readme.md

<hr/>

Defold has been manually installed on arch linux and the editor can be launched

<table>
<tr><td>Build time</td><td>2020-07-14T14:36:37.691977</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>3061bed6e880b423d87a33bcf55d6e920c3afa74</td></tr>
<tr><td>Defold engine sha</td><td>5791ee6d96b87e50eee5acd70abaa4026fefef28</td></tr>
<tr><td>Defold version</td><td>1.2.170</td></tr>
<tr><td>GPU</td><td>Radeon RX 580 Series (POLARIS10, DRM 3.37.0, 5.7.7-arch1-1, LLVM 10.0.0)</td></tr>
<tr><td>GPU Driver</td><td>4.6 (Compatibility Profile) Mesa 20.1.3</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>5.7.7-arch1-1</td></tr>
<table>

**Comment by britzl** [comment]
What happens if you instead try Project->Bundle->Linux? Does it produce an application bundle?

**Comment by LaurentOngaro** [comment]
no it fails, with the following build error (in french):
`/background/background.atlas
	/tmp/9539441454142763517/x86_64-linux/libPVRTexLib.so: /tmp/9539441454142763517/x86_64-linux/libPVRTexLib.so: échec d'adressage (mapping) du segment de l'objet partagé`

**Comment by britzl** [comment]
Could you share the most recent editor log file? Help->Show Log

**Comment by LaurentOngaro** [comment]
this is the full log content when building with error (cleaned just before build)
`2020-07-19 13:36:40.682 120491 [clojure-agent-send-off-pool-22] ERROR editor.error-reporting - {:line 110}
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: Could not initialize class com.dynamo.bob.TexcLibrary
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at clojure.core$deref_future.invokeStatic(core.clj:2300)
	at clojure.core$future_call$reify__8439.deref(core.clj:6974)
	at clojure.core$deref.invokeStatic(core.clj:2320)
	at clojure.core$deref.invoke(core.clj:2306)
	at clojure.core$map$fn__5851.invoke(core.clj:2755)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:58)
	at clojure.lang.RT.seq(RT.java:531)
	at clojure.core$seq__5387.invokeStatic(core.clj:137)
	at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:24)
	at clojure.core.protocols$fn__8131.invokeStatic(protocols.clj:75)
	at clojure.core.protocols$fn__8131.invoke(protocols.clj:75)
	at clojure.core.protocols$fn__8073$G__8068__8086.invoke(protocols.clj:13)
	at clojure.core$reduce.invokeStatic(core.clj:6824)
	at editor.pipeline$batched_pmap.invokeStatic(pipeline.clj:172)
	at editor.pipeline$build_BANG_.invokeStatic(pipeline.clj:187)
	at editor.build$build_project_BANG_.invokeStatic(build.clj:66)
	at editor.app_view$build_project_BANG_.invokeStatic(app_view.clj:742)
	at editor.app_view$async_build_BANG_$fn__45774$fn__45778.invoke(app_view.clj:761)
	at editor.app_view$async_build_BANG_$fn__45774.invoke(app_view.clj:761)
	at clojure.core$binding_conveyor_fn$fn__5739.invoke(core.clj:2030)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.dynamo.bob.TexcLibrary
	at editor.texture.engine$webp_compress_rgba_buffer.invokeStatic(engine.clj:151)
	at editor.pipeline.font_gen$compress$fn__58568.invoke(font_gen.clj:65)
	at clojure.core$map$fn__5851.invoke(core.clj:2755)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.Cons.next(Cons.java:39)
	at clojure.lang.RT.next(RT.java:709)
	at clojure.core$next__5371.invokeStatic(core.clj:64)
	at clojure.core.protocols$fn__8144.invokeStatic(protocols.clj:169)
	at clojure.core.protocols$fn__8144.invoke(protocols.clj:124)
	at clojure.core.protocols$fn__8099$G__8094__8108.invoke(protocols.clj:19)
	at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:31)
	at clojure.core.protocols$fn__8131.invokeStatic(protocols.clj:75)
	at clojure.core.protocols$fn__8131.invoke(protocols.clj:75)
	at clojure.core.protocols$fn__8073$G__8068__8086.invoke(protocols.clj:13)
	at clojure.core$transduce.invokeStatic(core.clj:6884)
	at clojure.core$transduce.invokeStatic(core.clj:6879)
	at editor.pipeline.font_gen$concat_byte_buffers.invokeStatic(font_gen.clj:38)
	at editor.pipeline.font_gen$compress.invokeStatic(font_gen.clj:57)
	at editor.font$build_font.invokeStatic(font.clj:486)
	at editor.font$build_font.invoke(font.clj:482)
	at editor.pipeline$build_BANG_$fn__17035.invoke(pipeline.clj:201)
	at clojure.core$map$fn__5851.invoke(core.clj:2755)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.RT.seq(RT.java:531)
	at clojure.core$seq__5387.invokeStatic(core.clj:137)
	at clojure.core$dorun.invokeStatic(core.clj:3133)
	at clojure.core$doall.invokeStatic(core.clj:3148)
	at editor.pipeline$batched_pmap$fn__17028.invoke(pipeline.clj:174)
	at clojure.core$pmap$fn__8447$fn__8448.invoke(core.clj:7022)
	... 6 common frames omitted
2020-07-19 13:36:45.040 124849 [Timer-1] INFO  editor.updater - {:line 295, :message "Checking for updates", :url "https://d.defold.com/editor2/channels/editor-alpha/update-v3.json"}
2020-07-19 13:36:45.397 125206 [Timer-1] INFO  editor.updater - {:line 302, :message "No update found"}
`

**Comment by britzl** [comment]
This FAQ entry should solve the problem: https://defold.com/manuals/linux/#q-the-defold-editor-crashes-when-opening-a-collection-or-game-object-and-the-crash-refers-to-libffiso
