### ISSUE TITLE
Bob remote builds should show build errors and warnings.

### ISSUE THREAD

**Issue by JCash** [defold/defold#5046]
For some reason, bob's error reporting has regressed, and doesn't show the build errors/warnings, just another exception thrown:

```
Exception in thread “main” com.dynamo.bob.CompileExceptionError: contextResource cannot be null.
at com.dynamo.bob.Project.build(Project.java:466)
at com.dynamo.bob.Bob.main(Bob.java:593)
Caused by: java.lang.IllegalArgumentException: contextResource cannot be null.
at com.dynamo.bob.MultipleCompileException.attachLog(MultipleCompileException.java:88)
at com.dynamo.bob.bundle.BundleHelper.buildEngineRemote(BundleHelper.java:1165)
at com.dynamo.bob.Project.buildEngine(Project.java:730)
at com.dynamo.bob.Project.doBuild(Project.java:851)
at com.dynamo.bob.Project.build(Project.java:456)
```

**Comment by AGulev** [comment]
I think this issue is outdated
