### ISSUE TITLE
Editor crash

### ISSUE THREAD

**Issue by viniciushedler** [defold/defold#5053]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2020-07-20T08:44:23.592964</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>a98007b48691529b59fb099fc369d81518059d00</td></tr>
<tr><td>Defold engine sha</td><td>29b8e598b0bce19b274327c5d9711f78b3bd0c22</td></tr>
<tr><td>Defold version</td><td>1.2.171</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"f71f713ee429415797367d72edc9e3d5"'>f71f713ee429415797367d72edc9e3d5</a></td></tr>
<tr><td>GPU</td><td>Intel(R) HD Graphics 620</td></tr>
<tr><td>GPU Driver</td><td>4.5.0 - Build 24.20.100.6286</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by britzl** [comment]
```
editor.resource_watch$make_directory_snapshot.invokeStatic.class java.lang.AssertionError: Assert failed: (and root (.isDirectory root))
    at editor.resource_watch$make_directory_snapshot.invokeStatic(resource_watch.clj:120)
    at editor.resource_watch$make_snapshot_info.invokeStatic(resource_watch.clj:163)
    at editor.workspace$make_snapshot_info.invokeStatic(workspace.clj:226)
    at editor.disk$start_reload_job_BANG_$fn.invoke(disk.clj:66)
    at clojure.core$binding_conveyor_fn$fn.invoke(core.clj:2030)
    at clojure.lang.AFn.call(AFn.java:18)
    at java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.lang.Thread.run(Thread.java:834)
```

**Comment by britzl** [comment]
https://github.com/defold/defold/blob/editor-dev/editor/src/clj/editor/resource_watch.clj#L132

**Comment by britzl** [comment]
@viniciushedler do you know what you did when the error occurred?

**Comment by AGulev** [comment]
user didn't provide more info
