### ISSUE TITLE
Spine scene makes other errors not print in editor when bundling / spine scene works when engine is ran from editor but will not bundle without error

### ISSUE THREAD

**Issue by subsoap** [defold/defold#5114]
### Expected behaviour
Windows bundling from the editor works

### Actual behaviour
Errors with: java.lang.NullPointerException: Unknown

Happens on 2 unique computers with the same project

Only error in error log:

2020-08-19 18:53:22.570 244051 [JavaFX Application Thread] ERROR editor.error-reporting - {:line 110}
java.lang.NullPointerException: null
	at com.dynamo.bob.util.SpineSceneUtil.loadSkin(SpineSceneUtil.java:748)
	at com.dynamo.bob.util.SpineSceneUtil.loadJson(SpineSceneUtil.java:905)
	at com.dynamo.bob.pipeline.GuiBuilder.transformScene(GuiBuilder.java:582)
	at com.dynamo.bob.pipeline.GuiBuilder.transform(GuiBuilder.java:686)
	at com.dynamo.bob.pipeline.GuiBuilder.transform(GuiBuilder.java:58)
	at com.dynamo.bob.ProtoBuilder.build(ProtoBuilder.java:55)
	at com.dynamo.bob.Project.runTasks(Project.java:1019)
	at com.dynamo.bob.Project.doBuild(Project.java:820)
	at com.dynamo.bob.Project.build(Project.java:455)
	at editor.pipeline.bob$run_commands_BANG_$fn__37229.invoke(bob.clj:99)
	at editor.pipeline.bob$run_commands_BANG_.invokeStatic(bob.clj:98)
	at editor.pipeline.bob$bob_build_BANG_.invokeStatic(bob.clj:140)
	at editor.disk$async_bob_build_BANG_$fn__38252$fn__38255$fn__38256.invoke(disk.clj:217)
	at clojure.core$binding_conveyor_fn$fn__5739.invoke(core.clj:2030)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

![err](https://user-images.githubusercontent.com/409170/90707863-5d115e80-e24d-11ea-95cb-a432fa2db72c.png)

### Steps to reproduce
Project -> Bundle -> Windows Application

It happens with our dev project, but not empty projects

<hr/>

<table>
<tr><td>Build time</td><td>2020-08-19T08:50:25.937762</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>4b6b1d22762865cf848564903cce9b80f761807a</td></tr>
<tr><td>Defold engine sha</td><td>dedf1ed10d96c92df6e361f5494531c79af4c1cf</td></tr>
<tr><td>Defold version</td><td>1.2.172</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"dcb29093209f48f5921880d5ee3efa15"'>dcb29093209f48f5921880d5ee3efa15</a></td></tr>
<tr><td>GPU</td><td>GeForce GTX 1060 6GB/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 446.14</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by subsoap** [comment]
Building project with bob directly gives the actual error it seems, I'll try fixing the file it's complaining about.

```
[Building x86_64-win32]
 1% 2% 3% 4% 5% 6% 7% 8% 9% 10% 11% 12% 13% 14% 15% 16% 17% 18% 19% 20% 21% 22% 23% 24% 25% 26% 27%java.lang.NullPointerException
        at com.dynamo.bob.util.SpineSceneUtil.loadSkin(SpineSceneUtil.java:748)
        at com.dynamo.bob.util.SpineSceneUtil.loadJson(SpineSceneUtil.java:905)
        at com.dynamo.bob.pipeline.GuiBuilder.transformScene(GuiBuilder.java:582)
        at com.dynamo.bob.pipeline.GuiBuilder.transform(GuiBuilder.java:686)
        at com.dynamo.bob.pipeline.GuiBuilder.transform(GuiBuilder.java:58)
        at com.dynamo.bob.ProtoBuilder.build(ProtoBuilder.java:55)
        at com.dynamo.bob.Project.runTasks(Project.java:1019)
        at com.dynamo.bob.Project.doBuild(Project.java:820)
        at com.dynamo.bob.Project.build(Project.java:455)
        at com.dynamo.bob.Bob.main(Bob.java:590)
 100%
The build failed for the following reasons:
ERROR screens/stage/code/actor.lua:26 'end' expected (to close 'function' at line 19) near '<eof>'

ERROR screens/stage/code/test_scene.gui:0 null
```

**Comment by subsoap** [comment]
Sample of the bad file actor.lua it wasn't reference anywhere in the project so probably never got cause by normal error checkers

```
local M = {}

M.actors = {}


-- Adds an actor by name to the actors table
-- Leave is_spine nil if not spine
-- Leave default_animation nil if no animation is eto be set
function M.define(name, is_spine, default_animation)
	local actor = {}
	actor.name = name
	actor.is_spine = is_spine or false
	actor.default_animation = default_animation or "idle"
	actor.node = gui.get_node(name)
	M.actors[name] = actor
end

-- Set dim between 0 and 1 to shade an actor with black color
function M.set_dim()

-- Actor is a helper module for Stage, it is meant to handle the scripting of Spine animations mostly.



return M
```

**Comment by subsoap** [comment]
It's still not bundling in bob or editor yet, there is still this error which I don't understand

```
[Building x86_64-win32]
 1% 2% 3% 4% 5% 6% 7% 8% 9% 10% 11% 12% 13% 14% 15% 16% 17% 18% 19% 20% 21% 22% 23% 24% 25% 26% 27%java.lang.NullPointerException
        at com.dynamo.bob.util.SpineSceneUtil.loadSkin(SpineSceneUtil.java:748)
        at com.dynamo.bob.util.SpineSceneUtil.loadJson(SpineSceneUtil.java:905)
        at com.dynamo.bob.pipeline.GuiBuilder.transformScene(GuiBuilder.java:582)
        at com.dynamo.bob.pipeline.GuiBuilder.transform(GuiBuilder.java:686)
        at com.dynamo.bob.pipeline.GuiBuilder.transform(GuiBuilder.java:58)
        at com.dynamo.bob.ProtoBuilder.build(ProtoBuilder.java:55)
        at com.dynamo.bob.Project.runTasks(Project.java:1019)
        at com.dynamo.bob.Project.doBuild(Project.java:820)
        at com.dynamo.bob.Project.build(Project.java:455)
        at com.dynamo.bob.Bob.main(Bob.java:590)
 100%
The build failed for the following reasons:
ERROR screens/stage/code/test_scene.gui:0 null
```

**Comment by subsoap** [comment]
Seems to be related to this, spine scene was using sprite swapping https://forum.defold.com/t/build-error-related-to-spine-models/64524/16

**Comment by subsoap** [comment]
Bundling works again after I completely purged the spine scene with sprite swapping from our project. It's odd that it works when running the engine from the editor but not bundling.

**Comment by subsoap** [comment]
[SpineModuleBundleError.zip](https://github.com/defold/defold/files/5101328/SpineModuleBundleError.zip)

Bundle with bob to see error messages that do not show up in the editor

There is a unique error for the bad module (missing an end) and the spine scene with sprite swapping feature used (with the "eyes" blinking). Note that running the project from the editor works fine.

Also I just tested and the module does get a real error in the editor when the included spine files are deleted so it's not a problem, but the spine issue does cause other errors to not properly appear in the editor.

``` 
/actor.lua
	Line 27: 'end' expected (to close 'function' at line 19) near '<eof>'
```

**Comment by ixiadev** [comment]
Posting the sample from my duplicated issue in case it gives any extra info. Minimal sample project ([Sample.zip](https://github.com/defold/defold/files/5114851/Sample.zip)) with a spinescene:

- Try `Build HTML5` & `Bundle` (I tried HTML5, Android & Mac),  the error mentioned above should occur.
- Try `Build`, it should work and if you display the spinescene it would show up without any issue.
- Delete `monster01/monster.spinescene`, now `Build HTML5` & `Bundle` work.
- Restore `monster01/monster.spinescene`, the error would occur again.

**Comment by AGulev** [comment]
new spine plugin released
