### ISSUE TITLE
Script with property values are lost changes when using an external editor.

### ISSUE THREAD

**Issue by Dragosha** [defold/defold#5237]
When a script component contained go.property() and  selected at editor's outline panel, and we changed something at this script in the external editor then Defold throws an internal error. After that Defold will ignoring changes in a script.
See screencast for details:
https://yadi.sk/d/fwYKcjzIwyDswQ

Perhaps, an issue depends with: https://github.com/defold/defold/issues/5205
<hr/>

<table>
<tr><td>Build time</td><td>2020-08-27T04:44:14.453565</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>96c820fb9fb9c3d6ddec975e5e1dde4762b0228d</td></tr>
<tr><td>Defold engine sha</td><td>dedf1ed10d96c92df6e361f5494531c79af4c1cf</td></tr>
<tr><td>Defold version</td><td>1.2.172</td></tr>
<tr><td>GPU</td><td>GeForce GTX 1060 6GB/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 456.38</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by Dragosha** [comment]
An issue still available in 1.2.184.
After editing a script file contained `go.property` in external editor (VS Code) Defold editor throws an error:
`clojure.lang.ExceptionInfo: Duplicate node key "name" from :editor.code.script/ScriptPropertyNode`
Only restarting a project fix that :(

**Comment by Dragosha** [comment]
ExceptionInfo:

`2021-07-20 16:53:30.484 101677376 [JavaFX Application Thread] ERROR editor.error-reporting - {:line 110}
clojure.lang.ExceptionInfo: Duplicate node key `name` from :editor.code.script/ScriptPropertyNode
	at dynamo.graph$collect_overridden_properties$fn__7290.invoke(graph.clj:1262)
	at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
	at clojure.core$reduce.invokeStatic(core.clj:6827)
	at dynamo.graph$collect_overridden_properties.invokeStatic(graph.clj:1276)
	at editor.defold_project$perform_resource_change_plan$fn__17497.invoke(defold_project.clj:439)
	at clojure.core$map$fn__5847$fn__5848.invoke(core.clj:2742)
	at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
	at clojure.core$transduce.invokeStatic(core.clj:6883)
	at clojure.core$into.invokeStatic(core.clj:6899)
	at editor.defold_project$perform_resource_change_plan.invokeStatic(defold_project.clj:442)
	at editor.defold_project$handle_resource_changes.invokeStatic(defold_project.clj:540)
	at editor.defold_project.ProjectResourceListener.handle_changes(defold_project.clj:709)
	at editor.workspace$resource_sync_BANG_$fn__11410.invoke(workspace.clj:323)
	at editor.workspace$resource_sync_BANG_.invokeStatic(workspace.clj:317)
	at editor.disk$start_reload_job_BANG_$fn__38301$fn__38302.invoke(disk.clj:84)
	at clojure.lang.AFn.run(AFn.java:22)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
	at java.base/java.lang.Thread.run(Thread.java:834)`

**Comment by AGulev** [comment]
dups of https://github.com/defold/defold/issues/5205
