### ISSUE TITLE
Cannot start defold on Mac Catalina 10.15.3

### ISSUE THREAD

**Issue by nikolajevs86** [defold/defold#5349]
**Describe the bug (REQUIRED)**
After starting defold version 1.2.175 it crashes without any error.

Logs:
2020-11-18 14:43:14.942 23817 [JavaFX Application Thread] ERROR editor.error-reporting - {:line 110}
java.security.PrivilegedActionException: null
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:447)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:412)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:446)
	at com.sun.glass.ui.View.handleMouseEvent(View.java:556)
	at com.sun.glass.ui.View.notifyMouse(View.java:942)
	at com.sun.glass.ui.mac.MacView.notifyMouse(MacView.java:127)
Caused by: java.lang.Exception: Setter of node 72057594037929098 (editor.gui/TemplateNode) :template could not be called
	at internal.transaction$call_setter_fn.invokeStatic(transaction.clj:425)
	at internal.transaction$invoke_setter$fn__6771.invoke(transaction.clj:453)
	at internal.transaction$invoke_setter.invokeStatic(transaction.clj:453)
	at internal.transaction$apply_defaults.invokeStatic(transaction.clj:461)
	at internal.transaction$ctx_add_node.invokeStatic(transaction.clj:469)
	at internal.transaction$fn__6785.invokeStatic(transaction.clj:478)
	at internal.transaction$fn__6785.invoke(transaction.clj:477)
	at clojure.lang.MultiFn.invoke(MultiFn.java:234)
	at internal.transaction$apply_tx$fn__6849.invoke(transaction.clj:630)
	at internal.transaction$apply_tx.invokeStatic(transaction.clj:630)
	at internal.transaction$apply_tx.invoke(transaction.clj:620)
	at internal.transaction$apply_tx.invokeStatic(transaction.clj:627)
	at internal.transaction$apply_tx.invoke(transaction.clj:620)
	at internal.transaction$apply_tx.invokeStatic(transaction.clj:627)
	at internal.transaction$transact_STAR_.invokeStatic(transaction.clj:697)
	at dynamo.graph$transact.invokeStatic(graph.clj:143)
	at editor.defold_project$load_nodes_BANG_.invokeStatic(defold_project.clj:174)
	at editor.defold_project$load_project$fn__17241.invoke(defold_project.clj:228)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:665)
	at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1973)
	at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1973)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at editor.defold_project$load_project.invokeStatic(defold_project.clj:228)
	at editor.defold_project$open_project_BANG_.invokeStatic(defold_project.clj:779)
	at editor.boot_open_project$open_project.invokeStatic(boot_open_project.clj:396)
	at editor.boot_open_project$open_project.invoke(boot_open_project.clj:394)
	at clojure.lang.AFn.applyToHelper(AFn.java:171)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:665)
	at editor.boot$open_project_with_progress_dialog$fn__89822.invoke(boot.clj:56)
	at editor.dialogs$make_load_project_dialog$fn__30987$fn__30990.invoke(dialogs.clj:422)
	at clojure.core$binding_conveyor_fn$fn__5739.invoke(core.clj:2030)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalArgumentException: No implementation of method: :produce-value of protocol: #'internal.graph.types/Evaluation found for class: nil
	at clojure.core$_cache_protocol_fn.invokeStatic(core_deftype.clj:583)
	at internal.graph.types$fn__3200$G__3195__3209.invoke(types.clj:26)
	at internal.node$node_value.invokeStatic(node.clj:425)
	at internal.system$node_value.invokeStatic(system.clj:353)
	at dynamo.graph$do_node_value.invokeStatic(graph.clj:807)
	at dynamo.graph$node_value.invokeStatic(graph.clj:810)
	at editor.gui$TemplateNode$property$template$setter.invokeStatic(gui.clj:1295)
	at editor.gui$TemplateNode$property$template$setter.invoke(gui.clj:1283)
	at internal.transaction$call_setter_fn.invokeStatic(transaction.clj:416)
	... 38 common frames omitted

**Comment by britzl** [comment]
Does this happen regardless of project?

> Caused by: java.lang.Exception: Setter of node 72057594037929098 (editor.gui/TemplateNode) :template could not be called

This seems to indicate a problem with a gui template.
