### ISSUE TITLE
Defold Editor Crash when dealing with input editing

### ISSUE THREAD

**Issue by ultimateprogramer** [defold/defold#5445]
**Describe the bug (REQUIRED)**
The editor presents me a crash screen `com.google.protobuf.UninitializedMessageException: Message missing required fields: input` when I edit inputs. It does not recover from that point. It inhibits everything else I do on the editor even after that, including also exiting the editor does not work.

**To Reproduce (REQUIRED)**
1. Go to and `game.input_binding` input.
2. Scroll to 'Gamepad Triggers'
3. Try add a trigger with the `+` button.
3. Try remove the trigger with the `-` button.

**Expected behavior (REQUIRED)**
Its not meant to happen.

**Defold version (REQUIRED):**
  - Version 1.2.177

**Platforms (REQUIRED):**
 - Platforms: Ubuntu Linux 20.04

**Logs (OPTIONAL):**
Stack trace:

```
com.google.protobuf.UninitializedMessageException: Message missing required fields: input
	at com.google.protobuf.AbstractMessage$Builder.newUninitializedMessageException(AbstractMessage.java:550)
	at com.dynamo.input.proto.Input$GamepadTrigger$Builder.build(Input.java:3289)
	at com.dynamo.input.proto.Input$GamepadTrigger$Builder.build(Input.java:3245)
	at editor.protobuf$pb_builder_raw$builder_fn__14717.invoke(protobuf.clj:421)
	at clojure.core$mapv$fn__8430.invoke(core.clj:6912)
	at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
	at clojure.core$reduce.invokeStatic(core.clj:6827)
	at clojure.core$mapv.invokeStatic(core.clj:6903)
	at clojure.core$mapv.invoke(core.clj:6903)
	at clojure.core$partial$fn__5824.invoke(core.clj:2624)
	at editor.protobuf$pb_builder_raw$fn__14713$fn__14714.invoke(protobuf.clj:412)
	at editor.protobuf$pb_builder_raw$builder_fn__14717.invoke(protobuf.clj:420)
	at editor.protobuf$map__GT_pb.invokeStatic(protobuf.clj:432)
	at editor.protobuf$map__GT_str.invokeStatic(protobuf.clj:555)
	at editor.protobuf$map__GT_str.invoke(protobuf.clj:555)
	at editor.protobuf$map__GT_str.invokeStatic(protobuf.clj:556)
	at editor.protobuf$map__GT_str.invoke(protobuf.clj:555)
	at clojure.core$partial$fn__5824.invoke(core.clj:2624)
	at editor.resource_node$fn__14875.invokeStatic(resource_node.clj:74)
	at editor.resource_node$fn__14875.invoke(resource_node.clj:68)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.lang.AFunction$1.doInvoke(AFunction.java:31)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.lang.Var.invoke(Var.java:384)
	at editor.protobuf_types$ProtobufNode$behavior$cleaned_save_value$fn__75226.invoke(protobuf_types.clj:69)
	at internal.node$trace_expr.invokeStatic(node.clj:41)
	at editor.protobuf_types$ProtobufNode$behavior$cleaned_save_value.invokeStatic(protobuf_types.clj:69)
	at editor.protobuf_types$ProtobufNode$behavior$cleaned_save_value.invoke(protobuf_types.clj:69)
	at clojure.lang.Var.invoke(Var.java:393)
	at internal.node.NodeImpl.produce_value(node.clj:283)
	at editor.protobuf_types$ProtobufNode$behavior$dirty_QMARK_$fn__75198.invoke(protobuf_types.clj:69)
	at internal.node$trace_expr.invokeStatic(node.clj:41)
	at editor.protobuf_types$ProtobufNode$behavior$dirty_QMARK_.invokeStatic(protobuf_types.clj:69)
	at editor.protobuf_types$ProtobufNode$behavior$dirty_QMARK_.invoke(protobuf_types.clj:69)
	at clojure.lang.Var.invoke(Var.java:393)
	at internal.node.NodeImpl.produce_value(node.clj:283)
	at internal.node$pull_first_input_value.invokeStatic(node.clj:1144)
	at editor.cljfx_form_view$CljfxFormView$behavior$view_dirty_QMARK_$fn__88628.invoke(cljfx_form_view.clj:51)
	at internal.node$trace_expr.invokeStatic(node.clj:41)
	at editor.cljfx_form_view$CljfxFormView$behavior$view_dirty_QMARK_.invokeStatic(cljfx_form_view.clj:51)
	at editor.cljfx_form_view$CljfxFormView$behavior$view_dirty_QMARK_.invoke(cljfx_form_view.clj:51)
	at clojure.lang.Var.invoke(Var.java:393)
	at internal.node.NodeImpl.produce_value(node.clj:283)
	at internal.node$pull_input_values$fn__5462.invoke(node.clj:1160)
	at clojure.core$mapv$fn__8430.invoke(core.clj:6912)
	at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
	at clojure.core$reduce.invokeStatic(core.clj:6827)
	at clojure.core$mapv.invokeStatic(core.clj:6903)
	at internal.node$pull_input_values.invokeStatic(node.clj:1161)
	at editor.app_view$AppView$behavior$open_dirty_views$fn__45113.invoke(app_view.clj:224)
	at internal.node$trace_expr.invokeStatic(node.clj:41)
	at editor.app_view$AppView$behavior$open_dirty_views.invokeStatic(app_view.clj:224)
	at editor.app_view$AppView$behavior$open_dirty_views.invoke(app_view.clj:224)
	at clojure.lang.Var.invoke(Var.java:393)
	at internal.node.NodeImpl.produce_value(node.clj:283)
	at editor.app_view$AppView$behavior$refresh_tab_panes$fn__44964.invoke(app_view.clj:224)
	at internal.node$trace_expr.invokeStatic(node.clj:41)
	at editor.app_view$AppView$behavior$refresh_tab_panes.invokeStatic(app_view.clj:224)
	at editor.app_view$AppView$behavior$refresh_tab_panes.invoke(app_view.clj:224)
	at clojure.lang.Var.invoke(Var.java:393)
	at internal.node.NodeImpl.produce_value(node.clj:283)
	at internal.node$node_value.invokeStatic(node.clj:425)
	at internal.system$node_value.invokeStatic(system.clj:353)
	at dynamo.graph$do_node_value.invokeStatic(graph.clj:807)
	at dynamo.graph$node_value.invokeStatic(graph.clj:810)
	at editor.app_view$refresh_views_BANG_$fn__46921.invoke(app_view.clj:1364)
	at editor.app_view$refresh_views_BANG_.invokeStatic(app_view.clj:1364)
	at editor.app_view$make_app_view$fn__46970.invoke(app_view.clj:1482)
	at editor.ui$__GT_timer$fn__13986$fn__13987.invoke(ui.clj:1923)
	at clojure.lang.AFn.run(AFn.java:22)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
	at java.base/java.lang.Thread.run(Thread.java:834)
2021-01-03 14:08:21.570 ERROR default    editor.error-reporting - {:line 110}
com.google.protobuf.UninitializedMessageException: Message missing required fields: input
	at com.google.protobuf.AbstractMessage$Builder.newUninitializedMessageException(AbstractMessage.java:550)
	at com.dynamo.input.proto.Input$GamepadTrigger$Builder.build(Input.java:3289)
	at com.dynamo.input.proto.Input$GamepadTrigger$Builder.build(Input.java:3245)
	at editor.protobuf$pb_builder_raw$builder_fn__14717.invoke(protobuf.clj:421)
	at clojure.core$mapv$fn__8430.invoke(core.clj:6912)
	at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
	at clojure.core$reduce.invokeStatic(core.clj:6827)
	at clojure.core$mapv.invokeStatic(core.clj:6903)
	at clojure.core$mapv.invoke(core.clj:6903)
	at clojure.core$partial$fn__5824.invoke(core.clj:2624)
	at editor.protobuf$pb_builder_raw$fn__14713$fn__14714.invoke(protobuf.clj:412)
	at editor.protobuf$pb_builder_raw$builder_fn__14717.invoke(protobuf.clj:420)
	at editor.protobuf$map__GT_pb.invokeStatic(protobuf.clj:432)
	at editor.protobuf$map__GT_str.invokeStatic(protobuf.clj:555)
	at editor.protobuf$map__GT_str.invoke(protobuf.clj:555)
	at editor.protobuf$map__GT_str.invokeStatic(protobuf.clj:556)
	at editor.protobuf$map__GT_str.invoke(protobuf.clj:555)
	at clojure.core$partial$fn__5824.invoke(core.clj:2624)
	at editor.resource_node$fn__14875.invokeStatic(resource_node.clj:74)
	at editor.resource_node$fn__14875.invoke(resource_node.clj:68)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.lang.AFunction$1.doInvoke(AFunction.java:31)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.lang.Var.invoke(Var.java:384)
	at editor.protobuf_types$ProtobufNode$behavior$cleaned_save_value$fn__75226.invoke(protobuf_types.clj:69)
	at internal.node$trace_expr.invokeStatic(node.clj:41)
	at editor.protobuf_types$ProtobufNode$behavior$cleaned_save_value.invokeStatic(protobuf_types.clj:69)
	at editor.protobuf_types$ProtobufNode$behavior$cleaned_save_value.invoke(protobuf_types.clj:69)
	at clojure.lang.Var.invoke(Var.java:393)
	at internal.node.NodeImpl.produce_value(node.clj:283)
	at editor.protobuf_types$ProtobufNode$behavior$dirty_QMARK_$fn__75198.invoke(protobuf_types.clj:69)
	at internal.node$trace_expr.invokeStatic(node.clj:41)
	at editor.protobuf_types$ProtobufNode$behavior$dirty_QMARK_.invokeStatic(protobuf_types.clj:69)
	at editor.protobuf_types$ProtobufNode$behavior$dirty_QMARK_.invoke(protobuf_types.clj:69)
	at clojure.lang.Var.invoke(Var.java:393)
	at internal.node.NodeImpl.produce_value(node.clj:283)
	at editor.protobuf_types$ProtobufNode$behavior$save_data$fn__75136.invoke(protobuf_types.clj:69)
	at internal.node$trace_expr.invokeStatic(node.clj:41)
	at editor.protobuf_types$ProtobufNode$behavior$save_data.invokeStatic(protobuf_types.clj:69)
	at editor.protobuf_types$ProtobufNode$behavior$save_data.invoke(protobuf_types.clj:69)
	at clojure.lang.Var.invoke(Var.java:393)
	at internal.node.NodeImpl.produce_value(node.clj:283)
	at internal.node$pull_input_values$fn__5462.invoke(node.clj:1160)
	at clojure.core$mapv$fn__8430.invoke(core.clj:6912)
	at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
	at clojure.core$reduce.invokeStatic(core.clj:6827)
	at clojure.core$mapv.invokeStatic(core.clj:6903)
	at internal.node$pull_input_values.invokeStatic(node.clj:1161)
	at editor.defold_project$Project$behavior$save_data$fn__17725.invoke(defold_project.clj:566)
	at internal.node$trace_expr.invokeStatic(node.clj:41)
	at editor.defold_project$Project$behavior$save_data.invokeStatic(defold_project.clj:566)
	at editor.defold_project$Project$behavior$save_data.invoke(defold_project.clj:566)
	at clojure.lang.Var.invoke(Var.java:393)
	at internal.node.NodeImpl.produce_value(node.clj:283)
	at editor.defold_project$Project$behavior$dirty_save_data$fn__17840.invoke(defold_project.clj:566)
	at internal.node$trace_expr.invokeStatic(node.clj:41)
	at editor.defold_project$Project$behavior$dirty_save_data.invokeStatic(defold_project.clj:566)
	at editor.defold_project$Project$behavior$dirty_save_data.invoke(defold_project.clj:566)
	at clojure.lang.Var.invoke(Var.java:393)
	at internal.node.NodeImpl.produce_value(node.clj:283)
	at internal.node$node_value.invokeStatic(node.clj:425)
	at internal.system$node_value.invokeStatic(system.clj:353)
	at dynamo.graph$do_node_value.invokeStatic(graph.clj:807)
	at dynamo.graph$node_value.invokeStatic(graph.clj:810)
	at editor.defold_project$dirty_save_data.invokeStatic(defold_project.clj:248)
	at editor.boot_open_project$load_stage$fn__89457.invoke(boot_open_project.clj:245)
	at editor.ui$fn__14040$fn__14041.invoke(ui.clj:1978)
	at editor.ui$chain_handler$reify__14004.handle(ui.clj:1964)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at com.sun.javafx.stage.WindowPeerListener.closing(WindowPeerListener.java:93)
	at com.sun.javafx.tk.quantum.GlassWindowEventHandler.run(GlassWindowEventHandler.java:147)
	at com.sun.javafx.tk.quantum.GlassWindowEventHandler.run(GlassWindowEventHandler.java:40)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassWindowEventHandler.lambda$handleWindowEvent$4(GlassWindowEventHandler.java:176)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:412)
	at com.sun.javafx.tk.quantum.GlassWindowEventHandler.handleWindowEvent(GlassWindowEventHandler.java:174)
	at com.sun.glass.ui.Window.handleWindowEvent(Window.java:1351)
	at com.sun.glass.ui.Window.notifyClose(Window.java:1251)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Workaround (OPTIONAL):**
You could try add a trigger to solve this but the editor remains broken in functionality.

**Comment by AGulev** [comment]
I can't reproduce it in 1.12.1
