### ISSUE TITLE
I didn't really do anything, and this is bullshit. What to do? Thank you!

### ISSUE THREAD

**Issue by SBalex-state** [defold/defold#5457]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2021-01-08T14:34:43.994431</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>e7fc2c4a3517d15fc25b365552f5ac6e7a35ad6d</td></tr>
<tr><td>Defold engine sha</td><td>f7778a8f59ef2a8dda5d445f471368e8bd1cb1ac</td></tr>
<tr><td>Defold version</td><td>1.2.177</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"9079aff654e24b759fd38f2a94220e47"'>9079aff654e24b759fd38f2a94220e47</a></td></tr>
<tr><td>GPU</td><td>GeForce 310M/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>3.3.0</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by britzl** [comment]
```
java.net.PlainSocketImpl.waitForConnect.class java.net.SocketTimeoutException: connect timed out
    at java.net.PlainSocketImpl.waitForConnect(PlainSocketImpl.java)
    at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:107)
    at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
    at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
    at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
    at java.net.Socket.connect(Socket.java:591)
    at editor.debugging.mobdebug$try_connect_BANG_.invokeStatic(mobdebug.clj:316)
    at editor.debugging.mobdebug$connect_BANG_$fn.invoke(mobdebug.clj:321)
    at clojure.lang.AFn.run(AFn.java:22)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
    at java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.lang.Thread.run(Thread.java:834)
```

**Comment by britzl** [comment]
This problem seemed to happen when you started your game with the Debug->Start/Attach.

Can you please confirm this?

Does it happen repeatedly or just once?

**Comment by SBalex-state** [comment]
Hello. Thank you for answer, I complete this problem!

Have a good day!


пн, 11 янв. 2021 г., 13:38 Björn Ritzl <notifications@github.com>:

**Comment by britzl** [comment]
Thanks. Closing.
