### ISSUE TITLE
java.lang.AssertionError: Assert failed: (and root (.isDirectory root))

### ISSUE THREAD

**Issue by Ragetto** [defold/defold#5495]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2021-01-21T11:58:21.335092</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>6a2045f58d54c0cad54994021954856dd1425178</td></tr>
<tr><td>Defold engine sha</td><td>af6a29c2a1e2545e2d033790089c606ac9f0bb7a</td></tr>
<tr><td>Defold version</td><td>1.2.178</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"6af1d911777449849757f44b69da574f"'>6af1d911777449849757f44b69da574f</a></td></tr>
<tr><td>GPU</td><td>Intel(R) UHD Graphics 630</td></tr>
<tr><td>GPU Driver</td><td>4.5.0 - Build 26.20.100.7985</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by britzl** [comment]
```
editor.resource_watch$make_directory_snapshot.invokeStatic.class java.lang.AssertionError: Assert failed: (and root (.isDirectory root))
    at editor.resource_watch$make_directory_snapshot.invokeStatic(resource_watch.clj:132)
    at editor.resource_watch$make_snapshot_info.invokeStatic(resource_watch.clj:175)
    at editor.workspace$make_snapshot_info.invokeStatic(workspace.clj:239)
    at editor.disk$start_reload_job_BANG_$fn.invoke(disk.clj:78)
    at clojure.core$binding_conveyor_fn$fn.invoke(core.clj:2030)
    at clojure.lang.AFn.call(AFn.java:18)
    at java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.lang.Thread.run(Thread.java:834)
```

**Comment by AGulev** [comment]
not enough info
