### ISSUE TITLE
Missing resources throws exception

### ISSUE THREAD

**Issue by Jerakin** [defold/defold#5516]
### Expected behaviour
Warnings in the console  or (probably better) a proper "missing resources" dialog

### Actual behaviour
Throws exception

### Steps to reproduce
Try to build with resources that can not be found

<hr/>

<table>
<tr><td>Build time</td><td>2021-01-29T08:52:52.433183</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>d313e728ea607cce6ae126956529744a7490e543</td></tr>
<tr><td>Defold engine sha</td><td>af6a29c2a1e2545e2d033790089c606ac9f0bb7a</td></tr>
<tr><td>Defold version</td><td>1.2.178</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"b7566385f28f48519007b2a8026b4e29"'>b7566385f28f48519007b2a8026b4e29</a></td></tr>
<tr><td>GPU</td><td>Intel(R) HD Graphics 5500</td></tr>
<tr><td>GPU Driver</td><td>4.4.0 - Build 20.19.15.5063</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by britzl** [comment]
```
java.util.concurrent.FutureTask.report.class java.util.concurrent.ExecutionException: java.io.FileNotFoundException: C:\Users\Owner\Documents\projects\Pokedex5E\assets\datafiles\pokemon\Abomasnow.json (Det går inte att hitta sökvägen)
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:191)
    at clojure.core$deref_future.invokeStatic(core.clj:2300)
    at clojure.core$future_call$reify.deref(core.clj:6974)
    at clojure.core$deref.invokeStatic(core.clj:2320)
    at clojure.core$deref.invoke(core.clj:2306)
    at clojure.core$map$fn.invoke(core.clj:2755)
    at clojure.lang.LazySeq.sval(LazySeq.java:42)
    at clojure.lang.LazySeq.seq(LazySeq.java:51)
    at clojure.lang.Cons.next(Cons.java:39)
    at clojure.lang.RT.next(RT.java:709)
    at clojure.core$next__5371.invokeStatic(core.clj:64)
    at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:27)
    at clojure.core.protocols$fn.invokeStatic(protocols.clj:75)
    at clojure.core.protocols$fn.invoke(protocols.clj:75)
    at clojure.core.protocols$fn$G__8068__8086.invoke(protocols.clj:13)
    at clojure.core$reduce.invokeStatic(core.clj:6824)
    at editor.build$batched_pmap.invokeStatic(build.clj:23)
    at editor.build$build_project_BANG_.invokeStatic(build.clj:59)
    at editor.app_view$build_project_BANG_.invokeStatic(app_view.clj:745)
    at editor.app_view$async_build_BANG_$fn$fn.invoke(app_view.clj:764)
    at editor.app_view$async_build_BANG_$fn.invoke(app_view.clj:764)
    at clojure.core$binding_conveyor_fn$fn.invoke(core.clj:2030)
    at clojure.lang.AFn.call(AFn.java:18)
    at java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.lang.Thread.run(Thread.java:834)
```

**Comment by Jerakin** [comment]
I can't remember this one. But I guess it was when adding something under "Custom Resources" that didn't exist? If that is the case it seems to be fixed now.

**Comment by AGulev** [comment]
I'm closing it for now, if you get it again please open a new one and provide repro steps. Thank you!
