### ISSUE TITLE
Unable to see scripts or other files on Mac Catalina 10.15.7. It says error

### ISSUE THREAD

**Issue by amitanubha** [defold/defold#5522]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2021-02-01T12:52:12.101903</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>6ce404156136f291c4f2c33a72b28f7bd923eb5e</td></tr>
<tr><td>Defold engine sha</td><td>af6a29c2a1e2545e2d033790089c606ac9f0bb7a</td></tr>
<tr><td>Defold version</td><td>1.2.178</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"98b91dcb0a33458e8f69a2d7e4ebadbf"'>98b91dcb0a33458e8f69a2d7e4ebadbf</a></td></tr>
<tr><td>GPU</td><td>AMD Radeon Pro 5300M OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 ATI-3.10.19</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.15.7</td></tr>
<table>

**Comment by britzl** [comment]
```
com.google.protobuf.AbstractMessage$Builder.newUninitializedMessageException.class com.google.protobuf.UninitializedMessageException: Message missing required fields: input
    at com.google.protobuf.AbstractMessage$Builder.newUninitializedMessageException(AbstractMessage.java:550)
    at com.dynamo.input.proto.Input$TouchTrigger$Builder.build(Input.java:3627)
    at com.dynamo.input.proto.Input$TouchTrigger$Builder.build(Input.java:3583)
    at editor.protobuf$pb_builder_raw$builder_fn.invoke(protobuf.clj:421)
    at clojure.core$mapv$fn.invoke(core.clj:6912)
    at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
    at clojure.core$reduce.invokeStatic(core.clj:6827)
    at clojure.core$mapv.invokeStatic(core.clj:6903)
    at clojure.core$mapv.invoke(core.clj:6903)
    at clojure.core$partial$fn.invoke(core.clj:2624)
    at editor.protobuf$pb_builder_raw$fn$fn.invoke(protobuf.clj:412)
    at editor.protobuf$pb_builder_raw$builder_fn.invoke(protobuf.clj:420)
    at editor.protobuf$map__GT_pb.invokeStatic(protobuf.clj:432)
    at editor.protobuf$map__GT_str.invokeStatic(protobuf.clj:555)
    at editor.protobuf$map__GT_str.invoke(protobuf.clj:555)
    at editor.protobuf$map__GT_str.invokeStatic(protobuf.clj:556)
    at editor.protobuf$map__GT_str.invoke(protobuf.clj:555)
    at clojure.core$partial$fn.invoke(core.clj:2624)
    at editor.resource_node$fn.invokeStatic(resource_node.clj:74)
    at editor.resource_node$fn.invoke(resource_node.clj:68)
    at clojure.lang.AFn.applyToHelper(AFn.java:154)
    at clojure.lang.AFn.applyTo(AFn.java:144)
    at clojure.lang.AFunction$1.doInvoke(AFunction.java:31)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at clojure.lang.Var.invoke(Var.java:384)
    at editor.protobuf_types$ProtobufNode$behavior$cleaned_save_value$fn.invoke(protobuf_types.clj:69)
    at internal.node$trace_expr$fn.invoke(node.clj:35)
    at internal.node$trace_expr.invokeStatic(node.clj:35)
    at editor.protobuf_types$ProtobufNode$behavior$cleaned_save_value.invokeStatic(protobuf_types.clj:69)
    at editor.protobuf_types$ProtobufNode$behavior$cleaned_save_value.invoke(protobuf_types.clj:69)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:283)
    at editor.protobuf_types$ProtobufNode$behavior$dirty_QMARK_$fn.invoke(protobuf_types.clj:69)
    at internal.node$trace_expr$fn.invoke(node.clj:35)
    at internal.node$trace_expr.invokeStatic(node.clj:35)
    at editor.protobuf_types$ProtobufNode$behavior$dirty_QMARK_.invokeStatic(protobuf_types.clj:69)
    at editor.protobuf_types$ProtobufNode$behavior$dirty_QMARK_.invoke(protobuf_types.clj:69)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:283)
    at editor.protobuf_types$ProtobufNode$behavior$save_data$fn.invoke(protobuf_types.clj:69)
    at internal.node$trace_expr$fn.invoke(node.clj:35)
    at internal.node$trace_expr.invokeStatic(node.clj:35)
    at editor.protobuf_types$ProtobufNode$behavior$save_data.invokeStatic(protobuf_types.clj:69)
    at editor.protobuf_types$ProtobufNode$behavior$save_data.invoke(protobuf_types.clj:69)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:283)
    at internal.node$pull_input_values$fn.invoke(node.clj:1160)
    at clojure.core$mapv$fn.invoke(core.clj:6912)
    at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
    at clojure.core$reduce.invokeStatic(core.clj:6827)
    at clojure.core$mapv.invokeStatic(core.clj:6903)
    at internal.node$pull_input_values.invokeStatic(node.clj:1161)
    at editor.defold_project$Project$behavior$save_data$fn.invoke(defold_project.clj:566)
    at internal.node$trace_expr$fn.invoke(node.clj:35)
    at internal.node$trace_expr.invokeStatic(node.clj:35)
    at editor.defold_project$Project$behavior$save_data.invokeStatic(defold_project.clj:566)
    at editor.defold_project$Project$behavior$save_data.invoke(defold_project.clj:566)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:283)
    at editor.defold_project$Project$behavior$dirty_save_data$fn.invoke(defold_project.clj:566)
    at internal.node$trace_expr$fn.invoke(node.clj:35)
    at internal.node$trace_expr.invokeStatic(node.clj:35)
    at editor.defold_project$Project$behavior$dirty_save_data.invokeStatic(defold_project.clj:566)
    at editor.defold_project$Project$behavior$dirty_save_data.invoke(defold_project.clj:566)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:283)
    at internal.node$node_value.invokeStatic(node.clj:425)
    at internal.system$node_value.invokeStatic(system.clj:353)
    at dynamo.graph$do_node_value.invokeStatic(graph.clj:807)
    at dynamo.graph$node_value.invokeStatic(graph.clj:810)
    at editor.defold_project$dirty_save_data.invokeStatic(defold_project.clj:248)
    at editor.defold_project$dirty_save_data_with_progress.invokeStatic(defold_project.clj:263)
    at editor.disk$start_save_job_BANG_$fn.invoke(disk.clj:132)
    at clojure.core$binding_conveyor_fn$fn.invoke(core.clj:2030)
    at clojure.lang.AFn.call(AFn.java:18)
    at java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.lang.Thread.run(Thread.java:834)
```

**Comment by britzl** [comment]
Does this happen for all projects or just one? Has it worked before?

**Comment by britzl** [comment]
No new info from user. Closing.
