### ISSUE TITLE
Error when trying to open game.collection from Platformer sample (Ubuntu 20.10)

### ISSUE THREAD

**Issue by UltraBurstXD** [defold/defold#5531]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2021-02-01T12:51:27.527828</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>6ce404156136f291c4f2c33a72b28f7bd923eb5e</td></tr>
<tr><td>Defold engine sha</td><td>af6a29c2a1e2545e2d033790089c606ac9f0bb7a</td></tr>
<tr><td>Defold version</td><td>1.2.178</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"e935d3147e064b2ebdbb261de932d08e"'>e935d3147e064b2ebdbb261de932d08e</a></td></tr>
<tr><td>GPU</td><td>Mesa DRI Intel(R) HD Graphics 400 (BSW)</td></tr>
<tr><td>GPU Driver</td><td>2.1 Mesa 20.2.6</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>5.8.0-41-generic</td></tr>
<table>

**Comment by britzl** [comment]
```
editor.handler$invoke_fnk.invokeStatic.class clojure.lang.ExceptionInfo: handler ':scene-play' in context ':global' failed at ':active?' with message 'No implementation of method: :produce-value of protocol: #'internal.graph.types/Evaluation found for class: nil'
    at editor.handler$invoke_fnk.invokeStatic(handler.clj:260)
    at editor.handler$get_active_handler$fn.invoke(handler.clj:271)
    at clojure.core$some.invokeStatic(core.clj:2701)
    at editor.handler$get_active_handler.invokeStatic(handler.clj:268)
    at editor.handler$get_active$fn.invoke(handler.clj:277)
    at clojure.core$some.invokeStatic(core.clj:2701)
    at editor.handler$get_active.invokeStatic(handler.clj:275)
    at editor.handler$active.invokeStatic(handler.clj:313)
    at editor.ui$make_menu_item.invokeStatic(ui.clj:1285)
    at editor.ui$make_menu_items$fn.invoke(ui.clj:1303)
    at clojure.core$keep$fn$fn.invoke(core.clj:7325)
    at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
    at clojure.core$transduce.invokeStatic(core.clj:6883)
    at clojure.core$into.invokeStatic(core.clj:6899)
    at editor.ui$make_menu_items.invokeStatic(ui.clj:1301)
    at editor.ui$make_menu_items.invoke(ui.clj:1301)
    at editor.ui$make_menu_item.invokeStatic(ui.clj:1279)
    at editor.ui$make_menu_items$fn.invoke(ui.clj:1303)
    at clojure.core$keep$fn$fn.invoke(core.clj:7325)
    at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
    at clojure.core$transduce.invokeStatic(core.clj:6883)
    at clojure.core$into.invokeStatic(core.clj:6899)
    at editor.ui$make_menu_items.invokeStatic(ui.clj:1301)
    at editor.ui$refresh_menubar_BANG_.invokeStatic(ui.clj:1504)
    at editor.ui$refresh_menus_BANG_.invokeStatic(ui.clj:1768)
    at editor.ui$refresh.invokeStatic(ui.clj:1789)
    at editor.app_view$refresh_menus_and_toolbars_BANG_.invokeStatic(app_view.clj:1358)
    at editor.app_view$make_app_view$fn.invoke(app_view.clj:1482)
    at editor.ui$__GT_timer$fn$fn.invoke(ui.clj:1923)
    at clojure.lang.AFn.run(AFn.java:22)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
    at java.security.AccessController.doPrivileged(AccessController.java)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
    at com.sun.glass.ui.gtk.GtkApplication._runLoop(GtkApplication.java)
    at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
    at java.lang.Thread.run(Thread.java:834)
```
