### ISSUE TITLE
Editor crash with java.security.PrivilegedActionException

### ISSUE THREAD

**Issue by jelly1514920642** [defold/defold#5532]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2021-01-16T10:47:07.405749</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>3d2d4932d02dabc7e57fd25fac275b0a6dc59158</td></tr>
<tr><td>Defold engine sha</td><td>af6a29c2a1e2545e2d033790089c606ac9f0bb7a</td></tr>
<tr><td>Defold version</td><td>1.2.178</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"65b0693d4c054e1b956c2f74bdbc5464"'>65b0693d4c054e1b956c2f74bdbc5464</a></td></tr>
<tr><td>GPU</td><td>Intel(R) UHD Graphics 630</td></tr>
<tr><td>GPU Driver</td><td>4.5.0 - Build 26.20.100.7637</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by britzl** [comment]
```
java.security.AccessController.doPrivileged.class java.security.PrivilegedActionException: null
    at java.security.AccessController.doPrivileged(AccessController.java)
    at com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:412)
    at com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:439)
    at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:563)
    at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:543)
    at com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(QuantumToolkit.java:536)
    at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(QuantumToolkit.java:342)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
    at com.sun.glass.ui.win.WinApplication._runLoop(WinApplication.java)
    at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
    at java.lang.Thread.run(Thread.java:834)
```

**Comment by britzl** [comment]
@jelly1514920642 what did you do when the problem occurred?

**Comment by britzl** [comment]
No new info from user. Closing.
