### ISSUE TITLE
problem 

### ISSUE THREAD

**Issue by katewynne** [defold/defold#5576]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2021-02-16T08:23:37.275112</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>492c3531153c849388976cfbdc058fc6f66cbd22</td></tr>
<tr><td>Defold engine sha</td><td>5209b50cf4bf8e925cb4c32fd0bde6c53fc85a66</td></tr>
<tr><td>Defold version</td><td>1.2.179</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"84e08cdae73448a4ad515f5a14082eb1"'>84e08cdae73448a4ad515f5a14082eb1</a></td></tr>
<tr><td>GPU</td><td>Apple M1</td></tr>
<tr><td>GPU Driver</td><td>2.1 Metal - 70.12.7</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.16</td></tr>
<table>

**Comment by britzl** [comment]
```
editor.debugging.mobdebug$connect_BANG_$fn__43039.invoke.class clojure.lang.ExceptionInfo: Failed to connect to debugger on 156.200.0.100:8172
    at editor.debugging.mobdebug$connect_BANG_$fn.invoke(mobdebug.clj:339)
    at clojure.lang.AFn.run(AFn.java:22)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
    at java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.lang.Thread.run(Thread.java:834)
```

**Comment by britzl** [comment]
It looks like a problem connecting the debugger to your game. Does this happen all the time or only sometimes?

**Comment by britzl** [comment]
No new info from user. Closing.
