### ISSUE TITLE
Defold hangs on startup (multiple versions) (Ubuntu 20.04)

### ISSUE THREAD

**Issue by joereynolds** [defold/defold#5646]
**Describe the bug (REQUIRED)**
When I try and start Defold from any source (tried both Steam and just zipped package from the Defold website)it hangs.

If I run the executable myself it gives me this trace:

```
2021-03-12 15:36:44.283 DEBUG default    com.defold.libs.ResourceUnpacker - unpacking '/_unpack/x86-win32/lib/jogl_mobile.dll' to '/home/joe/.Defold/unpack/3d2d4932d02dabc7e57fd25fac275b0a6dc59158/x86-win32/lib/jogl_mobile.dll'
2021-03-12 15:36:44.291 INFO  default    com.defold.libs.ResourceUnpacker - defold.unpack.path=/home/joe/.Defold/unpack/3d2d4932d02dabc7e57fd25fac275b0a6dc59158
com.jogamp.opengl.GLException: Graphics configuration failed [direct caps, eglGetConfig/chooser and fixed-caps(1-3)]
	at jogamp.opengl.egl.EGLGraphicsConfigurationFactory.chooseGraphicsConfigurationStatic(EGLGraphicsConfigurationFactory.java:317)
	at jogamp.opengl.egl.EGLDrawableFactory.evalConfig(EGLDrawableFactory.java:1060)
	at jogamp.opengl.egl.EGLDrawableFactory.createMutableSurfaceImpl(EGLDrawableFactory.java:1072)
	at jogamp.opengl.egl.EGLDrawableFactory.createMutableSurfaceImpl(EGLDrawableFactory.java:88)
	at jogamp.opengl.GLDrawableFactoryImpl.createOffscreenDrawable(GLDrawableFactoryImpl.java:432)
	at jogamp.opengl.GLDrawableFactoryImpl.createOffscreenAutoDrawable(GLDrawableFactoryImpl.java:373)
	at editor.gl$unchecked_offscreen_drawable.invokeStatic(gl.clj:51)
	at editor.gl$init_info_BANG_.invokeStatic(gl.clj:106)
	at editor.gl$info.invokeStatic(gl.clj:120)
	at editor.gl$gl_support_error.invokeStatic(gl.clj:122)
	at editor.boot$main.invokeStatic(boot.clj:111)
	at editor.boot$main.invoke(boot.clj:107)
	at clojure.lang.Var.invoke(Var.java:388)
	at editor.bootloader$main.invokeStatic(bootloader.clj:65)
	at editor.bootloader$main.invoke(bootloader.clj:59)
	at clojure.lang.Var.invoke(Var.java:384)
	at org.projectodd.shimdandy.impl.ClojureRuntimeShimImpl.invoke(ClojureRuntimeShimImpl.java:109)
	at org.projectodd.shimdandy.impl.ClojureRuntimeShimImpl.invoke(ClojureRuntimeShimImpl.java:102)
	at com.defold.editor.EditorApplication.run(EditorApplication.java:38)
	at com.defold.editor.Start.lambda$kickLoading$0(Start.java:62)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
	at java.base/java.lang.Thread.run(Thread.java:834)
2021-03-12 15:36:49.509 ERROR default    com.defold.editor.Start - failed to open editor
com.jogamp.opengl.GLException: Graphics configuration failed [direct caps, eglGetConfig/chooser and fixed-caps(1-3)]
	at jogamp.opengl.egl.EGLGraphicsConfigurationFactory.chooseGraphicsConfigurationStatic(EGLGraphicsConfigurationFactory.java:317)
	at jogamp.opengl.egl.EGLDrawableFactory.evalConfig(EGLDrawableFactory.java:1060)
	at jogamp.opengl.egl.EGLDrawableFactory.createMutableSurfaceImpl(EGLDrawableFactory.java:1072)
	at jogamp.opengl.egl.EGLDrawableFactory.createMutableSurfaceImpl(EGLDrawableFactory.java:88)
	at jogamp.opengl.GLDrawableFactoryImpl.createOffscreenDrawable(GLDrawableFactoryImpl.java:432)
	at jogamp.opengl.GLDrawableFactoryImpl.createOffscreenAutoDrawable(GLDrawableFactoryImpl.java:373)
	at editor.gl$unchecked_offscreen_drawable.invokeStatic(gl.clj:51)
	at editor.gl$init_info_BANG_.invokeStatic(gl.clj:106)
	at editor.gl$info.invokeStatic(gl.clj:120)
	at editor.gl$gl_support_error.invokeStatic(gl.clj:122)
	at editor.boot$main.invokeStatic(boot.clj:111)
	at editor.boot$main.invoke(boot.clj:107)
	at clojure.lang.Var.invoke(Var.java:388)
	at editor.bootloader$main.invokeStatic(bootloader.clj:65)
	at editor.bootloader$main.invoke(bootloader.clj:59)
	at clojure.lang.Var.invoke(Var.java:384)
	at org.projectodd.shimdandy.impl.ClojureRuntimeShimImpl.invoke(ClojureRuntimeShimImpl.java:109)
	at org.projectodd.shimdandy.impl.ClojureRuntimeShimImpl.invoke(ClojureRuntimeShimImpl.java:102)
	at com.defold.editor.EditorApplication.run(EditorApplication.java:38)
	at com.defold.editor.Start.lambda$kickLoading$0(Start.java:62)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
	at java.base/java.lang.Thread.run(Thread.java:834)

(java:22815): Gdk-WARNING **: 15:37:14.393: XSetErrorHandler() called with a GDK error trap pushed. Don't do that.

```
**To Reproduce (REQUIRED)**

On a Ubuntu 20.04 system:
1. Go to the Defold Steam page
2. Install Defold
3. Click Play
4. It will "load forever" and stay on the splash screen

**Expected behavior (REQUIRED)**
I expect Defold to start

**Defold version (REQUIRED):**
The debug logs say -Ddefold.version=1.2.178 for steam however it's also present on 1.2.180

**Platforms (REQUIRED):**
- Linux - Ubuntu 20.04

**Comment by joereynolds** [comment]
Closing this as I've seen [this thread[(https://forum.defold.com/t/glexception-graphics-configuration-failed/67230/9). Thanks for a great engine btw. Lua is an excellent choice!

**Comment by joereynolds** [comment]
For anyone else struggling, I downgraded to 1.2.177 and `export MESA_LOADER_DRIVER_OVERRIDE=i965` and then start Defold
