### ISSUE TITLE
defold can't load project/make new project properly

### ISSUE THREAD

**Issue by ZacharyInnit** [defold/defold#5647]
### Expected behaviour
the program to load?
### Actual behaviour
it crashed with message
java.security.PrivilegedActionException: Unknown
java.net.SocketException: Permission denied: listen
### Steps to reproduce
I just pressed create new program or loaded a program
<hr/>

<table>
<tr><td>Build time</td><td>2021-03-09T10:27:26.752538</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>f34b08dc12af1101ae62c6e880b6373a03206174</td></tr>
<tr><td>Defold engine sha</td><td>f34b08dc12af1101ae62c6e880b6373a03206174</td></tr>
<tr><td>Defold version</td><td>1.2.180</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"aa8f607f87f04c5a916da4bb9faceee7"'>aa8f607f87f04c5a916da4bb9faceee7</a></td></tr>
<tr><td>GPU</td><td>Intel(R) UHD Graphics</td></tr>
<tr><td>GPU Driver</td><td>4.5.0 - Build 26.20.100.7926</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by britzl** [comment]
It seems like there is something preventing the editor from downloading the selected project template from GitHub. What if you manually download a template and open it. For instance this one:

https://github.com/defold/template-empty

```
java.security.AccessController.doPrivileged.class java.security.PrivilegedActionException: null
    at java.security.AccessController.doPrivileged(AccessController.java)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:447)
    at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:412)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:446)
    at com.sun.glass.ui.View.handleMouseEvent(View.java:556)
    at com.sun.glass.ui.View.notifyMouse(View.java:942)
    at com.sun.glass.ui.win.WinApplication._runLoop(WinApplication.java)
    at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
    at java.lang.Thread.run(Thread.java:834)
sun.nio.ch.Net.listen.class java.net.SocketException: Permission denied: listen
    at sun.nio.ch.Net.listen(Net.java)
    at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:228)
    at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:80)
    at sun.net.httpserver.ServerImpl.<init>(ServerImpl.java:101)
    at sun.net.httpserver.HttpServerImpl.<init>(HttpServerImpl.java:50)
    at sun.net.httpserver.DefaultHttpServerProvider.createHttpServer(DefaultHttpServerProvider.java:35)
    at com.sun.net.httpserver.HttpServer.create(HttpServer.java:137)
    at util.http_server$__GT_server.invokeStatic(http_server.clj:70)
    at editor.boot_open_project$load_stage.invokeStatic(boot_open_project.clj:180)
    at editor.boot_open_project$open_project$fn.invoke(boot_open_project.clj:402)
    at editor.ui$do_run_now$fn.invoke(ui.clj:320)
    at clojure.lang.AFn.run(AFn.java:22)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
    at java.security.AccessController.doPrivileged(AccessController.java)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
    at com.sun.glass.ui.win.WinApplication._enterNestedEventLoopImpl(WinApplication.java)
    at com.sun.glass.ui.win.WinApplication._enterNestedEventLoop(WinApplication.java:201)
    at com.sun.glass.ui.Application.enterNestedEventLoop(Application.java:509)
    at com.sun.glass.ui.EventLoop.enter(EventLoop.java:107)
    at com.sun.javafx.tk.quantum.QuantumToolkit.enterNestedEventLoop(QuantumToolkit.java:635)
    at javafx.application.Platform.enterNestedEventLoop(Platform.java:291)
    at editor.fxui$mount_renderer_and_await_result_BANG_.invokeStatic(fxui.clj:228)
    at editor.dialogs$make_load_project_dialog$fn.invoke(dialogs.clj:414)
    at editor.ui$do_run_now.invokeStatic(ui.clj:315)
    at editor.dialogs$make_load_project_dialog.invokeStatic(dialogs.clj:413)
    at editor.boot$open_project_with_progress_dialog.invokeStatic(boot.clj:53)
    at editor.boot$select_project_from_welcome$fn$fn.invoke(boot.clj:74)
    at editor.welcome$show_welcome_dialog_BANG_$close_dialog_and_open_project_BANG___86595.invoke(welcome.clj:592)
    at editor.welcome$make_home_pane$open_selected_project_BANG___86519.invoke(welcome.clj:375)
    at editor.welcome$make_home_pane$fn.invoke(welcome.clj:379)
    at editor.ui$fn$reify.handle(ui.clj:854)
```

**Comment by britzl** [comment]
No new info from user. Closing.
