### ISSUE TITLE
Missing file when building

### ISSUE THREAD

**Issue by Faxo-Hack** [defold/defold#5650]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2021-01-16T10:47:07.405749</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>3d2d4932d02dabc7e57fd25fac275b0a6dc59158</td></tr>
<tr><td>Defold engine sha</td><td>af6a29c2a1e2545e2d033790089c606ac9f0bb7a</td></tr>
<tr><td>Defold version</td><td>1.2.178</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"7dc045c1910e4e41b1711e6ae09dec15"'>7dc045c1910e4e41b1711e6ae09dec15</a></td></tr>
<tr><td>GPU</td><td>Intel(R) UHD Graphics 630</td></tr>
<tr><td>GPU Driver</td><td>4.5.0 - Build 26.20.100.6911</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by britzl** [comment]
@Faxo-Hack It seems like a file is missing. Can you confirm that C:\Users\ninox\Desktop game\assets\images\background.png exists?

```
java.io.FileInputStream.open0.class java.io.FileNotFoundException: C:\Users\ninox\Desktop game\assets\images\background.png (Le chemin d’accès spécifié est introuvable)
    at java.io.FileInputStream.open0(FileInputStream.java)
    at java.io.FileInputStream.open(FileInputStream.java:219)
    at java.io.FileInputStream.<init>(FileInputStream.java:157)
    at clojure.java.io$fn.invokeStatic(io.clj:229)
    at clojure.java.io$fn.invoke(io.clj:229)
    at clojure.java.io$fn$G__11372__11386.invoke(io.clj:69)
    at editor.resource.FileResource.make_input_stream(resource.clj:135)
    at clojure.java.io$input_stream.invokeStatic(io.clj:136)
    at clojure.java.io$input_stream.doInvoke(io.clj:121)
    at clojure.lang.RestFn.invoke(RestFn.java:410)
    at editor.image_util$read_image.invokeStatic(image_util.clj:41)
    at editor.pipeline.texture_set_gen$atlas__GT_texture_set_data$fn.invoke(texture_set_gen.clj:97)
    at clojure.core$map$fn.invoke(core.clj:2753)
    at clojure.lang.LazySeq.sval(LazySeq.java:42)
    at clojure.lang.LazySeq.seq(LazySeq.java:51)
    at clojure.lang.RT.seq(RT.java:531)
    at clojure.lang.RT.nthFrom(RT.java:918)
    at clojure.lang.RT.nth(RT.java:893)
    at clojure.lang.LazySeq.get(LazySeq.java:233)
    at com.dynamo.bob.textureset.TextureSetGenerator.calculateLayout(TextureSetGenerator.java:332)
```

**Comment by britzl** [comment]
No new info from user. Closing.
