### ISSUE TITLE
I got a new defold update and i got this thing

### ISSUE THREAD

**Issue by EmeraldWizardX** [defold/defold#5667]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2021-03-18T11:58:23.113059</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>0775d21575af3ec4dbc3f01d34a0d6944a570c6b</td></tr>
<tr><td>Defold engine sha</td><td>f34b08dc12af1101ae62c6e880b6373a03206174</td></tr>
<tr><td>Defold version</td><td>1.2.180</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"9679673827144caab625e9345c94796f"'>9679673827144caab625e9345c94796f</a></td></tr>
<tr><td>GPU</td><td>Intel(R) UHD Graphics 630</td></tr>
<tr><td>GPU Driver</td><td>4.5.0 - Build 26.20.100.7584</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by britzl** [comment]
```
java.io.FileOutputStream.open0.class java.io.FileNotFoundException: C:\Users\basht\OneDrive\Desktop\My_Coding_Stuff\Friend or Foe?\.gitattributes (The filename, directory name, or volume label syntax is incorrect)
    at java.io.FileOutputStream.open0(FileOutputStream.java)
    at java.io.FileOutputStream.open(FileOutputStream.java:298)
    at java.io.FileOutputStream.<init>(FileOutputStream.java:237)
    at java.io.FileOutputStream.<init>(FileOutputStream.java:187)
    at editor.welcome$expand_proj_zip_BANG_.invokeStatic(welcome.clj:233)
    at editor.welcome$show_welcome_dialog_BANG_$download_template_BANG___86597$fn.invoke(welcome.clj:605)
    at clojure.core$binding_conveyor_fn$fn.invoke(core.clj:2030)
    at clojure.lang.AFn.call(AFn.java:18)
    at java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.lang.Thread.run(Thread.java:834)
```

Please try and remove the question mark from the folder name (from "Friend or Foe?"). As a rule of thumb you should try to avoid special characters in folder names. Reopen if the problem persists.
