### ISSUE TITLE
creating a new collection

### ISSUE THREAD

**Issue by Djeezus** [defold/defold#5673]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2021-02-19T13:21:16.671559</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>dc0725b3f70d22c8e0b1ad09bfd5f4f233d7fb0f</td></tr>
<tr><td>Defold engine sha</td><td>5209b50cf4bf8e925cb4c32fd0bde6c53fc85a66</td></tr>
<tr><td>Defold version</td><td>1.2.179</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"6a743301d4d0485abc47228571489cf1"'>6a743301d4d0485abc47228571489cf1</a></td></tr>
<tr><td>GPU</td><td>Mesa DRI Intel(R) UHD Graphics 620 (WHL GT2)</td></tr>
<tr><td>GPU Driver</td><td>3.0 Mesa 20.2.6</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>5.4.0-66-generic</td></tr>
<table>

**Comment by britzl** [comment]
```
editor.handler$invoke_fnk.invokeStatic.class clojure.lang.ExceptionInfo: handler ':new-file' in context ':global' failed at ':run' with message 'No implementation of method: :resource-type of protocol: #'editor.resource/Resource found for class: nil'
    at editor.handler$invoke_fnk.invokeStatic(handler.clj:260)
    at editor.handler$run.invokeStatic(handler.clj:287)
    at editor.ui$execute_command.invokeStatic(ui.clj:1158)
    at editor.ui$invoke_handler.invokeStatic(ui.clj:1179)
    at editor.ui$make_menu_command$reify.handle(ui.clj:1262)
    at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
    at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
    at javafx.event.Event.fireEvent(Event.java:198)
    at javafx.scene.control.MenuItem.fire(MenuItem.java:459)
    at com.sun.javafx.scene.control.ContextMenuContent$MenuItemContainer.doSelect(ContextMenuContent.java:1385)
    at com.sun.javafx.scene.control.ContextMenuContent$MenuItemContainer.lambda$createChildren$12(ContextMenuContent.java:1338)
    at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:247)
    at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
    at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
    at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
    at javafx.event.Event.fireEvent(Event.java:198)
    at javafx.scene.Scene$MouseHandler.process(Scene.java:3856)
    at javafx.scene.Scene.processMouseEvent(Scene.java:1851)
    at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2584)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:409)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:299)
    at java.security.AccessController.doPrivileged(AccessController.java)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:447)
    at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:412)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:446)
    at com.sun.glass.ui.View.handleMouseEvent(View.java:556)
    at com.sun.glass.ui.View.notifyMouse(View.java:942)
    at com.sun.glass.ui.gtk.GtkApplication._runLoop(GtkApplication.java)
    at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
    at java.lang.Thread.run(Thread.java:834)
```

**Comment by AGulev** [comment]
## Issue summary

The issue reports that creating a new collection in the editor on Linux could fail from the `:new-file` handler with `No implementation of method: :resource-type ... for class: nil`. The only issue comment includes the stack trace showing the failure happened while running the New File action.

## Status

Possibly outdated/fixed

## Evidence

- The current `:file.new` handler in `editor/src/clj/editor/asset_browser.clj:541` creates the file, runs `workspace/resource-sync!`, then looks the resource up in the workspace map.
- That handler now guards the open step with `(when (resource/loaded? resource) ...)` in `editor/src/clj/editor/asset_browser.clj:583`, which prevents the old nil dereference path implied by the issue stack trace.
- The new-file dialog now normalizes the chosen directory through `path/actual-cased` before constructing the file path in `editor/src/clj/editor/dialogs.clj:1088`, which is specifically meant to match the editor's case-sensitive internal resource maps.
- The issue was reported from Linux, where path/casing mismatches and resource lookup failures would surface directly instead of being masked by a case-insensitive filesystem.
- The issue is still open on GitHub, but the current code path contains defensive handling and path normalization that directly address the failure mode described in the report.

## Why it looks fixed

The reported crash requires the New File flow to continue with a missing resource and then call resource-type-dependent code on `nil`. In the current code, the flow first normalizes the destination path for exact resource-map lookup and then only opens the created resource when it is actually present and loaded. That makes the specific `nil`-resource failure described in issue #5673 look already addressed in practice.
