### ISSUE TITLE
Error on build project in Defold

### ISSUE THREAD

**Issue by BikiniKnight** [defold/defold#5702]
### Expected behaviour
Completion of builds and launch of the project
### Actual behaviour
Error on build:
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: Could not initialize class com.dynamo.bob.TexcLibrary
java.lang.NoClassDefFoundError: Could not initialize class com.dynamo.bob.TexcLibrary
### Steps to reproduce
Update to version Defold 1.2.180 and got an error on build project
On version 1.2.179 all be ok
(P.S. sorry for my bad English)
<hr/>

<table>
<tr><td>Build time</td><td>2021-03-27T07:32:27.485350</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>c89efe0dcac970ec71f153f0d4ed0c89fee55059</td></tr>
<tr><td>Defold engine sha</td><td>f34b08dc12af1101ae62c6e880b6373a03206174</td></tr>
<tr><td>Defold version</td><td>1.2.180</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"1e00d8d455e747c19ebe9399ddfa24ec"'>1e00d8d455e747c19ebe9399ddfa24ec</a></td></tr>
<tr><td>GPU</td><td>Mesa DRI Intel(R) HD Graphics 2500 (IVB GT1)</td></tr>
<tr><td>GPU Driver</td><td>3.0 Mesa 20.2.4</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>5.10.24-2.el7.x86_64</td></tr>
<table>

**Comment by JCash** [comment]
Hi @BikiniKnight !
What OS (distro) are you using?

**Comment by BikiniKnight** [comment]
Hi @JCash !
Im use custom linux based on CentOS:
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	RED SOFT

**Comment by Vbif** [comment]
Cooperated with BikiniKnight. Logs also contain this exceptions, which probably the source of problem. It refers to this code https://github.com/defold/defold/blob/1ae302ec33d4514408c04ad3ae5d3c1efe2057bd/com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/TexcLibrary.java#L53

Is there something more that we can check? Really want to push this issue forward.

```
Caused by: java.lang.UnsatisfiedLinkError: /tmp/jna-3506402/jna16952893420983322375.tmp: /tmp/jna-3506402/jna16952893420983322375.tmp: сбой отображения сегмента из разделяемого объекта
	at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
	at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2430)
	at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2487)
	at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2684)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2617)
	at java.base/java.lang.Runtime.load0(Runtime.java:767)
	at java.base/java.lang.System.load(System.java:1831)
	at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:761)
	at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:736)
	at com.sun.jna.Native.<clinit>(Native.java:131)
	at com.dynamo.bob.TexcLibrary.<clinit>(TexcLibrary.java:53)
	at editor.texture.engine$compress_rgba_buffer.invokeStatic(engine.clj:151)
	at editor.pipeline.font_gen$compress$fn__58690.invoke(font_gen.clj:65)
	at clojure.core$map$fn__5851.invoke(core.clj:2755)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.Cons.next(Cons.java:39)
	at clojure.lang.RT.next(RT.java:709)
	at clojure.core$next__5371.invokeStatic(core.clj:64)
	at clojure.core.protocols$fn__8144.invokeStatic(protocols.clj:169)
	at clojure.core.protocols$fn__8144.invoke(protocols.clj:124)
	at clojure.core.protocols$fn__8099$G__8094__8108.invoke(protocols.clj:19)
	at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:31)
	at clojure.core.protocols$fn__8131.invokeStatic(protocols.clj:75)
	at clojure.core.protocols$fn__8131.invoke(protocols.clj:75)
	at clojure.core.protocols$fn__8073$G__8068__8086.invoke(protocols.clj:13)
	at clojure.core$transduce.invokeStatic(core.clj:6884)
	at clojure.core$transduce.invokeStatic(core.clj:6879)
	at editor.pipeline.font_gen$concat_byte_buffers.invokeStatic(font_gen.clj:38)
	at editor.pipeline.font_gen$compress.invokeStatic(font_gen.clj:57)
	at editor.font$build_font.invokeStatic(font.clj:486)
	at editor.font$build_font.invoke(font.clj:482)
	at editor.pipeline$build_BANG_$fn__17037.invoke(pipeline.clj:201)
	at clojure.core$map$fn__5851.invoke(core.clj:2755)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.RT.seq(RT.java:531)
	at clojure.core$seq__5387.invokeStatic(core.clj:137)
	at clojure.core$dorun.invokeStatic(core.clj:3133)
	at clojure.core$doall.invokeStatic(core.clj:3148)
	at editor.pipeline$batched_pmap$fn__17030.invoke(pipeline.clj:174)
	at clojure.core$pmap$fn__8447$fn__8448.invoke(core.clj:7022)
	... 6 common frames omitted
```

**Comment by britzl** [comment]
Documentation for `Native.register()`:

> When called from a class static initializer, maps all native methods found within that class to native libraries via the JNA raw calling interface.

On the lines before the call to Native.register() we add a few paths which I believe are used when searching for the texc library:

https://github.com/defold/defold/blob/dev/com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/TexcLibrary.java#L50-L52

It would be interesting to either set a breakpoint and see what path it is or print it. Is there for some reason a problem that prevents the call to Native.register() from loading the library at that path? Permissions? Weird file path or characters?

**Comment by BikiniKnight** [comment]
Thanks everyone!
The problem was this:
_Caused by: java.lang.UnsatisfiedLinkError: /tmp/jna-3506402/jna16952893420983322375.tmp: /tmp/jna-3506402/jna16952893420983322375.tmp: сбой отображения сегмента из разделяемого объекта_

On /tmp was the mounted option "noexec". Dumped remounting and that solved the problem:
_sudo mount -o remount,exec /tmp_
