### ISSUE TITLE
What is this

### ISSUE THREAD

**Issue by Nekele4** [defold/defold#5712]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2021-03-27T07:32:49.667321</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>c89efe0dcac970ec71f153f0d4ed0c89fee55059</td></tr>
<tr><td>Defold engine sha</td><td>f34b08dc12af1101ae62c6e880b6373a03206174</td></tr>
<tr><td>Defold version</td><td>1.2.180</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"f06be5a4f5d546908818d4db97de3f77"'>f06be5a4f5d546908818d4db97de3f77</a></td></tr>
<tr><td>GPU</td><td>GeForce RTX 2060 SUPER/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 456.71</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by britzl** [comment]
When did this start happening? After an editor update? Does it happen for all projects?

```
com.sun.jna.Native.open.class java.lang.Error: Access is denied.

    at com.sun.jna.Native.open(Native.java)
    at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:171)
    at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:398)
    at com.sun.jna.Native.register(Native.java:1396)
    at com.sun.jna.Native.register(Native.java:1156)
    at com.dynamo.bob.TexcLibrary.<clinit>(TexcLibrary.java:53)
    at com.dynamo.bob.pipeline.TextureGenerator.generateFromColorAndFormat(TextureGenerator.java:240)
    at com.dynamo.bob.pipeline.TextureGenerator.generate(TextureGenerator.java:428)
    at editor.pipeline.tex_gen$make_texture_image.invokeStatic(tex_gen.clj:58)
    at editor.pipeline.tex_gen$make_texture_image.invoke(tex_gen.clj:51)
    at editor.pipeline.tex_gen$make_texture_image.invokeStatic(tex_gen.clj:55)
    at editor.pipeline.tex_gen$make_preview_texture_image.invokeStatic(tex_gen.clj:76)
    at editor.atlas$fn.invokeStatic(atlas.clj:577)
    at editor.atlas$fn.invoke(atlas.clj:577)
    at clojure.lang.AFn.applyToHelper(AFn.java:154)
    at clojure.lang.AFn.applyTo(AFn.java:144)
    at clojure.lang.AFunction$1.doInvoke(AFunction.java:31)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at clojure.lang.Var.invoke(Var.java:384)
```

**Comment by Nekele4** [comment]
> When did this start happening? After an editor update? Does it happen for all projects?
> 
> ```
> com.sun.jna.Native.open.class java.lang.Error: Access is denied.
> 
>     at com.sun.jna.Native.open(Native.java)
>     at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:171)
>     at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:398)
>     at com.sun.jna.Native.register(Native.java:1396)
>     at com.sun.jna.Native.register(Native.java:1156)
>     at com.dynamo.bob.TexcLibrary.<clinit>(TexcLibrary.java:53)
>     at com.dynamo.bob.pipeline.TextureGenerator.generateFromColorAndFormat(TextureGenerator.java:240)
>     at com.dynamo.bob.pipeline.TextureGenerator.generate(TextureGenerator.java:428)
>     at editor.pipeline.tex_gen$make_texture_image.invokeStatic(tex_gen.clj:58)
>     at editor.pipeline.tex_gen$make_texture_image.invoke(tex_gen.clj:51)
>     at editor.pipeline.tex_gen$make_texture_image.invokeStatic(tex_gen.clj:55)
>     at editor.pipeline.tex_gen$make_preview_texture_image.invokeStatic(tex_gen.clj:76)
>     at editor.atlas$fn.invokeStatic(atlas.clj:577)
>     at editor.atlas$fn.invoke(atlas.clj:577)
>     at clojure.lang.AFn.applyToHelper(AFn.java:154)
>     at clojure.lang.AFn.applyTo(AFn.java:144)
>     at clojure.lang.AFunction$1.doInvoke(AFunction.java:31)
>     at clojure.lang.RestFn.invoke(RestFn.java:408)
>     at clojure.lang.Var.invoke(Var.java:384)
> ```

I dont know, i just opened the editor and tried to make an atlas but it didnt let me.

**Comment by Nekele4** [comment]
It just happened out of the blue, I don't know why.

**Comment by Nekele4** [comment]
I tried everything,
I deleted it and installed it again
I got it on steam
I made a new project and tried it there
I tried it on other projects, it doesn't work

**Comment by britzl** [comment]
After some troubleshooting on Discord we found that the solution was to Run as Administrator. This has been added to the Windows FAQ
