### ISSUE TITLE
Error on Windows

### ISSUE THREAD

**Issue by ThomasLincoln** [defold/defold#5717]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2021-03-27T07:32:49.667321</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>c89efe0dcac970ec71f153f0d4ed0c89fee55059</td></tr>
<tr><td>Defold engine sha</td><td>f34b08dc12af1101ae62c6e880b6373a03206174</td></tr>
<tr><td>Defold version</td><td>1.2.180</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"6eb1cf8d955749669c5a639dbc546f09"'>6eb1cf8d955749669c5a639dbc546f09</a></td></tr>
<tr><td>GPU</td><td>Intel(R) HD Graphics</td></tr>
<tr><td>GPU Driver</td><td>4.4.0 - Build 20.19.15.4549</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by britzl** [comment]
```
editor.handler$invoke_fnk.invokeStatic.class clojure.lang.ExceptionInfo: handler ':new-file' in context ':global' failed at ':run' with message 'Cannot run program "code" (in directory "C:\Users\ezios\OneDrive\Documentos\Projetos\Jogos\Space Invaders 2.0"): CreateProcess error=2, O sistema não pode encontrar o arquivo especificado'
    at editor.handler$invoke_fnk.invokeStatic(handler.clj:260)
    at editor.handler$run.invokeStatic(handler.clj:287)
    at editor.ui$execute_command.invokeStatic(ui.clj:1158)
    at editor.ui$invoke_handler.invokeStatic(ui.clj:1179)
    at editor.ui$make_menu_command$reify.handle(ui.clj:1262)
    at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
    at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
    at javafx.event.Event.fireEvent(Event.java:198)
    at javafx.scene.control.MenuItem.fire(MenuItem.java:459)
    at com.sun.javafx.scene.control.ContextMenuContent$MenuItemContainer.doSelect(ContextMenuContent.java:1385)
    at com.sun.javafx.scene.control.ContextMenuContent$MenuItemContainer.lambda$createChildren$12(ContextMenuContent.java:1338)
    at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:247)
    at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
    at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
```

**Comment by britzl** [comment]
Does this happen for all projects or just this one?

One thing to try is to rename the project to remove any spaces and dots in the project name.

**Comment by britzl** [comment]
No reply from user. Closing.
