### ISSUE TITLE
Error when opening curve editor

### ISSUE THREAD

**Issue by carlosmpv** [defold/defold#5771]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2021-04-13T06:40:18.508649</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>b004f16e507cef52b6940c6970cbefc0d68722f0</td></tr>
<tr><td>Defold engine sha</td><td>ff5b94e432eb58dabdb8e367bed9acc5e99e129b</td></tr>
<tr><td>Defold version</td><td>1.2.181</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"b41d757ce0124f85bb7dadddd65b10b3"'>b41d757ce0124f85bb7dadddd65b10b3</a></td></tr>
<tr><td>GPU</td><td>Mesa Intel(R) HD Graphics 620 (KBL GT2)</td></tr>
<tr><td>GPU Driver</td><td>OpenGL ES-CM 1.1 Mesa 20.3.2</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>5.8.0-7642-generic</td></tr>
<table>

**Comment by britzl** [comment]
@carlosmpv did you manage to solve this problem by following the recommendation in the [Linux FAQ](https://defold.com/manuals/linux/#faq)?

```
editor.gl$gl_clear.invokeStatic.class java.lang.ClassCastException: class jogamp.opengl.es1.GLES1Impl cannot be cast to class com.jogamp.opengl.GL2ES2 (jogamp.opengl.es1.GLES1Impl and com.jogamp.opengl.GL2ES2 are in unnamed module of loader 'app')
    at editor.gl$gl_clear.invokeStatic(gl.clj:191)
    at editor.scene$render_BANG_.invokeStatic(scene.clj:273)
    at editor.scene$update_image_view_BANG_$fn.invoke(scene.clj:1158)
    at editor.scene$update_image_view_BANG_.invokeStatic(scene.clj:1155)
    at editor.scene$update_image_view_BANG_.invoke(scene.clj:1127)
    at editor.scene$refresh_scene_view_BANG_.invokeStatic(scene.clj:842)
    at editor.app_view$refresh_scene_views_BANG_$fn.invoke(app_view.clj:1370)
    at editor.app_view$refresh_scene_views_BANG_.invokeStatic(app_view.clj:1370)
    at editor.app_view$make_app_view$fn.invoke(app_view.clj:1482)
    at editor.ui$__GT_timer$fn$fn.invoke(ui.clj:1923)
    at clojure.lang.AFn.run(AFn.java:22)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
    at java.security.AccessController.doPrivileged(AccessController.java)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
    at com.sun.glass.ui.gtk.GtkApplication._runLoop(GtkApplication.java)
    at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
    at java.lang.Thread.run(Thread.java:834)
```
