### ISSUE TITLE
ParticleFX Editor stopped working

### ISSUE THREAD

**Issue by paweljarosz** [defold/defold#5812]
### Expected behaviour
No more such occurences.

### Actual behaviour
Particle Editor is not working and responding anymore and is not displaying anything.
![image](https://user-images.githubusercontent.com/11634203/117814319-7091a900-b264-11eb-8222-ed81c77bc1f7.png)

### Steps to reproduce
It happened after a while of using Defold. After Particle Editor of some particlefx seemed to be hanged up for a while (not responding to mouse clicks, but rest of the Editor was working) I closed that editor and opened the same particlefx again. The Error window appeared and I was seeing nothing (as above on the screenshot.

Closing and reopening the Particle Editor does not help. 

Closing and reopening the project solves the issue.

<hr/>

<table>
<tr><td>Build time</td><td>2021-04-13T06:40:35.736479</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>b004f16e507cef52b6940c6970cbefc0d68722f0</td></tr>
<tr><td>Defold engine sha</td><td>ff5b94e432eb58dabdb8e367bed9acc5e99e129b</td></tr>
<tr><td>Defold version</td><td>1.2.181</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"849de7cc0e0649c4b0eec004b3390516"'>849de7cc0e0649c4b0eec004b3390516</a></td></tr>
<tr><td>GPU</td><td>Intel(R) UHD Graphics</td></tr>
<tr><td>GPU Driver</td><td>4.5.0 - Build 26.20.100.7755</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by britzl** [comment]
OpenGL related. Stacktrace:

```
jogamp.opengl.windows.wgl.WindowsWGLContext.createImpl.class com.jogamp.opengl.GLException: Unable to create temp OpenGL context for device context 0x65012532
    at jogamp.opengl.windows.wgl.WindowsWGLContext.createImpl(WindowsWGLContext.java:352)
    at jogamp.opengl.GLContextImpl.makeCurrentWithinLock(GLContextImpl.java:765)
    at jogamp.opengl.GLContextImpl.makeCurrent(GLContextImpl.java:648)
    at jogamp.opengl.GLContextImpl.makeCurrent(GLContextImpl.java:586)
    at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1279)
    at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1147)
    at jogamp.opengl.GLAutoDrawableBase.defaultDisplay(GLAutoDrawableBase.java:476)
    at com.jogamp.opengl.GLAutoDrawableDelegate.display(GLAutoDrawableDelegate.java:190)
    at jogamp.opengl.GLAutoDrawableBase.defaultWindowResizedOp(GLAutoDrawableBase.java:260)
    at jogamp.opengl.GLOffscreenAutoDrawableImpl.setSurfaceSize(GLOffscreenAutoDrawableImpl.java:61)
    at editor.scene$make_gl_pane_BANG_$fn$fn.invoke(scene.clj:1281)
    at editor.scene$make_gl_pane_BANG_$fn.invoke(scene.clj:1271)
    at editor.scene.proxy$com.defold.control.Region$ff19274a.layoutChildren
    at javafx.scene.Parent.layout(Parent.java:1207)
    at javafx.scene.Parent.layout(Parent.java:1214)
    at javafx.scene.Parent.layout(Parent.java:1214)
    at javafx.scene.Parent.layout(Parent.java:1214)
    at javafx.scene.Parent.layout(Parent.java:1214)
    at javafx.scene.Parent.layout(Parent.java:1214)
    at javafx.scene.Parent.layout(Parent.java:1214)
    at javafx.scene.Parent.layout(Parent.java:1214)
    at javafx.scene.Parent.layout(Parent.java:1214)
    at javafx.scene.Parent.layout(Parent.java:1214)
    at javafx.scene.Parent.layout(Parent.java:1214)
    at javafx.scene.Parent.layout(Parent.java:1214)
    at javafx.scene.Parent.layout(Parent.java:1214)
    at javafx.scene.Parent.layout(Parent.java:1214)
    at javafx.scene.Parent.layout(Parent.java:1214)
    at javafx.scene.Parent.layout(Parent.java:1214)
    at javafx.scene.Parent.layout(Parent.java:1214)
    at javafx.scene.Scene.doLayoutPass(Scene.java:576)
    at javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2476)
    at com.sun.javafx.tk.Toolkit.lambda$runPulse$2(Toolkit.java:413)
    at java.security.AccessController.doPrivileged(AccessController.java)
    at com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:412)
    at com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:439)
    at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:563)
    at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:543)
    at com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(QuantumToolkit.java:536)
    at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(QuantumToolkit.java:342)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
    at com.sun.glass.ui.win.WinApplication._runLoop(WinApplication.java)
    at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
    at java.lang.Thread.run(Thread.java:834)
```

**Comment by AGulev** [comment]
can't repo
