### ISSUE TITLE
When swapping to viewing collection in editor from viewing tilemap this error occurred.

### ISSUE THREAD

**Issue by SpencerWF** [defold/defold#5813]
Changed from viewing tilemap in editor to viewing collection.  Was about to place tilemap inside collection when I saw this error. After this error I added the tilemap to the collection, expecting it to appear on screen but it did not appear on screen when viewing the collection.

### Expected behaviour
To see the collection and the tilemap within it.

### Actual behaviour
Error appeared and tilemap was not visible in editor except in the outline.

### Steps to reproduce
Have a pre-created collection, and a tilemap.  View the tilemap then swap to viewing the collection.

<hr/>

<table>
<tr><td>Build time</td><td>2021-02-01T12:51:27.527828</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>6ce404156136f291c4f2c33a72b28f7bd923eb5e</td></tr>
<tr><td>Defold engine sha</td><td>af6a29c2a1e2545e2d033790089c606ac9f0bb7a</td></tr>
<tr><td>Defold version</td><td>1.2.178</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"66eca30ed8704203b206842f0d912292"'>66eca30ed8704203b206842f0d912292</a></td></tr>
<tr><td>GPU</td><td>GeForce GTX 1660 Ti with Max-Q Design/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 460.73.01</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>5.8.0-50-generic</td></tr>
<table>

**Comment by britzl** [comment]
Can you reproduce it each time? What if you try with the latest Defold version (1.2.182)?

OpenGL related. Stacktrace:

```
jogamp.opengl.x11.glx.X11GLXContext.createImpl.class com.jogamp.opengl.GLException: JavaFX Application Thread: createImpl ARB n/a but required, profile > GL2 requested (OpenGL >= 3.1). Requested: GLProfile[GL4bc/GL4bc.hw], current: 4.6 (Compat profile, compat[ES2, ES3, ES31, ES32], FBO, hardware) - 4.6.0 NVIDIA 460.73.01
    at jogamp.opengl.x11.glx.X11GLXContext.createImpl(X11GLXContext.java:440)
    at jogamp.opengl.GLContextImpl.makeCurrentWithinLock(GLContextImpl.java:765)
    at jogamp.opengl.GLContextImpl.makeCurrent(GLContextImpl.java:648)
    at jogamp.opengl.GLContextImpl.makeCurrent(GLContextImpl.java:586)
    at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1279)
    at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1147)
    at jogamp.opengl.GLAutoDrawableBase.defaultDisplay(GLAutoDrawableBase.java:476)
    at com.jogamp.opengl.GLAutoDrawableDelegate.display(GLAutoDrawableDelegate.java:190)
    at jogamp.opengl.GLAutoDrawableBase.defaultWindowResizedOp(GLAutoDrawableBase.java:260)
    at jogamp.opengl.GLOffscreenAutoDrawableImpl.setSurfaceSize(GLOffscreenAutoDrawableImpl.java:61)
    at editor.scene$make_gl_pane_BANG_$fn$fn.invoke(scene.clj:1281)
    at editor.scene$make_gl_pane_BANG_$fn.invoke(scene.clj:1271)
    at editor.scene.proxy$com.defold.control.Region$ff19274a.layoutChildren
    at javafx.scene.Parent.layout(Parent.java:1207)
    at javafx.scene.Parent.layout(Parent.java:1214)
    at javafx.scene.Parent.layout(Parent.java:1214)
    at javafx.scene.Parent.layout(Parent.java:1214)
    at javafx.scene.Parent.layout(Parent.java:1214)
```

**Comment by SpencerWF** [comment]
Upon restarting Defold I haven't seen it since, but I'll try in the next couple days to see if it comes back up.

**Comment by britzl** [comment]
It seems like it was a temporary problem. Closing.
