### ISSUE TITLE
Console in editor stop working. When return long strings in __tostring metamethod in ne.

### ISSUE THREAD

**Issue by d954mas** [defold/defold#5862]
I am working on ne. For now editor throw error for me.For every build. Looks like it something with editor console.
[project.zip](https://github.com/defold/defold/files/6634295/project.zip)

After show error.
Engine not crashed.
Console in editor stop working. Need restart editor.

Console in windows bundle or build html correctly working.

Something wrong with ToString methods in my ne.
Changing size of string fixed it(look on last commit)
lua_pushfstring( L, "Box2DWorld[pointer:%p gravity:{x:%d y:%d}]",(void *) lua_world->world,gravity.x,gravity.y);
lua_pushfstring( L, "b2World[%p]",(void *) lua_world->world);

### Expected behaviour
editor not show error. Console in editor keep working
### Actual behaviour
console in editor stop working. Show error
2021-06-10 23:21:40.781 34688 [HTTP-Dispatcher] INFO  util.http-server - {:line 25, :msg "No handler for '/favicon.ico'"}
2021-06-10 23:24:33.336 207243 [JavaFX Application Thread] ERROR editor.error-reporting - {:line 110}
java.lang.AssertionError: Assert failed: (not (neg? resource-row))
	at editor.console$make_resource_reference_region.invokeStatic(console.clj:366)
	at editor.console$make_line_sub_regions$fn__27919.invoke(console.clj:391)
	at clojure.core$keep$fn__8540$fn__8541.invoke(core.clj:7325)
	at clojure.core$preserving_reduced$fn__8743.invoke(core.clj:7614)
	at clojure.core.protocols$fn__8144.invokeStatic(protocols.clj:168)
	at clojure.core.protocols$fn__8144.invoke(protocols.clj:124)
	at clojure.core.protocols$fn__8099$G__8094__8108.invoke(protocols.clj:19)
	at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:31)
	at clojure.core.protocols$fn__8129.invokeStatic(protocols.clj:75)
	at clojure.core.protocols$fn__8129.invoke(protocols.clj:75)
	at clojure.core.protocols$fn__8073$G__8068__8086.invoke(protocols.clj:13)
	at clojure.core$reduce.invokeStatic(core.clj:6828)
	at clojure.core$cat$fn__8746.invoke(core.clj:7625)
	at clojure.core$map$fn__5847$fn__5848.invoke(core.clj:2742)
	at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
	at clojure.core$transduce.invokeStatic(core.clj:6883)
	at clojure.core$into.invokeStatic(core.clj:6899)
	at editor.console$make_line_sub_regions.invokeStatic(console.clj:378)
	at editor.console$make_line_sub_regions.invoke(console.clj:378)
	at clojure.core$partial$fn__5826.invoke(core.clj:2632)
	at editor.code.data$append_distinct_lines$fn__15824.invoke(data.clj:1983)
	at editor.code.data$append_distinct_lines.invokeStatic(data.clj:1959)
	at editor.console$append_distinct_lines.invokeStatic(console.clj:409)
	at editor.console$append_entries$fn__27938.invoke(console.clj:437)
	at clojure.core.protocols$fn__8144.invokeStatic(protocols.clj:168)
	at clojure.core.protocols$fn__8144.invoke(protocols.clj:124)
	at clojure.core.protocols$fn__8099$G__8094__8108.invoke(protocols.clj:19)
	at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:31)
	at clojure.core.protocols$fn__8131.invokeStatic(protocols.clj:75)
	at clojure.core.protocols$fn__8131.invoke(protocols.clj:75)
	at clojure.core.protocols$fn__8073$G__8068__8086.invoke(protocols.clj:13)
	at clojure.core$reduce.invokeStatic(core.clj:6828)
	at editor.console$append_entries.invokeStatic(console.clj:435)
	at editor.console$repaint_console_view_BANG_.invokeStatic(console.clj:455)
	at editor.console$make_console_BANG_$fn__27953.invoke(console.clj:522)
	at editor.ui$__GT_timer$fn__13995$fn__13996.invoke(ui.clj:1923)
	at clojure.lang.AFn.run(AFn.java:22)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
	at java.base/java.lang.Thread.run(Thread.java:834)
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2021-05-10T09:03:48.033600</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>1a2776dac6a868eed1a35e41acb0c71a7e17948f</td></tr>
<tr><td>Defold engine sha</td><td>1a2776dac6a868eed1a35e41acb0c71a7e17948f</td></tr>
<tr><td>Defold version</td><td>1.2.182</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"b7027fe1ce0842c1b6e211059ec4bce0"'>b7027fe1ce0842c1b6e211059ec4bce0</a></td></tr>
<tr><td>GPU</td><td>GeForce GTX 1070 Ti/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 461.92</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by d954mas** [comment]
looks like something with printf

**Comment by d954mas** [comment]
Sorry, i upload project with fixed commit🤦‍♂️
Can you try prev commit.

**Comment by d954mas** [comment]
Yes, you need build from editor and it crashed

**Comment by d954mas** [comment]
Not on pc now. Not sure that added git to zip file. I can upload bad version, on monday.

Thanks)

**Comment by britzl** [comment]
> I can upload bad version, on monday.

Great! I'll wait for a new version then!

**Comment by d954mas** [comment]
New project. Now it throw error.
I try to make smaller repro case. But can't(

[issue5862.zip](https://github.com/defold/defold/files/6644557/issue5862.zip)

**Comment by d954mas** [comment]
video from my pc
https://user-images.githubusercontent.com/2655263/121820551-26a14600-cc9c-11eb-8134-996a15d2a27a.mp4

**Comment by d954mas** [comment]
```
static int ToString(lua_State *L){
	utils::check_arg_count(L, 1);

	World *lua_world = get_userdata_safe(L, 1);
	b2Vec2 gravity = lua_world->world->GetGravity();

	dmLogInfo("%p",(void *) lua_world->world);
	dmLogInfo("%d",gravity.x);
	dmLogInfo("%d",gravity.y);
	lua_pushfstring( L, "Box2DWorld[pointer:%p gravity:{x:%d y:%d}]",(void *) lua_world->world,gravity.x,gravity.y);
	return 1;
}
```

**Comment by d954mas** [comment]
In my pc. It reproduced every build.

**Comment by d954mas** [comment]
@britzl Hi. Can you reproduce it? :)

**Comment by britzl** [comment]
> Hi. Can you reproduce it? :)

Will try now!

**Comment by britzl** [comment]
It works on macOS:

![Screenshot 2021-06-17 at 07 00 02](https://user-images.githubusercontent.com/1300688/122334289-c4fe0780-cf39-11eb-944f-75ba07d78e3f.png)

Notice in the screenshot that the editor creates a file link for the "y:13" part of the line. I assume you are getting the same error if you print the line from Lua?

```
function init(self)
    print("Box2DWorld[pointer:0x7fefe7940000 gravity:{x:-484277888 y:13}]")
end
```

The line in question in console.clj is this one:

https://github.com/defold/defold/blob/dev/editor/src/clj/editor/console.clj#L366

Which deals with how the clickable parts of a console entry links back to a line of code in a file in the editor. I would have thought this part of the code to be platform independent.

As a workaround you can format that print-out different to not trick the editor into believing it's a link to a project resource and line number. I think if you skip the brackets [].

**Comment by d954mas** [comment]
Thanks.

It correct worked with your string.
print("Box2DWorld[pointer:0x7fefe7940000 gravity:{x:-484277888 y:13}]")
But with that string it throw error
print("Box2DWorld[pointer:0x7fefe7940000 gravity:{x:0 y:0}]")

Strange)  Can you try a second string, please.

**Comment by britzl** [comment]
Yes, now I get the same error. I guess the problem is that there is no line 0. I'll see if we can't fix this.
