### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by drmar** [defold/defold#5875]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2021-06-03T14:13:28.756036</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>d6f017f3deaee89c27612e047a30bd862d3fbb7a</td></tr>
<tr><td>Defold engine sha</td><td>f77b7f655a0ba68462f6c33604bed7000018735f</td></tr>
<tr><td>Defold version</td><td>1.2.183</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"49309b20c8124d02a5425768910b8f6d"'>49309b20c8124d02a5425768910b8f6d</a></td></tr>
<tr><td>GPU</td><td>Intel Iris OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 INTEL-14.7.17</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.15.7</td></tr>
<table>

**Comment by britzl** [comment]
```
com.sun.glass.ui.View$2.flush.class java.lang.UnsupportedOperationException: Flush is forbidden from target!
    at com.sun.glass.ui.View$2.flush(View.java:1022)
    at com.sun.javafx.tk.quantum.QuantumClipboard.flush(QuantumClipboard.java:274)
    at com.sun.javafx.tk.quantum.QuantumToolkit.startDrag(QuantumToolkit.java:1286)
    at javafx.scene.Scene$DnDGesture.dragDetectedProcessed(Scene.java:3043)
    at javafx.scene.Scene$DnDGesture.process(Scene.java:3112)
    at javafx.scene.Scene$MouseHandler.process(Scene.java:3872)
    at javafx.scene.Scene.processMouseEvent(Scene.java:1851)
    at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2584)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:409)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:299)
    at java.security.AccessController.doPrivileged(AccessController.java)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:447)
    at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:412)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:446)
    at com.sun.glass.ui.View.handleMouseEvent(View.java:556)
    at com.sun.glass.ui.View.notifyMouse(View.java:942)
    at com.sun.glass.ui.mac.MacView.notifyMouse(MacView.java:127)
```

**Comment by britzl** [comment]
What did you do when the error occurred?

**Comment by drmar** [comment]
I dragged and dropped a png file in a Defold folder, nothing else.

**Comment by AGulev** [comment]
Still possible to reproduce in 1.8.0 dragging to bulletins (not from the first attempt but pretty easy)
if it's so freq. Issue and have a repro, maybe we should add it into one of the next versions @britzl ?

**Comment by AGulev** [comment]
after a few attempts:

https://github.com/defold/defold/assets/2209596/2b841318-562f-4184-ba8c-57e5eae104a6
