### ISSUE TITLE
Error appears when clicking the "From Template"

### ISSUE THREAD

**Issue by KuhinaHiruko** [defold/defold#5890]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2021-01-16T10:47:07.405749</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>3d2d4932d02dabc7e57fd25fac275b0a6dc59158</td></tr>
<tr><td>Defold engine sha</td><td>af6a29c2a1e2545e2d033790089c606ac9f0bb7a</td></tr>
<tr><td>Defold version</td><td>1.2.178</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"3f319e5c687d49f7a0d21ef5709cc7ae"'>3f319e5c687d49f7a0d21ef5709cc7ae</a></td></tr>
<tr><td>GPU</td><td>Intel(R) HD Graphics 4400</td></tr>
<tr><td>GPU Driver</td><td>4.3.0 - Build 20.19.15.4300</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by britzl** [comment]
```java.net.AbstractPlainSocketImpl.connect.class java.net.UnknownHostException: www.w3.org
    at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:220)
    at java.net.Socket.connect(Socket.java:591)
    at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
    at sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
    at sun.net.www.http.HttpClient.openServer(HttpClient.java:569)
    at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
    at sun.net.www.http.HttpClient.New(HttpClient.java:341)
    at sun.net.www.http.HttpClient.New(HttpClient.java:362)
    at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1242)
    at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1181)
    at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1075)
    at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1009)
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1581)
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1509)
    at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.setupCurrentEntity(XMLEntityManager.java:678)
    at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.startEntity(XMLEntityManager.java:1401)
    at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.startDTDEntity(XMLEntityManager.java:1367)
    at com.sun.org.apache.xerces.internal.impl.XMLDTDScannerImpl.setInputSource(XMLDTDScannerImpl.java:257)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$DTDDriver.dispatch(XMLDocumentScannerImpl.java:1152)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$DTDDriver.next(XMLDocumentScannerImpl.java:1040)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:943)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:534)
    at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:888)
    at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:824)
    at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
    at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1216)
    at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:635)
    at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:324)
    at javax.xml.parsers.SAXParser.parse(SAXParser.java:197)```

The error happened due to a network connectivity issue trying to reach w3.org. Most likely when parsing an SVG which references the xmlns on w3.org:

https://github.com/defold/defold/blob/dev/editor/resources/welcome/images/desktop.svg?short_path=84f99ca#L1

@KuhinaHiruko Please check your network connectivity and ensure that you allow the Defold editor to make network connections.

**Comment by britzl** [comment]
Duplicate of https://github.com/defold/defold/issues/5533
