### ISSUE TITLE
Defold Crashing When Opening Atlas

### ISSUE THREAD

**Issue by RilDev** [defold/defold#5913]
### Expected behaviour
I just expected it to open my atlas to delete some files

### Actual behaviour
Nothing seems to work, Defold lags and crashes

### Steps to reproduce
I tried to open Defold twice, in two separate windows to copy some code over. Maybe that's where the sluggishness steams from. 

<hr/>

<table>
<tr><td>Build time</td><td>2021-06-29T18:27:45.303169</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>f881dd144800691f7c8e5f06c6c8aabc101435e6</td></tr>
<tr><td>Defold engine sha</td><td>1f5712609c345f870b691a85d611d4825d22a718</td></tr>
<tr><td>Defold version</td><td>1.2.184</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"cd372d0eb4bd46df9937db5a862bfc3c"'>cd372d0eb4bd46df9937db5a862bfc3c</a></td></tr>
<tr><td>GPU</td><td>Mesa DRI Intel(R) HD Graphics 630 (KBL GT2)</td></tr>
<tr><td>GPU Driver</td><td>3.0 Mesa 20.2.6</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>5.8.0-59-generic</td></tr>
<table>

**Comment by RilDev** [comment]
Update: I'm now trying to do animations with 1080X3000 pixels images (for backgrounds), with a weight per image of 96ko. Is it normal that my computer lags so much ? It's the first time I encounter this type of issue.

Should I reduce the size of my image? If yes, what is the recommended limit?

Thank you very much!

**Comment by britzl** [comment]
> I'm now trying to do animations with 1080X3000 pixels images (for backgrounds), with a weight per image of 96ko. Is it normal that my computer lags so much ? It's the first time I encounter this type of issue.
> 
> Should I reduce the size of my image? If yes, what is the recommended limit?

How many images of that size do you have? Using several such images in an atlas quickly results in a really large atlas that may not work. The total atlas size should be visible when you edit it.

**Comment by britzl** [comment]
Stacktrace:

```
editor.resource_update$resource_change_plan.invokeStatic.class java.lang.AssertionError: Assert failed: ["/assets"]
(not (seq unknown-changed))
    at editor.resource_update$resource_change_plan.invokeStatic(resource_update.clj:241)
    at editor.defold_project$handle_resource_changes.invokeStatic(defold_project.clj:540)
    at editor.defold_project.ProjectResourceListener.handle_changes(defold_project.clj:709)
    at editor.workspace$resource_sync_BANG_$fn.invoke(workspace.clj:323)
    at editor.workspace$resource_sync_BANG_.invokeStatic(workspace.clj:317)
    at editor.disk$start_reload_job_BANG_$fn$fn.invoke(disk.clj:84)
    at clojure.lang.AFn.run(AFn.java:22)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
    at java.security.AccessController.doPrivileged(AccessController.java)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
    at com.sun.glass.ui.gtk.GtkApplication._runLoop(GtkApplication.java)
    at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
    at java.lang.Thread.run(Thread.java:834)
```

**Comment by RilDev** [comment]
Hi there, sorry for the late reply!

I have A LOT of big images to import in my game. That's too bad, because I really wanted to use Defold to make this game.

I tried to do the same thing in Godot and it worked perfectly. So I'll be using it from now on.

Thank you for your kind help!

**Comment by britzl** [comment]
Thank you for the update. Best of luck with your game.

**Comment by RilDev** [comment]
Thank you sir!
