### ISSUE TITLE
Error when debugging project.

### ISSUE THREAD

**Issue by BuckeyBoi321** [defold/defold#5991]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2021-07-29T20:48:50.037370</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>0a8d3e879724132afb18d47e0040c2034be07504</td></tr>
<tr><td>Defold engine sha</td><td>0a8d3e879724132afb18d47e0040c2034be07504</td></tr>
<tr><td>Defold version</td><td>1.2.185</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"733ac69da79d4bcb98911bda9f643c3e"'>733ac69da79d4bcb98911bda9f643c3e</a></td></tr>
<tr><td>GPU</td><td>AMD Radeon(TM) Vega 8 Graphics</td></tr>
<tr><td>GPU Driver</td><td>4.5.13587 Compatibility Profile Context 19.40.54.01 26.20.14054.1001</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by britzl** [comment]
```
java.util.concurrent.FutureTask.report.class java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: Java heap space
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:191)
    at clojure.core$deref_future.invokeStatic(core.clj:2300)
    at clojure.core$future_call$reify.deref(core.clj:6974)
    at clojure.core$deref.invokeStatic(core.clj:2320)
    at clojure.core$deref.invoke(core.clj:2306)
    at clojure.core$map$fn.invoke(core.clj:2755)
    at clojure.lang.LazySeq.sval(LazySeq.java:42)
    at clojure.lang.LazySeq.seq(LazySeq.java:58)
    at clojure.lang.RT.seq(RT.java:531)
    at clojure.core$seq__5387.invokeStatic(core.clj:137)
    at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:24)
    at clojure.core.protocols$fn.invokeStatic(protocols.clj:75)
    at clojure.core.protocols$fn.invoke(protocols.clj:75)
    at clojure.core.protocols$fn$G__8068__8086.invoke(protocols.clj:13)
    at clojure.core$reduce.invokeStatic(core.clj:6824)
    at editor.pipeline$batched_pmap.invokeStatic(pipeline.clj:172)
    at editor.pipeline$build_BANG_.invokeStatic(pipeline.clj:187)
    at editor.build$build_project_BANG_.invokeStatic(build.clj:66)
    at editor.app_view$build_project_BANG_.invokeStatic(app_view.clj:745)
    at editor.app_view$async_build_BANG_$fn$fn.invoke(app_view.clj:764)
    at editor.app_view$async_build_BANG_$fn.invoke(app_view.clj:764)
    at clojure.core$binding_conveyor_fn$fn.invoke(core.clj:2030)
    at clojure.lang.AFn.call(AFn.java:18)
    at java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.lang.Thread.run(Thread.java:834)
```

**Comment by britzl** [comment]
@BuckeyBoi321 could you please try and modify your Defold editor config file to increase the heap size used by Java?

https://defold.com/manuals/editor/#q-why-am-i-am-getting-a-javalangoutofmemoryerror-java-heap-space-when-performing-certain-operations

**Comment by AGulev** [comment]
outdated

**Comment by britzl** [comment]
No reply from user. Closing.
