### ISSUE TITLE
Java Error

### ISSUE THREAD

**Issue by grafmariyan** [defold/defold#6050]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2021-09-09T20:26:36.042514</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>71d178069a8fa37a4a52d3b44b98bd7596197e4e</td></tr>
<tr><td>Defold engine sha</td><td>1f748d5b0a84e8b5c58bf747e4c48d153ef77a52</td></tr>
<tr><td>Defold version</td><td>1.2.186</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"8b981447ac4745d1ae5838d9bf6562e9"'>8b981447ac4745d1ae5838d9bf6562e9</a></td></tr>
<tr><td>GPU</td><td>Mesa Intel(R) HD Graphics 500 (APL 2)</td></tr>
<tr><td>GPU Driver</td><td>OpenGL ES-CM 1.1 Mesa 21.0.1</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>5.11.0-34-generic</td></tr>
<table>

**Comment by grafmariyan** [comment]
java.lang.ClassCastException: Unknown

**Comment by britzl** [comment]
```
editor.gl$gl_clear.invokeStatic.class java.lang.ClassCastException: class jogamp.opengl.es1.GLES1Impl cannot be cast to class com.jogamp.opengl.GL2ES2 (jogamp.opengl.es1.GLES1Impl and com.jogamp.opengl.GL2ES2 are in unnamed module of loader 'app')
    at editor.gl$gl_clear.invokeStatic(gl.clj:191)
    at editor.scene$render_BANG_.invokeStatic(scene.clj:273)
    at editor.scene$update_image_view_BANG_$fn.invoke(scene.clj:1158)
    at editor.scene$update_image_view_BANG_.invokeStatic(scene.clj:1155)
    at editor.scene$update_image_view_BANG_.invoke(scene.clj:1127)
    at editor.scene$refresh_scene_view_BANG_.invokeStatic(scene.clj:842)
    at editor.app_view$refresh_scene_views_BANG_$fn.invoke(app_view.clj:1370)
    at editor.app_view$refresh_scene_views_BANG_.invokeStatic(app_view.clj:1370)
    at editor.app_view$make_app_view$fn.invoke(app_view.clj:1482)
    at editor.ui$__GT_timer$fn$fn.invoke(ui.clj:1929)
    at clojure.lang.AFn.run(AFn.java:22)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
    at java.security.AccessController.doPrivileged(AccessController.java)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
    at com.sun.glass.ui.gtk.GtkApplication._runLoop(GtkApplication.java)
    at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
    at java.lang.Thread.run(Thread.java:834)
```

**Comment by britzl** [comment]
@grafmariyan please have a look at this FAQ entry: https://defold.com/manuals/linux/#q-the-defold-editor-crashes-when-opening-a-collection-or-game-object-and-the-crash-refers-to-comjogampopengl

**Comment by gurka** [comment]
> @grafmariyan please have a look at this FAQ entry: https://defold.com/manuals/linux/#q-the-defold-editor-crashes-when-opening-a-collection-or-game-object-and-the-crash-refers-to-comjogampopengl

I'm still getting the ClassCastException even after setting `MESA_GL_VERSION_OVERRIDE` (to 4.6 in my case). Are there any other solutions? And as grafmariyan I'm also on an Intel HD GPU.
