### ISSUE TITLE
Editor crash - JavaFX Application Thread: createImpl ARB

### ISSUE THREAD

**Issue by Grabli66** [defold/defold#6053]
com.jogamp.opengl.GLException: JavaFX Application Thread: createImpl ARB n/a but required, profile > GL2 requested (OpenGL >= 3.1). Requested: GLProfile[GL3bc/GL3bc.hw], current: 3.1 (Compat profile, compat[ES2, ES3], FBO, hardware) - 3.1 Mesa 20.3.0-devel (git-2b977ad 2020-10-06 bionic-oibaf-ppa)

Elementary OS 5.1.7 Hera
<hr/>

<table>
<tr><td>Build time</td><td>2021-09-09T20:26:36.042514</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>71d178069a8fa37a4a52d3b44b98bd7596197e4e</td></tr>
<tr><td>Defold engine sha</td><td>1f748d5b0a84e8b5c58bf747e4c48d153ef77a52</td></tr>
<tr><td>Defold version</td><td>1.2.186</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"a96b2b496dfe4f6684f49594d54de332"'>a96b2b496dfe4f6684f49594d54de332</a></td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>4.15.0-156-generic</td></tr>
<table>

**Comment by britzl** [comment]
```
jogamp.opengl.x11.glx.X11GLXContext.createImpl.class com.jogamp.opengl.GLException: JavaFX Application Thread: createImpl ARB n/a but required, profile > GL2 requested (OpenGL >= 3.1). Requested: GLProfile[GL3bc/GL3bc.hw], current: 3.1 (Compat profile, compat[ES2, ES3], FBO, hardware) - 3.1 Mesa 20.3.0-devel (git-2b977ad 2020-10-06 bionic-oibaf-ppa)
    at jogamp.opengl.x11.glx.X11GLXContext.createImpl(X11GLXContext.java:440)
    at jogamp.opengl.GLContextImpl.makeCurrentWithinLock(GLContextImpl.java:765)
    at jogamp.opengl.GLContextImpl.makeCurrent(GLContextImpl.java:648)
    at jogamp.opengl.GLContextImpl.makeCurrent(GLContextImpl.java:586)
    at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1279)
    at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1147)
    at jogamp.opengl.GLAutoDrawableBase.defaultDisplay(GLAutoDrawableBase.java:476)
    at com.jogamp.opengl.GLAutoDrawableDelegate.display(GLAutoDrawableDelegate.java:190)
    at jogamp.opengl.GLAutoDrawableBase.defaultWindowResizedOp(GLAutoDrawableBase.java:260)
    at jogamp.opengl.GLOffscreenAutoDrawableImpl.setSurfaceSize(GLOffscreenAutoDrawableImpl.java:61)
    at editor.scene$make_gl_pane_BANG_$fn$fn.invoke(scene.clj:1281)
    at editor.scene$make_gl_pane_BANG_$fn.invoke(scene.clj:1271)
    at editor.scene.proxy$com.defold.control.Region$ff19274a.layoutChildren
    at javafx.scene.Parent.layout(Parent.java:1207)
    at javafx.scene.Parent.layout(Parent.java:1214)
    at javafx.scene.Parent.layout(Parent.java:1214)
    at javafx.scene.Parent.layout(Parent.java:1214)
    at javafx.scene.Parent.layout(Parent.java:1214)
    at javafx.scene.Parent.layout(Parent.java:1214)
    at javafx.scene.Parent.layout(Parent.java:1214)
    at javafx.scene.Parent.layout(Parent.java:1214)
    at javafx.scene.Parent.layout(Parent.java:1214)
    at javafx.scene.Parent.layout(Parent.java:1214)
    at javafx.scene.Parent.layout(Parent.java:1214)
    at javafx.scene.Parent.layout(Parent.java:1214)
    at javafx.scene.Parent.layout(Parent.java:1214)
    at editor.app_view$restore_split_positions_BANG_.invokeStatic(app_view.clj:482)
    at editor.boot_open_project$load_stage$fn.invoke(boot_open_project.clj:242)
    at clojure.lang.AFn.run(AFn.java:22)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
    at java.security.AccessController.doPrivileged(AccessController.java)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
    at com.sun.glass.ui.gtk.GtkApplication.enterNestedEventLoopImpl(GtkApplication.java)
    at com.sun.glass.ui.gtk.GtkApplication._enterNestedEventLoop(GtkApplication.java:347)
    at com.sun.glass.ui.Application.enterNestedEventLoop(Application.java:509)
    at com.sun.glass.ui.EventLoop.enter(EventLoop.java:107)
    at com.sun.javafx.tk.quantum.QuantumToolkit.enterNestedEventLoop(QuantumToolkit.java:635)
    at javafx.application.Platform.enterNestedEventLoop(Platform.java:291)
    at editor.fxui$mount_renderer_and_await_result_BANG_.invokeStatic(fxui.clj:228)
    at editor.dialogs$make_load_project_dialog$fn.invoke(dialogs.clj:414)
    at editor.ui$do_run_now.invokeStatic(ui.clj:315)
    at editor.dialogs$make_load_project_dialog.invokeStatic(dialogs.clj:413)
    at editor.boot$open_project_with_progress_dialog.invokeStatic(boot.clj:53)
    at editor.boot$select_project_from_welcome$fn$fn.invoke(boot.clj:74)
    at editor.welcome$show_welcome_dialog_BANG_$close_dialog_and_open_project_BANG___86726.invoke(welcome.clj:592)
    at editor.welcome$show_welcome_dialog_BANG_$download_template_BANG___86728$fn$fn.invoke(welcome.clj:614)
    at clojure.lang.AFn.run(AFn.java:22)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
    at java.security.AccessController.doPrivileged(AccessController.java)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
    at com.sun.glass.ui.gtk.GtkApplication._runLoop(GtkApplication.java)
    at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
    at java.lang.Thread.run(Thread.java:834)
```

**Comment by britzl** [comment]
I'd suggest trying the MESA_OVERRIDE workaround mentioned here:

https://defold.com/manuals/linux/#q-the-defold-editor-crashes-when-opening-a-collection-or-game-object-and-the-crash-refers-to-comjogampopengl
