### ISSUE TITLE
Assert failed: (and root (.isDirectory root))

### ISSUE THREAD

**Issue by Ahmed11zxc** [defold/defold#6059]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2021-09-09T20:27:01.070836</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>71d178069a8fa37a4a52d3b44b98bd7596197e4e</td></tr>
<tr><td>Defold engine sha</td><td>1f748d5b0a84e8b5c58bf747e4c48d153ef77a52</td></tr>
<tr><td>Defold version</td><td>1.2.186</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"35195c97f9dd4d7ba456136a4553fe35"'>35195c97f9dd4d7ba456136a4553fe35</a></td></tr>
<tr><td>GPU</td><td>GeForce GTX 1660 Ti/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 456.71</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by britzl** [comment]
```
editor.resource_watch$make_directory_snapshot.invokeStatic.class java.lang.AssertionError: Assert failed: (and root (.isDirectory root))
    at editor.resource_watch$make_directory_snapshot.invokeStatic(resource_watch.clj:150)
    at editor.resource_watch$make_snapshot_info.invokeStatic(resource_watch.clj:193)
    at editor.workspace$make_snapshot_info.invokeStatic(workspace.clj:239)
    at editor.disk$start_reload_job_BANG_$fn.invoke(disk.clj:78)
    at clojure.core$binding_conveyor_fn$fn.invoke(core.clj:2030)
    at clojure.lang.AFn.call(AFn.java:18)
    at java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.lang.Thread.run(Thread.java:834)
```

@Ahmed11zxc when does this error happen?

**Comment by britzl** [comment]
No additional information provided. Closing.
