### ISSUE TITLE
Editor throws error popup in a loop -> issue with property name starting with an underscore

### ISSUE THREAD

**Issue by Shaunmax** [defold/defold#6070]
### Steps to reproduce

Step 1 : add `go.property("_health" , 100)`
Step 2 : delete `health` - > `go.property("_" , 100)` -> Editor throws error popups in a loop

<hr/>

<table>
<tr><td>Build time</td><td>2021-09-20T09:09:20.306316</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>03b14982258f69eb8a06d28810ae879e16bd63d7</td></tr>
<tr><td>Defold engine sha</td><td>581c6439ae93755a8a6bcf58732c39c724fa193c</td></tr>
<tr><td>Defold version</td><td>1.2.187</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"2bbdf0808cbb455ea0a60c98938af465"'>2bbdf0808cbb455ea0a60c98938af465</a></td></tr>
<tr><td>GPU</td><td>AMD Radeon Pro 5500M OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 ATI-3.10.18</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.15.7</td></tr>
<table>

**Comment by AGulev** [comment]
```
editor.util$capitalize_STAR_.invokeStatic.class java.lang.NullPointerException: Cannot invoke "Object.toString()" because "s" is null
    at editor.util$capitalize_STAR_.invokeStatic(util.clj:36)
    at editor.util$capitalize_STAR_.invoke(util.clj:33)
    at camel_snake_kebab$convert_case.invokeStatic(camel_snake_kebab.clj:46)
    at camel_snake_kebab$fn$convert_case_STAR___13159.invoke(camel_snake_kebab.clj:76)
    at clojure.core$comp$fn.invoke(core.clj:2586)
    at clojure.core$comp$fn.invoke(core.clj:2586)
    at editor.properties$keyword__GT_name.invokeStatic(properties.clj:573)
    at editor.properties$label.invokeStatic(properties.clj:580)
    at editor.properties_view$create_properties_row.invokeStatic(properties_view.clj:882)
    at editor.properties_view$create_properties$fn.invoke(properties_view.clj:942)
    at clojure.core$map_indexed$mapi__8680$fn.invoke(core.clj:7500)
    at clojure.lang.LazySeq.force(LazySeq.java:50)
    at clojure.lang.LazySeq.realize(LazySeq.java:89)
    at clojure.lang.LazySeq.seq(LazySeq.java:106)
    at clojure.lang.RT.seq(RT.java:555)
    at clojure.core$seq__5486.invokeStatic(core.clj:139)
    at clojure.core$dorun.invokeStatic(core.clj:3141)
    at clojure.core$doall.invokeStatic(core.clj:3156)
    at editor.properties_view$create_properties.invokeStatic(properties_view.clj:940)
    at editor.properties_view$make_grid.invokeStatic(properties_view.clj:955)
    at editor.properties_view$make_pane_BANG_$fn.invoke(properties_view.clj:987)
    at editor.properties_view$make_pane_BANG_.invokeStatic(properties_view.clj:979)
    at editor.properties_view$update_pane_BANG_.invokeStatic(properties_view.clj:1026)
    at editor.properties_view$fn$fn.invoke(properties_view.clj:1051)
    at clojure.lang.AFn.run(AFn.java:22)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:456)
    at java.security.AccessController.doPrivileged(AccessController.java:400)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:455)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
```

**Comment by AGulev** [comment]
this has been fixed and I can't reproduce it using 1.12.1
