### ISSUE TITLE
Fail

### ISSUE THREAD

**Issue by nebreywas** [defold/defold#6290]
### Expected behaviour
I clicked on an object in my game that's worked before...

### Actual behaviour
Runtime failed

### Steps to reproduce
Specific game so unable to reproduce -- will continue to test and see what it potentially might be.

<hr/>

<table>
<tr><td>Build time</td><td>2021-12-16T14:45:55.272228</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>09da5fbf86f611727c6f533a6078c0d84f6b8da9</td></tr>
<tr><td>Defold engine sha</td><td>d31d6397a72178541a5ef6e7ef2bed090d828f58</td></tr>
<tr><td>Defold version</td><td>1.2.190</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"604196e198fc43d9b1cb302de2780a46"'>604196e198fc43d9b1cb302de2780a46</a></td></tr>
<tr><td>GPU</td><td>Apple M1 Max</td></tr>
<tr><td>GPU Driver</td><td>2.1 Metal - 76.1</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.16</td></tr>
<table>

**Comment by britzl** [comment]
Has it happened more than once?

```
sun.net.httpserver.ExchangeImpl.bytes.class java.lang.NullPointerException: null
    at sun.net.httpserver.ExchangeImpl.bytes(ExchangeImpl.java:305)
    at sun.net.httpserver.ExchangeImpl.write(ExchangeImpl.java:285)
    at sun.net.httpserver.ExchangeImpl.sendResponseHeaders(ExchangeImpl.java:260)
    at sun.net.httpserver.HttpExchangeImpl.sendResponseHeaders(HttpExchangeImpl.java:85)
    at util.http_server$response__GT_exchange_BANG_.invokeStatic(http_server.clj:48)
    at util.http_server$setup_server_BANG_$reify.handle(http_server.clj:61)
    at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:77)
    at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:82)
    at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:80)
    at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:692)
    at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:77)
    at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:664)
    at sun.net.httpserver.ServerImpl$DefaultExecutor.execute(ServerImpl.java:159)
    at sun.net.httpserver.ServerImpl$Dispatcher.handle(ServerImpl.java:442)
    at sun.net.httpserver.ServerImpl$Dispatcher.run(ServerImpl.java:408)
    at java.lang.Thread.run(Thread.java:834)
```

**Comment by britzl** [comment]
Please re open if you can find clear steps to reproduce!
