### ISSUE TITLE
Editor error after switching branch in terminal Git

### ISSUE THREAD

**Issue by ghost** [defold/defold#6300]
### Expected behaviour
Defold editor assets files update after switching git branch in terminal.
### Actual behaviour
This error occured.
### Steps to reproduce
Switched to terminal.
Typed "git checkout branch_name".
Error occured switching back to the editor.

GIT version : 2.34.1
<hr/>

<table>
<tr><td>Build time</td><td>2021-12-16T14:45:55.272228</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>09da5fbf86f611727c6f533a6078c0d84f6b8da9</td></tr>
<tr><td>Defold engine sha</td><td>d31d6397a72178541a5ef6e7ef2bed090d828f58</td></tr>
<tr><td>Defold version</td><td>1.2.190</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"f737879e0eab497787a0d494d8081bec"'>f737879e0eab497787a0d494d8081bec</a></td></tr>
<tr><td>GPU</td><td>AMD Radeon Pro 5300M OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 ATI-4.6.20</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.16</td></tr>
<table>

**Comment by britzl** [comment]
```
editor.handler$invoke_fnk.invokeStatic.class clojure.lang.ExceptionInfo: handler ':cut' in context ':code-view' failed at ':enabled?' with message 'class clojure.lang.MapEntry cannot be cast to class editor.code.data.CursorRange (clojure.lang.MapEntry and editor.code.data.CursorRange are in unnamed module of loader 'app')'
    at editor.handler$invoke_fnk.invokeStatic(handler.clj:260)
    at editor.handler$enabled_QMARK_.invokeStatic(handler.clj:294)
    at editor.ui$make_menu_item.invokeStatic(ui.clj:1293)
    at editor.ui$make_menu_items$fn.invoke(ui.clj:1309)
    at clojure.core$keep$fn$fn.invoke(core.clj:7325)
```
