### ISSUE TITLE
IDE fails to open project with *.clj file

### ISSUE THREAD

**Issue by aglitchman** [defold/defold#6374]
**Describe the bug (REQUIRED)**
Defold fails to open a project if it contains a file with the `clj` extension.

**To Reproduce (REQUIRED)**
1. Create an empty project.
2. Add an empty file, `test.clj`.
3. Close IDE.
4. Open IDE and the project.

**Expected behavior (REQUIRED)**
IDE should display a popup with an error, at least.

**Defold version (REQUIRED):**
  - Version: 1.2.191
  - Editor SHA1: c317904bd98489a5644163ceecad942e8e8bb94b

**Platforms (REQUIRED):**
 - Platforms: Windows
 - OS: Windows 10

**Minimal repro case project (OPTIONAL):**
[issue_clj_file.zip](https://github.com/defold/defold/files/7994433/issue_clj_file.zip)

**Comment by britzl** [comment]
Crash:

```
2022-03-10 15:31:40.028 INFO  default    editor.workspace - {:line 276, :msg "Loading plugintest.clj"}
Hello!
2022-03-10 15:31:40.078 ERROR default    editor.dialogs - {:line 426}
java.lang.NullPointerException: null
	at editor.workspace$load_plugin_BANG_.invokeStatic(workspace.clj:278)
	at editor.workspace$load_editor_plugins_BANG_$fn__11393.invoke(workspace.clj:285)
	at clojure.core$map$fn__5851.invoke(core.clj:2755)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.RT.seq(RT.java:531)
	at clojure.core$seq__5387.invokeStatic(core.clj:137)
	at clojure.core$dorun.invokeStatic(core.clj:3133)
	at editor.workspace$load_editor_plugins_BANG_.invokeStatic(workspace.clj:281)
	at editor.workspace$resource_sync_BANG_$fn__11473.invoke(workspace.clj:437)
	at editor.workspace$resource_sync_BANG_.invokeStatic(workspace.clj:433)
	at editor.workspace$resource_sync_BANG_.invoke(workspace.clj:365)
	at editor.workspace$resource_sync_BANG_.invokeStatic(workspace.clj:374)
	at editor.workspace$resource_sync_BANG_.invoke(workspace.clj:365)
	at editor.workspace$resource_sync_BANG_.invokeStatic(workspace.clj:369)
	at editor.workspace$resource_sync_BANG_.invoke(workspace.clj:365)
	at editor.workspace$resource_sync_BANG_.invokeStatic(workspace.clj:367)
	at editor.boot_open_project$setup_workspace.invokeStatic(boot_open_project.clj:84)
	at editor.boot_open_project$open_project.invokeStatic(boot_open_project.clj:400)
	at editor.boot_open_project$open_project.invoke(boot_open_project.clj:398)
	at clojure.lang.AFn.applyToHelper(AFn.java:171)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:665)
	at editor.boot$open_project_with_progress_dialog$fn__87642.invoke(boot.clj:58)
	at editor.dialogs$make_load_project_dialog$fn__25038$fn__25041.invoke(dialogs.clj:424)
	at clojure.core$binding_conveyor_fn$fn__5739.invoke(core.clj:2030)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
2022-03-10 15:31:40.085 ERROR default    editor.error-reporting - {:line 112}
java.lang.NullPointerException: null
	at editor.workspace$load_plugin_BANG_.invokeStatic(workspace.clj:278)
	at editor.workspace$load_editor_plugins_BANG_$fn__11393.invoke(workspace.clj:285)
	at clojure.core$map$fn__5851.invoke(core.clj:2755)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.RT.seq(RT.java:531)
	at clojure.core$seq__5387.invokeStatic(core.clj:137)
	at clojure.core$dorun.invokeStatic(core.clj:3133)
	at editor.workspace$load_editor_plugins_BANG_.invokeStatic(workspace.clj:281)
	at editor.workspace$resource_sync_BANG_$fn__11473.invoke(workspace.clj:437)
	at editor.workspace$resource_sync_BANG_.invokeStatic(workspace.clj:433)
	at editor.workspace$resource_sync_BANG_.invoke(workspace.clj:365)
	at editor.workspace$resource_sync_BANG_.invokeStatic(workspace.clj:374)
	at editor.workspace$resource_sync_BANG_.invoke(workspace.clj:365)
	at editor.workspace$resource_sync_BANG_.invokeStatic(workspace.clj:369)
	at editor.workspace$resource_sync_BANG_.invoke(workspace.clj:365)
	at editor.workspace$resource_sync_BANG_.invokeStatic(workspace.clj:367)
	at editor.boot_open_project$setup_workspace.invokeStatic(boot_open_project.clj:84)
	at editor.boot_open_project$open_project.invokeStatic(boot_open_project.clj:400)
	at editor.boot_open_project$open_project.invoke(boot_open_project.clj:398)
	at clojure.lang.AFn.applyToHelper(AFn.java:171)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:665)
	at editor.boot$open_project_with_progress_dialog$fn__87642.invoke(boot.clj:58)
	at editor.dialogs$make_load_project_dialog$fn__25038$fn__25041.invoke(dialogs.clj:424)
	at clojure.core$binding_conveyor_fn$fn__5739.invoke(core.clj:2030)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
