### ISSUE TITLE
Update available can't update

### ISSUE THREAD

**Issue by wangdong20** [defold/defold#6517]
**Describe the bug (REQUIRED)**
Update available shows. Click it, it start update but then update available shows again. No update happened.

**To Reproduce (REQUIRED)**
See the screenshot video.

**Expected behavior (REQUIRED)**
Update should success and prompt to restart Defold.

**Defold version (REQUIRED):**
  1.3.0

**Platforms (REQUIRED):**
 - Platforms: macOS
 - OS: 12.1
 - Device: Mac Pro

**Screenshots (OPTIONAL):**
https://user-images.githubusercontent.com/3376491/162624847-bc456c9d-ee7e-4b23-9652-525946f20e68.mov

**Comment by britzl** [comment]
@wangdong20 what if you start the editor from a terminal? What does the output in the terminal say?

```
$> /Applications/Defold.app/Contents/MacOS/Defold
```

**Comment by wangdong20** [comment]
> @wangdong20 what if you start the editor from a terminal? What does the output in the terminal say?
> 
> ```
> $> /Applications/Defold.app/Contents/MacOS/Defold
> ```

After I click download update, it give me this.
`2022-04-12 16:53:00.624 INFO  default    editor.updater - {:line 213, :message "Update download failed"}
java.net.SocketTimeoutException: Read timed out
	at java.base/java.net.SocketInputStream.socketRead0(Native Method)
	at java.base/java.net.SocketInputStream.socketRead(SocketInputStream.java:115)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:168)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
	at java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:252)
	at java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:292)
	at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:351)
	at java.base/sun.net.www.MeteredStream.read(MeteredStream.java:134)
	at java.base/java.io.FilterInputStream.read(FilterInputStream.java:133)
	at java.base/sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3495)
	at java.base/sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3488)
	at clojure.java.io$fn__11500.invokeStatic(io.clj:305)
	at clojure.java.io$fn__11500.invoke(io.clj:302)
	at clojure.lang.MultiFn.invoke(MultiFn.java:239)
	at clojure.java.io$copy.invokeStatic(io.clj:406)
	at clojure.java.io$copy.doInvoke(io.clj:391)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at util.net$download_BANG_.invokeStatic(net.clj:62)
	at util.net$download_BANG_.doInvoke(net.clj:32)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at util.net$download_BANG_.invokeStatic(net.clj:48)
	at editor.updater$download_BANG_.invokeStatic(updater.clj:129)
	at editor.updater$download_and_extract_BANG_$fn__72733.invoke(updater.clj:205)
	at clojure.core$binding_conveyor_fn$fn__5739.invoke(core.clj:2030)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)`

**Comment by britzl** [comment]
Thanks. Could there possibly be something preventing your computer from downloading the update? Are you able to access d.defold.com for instance?

**Comment by wangdong20** [comment]
> d.defold.com

Yes, but it shows unsafe link in my browser.

**Comment by britzl** [comment]
Network security software? Out of scope for what we can solve from here. Closing.
