### ISSUE TITLE
not closing showing error that I cannot understand

### ISSUE THREAD

**Issue by programmerworst1** [defold/defold#6523]
### Expected behaviour
to close app
### Actual behaviour
not closing showing [ com.google.protobuf.UninitializedMessageException: Message missing required fields: input ]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2021-10-18T08:40:34.121967</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>6bfeea3b13d7b8920483ea2cba9c181a8650b84d</td></tr>
<tr><td>Defold engine sha</td><td>6bfeea3b13d7b8920483ea2cba9c181a8650b84d</td></tr>
<tr><td>Defold version</td><td>1.2.188</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"baebbe444a864f2e9436e63c0d2a9ec4"'>baebbe444a864f2e9436e63c0d2a9ec4</a></td></tr>
<tr><td>GPU</td><td>Radeon RX 580 Series</td></tr>
<tr><td>GPU Driver</td><td>4.5.13587 Compatibility Profile Context 20.4.2 26.20.15029.27017</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by britzl** [comment]
```
com.google.protobuf.AbstractMessage$Builder.newUninitializedMessageException.class com.google.protobuf.UninitializedMessageException: Message missing required fields: input
    at com.google.protobuf.AbstractMessage$Builder.newUninitializedMessageException(AbstractMessage.java:550)
    at com.dynamo.input.proto.Input$TouchTrigger$Builder.build(Input.java:3629)
    at com.dynamo.input.proto.Input$TouchTrigger$Builder.build(Input.java:3585)
    at editor.protobuf$pb_builder_raw$builder_fn.invoke(protobuf.clj:420)
    at clojure.core$mapv$fn.invoke(core.clj:6912)
    at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
    at clojure.core$reduce.invokeStatic(core.clj:6827)
    at clojure.core$mapv.invokeStatic(core.clj:6903)
    at clojure.core$mapv.invoke(core.clj:6903)
    at clojure.core$partial$fn.invoke(core.clj:2624)
    at editor.protobuf$pb_builder_raw$fn$fn.invoke(protobuf.clj:411)
    at editor.protobuf$pb_builder_raw$builder_fn.invoke(protobuf.clj:419)
    at editor.protobuf$map__GT_pb.invokeStatic(protobuf.clj:431)
    at editor.protobuf$map__GT_str.invokeStatic(protobuf.clj:554)
    at editor.protobuf$map__GT_str.invoke(protobuf.clj:554)
    at editor.protobuf$map__GT_str.invokeStatic(protobuf.clj:555)
    at editor.protobuf$map__GT_str.invoke(protobuf.clj:554)
...
```

**Comment by britzl** [comment]
@programmerworst1 When did this happen? Can you reproduce the problem again?

**Comment by AGulev** [comment]
The exmplanation wasn't provided
