### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by stone-age-jazz** [defold/defold#6526]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2022-04-05T08:30:44.734482</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>06bc078e490fd7d94ec01e38abac989f6cc351a5</td></tr>
<tr><td>Defold engine sha</td><td>06bc078e490fd7d94ec01e38abac989f6cc351a5</td></tr>
<tr><td>Defold version</td><td>1.3.1</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"209b422850d24008868ed6977e7942be"'>209b422850d24008868ed6977e7942be</a></td></tr>
<tr><td>GPU</td><td>Apple M1</td></tr>
<tr><td>GPU Driver</td><td>2.1 Metal - 76.3</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.16</td></tr>
<table>

**Comment by stone-age-jazz** [comment]
I was editing a script when I pressed "Shift + Tab" then this error showed up:

"clojure.lang.ExceptionInfo: handler ':backwards-tab-trigger' in context ':code-view' failed at ':run' with message 'null'
java.lang.NullPointerException: Unknown"

**Comment by britzl** [comment]
```
editor.handler$invoke_fnk.invokeStatic.class clojure.lang.ExceptionInfo: handler ':backwards-tab-trigger' in context ':code-view' failed at ':run' with message 'null'
    at editor.handler$invoke_fnk.invokeStatic(handler.clj:262)
    at editor.handler$run.invokeStatic(handler.clj:289)
    at editor.ui$execute_command.invokeStatic(ui.clj:1166)
    at editor.ui$invoke_handler.invokeStatic(ui.clj:1187)
    at editor.ui$invoke_handler.invoke(ui.clj:1181)
    at editor.ui$invoke_handler.invokeStatic(ui.clj:1183)
    at editor.keymap$execute_command$fn.invoke(keymap.clj:595)
    at clojure.lang.AFn.run(AFn.java:22)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:457)
    at java.security.AccessController.doPrivileged(AccessController.java)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:456)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
```

**Comment by britzl** [comment]
@stone-age-jazz does it happen all the time or just once?

**Comment by stone-age-jazz** [comment]
It seems to be happening only after I've been using Defold for a while.

**Comment by britzl** [comment]
Not enough information to investigate. Also an old issue. Is it still a problem?
