### ISSUE TITLE
Negative Array Error

### ISSUE THREAD

**Issue by stone-age-jazz** [defold/defold#6527]
### Steps to reproduce
I was trying to load around 150 PNG files in an atlas.
<hr/>

<table>
<tr><td>Build time</td><td>2022-04-05T08:30:44.734482</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>06bc078e490fd7d94ec01e38abac989f6cc351a5</td></tr>
<tr><td>Defold engine sha</td><td>06bc078e490fd7d94ec01e38abac989f6cc351a5</td></tr>
<tr><td>Defold version</td><td>1.3.1</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"dce037210fce4312b3cbbce88f653c06"'>dce037210fce4312b3cbbce88f653c06</a></td></tr>
<tr><td>GPU</td><td>Apple M1</td></tr>
<tr><td>GPU Driver</td><td>2.1 Metal - 76.3</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.16</td></tr>
<table>

**Comment by britzl** [comment]
```
java.awt.image.DataBufferByte.<init>.class java.lang.NegativeArraySizeException: -2147483648
    at java.awt.image.DataBufferByte.<init>(DataBufferByte.java:76)
    at java.awt.image.Raster.createInterleavedRaster(Raster.java:266)
    at java.awt.image.BufferedImage.<init>(BufferedImage.java:391)
    at com.dynamo.bob.textureset.TextureSetGenerator.layoutImages(TextureSetGenerator.java:345)
    at editor.pipeline.texture_set_gen$layout_images.invokeStatic(texture_set_gen.clj:68)
    at editor.atlas$generate_packed_image.invokeStatic(atlas.clj:505)
    at editor.atlas$generate_packed_image.invoke(atlas.clj:497)
    at editor.atlas$call_generator.invokeStatic(atlas.clj:495)
    at editor.atlas$fn.invokeStatic(atlas.clj:640)
    at editor.atlas$fn.invoke(atlas.clj:640)
    at clojure.lang.AFn.applyToHelper(AFn.java:154)
    at clojure.lang.AFn.applyTo(AFn.java:144)
    at clojure.lang.AFunction$1.doInvoke(AFunction.java:31)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at clojure.lang.Var.invoke(Var.java:384)
    at editor.atlas$AtlasNode$behavior$packed_image$fn.invoke(atlas.clj:575)
    at internal.node$trace_expr.invokeStatic(node.clj:43)
    at editor.atlas$AtlasNode$behavior$packed_image.invokeStatic(atlas.clj:575)
    at editor.atlas$AtlasNode$behavior$packed_image.invoke(atlas.clj:575)
    at clojure.lang.Var.invoke(Var.java:393)
```

**Comment by britzl** [comment]
Does it happen all the time or just once? With all images or just one?

**Comment by stone-age-jazz** [comment]
It only happened to me once when I was trying to load 150+ PNG files in an atlas. Never tried to fit so many before.

**Comment by stone-age-jazz** [comment]
![Screenshot 2022-04-16 at 11 32 24](https://user-images.githubusercontent.com/72341496/163668266-4e8e36c7-2b33-477f-b2e8-c2d203c72709.png)

There is also this error showing up, but Defold is completely frozen at this point so I can't report it.

**Comment by britzl** [comment]
Test: Add many really large images. How does the editor behave?

**Comment by AGulev** [comment]
requested info wasn't provided. If you are able to provide more info, please feel free to reopen the issue
