### ISSUE TITLE
Copying error?

### ISSUE THREAD

**Issue by nebreywas** [defold/defold#6564]
### Expected behaviour
I copied a gui file from one project to the other using finder... this created an error --

### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2022-04-21T12:53:52.515047</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>9df2b26c5a6ce8e23b0294d2fecd671f7326c108</td></tr>
<tr><td>Defold engine sha</td><td>06bc078e490fd7d94ec01e38abac989f6cc351a5</td></tr>
<tr><td>Defold version</td><td>1.3.1</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"193d7f7b045b4a2aac78f57cf5e1e428"'>193d7f7b045b4a2aac78f57cf5e1e428</a></td></tr>
<tr><td>GPU</td><td>Apple M1 Max</td></tr>
<tr><td>GPU Driver</td><td>2.1 Metal - 76.1</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.16</td></tr>
<table>

**Comment by britzl** [comment]
```
clojure.lang.Numbers.double_array.class java.lang.NullPointerException: null
    at clojure.lang.Numbers.double_array(Numbers.java:1236)
    at editor.geom$coords__GT_Point3d.invokeStatic(geom.clj:306)
    at editor.geom$coords__GT_aabb.invokeStatic(geom.clj:308)
    at editor.gui$fn.invokeStatic(gui.clj:2196)
    at editor.gui$fn.invoke(gui.clj:2194)
    at clojure.lang.AFn.applyToHelper(AFn.java:154)
    at clojure.lang.AFn.applyTo(AFn.java:144)
    at clojure.lang.AFunction$1.doInvoke(AFunction.java:31)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at clojure.lang.Var.invoke(Var.java:384)
    at editor.gui$GuiSceneNode$behavior$scene$fn.invoke(gui.clj:2306)
    at internal.node$trace_expr.invokeStatic(node.clj:43)
    at editor.gui$GuiSceneNode$behavior$scene.invokeStatic(gui.clj:2306)
    at editor.gui$GuiSceneNode$behavior$scene.invoke(gui.clj:2306)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:285)
...
```

**Comment by AGulev** [comment]
related to https://github.com/defold/defold/issues/3962

**Comment by AGulev** [comment]
This is a very old issue without repro steps. It's hard to act on it.

## Status

Possibly outdated/fixed

## Evidence

- GitHub still shows the issue as `OPEN` with `bug` and `editor` labels, but the report has no reliable reproduction steps and only one diagnostic comment with the old stack trace.
- The crash frame was in `geom/coords->Point3d`, but current GUI node loading no longer needs copied files to provide explicit size data: GUI nodes are instantiated from declared properties in `editor/src/clj/editor/gui.clj:4143`, while shape and text nodes define default `:manual-size` values in `editor/src/clj/editor/gui.clj:1777` and `editor/src/clj/editor/gui.clj:2056`.
- Current GUI code explicitly falls back to `geom/empty-bounding-box` when a template or particlefx source scene is missing in `editor/src/clj/editor/gui.clj:2355` and `editor/src/clj/editor/gui.clj:2447`, which avoids propagating missing-scene data into AABB calculations.
- The integration tests in `editor/test/integration/gui_test.clj:729` and `editor/test/integration/gui_test.clj:779` cover broken GUI resources, including imported template scenes with missing font, layer, texture, and particlefx references, and they assert recovery behavior instead of crashes.
- The current issue discussion does not contain any recent confirmation that the original Finder-copy scenario still reproduces on modern editor builds.

## Why I think it may already be fixed

The reported crash is consistent with older GUI import/loading code letting malformed or incomplete scene data reach AABB construction. In the current codebase, the likely failure modes from copying a `.gui` file between projects are handled more defensively: node properties have defaults, missing imported/template scenes fall back to empty bounds, and there are regression-style tests for broken GUI resource references in both direct and template-based scenes. I cannot prove the original Finder workflow end-to-end here, but the current code strongly suggests the old crash path has been closed.
