### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by IbrahimHamwi** [defold/defold#6574]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2022-04-21T12:53:01.210447</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>9df2b26c5a6ce8e23b0294d2fecd671f7326c108</td></tr>
<tr><td>Defold engine sha</td><td>06bc078e490fd7d94ec01e38abac989f6cc351a5</td></tr>
<tr><td>Defold version</td><td>1.3.1</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"e5688b2ce22f41419a46f4b09774b264"'>e5688b2ce22f41419a46f4b09774b264</a></td></tr>
<tr><td>GPU</td><td>Intel(R) Iris(R) Xe Graphics</td></tr>
<tr><td>GPU Driver</td><td>4.5.0 - Build 30.0.100.9805</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by britzl** [comment]
```
internal.transaction$call_setter_fn.invokeStatic.class java.lang.Exception: Setter of node 72057594037928460 (editor.gui/TemplateNode) :template could not be called
    at internal.transaction$call_setter_fn.invokeStatic(transaction.clj:427)
    at internal.transaction$invoke_setter$fn.invoke(transaction.clj:455)
    at internal.transaction$invoke_setter.invokeStatic(transaction.clj:455)
    at internal.transaction$apply_defaults.invokeStatic(transaction.clj:463)
    at internal.transaction$ctx_add_node.invokeStatic(transaction.clj:471)
    at internal.transaction$fn.invokeStatic(transaction.clj:480)
    at internal.transaction$fn.invoke(transaction.clj:479)
    at clojure.lang.MultiFn.invoke(MultiFn.java:234)
    at internal.transaction$apply_tx$fn.invoke(transaction.clj:632)
    at internal.transaction$apply_tx.invokeStatic(transaction.clj:632)
    at internal.transaction$apply_tx.invoke(transaction.clj:622)
    at internal.transaction$apply_tx.invokeStatic(transaction.clj:629)
    at internal.transaction$apply_tx.invoke(transaction.clj:622)
    at internal.transaction$apply_tx.invokeStatic(transaction.clj:629)
    at internal.transaction$transact_STAR_.invokeStatic(transaction.clj:699)
    at dynamo.graph$transact.invokeStatic(graph.clj:145)
    at editor.defold_project$load_nodes_BANG_.invokeStatic(defold_project.clj:176)
```

**Comment by britzl** [comment]
@IbrahimHamwi Are you able to reproduce this problem repeatedly?

**Comment by Jhonnyg** [comment]
Too stale and not enough information, closing this for now.
