### ISSUE TITLE
Resolving libraries - SSLHandshakeException: Remote host terminated the handshake

### ISSUE THREAD

**Issue by FarikAlex** [defold/defold#6585]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2022-05-02T08:45:09.085569</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>563d19f88cdf76ddd11128859aada8c6541c9a97</td></tr>
<tr><td>Defold engine sha</td><td>287c945fab310c324493e08b191ee1b1538ef973</td></tr>
<tr><td>Defold version</td><td>1.3.2</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"f36ed6ebddec4f769b97869e8d0f6bcc"'>f36ed6ebddec4f769b97869e8d0f6bcc</a></td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce RTX 2060/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 496.13</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by britzl** [comment]
```
sun.security.ssl.SSLSocketImpl.handleEOF.class javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake
    at sun.security.ssl.SSLSocketImpl.handleEOF(SSLSocketImpl.java:1321)
    at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1160)
    at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1063)
    at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:402)
    at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:567)
    at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
    at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:163)
    at com.dynamo.bob.Project.resolveLibUrls(Project.java:1513)
    at editor.pipeline.bob$bob_build_BANG_$fn.invoke(bob.clj:181)
```

**Comment by britzl** [comment]
This seems to happen while resolving library dependencies. Does it happen repeatedly or just once? If it happens repeatedly I'd like to ask you to check your library dependencies in game.project.

**Comment by JCash** [comment]
To me, this sounds like a Github hiccup.
I'll close this due to lack of info.
