### ISSUE TITLE
Problem opening main.collection

### ISSUE THREAD

**Issue by juliovivian** [defold/defold#6619]
### Expected behaviour
Simply open and edit main.collection

### Actual behaviour
Since I've uodated Defold to version 1.3.2, Build time: 2022-05-19T08:42:50.389319
   Editor SHA1: 92bfcab05e2b9b5713df4f25eda838f5a7114a5d
   Engine SHA1: 287c945fab310c324493e08b191ee1b1538ef973

### Steps to reproduce

Just open main.collection (or any object) for edition.

<hr/>

<table>
<tr><td>Build time</td><td>2022-05-19T08:42:50.389319</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>92bfcab05e2b9b5713df4f25eda838f5a7114a5d</td></tr>
<tr><td>Defold engine sha</td><td>287c945fab310c324493e08b191ee1b1538ef973</td></tr>
<tr><td>Defold version</td><td>1.3.2</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"e07f3503d49d4172a24390a076cc5e69"'>e07f3503d49d4172a24390a076cc5e69</a></td></tr>
<tr><td>GPU</td><td>Mesa Intel(R) HD Graphics 400 (BSW)</td></tr>
<tr><td>GPU Driver</td><td>OpenGL ES-CM 1.1 Mesa 22.0.3</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>5.15.38-1-MANJARO</td></tr>
<table>

**Comment by britzl** [comment]
```
editor.gl$gl_clear.invokeStatic.class java.lang.ClassCastException: class jogamp.opengl.es1.GLES1Impl cannot be cast to class com.jogamp.opengl.GL2ES2 (jogamp.opengl.es1.GLES1Impl and com.jogamp.opengl.GL2ES2 are in unnamed module of loader 'app')
    at editor.gl$gl_clear.invokeStatic(gl.clj:194)
    at editor.scene$render_BANG_.invokeStatic(scene.clj:275)
    at editor.scene$update_image_view_BANG_$fn.invoke(scene.clj:1160)
    at editor.scene$update_image_view_BANG_.invokeStatic(scene.clj:1157)
    at editor.scene$update_image_view_BANG_.invoke(scene.clj:1129)
```

**Comment by britzl** [comment]
@juliovivian We're working on an improved setup/launch script. 

In the meantime maybe you could try this: https://defold.com/manuals/linux/#q-the-defold-editor-crashes-when-opening-a-collection-or-game-object-and-the-crash-refers-to-comjogampopengl
