### ISSUE TITLE
OpenGL problems in Editor - not displaying sprites with custom fp on Ubuntu 20.04

### ISSUE THREAD

**Issue by paweljarosz** [defold/defold#6622]
### Expected behaviour
Sprite (with custom fp) preview is visible in Editor.

### Actual behaviour
Editor not displaying sprites with custom shaders on Ubuntu.

### Steps to reproduce
1. Download attached zip.
2. Open main.collection.
3. The sprite is not visible - using custom fragment program.
4. Run the project - sprite is visible with applied changes from fp.

Try any other project with custom fp on Ubuntu 20.04 LTS. When no color is modified in the fp the preview is available.

Repro project:

[RenderPipeline.zip](https://github.com/defold/defold/files/8747881/RenderPipeline.zip)
1-generic
![Screenshot from 2022-05-21 17-24-00](https://user-images.githubusercontent.com/11634203/169658787-09ad3e53-4b14-4378-9f97-e03b1cfa7161.png)

Screenshot:
![Screenshot from 2022-05-21 17-24-00](https://user-images.githubusercontent.com/11634203/169658898-008281b3-52df-446a-b7e4-021af97286e6.png)

<hr/>

<table>
<tr><td>Build time</td><td>2022-05-04T12:16:24.095440</td></tr>
<tr><td>Defold channel</td><td>alpha</td></tr>
<tr><td>Defold editor sha</td><td>2bf9ec3dfa2f59a9e1808f4768ff9a1fbaac61b4</td></tr>
<tr><td>Defold engine sha</td><td>2bf9ec3dfa2f59a9e1808f4768ff9a1fbaac61b4</td></tr>
<tr><td>Defold version</td><td>1.3.3</td></tr>
<tr><td>GPU</td><td>Mesa Intel(R) UHD Graphics (CML GT2)</td></tr>
<tr><td>GPU Driver</td><td>OpenGL ES-CM 1.1 Mesa 21.2.6</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>5.13.0-4</td></tr>
<table>

Problem occurs when running Defold from Steam too (above is directly from Defold zip):

<table>
<tr><td>Build time</td><td>2022-05-02T08:44:16.219819</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>563d19f88cdf76ddd11128859aada8c6541c9a97</td></tr>
<tr><td>Defold engine sha</td><td>287c945fab310c324493e08b191ee1b1538ef973</td></tr>
<tr><td>Defold version</td><td>1.3.2</td></tr>
<tr><td>GPU</td><td>Mesa Intel(R) UHD Graphics (CML GT2)</td></tr>
<tr><td>GPU Driver</td><td>2.1 Mesa 21.2.6</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>5.13.0-41-generic</td></tr>
<table>

**Comment by AGulev** [comment]
is it still an issue in new Defold?

**Comment by paweljarosz** [comment]
I tried opening the repro project, but the Editor hangs, when I open "main.collection" :/ 

<img width="1190" height="710" alt="Image" src="https://github.com/user-attachments/assets/e4587af1-6841-4b7d-9d72-ddfd9c420f67" />

I tested further, it just hangs when this material is used, even after I added a sampler in the material file.

log:

```
2026-03-11 10:48:24.863 ERROR default    editor.scene - {:line 241, :message "skipping renderable", :pass-name "transparent", :render-fn #object[editor.sprite$render_sprites 0x618e34bd "editor.sprite$render_sprites@618e34bd"], :ex-data {:source-strings ["#ifndef GL_ES\n#define lowp\n#define mediump\n#define highp\n#endif\n\nvarying mediump vec2 var_texcoord0;\n\nuniform lowp sampler2D texture_sampler;\nuniform lowp vec4 tint;\nuniform lowp vec4 cloak;\nuniform lowp vec4 armor;\nuniform lowp vec4 gloves;\nuniform lowp vec4 sword;\nuniform lowp vec4 boots;\nuniform lowp vec4 necklace;\nuniform lowp vec4 blade;\nuniform lowp vec4 jacket;\nuniform lowp vec4 skin;\nuniform lowp vec4 jeans;\n\nvoid main()\n{\n    // Pre-multiply alpha since all runtime textures already are\n    lowp vec4 pixel_color = texture2D(texture_sampler, var_texcoord0.xy);\n    pixel_color.r = 1;\n\n    gl_FragColor = pixel_color * vec4(tint.xyz * tint.w, tint.w);\n}\n"], :error-log "0:26(2): error: value of type int cannot be assigned to variable of type float\n"}}
clojure.lang.ExceptionInfo: Shader compilation failure.
0:26(2): error: value of type int cannot be assigned to variable of type float

	at editor.gl.shader$make_shader_STAR_.invokeStatic(shader.clj:432)
	at editor.gl.shader$make_shader_program$fn__48897.invoke(shader.clj:847)
	at clojure.lang.PersistentVector.reduce(PersistentVector.java:418)
	at clojure.core$reduce.invokeStatic(core.clj:6964)
	at editor.gl.shader$make_shader_program.invokeStatic(shader.clj:858)
	at editor.gl.shader$make_shader_program.invoke(shader.clj:841)
	at editor.scene_cache$request_object_BANG_.invokeStatic(scene_cache.clj:170)
	at editor.gl.shader.ShaderLifecycle.bind_BANG_(shader.clj:471)
	at editor.gl$with_gl_bindings_impl$fn__18023.invoke(gl.clj:491)
	at util.coll$find_values$fn__4205$xf__4206.invoke(coll.clj:911)
	at clojure.lang.PersistentVector.reduce(PersistentVector.java:418)
	at clojure.core$transduce.invokeStatic(core.clj:7025)
	at editor.gl$with_gl_bindings_impl.invokeStatic(gl.clj:482)
	at editor.sprite$render_sprites.invokeStatic(sprite.clj:191)
	at editor.sprite$render_sprites.invoke(sprite.clj:182)
	at editor.scene$render_nodes.invokeStatic(scene.clj:239)
	at editor.scene$batch_render.invokeStatic(scene.clj:267)
	at editor.scene$render_BANG_.invokeStatic(scene.clj:344)
	at editor.scene$update_image_view_BANG_$fn__57329.invoke(scene.clj:1496)
	at editor.scene$update_image_view_BANG_.invokeStatic(scene.clj:1493)
	at editor.scene$update_image_view_BANG_.invoke(scene.clj:1460)
	at editor.scene$refresh_scene_view_BANG_.invokeStatic(scene.clj:1045)
	at editor.app_view$refresh_scene_view_BANG_.invokeStatic(app_view.clj:2012)
	at editor.app_view$refresh_scene_views_BANG_.invokeStatic(app_view.clj:2021)
	at editor.app_view$make_app_view$fn__74200.invoke(app_view.clj:2132)
	at editor.ui$__GT_timer$fn__30705$fn__30706.invoke(ui.clj:2373)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1990)
	at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1990)
	at clojure.lang.RestFn.invoke(RestFn.java:428)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.RestFn.applyTo(RestFn.java:135)
	at clojure.core$apply.invokeStatic(core.clj:671)
	at clojure.core$bound_fn_STAR_$fn__5837.doInvoke(core.clj:2020)
	at clojure.lang.RestFn.invoke(RestFn.java:400)
	at clojure.lang.AFn.run(AFn.java:22)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$0(PlatformImpl.java:424)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$0(GtkApplication.java:240)
	at java.base/java.lang.Thread.run(Thread.java:1474)
```

So I checked the fragment program and indeed, there was an assignment of the int value to the "pixel" variable defined as float... So my mistake.

**Comment by AGulev** [comment]
## Issue summary

The issue reports that on Ubuntu 20.04, sprites using a custom fragment program render correctly at runtime but disappear in the editor preview/scene view whenever the fragment shader changes the sampled color.

## Status

Possibly outdated/fixed

## Evidence

- The GitHub issue is still open, but it has no follow-up comments or linked public fix discussion beyond the original 2022 report.
- Current editor material rendering no longer uses raw material shader text directly; `editor/src/clj/editor/material.clj:177` routes material shaders through `shader-gen/transpile-shader-source` before the scene shader is created.
- The transpiler explicitly targets `:language-glsl-sm120` for editor rendering in `editor/src/clj/editor/pipeline/shader_gen.clj:109`, with the comment "Use the old GLES2-compatible shaders for rendering in the editor." That is a direct compatibility measure for older desktop/Linux OpenGL stacks.
- Sprite scene rendering uses the material-produced shader from scene data in `editor/src/clj/editor/sprite.clj:186`, so custom sprite materials now go through that compatibility transpilation path in the editor preview.
- The editor test suite has coverage that sprite scene data uses the assigned material shader in `editor/test/integration/sprite_test.clj:54`, and material nodes successfully produce a shader in `editor/test/integration/material_test.clj:28`.
- The compatibility transpilation path was introduced in commit `7563fc3ce7786d28c0eacb5eb0f5fb746d831004` (2025-05-13), which added `editor/src/clj/editor/pipeline/shader_gen.clj` and the current editor-side shader pipeline.

## Why I think it is already fixed

The original symptom was specific to editor preview rendering of custom fragment programs on Linux. In the current codebase, editor preview shaders for materials are first cross-compiled into an editor-specific GLSL SM120 variant instead of being used as-is. That is exactly the kind of compatibility layer that would address Linux/Mesa shader preview failures like the one described in #6622. I cannot prove runtime behavior without reproducing on the affected Ubuntu/Mesa setup, but the present rendering path looks materially different from the 2022 architecture and strongly suggests the issue is stale.

**Comment by paweljarosz** [comment]
Maybe it would be good to add an error/warning of that type somewhere explicitly to users (I found the error in terminal, usually users, don't run Defold with it, and just hanging without showing an error is bad).
