### ISSUE TITLE
Error when creating or removing any component on Ubuntu

### ISSUE THREAD

**Issue by paweljarosz** [defold/defold#6623]
Editor shows error everytime I create or remove any component in Assets pane.

### Expected behaviour
No error pop-ups.

### Actual behaviour
Error pop-ups when creating or removing any component.

### Steps to reproduce

<hr/>

When creating a component (after I select a name and click Create...)

<table>
<tr><td>Build time</td><td>2022-05-19T08:42:50.389319</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>92bfcab05e2b9b5713df4f25eda838f5a7114a5d</td></tr>
<tr><td>Defold engine sha</td><td>287c945fab310c324493e08b191ee1b1538ef973</td></tr>
<tr><td>Defold version</td><td>1.3.2</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"0832b77da0244865a81a3d1fc7246006"'>0832b77da0244865a81a3d1fc7246006</a></td></tr>
<tr><td>GPU</td><td>Mesa Intel(R) UHD Graphics (CML GT2)</td></tr>
<tr><td>GPU Driver</td><td>2.1 Mesa 21.2.6</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>5.13.0-41-generic</td></tr>
<table>

<hr/>

When removing a component (after I click Delete):

<table>
<tr><td>Build time</td><td>2022-05-19T08:42:50.389319</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>92bfcab05e2b9b5713df4f25eda838f5a7114a5d</td></tr>
<tr><td>Defold engine sha</td><td>287c945fab310c324493e08b191ee1b1538ef973</td></tr>
<tr><td>Defold version</td><td>1.3.2</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"0acec0436a6941308a8bb45e10819872"'>0acec0436a6941308a8bb45e10819872</a></td></tr>
<tr><td>GPU</td><td>Mesa Intel(R) UHD Graphics (CML GT2)</td></tr>
<tr><td>GPU Driver</td><td>2.1 Mesa 21.2.6</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>5.13.0-41-generic</td></tr>
<table>

**Comment by britzl** [comment]
```
editor.handler$invoke_fnk.invokeStatic.class clojure.lang.ExceptionInfo: handler ':new-file' in context ':global' failed at ':run' with message 'No implementation of method: :user-data of protocol: #'editor.ui/HasUserData found for class: nil'
    at editor.handler$invoke_fnk.invokeStatic(handler.clj:262)
    at editor.handler$run.invokeStatic(handler.clj:289)
    at editor.ui$execute_command.invokeStatic(ui.clj:1166)
    at editor.ui$invoke_handler.invokeStatic(ui.clj:1187)
    at editor.ui$make_menu_command$reify.handle(ui.clj:1270)
    at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
    at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
    at javafx.event.Event.fireEvent(Event.java:198)
    at javafx.scene.control.MenuItem.fire(MenuItem.java:459)
    at com.sun.javafx.scene.control.ContextMenuContent$MenuItemContainer.doSelect(ContextMenuContent.java:1385)
    at com.sun.javafx.scene.control.ContextMenuContent$MenuItemContainer.lambda$createChildren$12(ContextMenuContent.java:1338)
    at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:247)
    at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
    at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
    at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
    at javafx.event.Event.fireEvent(Event.java:198)
    at javafx.scene.Scene$MouseHandler.process(Scene.java:3881)
    at javafx.scene.Scene.processMouseEvent(Scene.java:1874)
    at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2607)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:411)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:301)
    at java.security.AccessController.doPrivileged(AccessController.java)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:450)
    at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:424)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:449)
    at com.sun.glass.ui.View.handleMouseEvent(View.java:551)
    at com.sun.glass.ui.View.notifyMouse(View.java:937)
    at com.sun.glass.ui.gtk.GtkApplication._runLoop(GtkApplication.java)
    at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:316)
    at java.lang.Thread.run(Thread.java:834)
```

**Comment by vlaaad** [comment]
Hi @paweljarosz, does your editor have any other errors in editor logs? You can find them in Help - Show Logs.

Note: the error is NPE on accessing `(ui/user-data list-view :refresh-pending)` of changes view — list view has to be null. This also should be impossible because we set `list-view` upon creating the changes view and then never modify it. I think we can be in this situation if `changes-view` is null when we try to refresh it:  `(g/node-value nil :list-view)` returns null instead of throwing exceptions. It's possible that `make-changes-view` returns null instead of view id — there is try/catch block that will log the exception and return null.

**Comment by paweljarosz** [comment]
Logs from today, when I created a collection and error popped out, and then I removed this collection and error popped out too:
[editor2.2022-05-23.log](https://github.com/defold/defold/files/8754130/editor2.2022-05-23.log)

**Comment by vlaaad** [comment]
There is an error during performing `git status` when initializing changes view:
```
 Malformed input or input contains unmappable characters: /home/pjarosz4/Desktop/witchcrafter/assets/images/gui/backpack_bg ��� kopia.png
 ```

**Comment by paweljarosz** [comment]
Oh, I removed the problematic asset. The issue is still happening though :/

I removed the logs, opened the Editor again and create and removed a collection.

Creating a.collection - error:
clojure.lang.ExceptionInfo: handler ':new-file' in context ':global' failed at ':run' with message 'No implementation of method: :user-data of protocol: #'editor.ui/HasUserData found for class: nil'
java.lang.IllegalArgumentException: No implementation of method: :user-data of protocol: #'editor.ui/HasUserData found for class: nil
https://sentry.io/organizations/defold/issues/?query=id%3A"5ed7cc85e81d456dbacae9e727db176b"

Removing it does presents an error:
clojure.lang.ExceptionInfo: handler ':delete' in context ':asset-browser' failed at ':run' with message 'No implementation of method: :user-data of protocol: #'editor.ui/HasUserData found for class: nil'
java.lang.IllegalArgumentException: No implementation of method: :user-data of protocol: #'editor.ui/HasUserData found for class: nil
https://sentry.io/organizations/defold/issues/?query=id%3A"17755696b8d048c2a089b7fa7caa2de2"

[editor2.2022-05-23.log](https://github.com/defold/defold/files/8754672/editor2.2022-05-23.log)

**Comment by paweljarosz** [comment]
For clarifications those assets were a copy of some assets with name probably created in Windows and when I moved everything to Linux, I didn't notice them. The names were including a long dash sign - between name and phrase kopia (copy). On Windows everything worked unnoticed :D

**Comment by vlaaad** [comment]
I fixed the issue so in the future git-related exceptions will be directly shown to the user, and this NPE shouldn't happen again.
