### ISSUE TITLE
Defold editor crash after click open project from disk

### ISSUE THREAD

**Issue by wangdong20** [defold/defold#6702]
**Describe the bug (REQUIRED)**
Editor crashed when I tried to open project from disk.

**To Reproduce (REQUIRED)**
1. Open Defold
2. Open project from disk 

**Expected behavior (REQUIRED)**
Defold editor should be opened.

**Defold version (REQUIRED):**
  - Version 1.3.2

**Platforms (REQUIRED):**
 - OS: [macOS 12.1]

**Minimal repro case project (OPTIONAL):**
Please attach a minimal project where the bug is reproduced. This will greatly help the person trying to investigate and fix the bug.

**Logs (OPTIONAL):**
Please provide relevant logs from engine, editor or build server. Learn where the logs are stored [here](https://defold.com/manuals/getting-help/#log-files).
`2022-06-11 22:46:21.354 ERROR default    editor.dialogs - {:line 426}
java.io.EOFException: Unexpected end of ZLIB input stream
	at java.base/java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:245)
	at java.base/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:159)
	at java.base/java.util.zip.ZipInputStream.read(ZipInputStream.java:195)
	at java.base/java.util.zip.ZipInputStream.closeEntry(ZipInputStream.java:141)
	at java.base/java.util.zip.ZipInputStream.getNextEntry(ZipInputStream.java:119)
	at editor.library$locate_zip_entry.invokeStatic(library.clj:163)
	at editor.library$library_base_path.invokeStatic(library.clj:165)
	at editor.resource_watch$load_library_zip.invokeStatic(resource_watch.clj:43)
	at editor.resource_watch$make_library_snapshot.invokeStatic(resource_watch.clj:55)
	at editor.resource_watch$update_library_snapshot_cache$fn__11286.invoke(resource_watch.clj:72)
`

**Workaround (OPTIONAL):**
If there is a workaround, please describe it here.

**Screenshots (OPTIONAL):**

**Additional context (OPTIONAL):**

**Comment by britzl** [comment]
It sounds like there's a corrupted dependency. Could you please delete the .internal folder of your project and try again?

**Comment by AGulev** [comment]
no action/answer from the reporter
