### ISSUE TITLE
Editor exception

### ISSUE THREAD

**Issue by ekharkunov** [defold/defold#6717]
Exception occured after adding new editor_script file.

### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2022-06-15T12:05:49.115988</td></tr>
<tr><td>Defold channel</td><td>dev</td></tr>
<tr><td>Defold editor sha</td><td>da77daf0123db03d44bbb08ff21853df540c4f7e</td></tr>
<tr><td>Defold engine sha</td><td>da77daf0123db03d44bbb08ff21853df540c4f7e</td></tr>
<tr><td>Defold version</td><td>1.2.192</td></tr>
<tr><td>GPU</td><td>AMD Radeon Pro 5500M OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 ATI-4.5.14</td></tr>
<tr><td>Java version</td><td>11.0.15+10-LTS</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>11.4</td></tr>
<table>

**Comment by vlaaad** [comment]
There is no exception...
Looking at sentry's exceptions for `da77af` editor sha, there is a couple of different errors:

1. NPE during `repaint-canvas!` — since it's about code editor view, might be this one
```
editor.code.view$repaint_canvas_BANG_.invokeStatic.class java.lang.NullPointerException: null
    at editor.code.view$repaint_canvas_BANG_.invokeStatic(view.clj:782)
    at editor.code.view$repaint_view_BANG_.invokeStatic(view.clj:2225)
    at editor.code.view$make_view_BANG_$fn.invoke(view.clj:2561)
    at clojure.lang.AFn.run(AFn.java:22)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:457)
    at java.security.AccessController.doPrivileged(AccessController.java)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:456)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
```
2. Cannot open <nil> as an InputStream — hmm... 
```
clojure.java.io$fn__11444.invokeStatic.class java.lang.IllegalArgumentException: Cannot open <nil> as an InputStream.
    at clojure.java.io$fn.invokeStatic(io.clj:167)
    at clojure.java.io$fn.invoke(io.clj:167)
    at clojure.java.io$fn$G__11372__11386.invoke(io.clj:69)
    at clojure.java.io$input_stream.invokeStatic(io.clj:136)
    at clojure.java.io$input_stream.doInvoke(io.clj:121)
    at clojure.lang.RestFn.invoke(RestFn.java:410)
    at editor.image_util$read_image.invokeStatic(image_util.clj:41)
    at editor.pipeline.texture_set_gen$atlas__GT_texture_set_data$fn.invoke(texture_set_gen.clj:97)
    at clojure.core$map$fn.invoke(core.clj:2753)
    at clojure.lang.LazySeq.sval(LazySeq.java:42)
    at clojure.lang.LazySeq.seq(LazySeq.java:51)
    at clojure.lang.RT.seq(RT.java:531)
    at clojure.lang.RT.nthFrom(RT.java:918)
    at clojure.lang.RT.nth(RT.java:893)
    at clojure.lang.LazySeq.get(LazySeq.java:233)
    at com.dynamo.bob.textureset.TextureSetGenerator.calculateLayout(TextureSetGenerator.java:332)
    at editor.pipeline.texture_set_gen$atlas__GT_texture_set_data.invokeStatic(texture_set_gen.clj:104)
    at editor.atlas$generate_texture_set_data.invokeStatic(atlas.clj:489)
    at editor.atlas$generate_texture_set_data.invoke(atlas.clj:489)
    at editor.atlas$call_generator.invokeStatic(atlas.clj:493)
    at editor.atlas$generate_packed_image.invokeStatic(atlas.clj:503)
    at editor.atlas$generate_packed_image.invoke(atlas.clj:495)
    at editor.atlas$call_generator.invokeStatic(atlas.clj:493)
```
3. FileNotFoundException
```
java.io.FileInputStream.open0.class java.io.FileNotFoundException: [REDACTED]/shop_energy_01.png (No such file or directory)
    at java.io.FileInputStream.open0(FileInputStream.java)
    at java.io.FileInputStream.open(FileInputStream.java:219)
    at java.io.FileInputStream.<init>(FileInputStream.java:157)
    at clojure.java.io$fn.invokeStatic(io.clj:229)
    at clojure.java.io$fn.invoke(io.clj:229)
    at clojure.java.io$fn$G__11372__11386.invoke(io.clj:69)
    at editor.resource.FileResource.make_input_stream(resource.clj:135)
    at clojure.java.io$input_stream.invokeStatic(io.clj:136)
    at clojure.java.io$input_stream.doInvoke(io.clj:121)
    at clojure.lang.RestFn.invoke(RestFn.java:410)
    at editor.image_util$read_image.invokeStatic(image_util.clj:41)
    at editor.pipeline.texture_set_gen$atlas__GT_texture_set_data$fn.invoke(texture_set_gen.clj:97)
    at clojure.core$map$fn.invoke(core.clj:2753)
```

**Comment by ekharkunov** [comment]
Obsolete.
