### ISSUE TITLE
A n00bs moot musing on an exceptionally vain desire, unfulfilled to my hearts-desire....I'll survive.  

### ISSUE THREAD

**Issue by Aboman-87** [defold/defold#6748]
Subtitle, 'An expose on prosody of prose, beset sufferable details found insufferably  rousing'
"Rock, refuses to break into its own universe unto itself....within a universe . . . nauseum"

Very-very-likely a result of the file with which a 'new' window was sought out for; being nested within a *.md file to begin with--opposed to a discreetly referenced image file. Such to say, host OS shrugged at the thought of deciding how to open an *.md file as though it were an *.png file. --- arose from a non-issue to begin with. I've nothing better to do, local organics already sought altruistically sourced dopamine. 

### Expected behaviour
Same-as-if "Open in Desktop" were selected for other contextual 'objects'
--OR--
An undocked window or possibly a tab within the docked editor window unto itself.

### Actual behaviour
An error pops with the declaration:  "java.io.IOException: An established connection was aborted by the software in your host machine"
Readme.md tab becomes instead 'tilesource.jpg' replacing readme.md opposed to 'open in a new window', filename irrelevant[--IF--from within the readme.md tab] occurred with whichever image is attempted to have "Open in New Window")

### Steps to reproduce
Right-click an image (this case, within the Readme.md of a tutorial project) choose "Open in a New Window."
<hr/>

<table>
<tr><td>Build time</td><td>2022-06-23T09:54:42.946252</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>9dcfb8737ada7cad493aa17acbcb13e4d841dd5d</td></tr>
<tr><td>Defold engine sha</td><td>c2ab1630e34f1311d8340d81494cf5317d25fe16</td></tr>
<tr><td>Defold version</td><td>1.3.3</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"e29c446178394ea3af2d25768ef99086"'>e29c446178394ea3af2d25768ef99086</a></td></tr>
<tr><td>GPU</td><td>GeForce GTX 260/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>3.3.0</td></tr>
<tr><td>Java version</td><td>11.0.15+10-LTS</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by britzl** [comment]
> I've nothing better to do, local organics already sought altruistically sourced dopamine.

Here, a gold :star for the most entertaining bug report this year!

Stack trace:

```
sun.nio.ch.SocketDispatcher.write0.class java.io.IOException: An established connection was aborted by the software in your host machine
    at sun.nio.ch.SocketDispatcher.write0(SocketDispatcher.java)
    at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:51)
    at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:113)
    at sun.nio.ch.IOUtil.write(IOUtil.java:79)
    at sun.nio.ch.IOUtil.write(IOUtil.java:50)
    at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:459)
    at sun.net.httpserver.Request$WriteStream.write(Request.java:393)
    at sun.net.httpserver.ChunkedOutputStream.writeChunk(ChunkedOutputStream.java:125)
    at sun.net.httpserver.ChunkedOutputStream.flush(ChunkedOutputStream.java:159)
    at sun.net.httpserver.ChunkedOutputStream.close(ChunkedOutputStream.java:134)
    at sun.net.httpserver.PlaceholderOutputStream.close(ExchangeImpl.java:460)
    at util.http_server$response__GT_exchange_BANG_$fn.invoke(http_server.clj:52)
    at util.http_server$response__GT_exchange_BANG_.invokeStatic(http_server.clj:52)
    at util.http_server$setup_server_BANG_$reify.handle(http_server.clj:63)
    at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:77)
    at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:82)
    at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:80)
    at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:730)
    at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:77)
    at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:699)
    at sun.net.httpserver.ServerImpl$DefaultExecutor.execute(ServerImpl.java:159)
    at sun.net.httpserver.ServerImpl$Dispatcher.handle(ServerImpl.java:446)
    at sun.net.httpserver.ServerImpl$Dispatcher.run(ServerImpl.java:412)
    at java.lang.Thread.run(Thread.java:829)
```

**Comment by AGulev** [comment]
## Issue summary

The report says that right-clicking an image shown inside a `README.md` preview and choosing "Open in a New Window" failed on Windows in Defold `1.3.3` alpha. Instead of opening a separate window, the preview tab switched to the image resource and the editor logged a local HTTP server `java.io.IOException` while serving the markdown/web preview content.

## Status

Possibly outdated/fixed

## Evidence

- The current markdown/HTML preview no longer uses a browser/webview-based rendering path. `editor/src/clj/editor/html_view.clj:30` renders HTML through `markdown/html-view`, and `editor/src/clj/editor/markdown.clj:391` loads image data directly from project resources instead of serving them through the local HTTP server.
- Link handling in the current markdown viewer is internal and explicit: `editor/src/clj/editor/markdown.clj:102` resolves local links to `:file.open`, while the secondary-click menu at `editor/src/clj/editor/markdown.clj:145` only offers `Copy Link`. That means the old browser-style context menu action "Open in a New Window" described in the issue no longer appears to exist in this code path.
- The current HTTP server also explicitly treats aborted client connections as non-fatal. `editor/src/clj/util/http_server.clj:364` documents this exact case, and `editor/src/clj/util/http_server.clj:368` catches `IOException` and only logs a warning instead of surfacing it as an editor error.
- Git history shows two relevant later changes: `baeeef22ff` replaced the editor's markdown/HTML web view with a custom viewer, and `43a9a104bc` refactored the HTTP server to handle disconnected clients more gracefully.

## Why I think it may already be fixed

The original bug report depends on an older markdown preview architecture that exposed a browser/webview context menu and routed image/content loading through the editor's local HTTP server. In the current codebase, markdown preview uses a custom JavaFX viewer, image resources are loaded directly, the problematic "Open in a New Window" browser action is not present in the markdown viewer, and the HTTP server now safely ignores the disconnected-client `IOException` shown in the issue comment. Taken together, the exact failure mode from `#6748` looks more like an obsolete path than an active bug in today's editor.
