### ISSUE TITLE
Defold crash when using Simulate Resolution

### ISSUE THREAD

**Issue by EbmGastroService** [defold/defold#6793]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2022-07-11T09:22:18.167890</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>c0ed825ede46b0112d1e4fd744fd50f460073229</td></tr>
<tr><td>Defold engine sha</td><td>80b1b73fd9cdbd4682c2583403fddfbaf0919107</td></tr>
<tr><td>Defold version</td><td>1.3.4</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"148067e9fbb54a7fa95014c008e4e952"'>148067e9fbb54a7fa95014c008e4e952</a></td></tr>
<tr><td>GPU</td><td>Intel(R) HD Graphics 4000</td></tr>
<tr><td>GPU Driver</td><td>4.0.0 - Build 10.18.10.5161</td></tr>
<tr><td>Java version</td><td>11.0.15+10-LTS</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by britzl** [comment]
```
editor.handler$invoke_fnk.invokeStatic.class clojure.lang.ExceptionInfo: handler ':set-resolution' in context ':global' failed at ':run' with message 'Read timed out'
    at editor.handler$invoke_fnk.invokeStatic(handler.clj:262)
    at editor.handler$run.invokeStatic(handler.clj:289)
    at editor.ui$execute_command.invokeStatic(ui.clj:1166)
    at editor.ui$invoke_handler.invokeStatic(ui.clj:1187)
    at editor.ui$make_menu_command$reify.handle(ui.clj:1270)
    at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
    at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
    at javafx.event.Event.fireEvent(Event.java:198)
    at javafx.scene.control.MenuItem.fire(MenuItem.java:459)
    at com.sun.javafx.scene.control.ContextMenuContent$MenuItemContainer.doSelect(ContextMenuContent.java:1385)
    at com.sun.javafx.scene.control.ContextMenuContent$MenuItemContainer.lambda$createChildren$12(ContextMenuContent.java:1338)
```

**Comment by britzl** [comment]
@EbmGastroService this happened when you tried Debug->Simulate Resolution?

Does it happen every time?

**Comment by AGulev** [comment]
can't repo
not enough info
