### ISSUE TITLE
Error related to missing resource

### ISSUE THREAD

**Issue by ssamoshin-ms** [defold/defold#6819]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2022-06-15T12:05:49.115988</td></tr>
<tr><td>Defold channel</td><td>dev</td></tr>
<tr><td>Defold editor sha</td><td>da77daf0123db03d44bbb08ff21853df540c4f7e</td></tr>
<tr><td>Defold engine sha</td><td>da77daf0123db03d44bbb08ff21853df540c4f7e</td></tr>
<tr><td>Defold version</td><td>1.2.192</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"e9a587023cef452c86f332afabc6c660"'>e9a587023cef452c86f332afabc6c660</a></td></tr>
<tr><td>GPU</td><td>Apple M1 Pro</td></tr>
<tr><td>GPU Driver</td><td>2.1 Metal - 76.3</td></tr>
<tr><td>Java version</td><td>11.0.15+10-LTS</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>12.4</td></tr>
<table>

**Comment by britzl** [comment]
It seems like you are missing a resource:

```
java.io.FileInputStream.open0.class java.io.FileNotFoundException: /Users/***/project/***/main/generated/items/empty.png (No such file or directory)
    at java.io.FileInputStream.open0(FileInputStream.java)
    at java.io.FileInputStream.open(FileInputStream.java:219)
    at java.io.FileInputStream.<init>(FileInputStream.java:157)
    at clojure.java.io$fn.invokeStatic(io.clj:229)
    at clojure.java.io$fn.invoke(io.clj:229)
    at clojure.java.io$fn$G__11372__11386.invoke(io.clj:69)
    at editor.resource.FileResource.make_input_stream(resource.clj:135)
    at clojure.java.io$input_stream.invokeStatic(io.clj:136)
    at clojure.java.io$input_stream.doInvoke(io.clj:121)
    at clojure.lang.RestFn.invoke(RestFn.java:410)
    at editor.image_util$read_image.invokeStatic(image_util.clj:41)
    at editor.pipeline.texture_set_gen$atlas__GT_texture_set_data$fn.invoke(texture_set_gen.clj:97)
    at clojure.core$map$fn.invoke(core.clj:2753)
    at clojure.lang.LazySeq.sval(LazySeq.java:42)
    at clojure.lang.LazySeq.seq(LazySeq.java:51)
    at clojure.lang.RT.seq(RT.java:531)
    at clojure.lang.RT.nthFrom(RT.java:918)
    at clojure.lang.RT.nth(RT.java:893)
```

**Comment by britzl** [comment]
Hi, Can you verify that the file `/Users/***/project/***/main/generated/items/empty.png` does exist? It seems like an image is missing from the atlas which I believe you are generating using an external tool. @ekharkunov-ms can you please assist and confirm if this is the case or not?

**Comment by AGulev** [comment]
@ssamoshin-ms did you solve your issue?
