### ISSUE TITLE
Error trying to export to HTML5

### ISSUE THREAD

**Issue by DanielRuizCabanellas** [defold/defold#6824]
### Steps to reproduce Click Project > Build HTML5

<hr/>

<table>
<tr><td>Build time</td><td>2022-05-23T17:40:17.807659</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>766a51fe39df047a249d3efc48ae10f052ca51b7</td></tr>
<tr><td>Defold engine sha</td><td>287c945fab310c324493e08b191ee1b1538ef973</td></tr>
<tr><td>Defold version</td><td>1.3.2</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"6e8b8d11e4964d09b0c9eec7dc185e08"'>6e8b8d11e4964d09b0c9eec7dc185e08</a></td></tr>
<tr><td>GPU</td><td>Intel(R) UHD Graphics 630</td></tr>
<tr><td>GPU Driver</td><td>4.5.0 - Build 27.20.100.9664</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by britzl** [comment]
```
java.lang.String.<init>.class java.lang.NullPointerException: null
    at java.lang.String.<init>(String.java:614)
    at com.dynamo.bob.pipeline.ProtoUtil.merge(ProtoUtil.java:30)
    at com.dynamo.bob.pipeline.CollectionBuilder.countComponentInResource(CollectionBuilder.java:181)
    at com.dynamo.bob.pipeline.CollectionBuilder.countComponentsInCollectionRecursively(CollectionBuilder.java:208)
    at com.dynamo.bob.pipeline.CollectionBuilder.countAllComponentTypes(CollectionBuilder.java:230)
    at com.dynamo.bob.pipeline.CollectionBuilder.transform(CollectionBuilder.java:484)
    at com.dynamo.bob.pipeline.CollectionBuilder.transform(CollectionBuilder.java:60)
    at com.dynamo.bob.ProtoBuilder.build(ProtoBuilder.java:92)
    at com.dynamo.bob.Project.runTasks(Project.java:1407)
    at com.dynamo.bob.Project.doBuild(Project.java:1194)
    at com.dynamo.bob.Project.build(Project.java:630)
    at editor.pipeline.bob$run_commands_BANG_$fn.invoke(bob.clj:142)
    at editor.pipeline.bob$run_commands_BANG_.invokeStatic(bob.clj:141)
    at editor.pipeline.bob$bob_build_BANG_.invokeStatic(bob.clj:183)
    at editor.disk$async_bob_build_BANG_$fn$fn$fn.invoke(disk.clj:224)
    at clojure.core$binding_conveyor_fn$fn.invoke(core.clj:2030)
    at clojure.lang.AFn.call(AFn.java:18)
    at java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.lang.Thread.run(Thread.java:829)
```

**Comment by britzl** [comment]
@DanielRuizCabanellas can you reproduce this problem? Is it possible for you to share the project?

**Comment by DanielRuizCabanellas** [comment]
The problem is occurring constantly when I try to export to HTML5 the game
as  I stated.

I thought it could've been a problem of Defold needing an update or from a
library that was recently added, but updating Defold and removing the
libraries didn't solve the problem. I will share a zip file with the
project inside, thanks for the help!

**Comment by britzl** [comment]
> Defold version | 1.3.2

Have you tried with a newer version of Defold?

**Comment by DanielRuizCabanellas** [comment]
Sorry for the delayed response! Yes, I did try the newest version on my
workplace computer and didn't work. But as of today as I just tried on my
personal computer it works perfectly fine.

Thanks for the help, I will close the threat as resolved, have a nice day!
