### ISSUE TITLE
Not build Android bundle

### ISSUE THREAD

**Issue by redflasher** [defold/defold#6840]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2022-07-26T10:22:01.861651</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>0bcffa30741078f7af1759d8a3ce4b01cb9a77f5</td></tr>
<tr><td>Defold engine sha</td><td>80b1b73fd9cdbd4682c2583403fddfbaf0919107</td></tr>
<tr><td>Defold version</td><td>1.3.4</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"7c2d0c1db83b4c2abb4f07d07b19f5d9"'>7c2d0c1db83b4c2abb4f07d07b19f5d9</a></td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 465.89</td></tr>
<tr><td>Java version</td><td>11.0.15+10-LTS</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by britzl** [comment]
```
java.lang.String.<init>.class java.lang.NullPointerException: null
    at java.lang.String.<init>(String.java:614)
    at com.dynamo.bob.pipeline.ProtoUtil.merge(ProtoUtil.java:30)
    at com.dynamo.bob.pipeline.CollectionBuilder.countComponentInResource(CollectionBuilder.java:181)
    at com.dynamo.bob.pipeline.CollectionBuilder.countComponentsInCollectionRecursively(CollectionBuilder.java:208)
    at com.dynamo.bob.pipeline.CollectionBuilder.countAllComponentTypes(CollectionBuilder.java:230)
    at com.dynamo.bob.pipeline.CollectionBuilder.transform(CollectionBuilder.java:484)
    at com.dynamo.bob.pipeline.CollectionBuilder.transform(CollectionBuilder.java:60)
    at com.dynamo.bob.ProtoBuilder.build(ProtoBuilder.java:92)
    at com.dynamo.bob.Project.runTasks(Project.java:1407)
    at com.dynamo.bob.Project.doBuild(Project.java:1194)
    at com.dynamo.bob.Project.build(Project.java:630)
    at editor.pipeline.bob$run_commands_BANG_$fn.invoke(bob.clj:142)
    at editor.pipeline.bob$run_commands_BANG_.invokeStatic(bob.clj:141)
    at editor.pipeline.bob$bob_build_BANG_.invokeStatic(bob.clj:183)
    at editor.disk$async_bob_build_BANG_$fn$fn$fn.invoke(disk.clj:224)
    at clojure.core$binding_conveyor_fn$fn.invoke(core.clj:2030)
    at clojure.lang.AFn.call(AFn.java:18)
    at java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.lang.Thread.run(Thread.java:829)
```

**Comment by britzl** [comment]
@redflasher it is likely that you are bundling a project with a missing resource, like in this very similar issue:

https://github.com/defold/defold/issues/6436#issuecomment-1049560997

**Comment by redflasher** [comment]
Yes, I found it. It was unused game object with missing resource.
