### ISSUE TITLE
Problem quitting Defold Projects screen after downloading update

### ISSUE THREAD

**Issue by paweljarosz** [defold/defold#6951]
### Steps to reproduce
I clicked Updating on the first screen and when I try to "Restart to update" I get:

<table>
<tr><td>Build time</td><td>2022-08-30T15:09:35.126635</td></tr>
<tr><td>Defold channel</td><td>alpha</td></tr>
<tr><td>Defold editor sha</td><td>8d6217b949d1d508c64490df68cff200bc1494de</td></tr>
<tr><td>Defold engine sha</td><td>8d6217b949d1d508c64490df68cff200bc1494de</td></tr>
<tr><td>Defold version</td><td>1.3.6</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"61ef0fde912c4d96bc773be035f7999e"'>61ef0fde912c4d96bc773be035f7999e</a></td></tr>
<tr><td>GPU</td><td>Mesa Intel(R) UHD Graphics (CML GT2)</td></tr>
<tr><td>GPU Driver</td><td>4.6 (Compatibility Profile) Mesa 21.2.6</td></tr>
<tr><td>Java version</td><td>11.0.15+10-LTS</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>5.15.0-46-generic</td></tr>
<table>

And when I try to close the window:

<hr/>

<table>
<tr><td>Build time</td><td>2022-08-30T15:09:35.126635</td></tr>
<tr><td>Defold channel</td><td>alpha</td></tr>
<tr><td>Defold editor sha</td><td>8d6217b949d1d508c64490df68cff200bc1494de</td></tr>
<tr><td>Defold engine sha</td><td>8d6217b949d1d508c64490df68cff200bc1494de</td></tr>
<tr><td>Defold version</td><td>1.3.6</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"c14c48fc0ff5409b835db3b8a7b040a4"'>c14c48fc0ff5409b835db3b8a7b040a4</a></td></tr>
<tr><td>GPU</td><td>Mesa Intel(R) UHD Graphics (CML GT2)</td></tr>
<tr><td>GPU Driver</td><td>4.6 (Compatibility Profile) Mesa 21.2.6</td></tr>
<tr><td>Java version</td><td>11.0.15+10-LTS</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>5.15.0-46-generic</td></tr>
<table>

**Comment by paweljarosz** [comment]
Fixed after restarting the machine, but perhaps still worth looking at? :)

**Comment by britzl** [comment]
```
sun.nio.fs.UnixFileSystemProvider.move.class java.lang.NoClassDefFoundError: Could not initialize class sun.nio.fs.UnixCopyFile
    at sun.nio.fs.UnixFileSystemProvider.move(UnixFileSystemProvider.java:267)
    at java.nio.file.Files.move(Files.java:1422)
    at editor.updater$move_file_BANG_.invokeStatic(updater.clj:219)
    at editor.updater$install_unix_file_BANG_.invokeStatic(updater.clj:225)
    at editor.updater$install_file_BANG_.invokeStatic(updater.clj:241)
    at editor.updater$install_BANG_.invokeStatic(updater.clj:266)
    at editor.ui.updater$install_BANG_.invokeStatic(updater.clj:33)
    at editor.ui.updater$install_and_restart_BANG_.invokeStatic(updater.clj:43)
    at editor.welcome$init_pending_update_indicator_BANG_$install_and_restart_BANG___87112.invoke(welcome.clj:541)
    at editor.ui.updater$init_BANG_$fn.invoke(updater.clj:63)
    at editor.ui$fn$reify.handle(ui.clj:863)
    at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(C
```


Possibly related: https://github.com/CatalogueOfLife/backend/issues/621#issuecomment-626637514

**Comment by AGulev** [comment]
## Short Summary

The issue reports that on Linux alpha build `1.3.6`, clicking `Restart to update` or simply closing the Projects screen after downloading an update crashed during installation with `NoClassDefFoundError: Could not initialize class sun.nio.fs.UnixCopyFile`. One follow-up comment says the problem disappeared after rebooting the machine.

## Status

Possibly outdated/fixed.

## Evidence

- The failing path from the issue comment still maps to the current updater flow: `editor/src/clj/editor/ui/updater.clj:34` calls `editor/src/clj/editor/updater.clj:256`, which installs the extracted update by moving files into the live installation.
- Current updater code explicitly skips replacing the bundled JDK directory via `protected-dirs` in `editor/src/clj/editor/updater.clj:343`, so the updater no longer attempts to overwrite the running Java runtime during install.
- Git history shows that this JDK-skip behavior is intentional (`dda1968731`, "Don't update jdk dir") and the protected JDK path has been kept in sync with later bundled JDK upgrades, including the move from `jdk-11.0.15+10` to newer runtimes.
- The reported stack trace came from Java `11.0.15+10`, while the current repository bundles `jdk-25+36` in `scripts/build.py:2558`, so the exact runtime involved in the crash is no longer the same.
- I did not find a current test or issue comment demonstrating the same Linux update failure on the modern updater/runtime combination.

## Why It Looks Possibly Fixed

The original failure appears tied to the old Java 11 runtime and/or a transient machine state, not to a clearly reproducible updater logic bug that is still visible in the current codebase. Since the reporter said a reboot made the problem go away, the updater now avoids replacing the bundled JDK, and the editor has since moved to newer bundled JDK versions, this specific issue looks more likely outdated than actively reproducible today.
