### ISSUE TITLE
Can't quit Defold or do several other actions

### ISSUE THREAD

**Issue by skyfallwastaken** [defold/defold#6994]
### Expected behaviour
Being able to quit Defold
### Actual behaviour
![image](https://user-images.githubusercontent.com/55807755/191594141-7c1962ff-5add-43ee-95ba-f0b06342c1ef.png)
### Steps to reproduce
I'm not really sure? This just seems to be mostly random.
<hr/>

<table>
<tr><td>Build time</td><td>2022-09-14T09:13:39.506451</td></tr>
<tr><td>Defold channel</td><td>beta</td></tr>
<tr><td>Defold editor sha</td><td>905234d8da2e642f1075c73aaa1bfb72e49199e3</td></tr>
<tr><td>Defold engine sha</td><td>905234d8da2e642f1075c73aaa1bfb72e49199e3</td></tr>
<tr><td>Defold version</td><td>1.3.6</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"30f5ba621e434c3983afdd60f85e5ef2"'>30f5ba621e434c3983afdd60f85e5ef2</a></td></tr>
<tr><td>GPU</td><td>Mesa Intel(R) HD Graphics 2000 (SNB GT1)</td></tr>
<tr><td>GPU Driver</td><td>3.1 Mesa 22.0.5</td></tr>
<tr><td>Java version</td><td>11.0.15+10-LTS</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>5.19.0-76051900-generic</td></tr>
<table>

**Comment by britzl** [comment]
```
com.google.protobuf.AbstractMessage$Builder.newUninitializedMessageException.class com.google.protobuf.UninitializedMessageException: Message missing required fields: input
    at com.google.protobuf.AbstractMessage$Builder.newUninitializedMessageException(AbstractMessage.java:475)
    at com.dynamo.input.proto.Input$KeyTrigger$Builder.build(Input.java:6526)
    at com.dynamo.input.proto.Input$KeyTrigger$Builder.build(Input.java:6469)
    at editor.protobuf$pb_builder_raw$builder_fn.invoke(protobuf.clj:424)
    at clojure.core$mapv$fn.invoke(core.clj:6912)
    at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
    at clojure.core$reduce.invokeStatic(core.clj:6827)
    at clojure.core$mapv.invokeStatic(core.clj:6903)
    at clojure.core$mapv.invoke(core.clj:6903)
    at clojure.core$partial$fn.invoke(core.clj:2624)
    at editor.protobuf$pb_builder_raw$fn$fn.invoke(protobuf.clj:415)
    at editor.protobuf$pb_builder_raw$builder_fn.invoke(protobuf.clj:423)
    at editor.protobuf$map__GT_pb.invokeStatic(protobuf.clj:435)
    at editor.protobuf$map__GT_str.invokeStatic(protobuf.clj:559)
    at editor.protobuf$map__GT_str.invoke(protobuf.clj:559)
    at editor.protobuf$map__GT_str.invokeStatic(protobuf.clj:560)
    at editor.protobuf$map__GT_str.invoke(protobuf.clj:559)
    at clojure.core$partial$fn.invoke(core.clj:2624)
    at editor.resource_node$fn.invokeStatic(resource_node.clj:77)
    at editor.resource_node$fn.invoke(resource_node.clj:71)
    at clojure.lang.AFn.applyToHelper(AFn.java:154)
    at clojure.lang.AFn.applyTo(AFn.java:144)
    at clojure.lang.AFunction$1.doInvoke(AFunction.java:31)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at clojure.lang.Var.invoke(Var.java:384)
    at editor.protobuf_types$ProtobufNode$behavior$cleaned_save_value$fn.invoke(protobuf_types.clj:71)
    at internal.node$trace_expr.invokeStatic(node.clj:43)
    at editor.protobuf_types$ProtobufNode$behavior$cleaned_save_value.invokeStatic(protobuf_types.clj:71)
    at editor.protobuf_types$ProtobufNode$behavior$cleaned_save_value.invoke(protobuf_types.clj:71)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:285)
    at editor.protobuf_types$ProtobufNode$behavior$dirty_QMARK_$fn.invoke(protobuf_types.clj:71)
    at internal.node$trace_expr.invokeStatic(node.clj:43)
    at editor.protobuf_types$ProtobufNode$behavior$dirty_QMARK_.invokeStatic(protobuf_types.clj:71)
    at editor.protobuf_types$ProtobufNode$behavior$dirty_QMARK_.invoke(protobuf_types.clj:71)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:285)
    at editor.protobuf_types$ProtobufNode$behavior$save_data$fn.invoke(protobuf_types.clj:71)
    at internal.node$trace_expr.invokeStatic(node.clj:43)
    at editor.protobuf_types$ProtobufNode$behavior$save_data.invokeStatic(protobuf_types.clj:71)
    at editor.protobuf_types$ProtobufNode$behavior$save_data.invoke(protobuf_types.clj:71)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:285)
    at internal.node$pull_input_values$fn.invoke(node.clj:1166)
    at clojure.core$mapv$fn.invoke(core.clj:6912)
    at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
    at clojure.core$reduce.invokeStatic(core.clj:6827)
    at clojure.core$mapv.invokeStatic(core.clj:6903)
    at internal.node$pull_input_values.invokeStatic(node.clj:1167)
    at editor.defold_project$Project$behavior$save_data$fn.invoke(defold_project.clj:671)
    at internal.node$trace_expr.invokeStatic(node.clj:43)
    at editor.defold_project$Project$behavior$save_data.invokeStatic(defold_project.clj:671)
    at editor.defold_project$Project$behavior$save_data.invoke(defold_project.clj:671)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:285)
    at editor.defold_project$Project$behavior$dirty_save_data$fn.invoke(defold_project.clj:671)
    at internal.node$trace_expr.invokeStatic(node.clj:43)
    at editor.defold_project$Project$behavior$dirty_save_data.invokeStatic(defold_project.clj:671)
    at editor.defold_project$Project$behavior$dirty_save_data.invoke(defold_project.clj:671)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:285)
    at internal.node$node_value.invokeStatic(node.clj:432)
    at internal.system$node_value.invokeStatic(system.clj:354)
    at dynamo.graph$do_node_value.invokeStatic(graph.clj:812)
    at dynamo.graph$node_value.invokeStatic(graph.clj:815)
    at editor.defold_project$dirty_save_data.invokeStatic(defold_project.clj:294)
    at editor.boot_open_project$load_stage_BANG_$fn.invoke(boot_open_project.clj:257)
    at editor.ui$fn$fn.invoke(ui.clj:2009)
    at editor.ui$chain_handler$reify.handle(ui.clj:1995)
    at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
    at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
    at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
    at javafx.event.Event.fireEvent(Event.java:198)
    at com.sun.javafx.stage.WindowPeerListener.closing(WindowPeerListener.java:93)
    at com.sun.javafx.tk.quantum.GlassWindowEventHandler.run(GlassWindowEventHandler.java:147)
    at com.sun.javafx.tk.quantum.GlassWindowEventHandler.run(GlassWindowEventHandler.java:40)
    at java.security.AccessController.doPrivileged(AccessController.java)
    at com.sun.javafx.tk.quantum.GlassWindowEventHandler.lambda$handleWindowEvent$4(GlassWindowEventHandler.java:178)
    at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:424)
    at com.sun.javafx.tk.quantum.GlassWindowEventHandler.handleWindowEvent(GlassWindowEventHandler.java:176)
    at com.sun.glass.ui.Window.handleWindowEvent(Window.java:1248)
    at com.sun.glass.ui.Window.notifyClose(Window.java:1153)
    at com.sun.glass.ui.gtk.GtkApplication._runLoop(GtkApplication.java)
    at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:316)
    at java.lang.Thread.run(Thread.java:829)
```

**Comment by AGulev** [comment]
related https://github.com/defold/defold/issues/5958

**Comment by AGulev** [comment]
related to https://github.com/defold/defold/issues/5445

**Comment by AGulev** [comment]
## Evidence

- The protobuf schema still requires `input` for every trigger row in `input_binding` files, so the historic crash signature is real when an incomplete row reaches serialization: `engine/input/proto/input/input_ddf.proto:243`, `engine/input/proto/input/input_ddf.proto:255`, `engine/input/proto/input/input_ddf.proto:273`.
- The current input-binding form now provides a default `:input` value for every trigger table row, including key, mouse, gamepad, touch, and text triggers: `editor/src/clj/editor/protobuf_forms.clj:82`, `editor/src/clj/editor/protobuf_forms.clj:89`, `editor/src/clj/editor/protobuf_forms.clj:100`, `editor/src/clj/editor/protobuf_forms.clj:111`, `editor/src/clj/editor/protobuf_forms.clj:122`, `editor/src/clj/editor/protobuf_forms.clj:133`.
- New table rows are added from field defaults, so pressing `+` now inserts a complete row instead of a partial one: `editor/src/clj/editor/form.clj:88`, `editor/src/clj/editor/cljfx_form_view.clj:956`, `editor/src/clj/editor/cljfx_form_view.clj:961`.
- Existing protobuf resources are loaded through `load-pb`, which injects protobuf defaults back into the in-memory map before editing/saving. That means older `input_binding` files missing `:input` get normalized on load instead of staying incomplete: `editor/src/clj/editor/protobuf_types.clj:166`, `editor/src/clj/editor/protobuf_types.clj:168`, `editor/src/clj/editor/protobuf.clj:1370`.
- The issue discussion links #5445 as related, and that issue is the same underlying failure on `input_binding` editing. It is now closed, with a 2026 maintainer comment saying it could not be reproduced in Defold 1.12.1.

## Why this looks already fixed

The current editor code blocks the two most likely ways this bug used to happen: creating a trigger row without an `input`, and keeping an older incomplete trigger row incomplete after load. Since the present form code supplies defaults for every trigger type and the current load path injects protobuf defaults before the resource is edited or saved, the `missing required fields: input` crash reported in #6994 looks more like an old stale manifestation of the already-addressed `input_binding` form problem than a still-current editor quit bug.
