### ISSUE TITLE
Editor 1.3.6. NullPointerException

### ISSUE THREAD

**Issue by Dragosha** [defold/defold#7018]
Rare exception (I catched it twice for 2 week when copy-past the game object with scaled sprite).

java.lang.NullPointerException: Unknown

Editor log:
```
2022-09-28 20:53:17.174 31147869 [JavaFX Application Thread] ERROR editor.error-reporting - {:line 112}
java.lang.NullPointerException: null
	at javax.vecmath.Tuple3d.sub(Tuple3d.java:221)
	at editor.scene_tools$manip__GT_apply_fn$fn__37463.invoke(scene_tools.clj:444)
	at editor.scene_tools$apply_manipulator.invokeStatic(scene_tools.clj:494)
	at editor.scene_tools$handle_input.invokeStatic(scene_tools.clj:528)
	at editor.scene_tools$handle_input.invoke(scene_tools.clj:498)
	at editor.scene$dispatch_input$fn__43508.invoke(scene.clj:1121)
	at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
	at clojure.core$reduce.invokeStatic(core.clj:6827)
	at editor.scene$dispatch_input.invokeStatic(scene.clj:1118)
	at editor.scene$update_image_view_BANG_$fn__43523.invoke(scene.clj:1160)
	at editor.scene$update_image_view_BANG_.invokeStatic(scene.clj:1158)
	at editor.scene$update_image_view_BANG_.invoke(scene.clj:1137)
	at editor.scene$refresh_scene_view_BANG_.invokeStatic(scene.clj:852)
	at editor.app_view$refresh_scene_views_BANG_$fn__48863.invoke(app_view.clj:1521)
	at editor.app_view$refresh_scene_views_BANG_.invokeStatic(app_view.clj:1521)
	at editor.app_view$make_app_view$fn__48901.invoke(app_view.clj:1633)
	at editor.ui$__GT_timer$fn__16250$fn__16251.invoke(ui.clj:1954)
	at clojure.lang.AFn.run(AFn.java:22)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:457)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:456)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:184)
	at java.base/java.lang.Thread.run(Thread.java:829)
```
<hr/>

<table>
<tr><td>Build time</td><td>2022-09-22T20:40:36.492761</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>3366b16bf439feaa518e981af04f678d970d4801</td></tr>
<tr><td>Defold engine sha</td><td>65e2f79be3b8c99f1999a976399a17eb31a79ff2</td></tr>
<tr><td>Defold version</td><td>1.3.6</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"a08650a6142a4fc1b2a7ff46767cf580"'>a08650a6142a4fc1b2a7ff46767cf580</a></td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 516.94</td></tr>
<tr><td>Java version</td><td>11.0.15+10-LTS</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by AGulev** [comment]
Are you able to reproduce this issue in newer editor?

**Comment by Dragosha** [comment]
> Are you able to reproduce this issue in newer editor?

I've already forgotten about that issue. It seems that it does not reproduce, we can close it.
