### ISSUE TITLE
error when opening any atlas

### ISSUE THREAD

**Issue by i200cm3** [defold/defold#7024]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2022-09-26T11:32:11.382507</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>e9aea46e5ef75b2f83052942027fcbd5eae5d05e</td></tr>
<tr><td>Defold engine sha</td><td>65e2f79be3b8c99f1999a976399a17eb31a79ff2</td></tr>
<tr><td>Defold version</td><td>1.3.6</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"6391b0db2e0b4a8eaf27af2ae44419d6"'>6391b0db2e0b4a8eaf27af2ae44419d6</a></td></tr>
<tr><td>GPU</td><td>Apple M1</td></tr>
<tr><td>GPU Driver</td><td>2.1 Metal - 76.3</td></tr>
<tr><td>Java version</td><td>11.0.15+10-LTS</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>12.4</td></tr>
<table>

**Comment by i200cm3** [comment]
An error occurred after using an atlas from another project. Restarted the editor and after that not one atlas was opened, and such an error occurred

**Comment by i200cm3** [comment]
The situation is worse. Nothing opens fonts, gui, collections. Even in a clean new project. Can you somehow clear the cache?

**Comment by britzl** [comment]
```
java.util.prefs.AbstractPreferences.put.class java.lang.IllegalArgumentException: Value too long: ["^REDACTED ]
    at java.util.prefs.AbstractPreferences.put(AbstractPreferences.java:253)
    at editor.prefs$fn.invokeStatic(prefs.clj:76)
    at editor.prefs$fn.invoke(prefs.clj:63)
    at editor.prefs$fn$G__12791__12805.invoke(prefs.clj:46)
    at editor.recent_files$add_BANG_.invokeStatic(recent_files.clj:44)
    at editor.app_view$make_tab_BANG_.invokeStatic(app_view.clj:1661)
    at editor.app_view$open_resource.invokeStatic(app_view.clj:1745)
    at editor.app_view$open_resource.invoke(app_view.clj:1699)
    at editor.app_view$open_resource.invokeStatic(app_view.clj:1701)
    at editor.app_view$fn$fnk48988_positional__48996.invoke(app_view.clj:1775)
    at editor.app_view$fn$fnk48988__49013$fn.invoke(app_view.clj:1771)
    at editor.app_view$fn$fnk48988__49013.invoke(app_view.clj:1771)
    at clojure.lang.AFn.applyToHelper(AFn.java:154)
    at clojure.lang.AFn.applyTo(AFn.java:144)
    at clojure.lang.AFunction$1.doInvoke(AFunction.java:31)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at editor.handler$invoke_fnk.invokeStatic(handler.clj:256)
    at editor.handler$run.invokeStatic(handler.clj:289)
    at editor.ui$execute_command.invokeStatic(ui.clj:1168)
    at editor.ui$run_command.invokeStatic(ui.clj:1404)
    at editor.ui$bind_double_click_BANG_$reify.handle(ui.clj:1436)
    at com.sun.javafx.event.CompositeEventHandler$NormalEventFilterRecord.handleCapturingEvent(CompositeEventHandler.java:321)
    at com.sun.javafx.event.CompositeEventHandler.dispatchCapturingEvent(CompositeEventHandler.java:98)
    at com.sun.javafx.event.EventHandlerManager.dispatchCapturingEvent(EventHandlerManager.java:221)
    at com.sun.javafx.event.EventHandlerManager.dispatchCapturingEvent(EventHandlerManager.java:180)
    at com.sun.javafx.event.CompositeEventDispatcher.dispatchCapturingEvent(CompositeEventDispatcher.java:43)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:52)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
    at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
    at javafx.event.Event.fireEvent(Event.java:198)
    at javafx.scene.Scene$ClickGenerator.postProcess(Scene.java:3586)
    at javafx.scene.Scene$MouseHandler.process(Scene.java:3890)
    at javafx.scene.Scene.processMouseEvent(Scene.java:1874)
    at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2607)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:411)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:301)
    at java.security.AccessController.doPrivileged(AccessController.java)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:450)
    at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:424)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:449)
    at com.sun.glass.ui.View.handleMouseEvent(View.java:551)
    at com.sun.glass.ui.View.notifyMouse(View.java:937)
    at com.sun.glass.ui.mac.MacView.notifyMouse(MacView.java:127)
```
