### ISSUE TITLE
ERROR editor.dialogs (No method in multimethod 'perform' for dispatch value: null)

### ISSUE THREAD

**Issue by TinyDobbins** [defold/defold#7038]
Windows 10. 

Defold 1.3.6.  (18bcb39)

during opening project got the following error:

```
2022-10-06 15:30:04.721 2327 [Thread-4] DEBUG com.defold.libs.ResourceUnpacker - unpacking '/_unpack/x86_64-linux/bin/dmengine' to 'C:\Users\bunbunbun\AppData\Local\Defold\unpack\18bcb391eb01d8d4f627df7a53c4cb0302acf403\x86_64-linux\bin\dmengine'
2022-10-06 15:30:04.829 2435 [Thread-4] DEBUG com.defold.libs.ResourceUnpacker - unpacking '/_unpack/x86_64-linux/bin/luajit-32' to 'C:\Users\bunbunbun\AppData\Local\Defold\unpack\18bcb391eb01d8d4f627df7a53c4cb0302acf403\x86_64-linux\bin\luajit-32'
2022-10-06 15:30:04.833 2439 [Thread-4] DEBUG com.defold.libs.ResourceUnpacker - unpacking '/_unpack/x86_64-linux/bin/luajit-64' to 'C:\Users\bunbunbun\AppData\Local\Defold\unpack\18bcb391eb01d8d4f627df7a53c4cb0302acf403\x86_64-linux\bin\luajit-64'
2022-10-06 15:30:04.842 2448 [Thread-4] INFO  com.defold.libs.ResourceUnpacker - defold.unpack.path=C:\Users\bunbunbun\AppData\Local\Defold\unpack\18bcb391eb01d8d4f627df7a53c4cb0302acf403
2022-10-06 15:30:09.255 6861 [Timer-0] INFO  editor.updater - {:line 300, :message "Checking for updates", :url "https://d.defold.com/editor2/channels/editor-alpha/update-v4.json"}
2022-10-06 15:30:09.617 7223 [Timer-0] INFO  editor.updater - {:line 307, :message "No update found"}
2022-10-06 15:30:15.964 13570 [clojure-agent-send-off-pool-5] INFO  editor.workspace - {:line 289, :msg "Loading plugin defold-spine/editor/src/spineext.clj"}
2022-10-06 15:30:17.147 14753 [clojure-agent-send-off-pool-5] INFO  editor.workspace - {:line 294, :msg "Loaded plugin defold-spine/editor/src/spineext.clj"}
2022-10-06 15:30:17.148 14754 [clojure-agent-send-off-pool-5] INFO  editor.workspace - {:line 289, :msg "Loading plugin defold-spine/editor/src/spineguiext.clj"}
2022-10-06 15:30:17.760 15366 [clojure-agent-send-off-pool-5] INFO  editor.workspace - {:line 294, :msg "Loaded plugin defold-spine/editor/src/spineguiext.clj"}
2022-10-06 15:30:20.756 18362 [clojure-agent-send-off-pool-5] ERROR editor.dialogs - {:line 436}
java.lang.IllegalArgumentException: No method in multimethod 'perform' for dispatch value: null
	at clojure.lang.MultiFn.getFn(MultiFn.java:156)
	at clojure.lang.MultiFn.invoke(MultiFn.java:233)
	at internal.transaction$apply_tx$fn__9572.invoke(transaction.clj:792)
	at internal.transaction$apply_tx.invokeStatic(transaction.clj:790)
	at internal.transaction$apply_tx.invoke(transaction.clj:782)
	at internal.transaction$apply_tx.invokeStatic(transaction.clj:789)
	at internal.transaction$apply_tx.invoke(transaction.clj:782)
	at internal.transaction$apply_tx.invokeStatic(transaction.clj:789)
	at internal.transaction$apply_tx.invoke(transaction.clj:782)
	at internal.transaction$apply_tx.invokeStatic(transaction.clj:789)
	at internal.transaction$transact_STAR_.invokeStatic(transaction.clj:872)
	at dynamo.graph$transact.invokeStatic(graph.clj:158)
	at editor.defold_project$load_nodes_BANG_.invokeStatic(defold_project.clj:201)
	at editor.defold_project$load_project$fn__21662.invoke(defold_project.clj:257)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:665)
	at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1973)
	at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1973)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at editor.defold_project$load_project.invokeStatic(defold_project.clj:257)
	at editor.defold_project$open_project_BANG_.invokeStatic(defold_project.clj:922)
	at editor.boot_open_project$open_project_BANG_.invokeStatic(boot_open_project.clj:408)
	at editor.boot_open_project$open_project_BANG_.invoke(boot_open_project.clj:406)
	at clojure.lang.AFn.applyToHelper(AFn.java:171)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:665)
	at editor.boot$open_project_with_progress_dialog$fn__91520.invoke(boot.clj:69)
	at editor.dialogs$make_load_project_dialog$fn__18286$fn__18289.invoke(dialogs.clj:434)
	at clojure.core$binding_conveyor_fn$fn__5739.invoke(core.clj:2030)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2022-10-06 15:30:20.793 18399 [JavaFX Application Thread] ERROR editor.error-reporting - {:line 112}
java.lang.IllegalArgumentException: No method in multimethod 'perform' for dispatch value: null
	at clojure.lang.MultiFn.getFn(MultiFn.java:156)
	at clojure.lang.MultiFn.invoke(MultiFn.java:233)
	at internal.transaction$apply_tx$fn__9572.invoke(transaction.clj:792)
	at internal.transaction$apply_tx.invokeStatic(transaction.clj:790)
	at internal.transaction$apply_tx.invoke(transaction.clj:782)
	at internal.transaction$apply_tx.invokeStatic(transaction.clj:789)
	at internal.transaction$apply_tx.invoke(transaction.clj:782)
	at internal.transaction$apply_tx.invokeStatic(transaction.clj:789)
	at internal.transaction$apply_tx.invoke(transaction.clj:782)
	at internal.transaction$apply_tx.invokeStatic(transaction.clj:789)
	at internal.transaction$transact_STAR_.invokeStatic(transaction.clj:872)
	at dynamo.graph$transact.invokeStatic(graph.clj:158)
	at editor.defold_project$load_nodes_BANG_.invokeStatic(defold_project.clj:201)
	at editor.defold_project$load_project$fn__21662.invoke(defold_project.clj:257)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:665)
	at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1973)
	at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1973)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at editor.defold_project$load_project.invokeStatic(defold_project.clj:257)
	at editor.defold_project$open_project_BANG_.invokeStatic(defold_project.clj:922)
	at editor.boot_open_project$open_project_BANG_.invokeStatic(boot_open_project.clj:408)
	at editor.boot_open_project$open_project_BANG_.invoke(boot_open_project.clj:406)
	at clojure.lang.AFn.applyToHelper(AFn.java:171)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:665)
	at editor.boot$open_project_with_progress_dialog$fn__91520.invoke(boot.clj:69)
	at editor.dialogs$make_load_project_dialog$fn__18286$fn__18289.invoke(dialogs.clj:434)
	at clojure.core$binding_conveyor_fn$fn__5739.invoke(core.clj:2030)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by vlaaad** [comment]
The issue turned out to be a `spinejson` file exported by an unsupported Spine version (4.1.+)

**Comment by britzl** [comment]
> The issue turned out to be a `spinejson` file exported by an unsupported Spine version (4.1.+)

I wonder if we can't add a version check and hadle this more gracefully? (assuming the spine format contains a version)

**Comment by vlaaad** [comment]
It is, actually

**Comment by TinyDobbins** [comment]
yes, works fine with Spine version 4.0+ !
