### ISSUE TITLE
I was selecting a couple of Game Objects from a collection

### ISSUE THREAD

**Issue by DeRaNGeR** [defold/defold#7128]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2022-11-03T18:44:27.090998</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>cbef6984dd0e2953b6371c7800905915a894a5f8</td></tr>
<tr><td>Defold engine sha</td><td>f0ad06a2f1fbf0e9cbddbf96162a75bc006d84bb</td></tr>
<tr><td>Defold version</td><td>1.3.7</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"ab43e7e65a98483db9863c09a1dc0a27"'>ab43e7e65a98483db9863c09a1dc0a27</a></td></tr>
<tr><td>GPU</td><td>Intel(R) UHD Graphics</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 - Build 27.20.100.8783</td></tr>
<tr><td>Java version</td><td>11.0.15+10-LTS</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 11</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by britzl** [comment]
```
editor.ui$fn__15371$fn__15372.invoke.class java.lang.NullPointerException: null
    at editor.ui$fn$fn.invoke(ui.clj:920)
    at clojure.core$mapv$fn.invoke(core.clj:6912)
    at clojure.core.protocols$iter_reduce.invokeStatic(protocols.clj:49)
    at clojure.core.protocols$fn.invokeStatic(protocols.clj:75)
    at clojure.core.protocols$fn.invoke(protocols.clj:75)
    at clojure.core.protocols$fn$G__8068__8086.invoke(protocols.clj:13)
    at clojure.core$reduce.invokeStatic(core.clj:6828)
    at clojure.core$mapv.invokeStatic(core.clj:6903)
    at editor.ui$fn.invokeStatic(ui.clj:920)
    at editor.ui$fn.invoke(ui.clj:915)
    at editor.ui$fn$G__15057__15129.invoke(ui.clj:661)
    at editor.ui$observe_selection$fn.invoke(ui.clj:1058)
    at editor.ui$observe_list$reify.onChanged(ui.clj:277)
    at com.sun.javafx.collections.ListListenerHelper$SingleChange.fireValueChangedEvent(ListListenerHelper.java:164)
    at com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(ListListenerHelper.java:73)
    at javafx.collections.ObservableListBase.fireChange(ObservableListBase.java:239)
    at javafx.collections.ListChangeBuilder.commit(ListChangeBuilder.java:482)
    at javafx.collections.ListChangeBuilder.endChange(ListChangeBuilder.java:541)
    at javafx.collections.ObservableListBase.endChange(ObservableListBase.java:211)
    at com.sun.javafx.scene.control.SelectedItemsReadOnlyObservableList.lambda$new$0(SelectedItemsReadOnlyObservableList.java:91)
    at com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(ListListenerHelper.java:329)
    at com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(ListListenerHelper.java:73)
    at javafx.collections.ObservableListBase.fireChange(ObservableListBase.java:239)
    at javafx.collections.ListChangeBuilder.commit(ListChangeBuilder.java:482)
    at javafx.collections.ListChangeBuilder.endChange(ListChangeBuilder.java:541)
    at javafx.collections.ObservableListBase.endChange(ObservableListBase.java:211)
    at com.sun.javafx.scene.control.ReadOnlyUnbackedObservableList._endChange(ReadOnlyUnbackedObservableList.java:64)
    at javafx.scene.control.MultipleSelectionModelBase$SelectedIndicesList._endChange(MultipleSelectionModelBase.java:918)
    at javafx.scene.control.TreeView$TreeViewBitSetSelectionModel.lambda$new$2(TreeView.java:1388)
    at javafx.event.WeakEventHandler.handle(WeakEventHandler.java:79)
    at com.sun.javafx.event.CompositeEventHandler$WeakEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:282)
    at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
    at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
    at javafx.event.Event.fireEvent(Event.java:198)
    at javafx.scene.control.TreeItem.fireEvent(TreeItem.java:764)
    at javafx.scene.control.TreeItem$4.invalidated(TreeItem.java:563)
    at javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:110)
    at javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:145)
    at javafx.beans.property.BooleanProperty.setValue(BooleanProperty.java:79)
    at javafx.scene.control.TreeItem.setExpanded(TreeItem.java:539)
    at editor.ui$custom_tree_view_mouse_pressed_BANG_.invokeStatic(ui.clj:1003)
    at editor.ui$reify.handle(ui.clj:1012)
    at com.sun.javafx.event.CompositeEventHandler$NormalEventFilterRecord.handleCapturingEvent(CompositeEventHandler.java:321)
    at com.sun.javafx.event.CompositeEventHandler.dispatchCapturingEvent(CompositeEventHandler.java:98)
    at com.sun.javafx.event.EventHandlerManager.dispatchCapturingEvent(EventHandlerManager.java:221)
    at com.sun.javafx.event.EventHandlerManager.dispatchCapturingEvent(EventHandlerManager.java:180)
    at com.sun.javafx.event.CompositeEventDispatcher.dispatchCapturingEvent(CompositeEventDispatcher.java:43)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:52)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
    at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
    at javafx.event.Event.fireEvent(Event.java:198)
    at javafx.scene.Scene$MouseHandler.process(Scene.java:3881)
    at javafx.scene.Scene.processMouseEvent(Scene.java:1874)
    at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2607)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:411)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:301)
    at java.security.AccessController.doPrivileged(AccessController.java)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:450)
    at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:424)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:449)
    at com.sun.glass.ui.View.handleMouseEvent(View.java:551)
    at com.sun.glass.ui.View.notifyMouse(View.java:937)
    at com.sun.glass.ui.win.WinApplication._runLoop(WinApplication.java)
    at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:184)
    at java.lang.Thread.run(Thread.java:829)
```

**Comment by vlaaad** [comment]
Happens here:
```clj
(->> ^TreeView this
     .getSelectionModel
     .getSelectedItems
     (mapv #(.getValue ^TreeItem %)))
```
...which implies selected items might contain `nil` tree items, possibly a JavaFX bug we can easily workaround.

**Comment by AGulev** [comment]
## Status

Possibly outdated/fixed

## Evidence

- The issue comments already identified the likely root cause: `TreeView.getSelectedItems()` may contain `nil` entries, which made the old code crash when it blindly called `.getValue` on every selected `TreeItem`.
- Current `TreeView` selection code now explicitly filters out `nil` items before reading their values: `editor/src/clj/editor/ui.clj:1067`.
- The exact code change appears in commit `a2c22b9270aed3655919ed4d84dcbdfc8dff7611` from 2025-07-21, titled `filter out nil items from tree selection (#10991)`, which changes the old `mapv #(.getValue ^TreeItem %)` implementation into a nil-safe `keep` pipeline.
- The current implementation returns a concrete vector after filtering, so the crash path described in the 2022 stack trace no longer exists in the same form: `editor/src/clj/editor/ui.clj:1067`.
- The repository bug triage checklist also marks `#7128` as reviewed in `bugs/open-bug-checklist.md:129`.

## Why I think it is already fixed

The maintainer diagnosis in the issue matches the current code change very closely: the bug was caused by unexpected `nil` tree items coming from JavaFX selection state, and the editor now guards that exact path by dropping `nil` entries before dereferencing them. I did not reproduce the old Windows 11 editor behavior locally, but the relevant crash site has been directly hardened in the present codebase, so this issue looks stale rather than still open in practice.
