### ISSUE TITLE
Macos when creating project with subfolder it gives error

### ISSUE THREAD

**Issue by sgulci** [defold/defold#7137]
### Expected behaviour
  
if we create a project to a subfolder it should create parent folders if not exists already

### Actual behaviour

cannot create a project

### Steps to reproduce

when creating a new project give folders with contain subfolders which the parent folder should not exist

<hr/>

<table>
<tr><td>Build time</td><td>2022-09-14T14:50:36.106528</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>ac8e0b6bc32b859ecdaceeb6046dbc0444458aba</td></tr>
<tr><td>Defold engine sha</td><td>c1c0592986a4421f33490422c2af532e533aeca5</td></tr>
<tr><td>Defold version</td><td>1.3.5</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"0a559b1f902140bb9cfa9da76d3c63fe"'>0a559b1f902140bb9cfa9da76d3c63fe</a></td></tr>
<tr><td>GPU</td><td>AMD Radeon Pro 5500M OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 ATI-4.8.54</td></tr>
<tr><td>Java version</td><td>11.0.15+10-LTS</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>12.4</td></tr>
<table>

**Comment by britzl** [comment]
```
java.io.FileOutputStream.open0.class java.io.FileNotFoundException: /Users/sahin/defold-workspace/platformer1/.gitattributes (No such file or directory)
    at java.io.FileOutputStream.open0(FileOutputStream.java)
    at java.io.FileOutputStream.open(FileOutputStream.java:298)
    at java.io.FileOutputStream.<init>(FileOutputStream.java:237)
    at java.io.FileOutputStream.<init>(FileOutputStream.java:187)
    at editor.welcome$expand_proj_zip_BANG_.invokeStatic(welcome.clj:251)
    at editor.welcome$show_welcome_dialog_BANG_$download_template_BANG___88329$fn.invoke(welcome.clj:627)
    at clojure.core$binding_conveyor_fn$fn.invoke(core.clj:2030)
    at clojure.lang.AFn.call(AFn.java:18)
    at java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.lang.Thread.run(Thread.java:829)
```

**Comment by britzl** [comment]
```
java.io.FileOutputStream.open0.class java.io.FileNotFoundException: /Users/sahin/defold-workspace/platformer1/.gitattributes (No such file or directory)
    at java.io.FileOutputStream.open0(FileOutputStream.java)
    at java.io.FileOutputStream.open(FileOutputStream.java:298)
    at java.io.FileOutputStream.<init>(FileOutputStream.java:237)
    at java.io.FileOutputStream.<init>(FileOutputStream.java:187)
    at editor.welcome$expand_proj_zip_BANG_.invokeStatic(welcome.clj:251)
    at editor.welcome$show_welcome_dialog_BANG_$download_template_BANG___88329$fn.invoke(welcome.clj:627)
    at clojure.core$binding_conveyor_fn$fn.invoke(core.clj:2030)
    at clojure.lang.AFn.call(AFn.java:18)
    at java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.lang.Thread.run(Thread.java:829)
```

**Comment by britzl** [comment]
@sgulci how do you manage to select a folder that doesn't exist on macOS. Can you give the exact steps to reproduce please?

**Comment by AGulev** [comment]
no answer from the reporter
