### ISSUE TITLE
upgrade download failed. the progress was always 0

### ISSUE THREAD

**Issue by Stonekity** [defold/defold#7182]
### Expected behaviour
download and upgrade successfully

### Actual behaviour
but failed, no response

### Steps to reproduce
clink the hint of 'Update Available'

<hr/>

<table>
<tr><td>Build time</td><td>2022-09-14T14:50:36.106528</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>ac8e0b6bc32b859ecdaceeb6046dbc0444458aba</td></tr>
<tr><td>Defold engine sha</td><td>c1c0592986a4421f33490422c2af532e533aeca5</td></tr>
<tr><td>Defold version</td><td>1.3.5</td></tr>
<tr><td>GPU</td><td>AMD Radeon Pro 5300M OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 ATI-4.8.54</td></tr>
<tr><td>Java version</td><td>11.0.15+10-LTS</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>12.4</td></tr>
<table>

**Comment by britzl** [comment]
What if you launch Defold from the terminal?

```bash
$> /Applications/Defold.app/Contents/MacOS/Defold
```

What does the terminal output say?

**Comment by Stonekity** [comment]
2022-11-29 16:53:58.382 INFO  default    editor.updater - {:line 299, :message "Checking for updates", :url "https://d.defold.com/editor2/channels/editor-alpha/update-v3.json"}
2022-11-29 16:54:01.302 INFO  default    editor.updater - {:line 305, :message "New version found", :sha1 "f06501e9ac279cae0372b04f3fbc2800f7ecaf9c"}
2022-11-29 16:54:16.330 INFO  default    editor.updater - {:line 124, :message "Downloading update", :url "https://d.defold.com/archive/f06501e9ac279cae0372b04f3fbc2800f7ecaf9c/editor-alpha/editor2/Defold-x86_64-darwin.zip", :file "/private/var/folders/6t/kvwyszgn1dvg36ml3xrx1hrh0000gn/T/defold-update9350505609895409815.zip"}
moved permanently 'https://d.defold.com/archive/f06501e9ac279cae0372b04f3fbc2800f7ecaf9c/editor-alpha/editor2/Defold-x86_64-darwin.zip' -> 'http://d.defold.com/archive/editor-alpha/f06501e9ac279cae0372b04f3fbc2800f7ecaf9c/editor-alpha/editor2/Defold-x86_64-macos.zip'
2022-11-29 16:55:06.090 INFO  default    editor.updater - {:line 213, :message "Update download failed"}
java.net.SocketTimeoutException: Read timed out
	at java.base/java.net.SocketInputStream.socketRead0(Native Method)
	at java.base/java.net.SocketInputStream.socketRead(SocketInputStream.java:115)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:168)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
	at java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:252)
	at java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:292)
	at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:351)
	at java.base/sun.net.www.MeteredStream.read(MeteredStream.java:134)
	at java.base/java.io.FilterInputStream.read(FilterInputStream.java:133)
	at java.base/sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3510)
	at java.base/sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3503)
	at clojure.java.io$fn__11500.invokeStatic(io.clj:305)
	at clojure.java.io$fn__11500.invoke(io.clj:302)
	at clojure.lang.MultiFn.invoke(MultiFn.java:239)
	at clojure.java.io$copy.invokeStatic(io.clj:406)
	at clojure.java.io$copy.doInvoke(io.clj:391)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at util.net$download_BANG_.invokeStatic(net.clj:62)
	at util.net$download_BANG_.doInvoke(net.clj:32)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at util.net$download_BANG_.invokeStatic(net.clj:48)
	at editor.updater$download_BANG_.invokeStatic(updater.clj:129)
	at editor.updater$download_and_extract_BANG_$fn__76785.invoke(updater.clj:205)
	at clojure.core$binding_conveyor_fn$fn__5739.invoke(core.clj:2030)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by Stonekity** [comment]
<img width="472" alt="image" src="https://user-images.githubusercontent.com/3970392/204483983-dda57a50-74f6-4dd1-a6c8-8882d67e26a7.png">

**Comment by Stonekity** [comment]
I can download the zip file from "http://d.defold.com/archive/editor-alpha/f06501e9ac279cae0372b04f3fbc2800f7ecaf9c/editor-alpha/editor2/Defold-x86_64-macos.zip" in the browser, but not in the Editor

**Comment by britzl** [comment]
> Maybe it's because my network is poor? only 30+KB/s when downloads

Probably yes. There is a `java.net.SocketTimeoutException: Read timed out` which indicates network issues. It could also be that we need to increase the timeout to better accommodate for low quality/slow connections.

My recommendation for you is to download the updated editor manually from d.defold.com
