### ISSUE TITLE
Attempting to select nil values

### ISSUE THREAD

**Issue by alvarohghg** [defold/defold#7194]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2022-09-22T20:40:36.492761</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>3366b16bf439feaa518e981af04f678d970d4801</td></tr>
<tr><td>Defold engine sha</td><td>65e2f79be3b8c99f1999a976399a17eb31a79ff2</td></tr>
<tr><td>Defold version</td><td>1.3.6</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"9068f9b266ae4e47bd535409f4316b38"'>9068f9b266ae4e47bd535409f4316b38</a></td></tr>
<tr><td>GPU</td><td>Intel(R) UHD Graphics</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 - Build 30.0.101.2079</td></tr>
<tr><td>Java version</td><td>11.0.15+10-LTS</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by britzl** [comment]
```
editor.defold_project$select.invokeStatic.class java.lang.AssertionError: Assert failed: Attempting to select nil values
(every? some? node-ids)
    at editor.defold_project$select.invokeStatic(defold_project.clj:453)
    at editor.app_view$select.invokeStatic(app_view.clj:1462)
    at editor.app_view$select.invoke(app_view.clj:1462)
    at editor.app_view$select.invokeStatic(app_view.clj:1464)
    at editor.app_view$select_BANG_.invokeStatic(app_view.clj:1471)
    at editor.app_view$select_BANG_.invoke(app_view.clj:1471)
    at editor.app_view$select_BANG_.invokeStatic(app_view.clj:1473)
    at editor.boot_open_project$load_stage_BANG_$fn.invoke(boot_open_project.clj:203)
    at editor.build_errors_view$make_build_errors_view$fn.invoke(build_errors_view.clj:274)
    at editor.ui$on_double_BANG_$reify.handle(ui.clj:522)
    at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
```

**Comment by britzl** [comment]
When does this happen? When selecting a project from the Recent Projects list on the welcome screen?

**Comment by AGulev** [comment]
no answr from the reporter
