### ISSUE TITLE
Side scroller tutorial error

### ISSUE THREAD

**Issue by Ugnx2** [defold/defold#7241]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2022-05-30T09:03:16.742362</td></tr>
<tr><td>Defold channel</td><td>beta</td></tr>
<tr><td>Defold editor sha</td><td>c2ab1630e34f1311d8340d81494cf5317d25fe16</td></tr>
<tr><td>Defold engine sha</td><td>c2ab1630e34f1311d8340d81494cf5317d25fe16</td></tr>
<tr><td>Defold version</td><td>1.3.3</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"96936d1232d143828fc7f4c13683c5e4"'>96936d1232d143828fc7f4c13683c5e4</a></td></tr>
<tr><td>GPU</td><td>GeForce GTX 750 Ti/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 430.64</td></tr>
<tr><td>Java version</td><td>11.0.15+10-LTS</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>4.4.0-21-generic</td></tr>
<table>

**Comment by britzl** [comment]
```
java.util.concurrent.FutureTask.report.class java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: Could not initialize class com.dynamo.bob.TexcLibrary
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:191)
    at clojure.core$deref_future.invokeStatic(core.clj:2300)
    at clojure.core$future_call$reify.deref(core.clj:6974)
    at clojure.core$deref.invokeStatic(core.clj:2320)
    at clojure.core$deref.invoke(core.clj:2306)
    at clojure.core$map$fn.invoke(core.clj:2755)
    at clojure.lang.LazySeq.sval(LazySeq.java:42)
    at clojure.lang.LazySeq.seq(LazySeq.java:58)
    at clojure.lang.RT.seq(RT.java:531)
    at clojure.core$seq__5387.invokeStatic(core.clj:137)
    at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:24)
    at clojure.core.protocols$fn.invokeStatic(protocols.clj:75)
    at clojure.core.protocols$fn.invoke(protocols.clj:75)
    at clojure.core.protocols$fn$G__8068__8086.invoke(protocols.clj:13)
    at clojure.core$reduce.invokeStatic(core.clj:6824)
    at editor.pipeline$batched_pmap.invokeStatic(pipeline.clj:174)
    at editor.pipeline$build_BANG_.invokeStatic(pipeline.clj:189)
    at editor.build$build_project_BANG_.invokeStatic(build.clj:59)
    at editor.app_view$build_project_BANG_.invokeStatic(app_view.clj:752)
```

**Comment by britzl** [comment]
@Ugnx2 Could you please check which version of glibc you have and upgrade to 2.29+ if lower?

**Comment by AGulev** [comment]
duplicate https://github.com/defold/defold/issues/6917
