### ISSUE TITLE
Failure debugging to real device via wifi / USB

### ISSUE THREAD

**Issue by jcbk101** [defold/defold#7248]
### Expected behaviour
Build / Run executes to connected device

### Actual behaviour
Fails to connect to device even though device selected as a target

### Steps to reproduce
Install debug dev app to device, run, then attempt to build / run with changes.

<hr/>

<table>
<tr><td>Build time</td><td>2022-12-28T16:03:38.845301</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>93e98c1faf79e977d4b4bf5a0434483831a405b2</td></tr>
<tr><td>Defold engine sha</td><td>8f96e450ddfb006a99aa134fdd373cace3760571</td></tr>
<tr><td>Defold version</td><td>1.4.1</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"ed81207df1734d579bde3f5fcf476382"'>ed81207df1734d579bde3f5fcf476382</a></td></tr>
<tr><td>GPU</td><td>GeForce GT 730/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 456.71</td></tr>
<tr><td>Java version</td><td>11.0.15+10-LTS</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by britzl** [comment]
```
editor.debugging.mobdebug$connect_BANG_$fn__45296.invoke.class clojure.lang.ExceptionInfo: Failed to connect to debugger on localhost:8172
    at editor.debugging.mobdebug$connect_BANG_$fn.invoke(mobdebug.clj:342)
    at clojure.lang.AFn.run(AFn.java:22)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
    at java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.lang.Thread.run(Thread.java:829)
```

**Comment by britzl** [comment]
It looks like you are attempting to start a debugging session (using F5 or Debug->Start/Attach). What if you do Project->Build instead?

**Comment by jcbk101** [comment]
It fails also. I did get it to work one single time over USB and it stopped working after my first build. Wifi will not allow a Build/Run


________________________________

**Comment by britzl** [comment]
Do you have some antivirus or other security software that might prevent Defold from connecting to the running game? Try whitelisting defold.exe and dmengine.exe

**Comment by jcbk101** [comment]
Only anti virus software I have on my computer is windows defender. I can check my router to see if that has any settings on it I need to be checked but I doubt it


________________________________

**Comment by britzl** [comment]
> I can check my router to see if that has any settings on it I need to be checked but I doubt it

Yeah, unlikely that it is a problem. It would be interesting if you have the possibility to test on another network though. In general it should not be a problem to reload over wifi. I'm also surprised that you have issues running over USB to be honest...

**Comment by britzl** [comment]
Just to be clear: Have you tested with a small, almost empty project, without any extensions or dependencies?

**Comment by jcbk101** [comment]
I have not, but I will try that. I never directly installed dnengine onto my android device, was I supposed to do that?


________________________________

**Comment by britzl** [comment]
> ### Steps to reproduce
> Install debug dev app to device, run, then attempt to build / run with changes.


> I never directly installed dnengine onto my android device, was I supposed to do that?

I'm not sure I follow. What have you installed on your phone?

Let's do like this instead. Please follow these exact steps and report result:

1. Create a new project from the Mobile Game template
2. Bundle the project for Android.
   * Make sure you create a Debug bundle
   * Select APK as bundle format
3. Install the apk.
4. Start the installed app. You should see a black screen.
5. Make sure your phone and computer are on the same wifi network.
6. Target your phone using editor menu option Project->Target
7. Open main.collection
  * Add a game object and move it to 200, 200, 0
  * Add a sprite
  * Set Image to "/builtins/graphics/particle_blob.tilesource"
  * Set animation to "anim"
  * Make sure the sprite is visible in the scene view
8. Select Project->Build (double check that your phone is still set as target)

Expected result: The game object and sprite should now be visible in the running app on your phone. If nothing happens then please do the following:

* Check the editor console for errors. Are there any errors? Please share them?
* Read log on your phone using logcat tool: https://defold.com/manuals/debugging-game-and-system-logs/#android. Share the log here!

**Comment by jcbk101** [comment]
Okay, finally made it home and gave it all a try. 

Blank project fails to Project->build. I get this error:

INFO:ENGINE: Defold Engine 1.4.1 (8f96e45)
FATAL:ENGINE: Unable to load project file: 'http://192.168.1.93:52052/build/game.projectc' (-1)
INFO:DLIB: SSDP: Done on address 192.168.1.68

IP: xx.xx.93 is my Dev PC
IP: xx.xx.68 is the device I am trying to deploy updates to (an old phone).

I also tried to do a hot-reload and nothing changed.

**Comment by britzl** [comment]
> FATAL:ENGINE: Unable to load project file: 'http://192.168.1.93:52052/build/game.projectc' (-1)

Ok, that's great (sort of). Now we do have something tangible. For some reason your old phone is not allowed to connect to and download '192.168.1.93:52052/build/game.projectc'.

I've seen network routers and firewalls block high "random" ports such as 52052. I wonder if this is the case for you?

**Comment by jcbk101** [comment]
Hmmm, interesting. Are these ports set automatically in Defold?


________________________________

**Comment by britzl** [comment]
> Are these ports set automatically in Defold?

Yes. We select a random port within a high range.

**Comment by britzl** [comment]
> What are my options for testing different ports? Should I allow these ranges in my router / gateway / modem??

We need to figure out if it is indeed the router which blocks access or not. Start by checking if you can access the url from another phone or computer on the same network (like I wrote above).



> If you have another PC on the same network then try opening http://192.168.1.93:52052/build/game.projectc in the browser of that PC. Does it work?
> 
> PS The port changes each time so pay attention to the output in the console!

**Comment by jcbk101** [comment]
Lol. Thanks, that was o e of the first things I tried. My laptop and other phones do the same thing. I test 3 phones with different resolutions


________________________________

**Comment by jcbk101** [comment]
As for thevport changes, I recall seeing a failure on 8081?? I believe. Can't recall, but I do remember seeing 8080 or 8081.


________________________________

**Comment by AGulev** [comment]
I think it should work now

**Comment by jcbk101** [comment]
Thanks. I believe it does. Much appreciate.


________________________________
