### ISSUE TITLE
Collection becomes unresponsive when attaching an animation set to a model component using GLB files

### ISSUE THREAD

**Issue by Makoren** [defold/defold#7294]
### Expected behaviour
Should be able to attach an `.animationset` file to a model component consisting of GLB files with no errors, allowing you to play those animations.

### Actual behaviour
Attaching an animation set to the model component throws a Clojure error and causes the affected collection file to become unresponsive. Building the game also throws an error.

You can reverse the change by editing the text of the collection file to remove the animation set and restarting Defold.

### Steps to reproduce
1. Download the [attached Defold project](https://github.com/defold/defold/files/10462965/animsetbug.zip). It's an empty project with only the affected files.
2. Open `main.collection`.
3. Click on the model component, and attach `ybot.animationset` to the Animations property.

<hr/>

<table>
<tr><td>Build time</td><td>2023-01-19T21:57:02.089212</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>26e4e30870571b201415a84178387305d91d630b</td></tr>
<tr><td>Defold engine sha</td><td>8f96e450ddfb006a99aa134fdd373cace3760571</td></tr>
<tr><td>Defold version</td><td>1.4.1</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"c4d938f09b0f48f388708173ce4f68a5"'>c4d938f09b0f48f388708173ce4f68a5</a></td></tr>
<tr><td>GPU</td><td>Apple M1</td></tr>
<tr><td>GPU Driver</td><td>2.1 Metal - 83</td></tr>
<tr><td>Java version</td><td>11.0.15+10-LTS</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>13.1</td></tr>
<table>

**Comment by britzl** [comment]
```
editor.handler$invoke_fnk.invokeStatic.class clojure.lang.ExceptionInfo: handler ':cut' in context ':workbench' failed at ':enabled?' with message 'null'
    at editor.handler$invoke_fnk.invokeStatic(handler.clj:262)
    at editor.handler$enabled_QMARK_.invokeStatic(handler.clj:296)
    at editor.ui$refresh_menu_item_state.invokeStatic(ui.clj:1617)
    at editor.ui$refresh_menu_item_state.invoke(ui.clj:1593)
    at editor.ui$refresh_menu_item_state.invokeStatic(ui.clj:1599)
    at editor.ui$refresh_menubar_state.invokeStatic(ui.clj:1630)
    at editor.ui$refresh_menus_BANG_.invokeStatic(ui.clj:1778)
    at editor.ui$refresh.invokeStatic(ui.clj:1799)
    at editor.app_view$refresh_menus_and_toolbars_BANG_.invokeStatic(app_view.clj:1572)
    at editor.app_view$make_app_view$fn.invoke(app_view.clj:1696)
    at editor.ui$__GT_timer$fn$fn.invoke(ui.clj:1933)
    at clojure.lang.AFn.run(AFn.java:22)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:457)
    at java.security.AccessController.doPrivileged(AccessController.java)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:456)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
com.dynamo.bob.pipeline.ModelUtil$SortOnNodeIndex.compare.class java.lang.NullPointerException: null
    at com.dynamo.bob.pipeline.ModelUtil$SortOnNodeIndex.compare(ModelUtil.java:273)
    at com.dynamo.bob.pipeline.ModelUtil$SortOnNodeIndex.compare(ModelUtil.java:266)
    at java.util.TimSort.countRunAndMakeAscending(TimSort.java:355)
    at java.util.TimSort.sort(TimSort.java:234)
    at java.util.Arrays.sort(Arrays.java:1441)
    at com.dynamo.bob.pipeline.ModelUtil.loadAnimations(ModelUtil.java:332)
    at com.dynamo.bob.pipeline.AnimationSetBuilder.loadModelAnimations(AnimationSetBuilder.java:181)
    at com.dynamo.bob.pipeline.AnimationSetBuilder.buildAnimations(AnimationSetBuilder.java:215)
    at editor.animation_set$load_and_validate_animation_set.invokeStatic(animation_set.clj:78)
    at editor.animation_set$fn.invokeStatic(animation_set.clj:87)
    at editor.animation_set$fn.invoke(animation_set.clj:84)
    at clojure.lang.AFn.applyToHelper(AFn.java:154)
    at clojure.lang.AFn.applyTo(AFn.java:144)
    at clojure.lang.AFunction$1.doInvoke(AFunction.java:31)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at clojure.lang.Var.invoke(Var.java:384)
    at editor.model$ModelNode$behavior$animation_set_info$fn.invoke(model.clj:163)
    at internal.node$trace_expr.invokeStatic(node.clj:44)
    at editor.model$ModelNode$behavior$animation_set_info.invokeStatic(model.clj:163)
    at editor.model$ModelNode$behavior$animation_set_info.invoke(model.clj:163)
```
