### ISSUE TITLE
Unable to open readme markdown file in editor

### ISSUE THREAD

**Issue by JinqiZ** [defold/defold#7295]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2023-01-19T21:56:05.482617</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>26e4e30870571b201415a84178387305d91d630b</td></tr>
<tr><td>Defold engine sha</td><td>8f96e450ddfb006a99aa134fdd373cace3760571</td></tr>
<tr><td>Defold version</td><td>1.4.1</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"5298bc0f848744ea904dc8de8e6a791f"'>5298bc0f848744ea904dc8de8e6a791f</a></td></tr>
<tr><td>GPU</td><td>Intel(R) Iris(R) Xe Graphics</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 - Build 31.0.101.3616</td></tr>
<tr><td>Java version</td><td>11.0.15+10-LTS</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 11</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by britzl** [comment]
```
javafx.scene.web.WebEngine.<init>.class java.lang.NoClassDefFoundError: Could not initialize class com.sun.webkit.WebPage
    at javafx.scene.web.WebEngine.<init>(WebEngine.java:854)
    at javafx.scene.web.WebEngine.<init>(WebEngine.java:839)
    at javafx.scene.web.WebView.<init>(WebView.java:275)
    at editor.html_view$make_web_view.invokeStatic(html_view.clj:223)
    at editor.html_view$make_view.invokeStatic(html_view.clj:271)
    at editor.html_view$make_view.invoke(html_view.clj:269)
    at editor.app_view$make_tab_BANG_.invokeStatic(app_view.clj:1723)
    at editor.app_view$open_resource.invokeStatic(app_view.clj:1811)
    at editor.app_view$open_resource.invoke(app_view.clj:1762)
    at editor.app_view$open_resource.invokeStatic(app_view.clj:1764)
    at editor.app_view$fn$fnk58470_positional__58478.invoke(app_view.clj:1841)
    at editor.app_view$fn$fnk58470__58495$fn.invoke(app_view.clj:1837)
    at editor.app_view$fn$fnk58470__58495.invoke(app_view.clj:1837)
    at clojure.lang.AFn.applyToHelper(AFn.java:154)
    at clojure.lang.AFn.applyTo(AFn.java:144)
    at clojure.lang.AFunction$1.doInvoke(AFunction.java:31)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at editor.handler$invoke_fnk.invokeStatic(handler.clj:256)
    at editor.handler$run.invokeStatic(handler.clj:289)
    at editor.ui$execute_command.invokeStatic(ui.clj:1147)
    at editor.ui$run_command.invokeStatic(ui.clj:1383)
    at editor.ui$bind_double_click_BANG_$reify.handle(ui.clj:1415)
    at com.sun.javafx.event.CompositeEventHandler$NormalEventFilterRecord.handleCapturingEvent(CompositeEventHandler.java:321)
    at com.sun.javafx.event.CompositeEventHandler.dispatchCapturingEvent(CompositeEventHandler.java:98)
    at com.sun.javafx.event.EventHandlerManager.dispatchCapturingEvent(EventHandlerManager.java:221)
    at com.sun.javafx.event.EventHandlerManager.dispatchCapturingEvent(EventHandlerManager.java:180)
    at com.sun.javafx.event.CompositeEventDispatcher.dispatchCapturingEvent(CompositeEventDispatcher.java:43)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:52)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
    at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
    at javafx.event.Event.fireEvent(Event.java:198)
    at javafx.scene.Scene$ClickGenerator.postProcess(Scene.java:3586)
    at javafx.scene.Scene$MouseHandler.process(Scene.java:3890)
    at javafx.scene.Scene.processMouseEvent(Scene.java:1874)
    at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2607)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:411)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:301)
    at java.security.AccessController.doPrivileged(AccessController.java)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:450)
    at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:424)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:449)
    at com.sun.glass.ui.View.handleMouseEvent(View.java:551)
    at com.sun.glass.ui.View.notifyMouse(View.java:937)
    at com.sun.glass.ui.win.WinApplication._runLoop(WinApplication.java)
    at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:184)
    at java.lang.Thread.run(Thread.java:829)
```

**Comment by britzl** [comment]
Does this happen with all readme files or just one specific file? If so, which one?

**Comment by AGulev** [comment]
no answer from the reporter
