### ISSUE TITLE
Error when launching

### ISSUE THREAD

**Issue by dagerix** [defold/defold#7310]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2023-01-23T11:49:45.801286</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>cb8b76d36177dbe7fefab1b4a2fa3f93fc1bd6bd</td></tr>
<tr><td>Defold engine sha</td><td>8f96e450ddfb006a99aa134fdd373cace3760571</td></tr>
<tr><td>Defold version</td><td>1.4.1</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"ca6de23404f04ad2962fbbf9dc41d757"'>ca6de23404f04ad2962fbbf9dc41d757</a></td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce RTX 3050/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 528.02</td></tr>
<tr><td>Java version</td><td>11.0.15+10-LTS</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 11</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by britzl** [comment]
```
clojure.lang.RT.seqFrom.class java.lang.IllegalArgumentException: Don't know how to create ISeq from: clojure.lang.Symbol
    at clojure.lang.RT.seqFrom(RT.java:553)
    at clojure.lang.RT.seq(RT.java:533)
    at clojure.core$seq__5387.invokeStatic(core.clj:137)
    at clojure.core$map$fn.invoke(core.clj:2746)
    at clojure.lang.LazySeq.sval(LazySeq.java:42)
    at clojure.lang.LazySeq.seq(LazySeq.java:51)
    at clojure.lang.RT.seq(RT.java:531)
    at clojure.core$seq__5387.invokeStatic(core.clj:137)
    at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:24)
    at clojure.core.protocols$fn.invokeStatic(protocols.clj:75)
    at clojure.core.protocols$fn.invoke(protocols.clj:75)
    at clojure.core.protocols$fn$G__8068__8086.invoke(protocols.clj:13)
    at clojure.core$reduce.invokeStatic(core.clj:6828)
    at editor.keymap$key_binding_data__GT_keymap.invokeStatic(keymap.clj:517)
    at editor.keymap$make_keymap_STAR_.invokeStatic(keymap.clj:559)
    at editor.keymap$make_keymap.invokeStatic(keymap.clj:564)
    at editor.app_view$fn.invokeStatic(app_view.clj:299)
    at editor.app_view$fn.invoke(app_view.clj:299)
    at clojure.lang.AFn.applyToHelper(AFn.java:154)
    at clojure.lang.AFn.applyTo(AFn.java:144)
    at clojure.lang.AFunction$1.doInvoke(AFunction.java:31)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at clojure.lang.Var.invoke(Var.java:384)
    at editor.app_view$AppView$behavior$keymap$fn.invoke(app_view.clj:238)
    at internal.node$trace_expr.invokeStatic(node.clj:44)
    at editor.app_view$AppView$behavior$keymap.invokeStatic(app_view.clj:238)
    at editor.app_view$AppView$behavior$keymap.invoke(app_view.clj:238)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:287)
    at internal.node$node_value.invokeStatic(node.clj:446)
    at internal.system$node_value.invokeStatic(system.clj:354)
    at dynamo.graph$do_node_value.invokeStatic(graph.clj:815)
    at dynamo.graph$node_value.invokeStatic(graph.clj:818)
    at editor.app_view$make_app_view.invokeStatic(app_view.clj:1688)
    at editor.boot_open_project$load_stage_BANG_.invokeStatic(boot_open_project.clj:173)
    at editor.boot_open_project$open_project_BANG_$fn.invoke(boot_open_project.clj:402)
    at editor.ui$do_run_now$fn.invoke(ui.clj:304)
    at clojure.lang.AFn.run(AFn.java:22)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:457)
    at java.security.AccessController.doPrivileged(AccessController.java)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:456)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
    at com.sun.glass.ui.win.WinApplication._enterNestedEventLoopImpl(WinApplication.java)
    at com.sun.glass.ui.win.WinApplication._enterNestedEventLoop(WinApplication.java:211)
    at com.sun.glass.ui.Application.enterNestedEventLoop(Application.java:515)
    at com.sun.glass.ui.EventLoop.enter(EventLoop.java:107)
    at com.sun.javafx.tk.quantum.QuantumToolkit.enterNestedEventLoop(QuantumToolkit.java:631)
    at javafx.application.Platform.enterNestedEventLoop(Platform.java:301)
    at editor.fxui$mount_renderer_and_await_result_BANG_.invokeStatic(fxui.clj:319)
    at editor.dialogs$make_load_project_dialog$fn.invoke(dialogs.clj:426)
    at editor.ui$do_run_now.invokeStatic(ui.clj:299)
    at editor.dialogs$make_load_project_dialog.invokeStatic(dialogs.clj:425)
    at editor.boot$open_project_with_progress_dialog.invokeStatic(boot.clj:54)
    at editor.boot$select_project_from_welcome$fn$fn.invoke(boot.clj:79)
    at editor.welcome$show_welcome_dialog_BANG_$close_dialog_and_open_project_BANG___99345.invoke(welcome.clj:611)
    at editor.welcome$show_welcome_dialog_BANG_$download_template_BANG___99347$fn$fn.invoke(welcome.clj:633)
    at clojure.lang.AFn.run(AFn.java:22)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:457)
    at java.security.AccessController.doPrivileged(AccessController.java)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:456)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
    at com.sun.glass.ui.win.WinApplication._runLoop(WinApplication.java)
    at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:184)
    at java.lang.Thread.run(Thread.java:829)
```

**Comment by britzl** [comment]
@dagerix is this happening each time you are launching Defold? Does it happen with all projects or just one?

**Comment by AGulev** [comment]
no answer from the reporter
