### ISSUE TITLE
Validate package name on Android and Bundle Identifier on iOS/MacOS contains only valid symbols

### ISSUE THREAD

**Issue by Wallhow** [defold/defold#7324]
Describe the error
After building an android app from the defold editor and launching it on a physical device, the app immediately crashes if its name contains numbers

**Steps to reproduce**
Steps to reproduce the behavior in the name of the project in game.project write numbers at the beginning. In our case it was "21 points".

**Expected behavior**
Build the apk app and run it on your smartphone

**Default version:**.
  - Version [1.4.1].

**Platforms:**.
 - Platforms: Android

**Screenshots (OPTION):**.
Screenshot of the error 
![photo_2023-01-26_20-47-06](https://user-images.githubusercontent.com/25282206/214896910-b231811f-1801-4444-a2b4-6c937e795374.jpg)

**Comment by AGulev** [comment]
[21 point.zip](https://github.com/defold/defold/files/10539194/21.point.zip)
I can't reproduce this issue (my repo attached)

So, we need more information:
What is android version you can reproduce crash on? Do you use native extensions?

You skiped many important points in the original bug report form. Could you plese provide a bit more info?

**Comment by AGulev** [comment]
maybe share you game.project file

**Comment by Wallhow** [comment]
Sorry, maybe the problem occurs when you specify numbers in the package name of the android application. For example com.21points.name
These two changes were made before building the bundle and running the apk and then crashing the app

**Comment by britzl** [comment]
> For example com.21points.name

That is not a valid package name actually. You can't start a Java name with a digit. You can also not include a hyphen or a reserved Java keyword.

https://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html

**Comment by AGulev** [comment]
> Sorry, maybe the problem occurs when you specify numbers in the package name of the android application. For example com.21points.name
> These two changes were made before building the bundle and running the apk and then crashing the app

https://developer.android.com/guide/topics/manifest/manifest-element#package

<img width="815" alt="image" src="https://user-images.githubusercontent.com/2209596/215780352-4c7fe492-02a6-4c79-9332-8dc62f8dc23b.png">

**Comment by AGulev** [comment]
I think we should change task to "Validate package name for ios/android" @britzl ?

**Comment by osov** [comment]
The problem is not really the package name. if we set the project name with numbers + use our AppManifest + russian chars, then the application crashes.
If you do not use the manifest, then we get an error during the build:
```Failed compiling Android resources```

[CrashAndroid.zip](https://github.com/defold/defold/files/10548154/CrashAndroid.zip)

**Comment by britzl** [comment]
> The problem is not really the package name. if we set the project name with numbers + use our AppManifest + russian chars, then the application crashes. If you do not use the manifest, then we get an error during the build: `Failed compiling Android resources`
> 
> [CrashAndroid.zip](https://github.com/defold/defold/files/10548154/CrashAndroid.zip)

Yeah, we need to add proper validation of the package name according to the limitations @AGulev posted.

**Comment by osov** [comment]
The problem is relevant. if you set numbers in the project name, for example "game 2", then when you start the application it crashes.

**Comment by britzl** [comment]
> The problem is relevant. if you set numbers in the project name, for example "game 2", then when you start the application it crashes.

What does the device log say? Why does it crash?

**Comment by osov** [comment]
```
2023-09-06 16:46:57.811 15686-15686/? W/Bundle: Key android.app.lib_name expected String but value was a java.lang.Integer.  The default value <null> was returned.
2023-09-06 16:46:57.811 15686-15686/? W/Bundle: Attempt to cast generated internal exception:
    java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String
        at android.os.BaseBundle.getString(BaseBundle.java:1199)
        at android.app.NativeActivity.onCreate(NativeActivity.java:150)
        at com.dynamo.android.DefoldActivity.onCreate(DefoldActivity.java:225)
        at android.app.Activity.performCreate(Activity.java:8191)
        at android.app.Activity.performCreate(Activity.java:8159)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1330)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3735)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3929)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2284)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:210)
        at android.os.Looper.loop(Looper.java:299)
        at android.app.ActivityThread.main(ActivityThread.java:8302)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1037)
2023-09-06 16:46:57.812 15686-15686/? D/AndroidRuntime: Shutting down VM
    
    
    --------- beginning of crash
2023-09-06 16:46:57.812 15686-15686/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.sbg.game, PID: 15686
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.sbg.game/com.dynamo.android.DefoldActivity}: java.lang.IllegalArgumentException: Unable to find native library main using classloader: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/~~hE9YYlizmoDNuCEdUNtXXw==/com.sbg.game-QdpU2TOY6F4uN5RUj_Ysiw==/base.apk"],nativeLibraryDirectories=[/data/app/~~hE9YYlizmoDNuCEdUNtXXw==/com.sbg.game-QdpU2TOY6F4uN5RUj_Ysiw==/lib/arm64, /data/app/~~hE9YYlizmoDNuCEdUNtXXw==/com.sbg.game-QdpU2TOY6F4uN5RUj_Ysiw==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]]
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3762)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3929)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2284)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:210)
        at android.os.Looper.loop(Looper.java:299)
        at android.app.ActivityThread.main(ActivityThread.java:8302)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1037)
     Caused by: java.lang.IllegalArgumentException: Unable to find native library main using classloader: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/~~hE9YYlizmoDNuCEdUNtXXw==/com.sbg.game-QdpU2TOY6F4uN5RUj_Ysiw==/base.apk"],nativeLibraryDirectories=[/data/app/~~hE9YYlizmoDNuCEdUNtXXw==/com.sbg.game-QdpU2TOY6F4uN5RUj_Ysiw==/lib/arm64, /data/app/~~hE9YYlizmoDNuCEdUNtXXw==/com.sbg.game-QdpU2TOY6F4uN5RUj_Ysiw==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]]
        at android.app.NativeActivity.onCreate(NativeActivity.java:164)
        at com.dynamo.android.DefoldActivity.onCreate(DefoldActivity.java:225)
        at android.app.Activity.performCreate(Activity.java:8191)
        at android.app.Activity.performCreate(Activity.java:8159)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1330)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3735)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3929) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2284) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loopOnce(Looper.java:210) 
        at android.os.Looper.loop(Looper.java:299) 
        at android.app.ActivityThread.main(ActivityThread.java:8302) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1037) 
2023-09-06 16:46:57.813 4600-4907/? E/OOMEventManager: oom event not support this pkg, dismiss this!
```

**Comment by AGulev** [comment]
## Status

Possibly outdated/fixed

## Evidence

- The GitHub issue is still `OPEN`, but the later comments explicitly reframed it as a validation task for Android package names and Apple bundle identifiers.
- `com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/bundle/BundleHelper.java:977` now has `isValidAndroidPackageName()` and `com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/bundle/BundleHelper.java:985` has `isValidAppleBundleIdentifier()`.
- `com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/bundle/AndroidBundler.java:880`-`886` rejects invalid `android.package` values during bundling with `Android package name '...' is not valid.`
- `com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/bundle/IOSBundler.java:248`-`254` and `com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/bundle/MacOSBundler.java:89`-`95` reject invalid Apple bundle identifiers.
- `com.dynamo.cr/com.dynamo.cr.bob.test/src/com/dynamo/bob/bundle/test/BundleHelperTest.java:273`-`343` includes unit tests covering valid and invalid identifiers, including leading-digit cases like `1com.foo`, `com.1foo`, and `123.456`.
- The Android manifest still uses `{{exe-name}}` for `android.app.lib_name` in `engine/engine/content/builtins/manifests/android/AndroidManifest.xml:38`, but the current issue title is specifically about package/bundle identifier validation, and that validation is now present.

## Why it looks already fixed

The maintainers changed the scope in the comments from a vague crash report to a concrete validation task, and the codebase now implements exactly that validation in the bundlers plus unit-test coverage for the invalid-symbol and leading-digit cases discussed in the issue. The issue appears to remain open even though the requested guardrails are already in place.
