### ISSUE TITLE
Android Device contentless connection / debug failure using wifi

### ISSUE THREAD

**Issue by jcbk101** [defold/defold#7332]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2023-01-05T10:40:08.247792</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>a3e05583f34f7a0674aaa70786e466230ae2653e</td></tr>
<tr><td>Defold engine sha</td><td>8f96e450ddfb006a99aa134fdd373cace3760571</td></tr>
<tr><td>Defold version</td><td>1.4.1</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"ebfa23348c5c4de3bd8573c7f7653e0e"'>ebfa23348c5c4de3bd8573c7f7653e0e</a></td></tr>
<tr><td>GPU</td><td>GeForce GT 730/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 456.71</td></tr>
<tr><td>Java version</td><td>11.0.15+10-LTS</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by britzl** [comment]
```
editor.debugging.mobdebug$connect_BANG_$fn__54593.invoke.class clojure.lang.ExceptionInfo: Failed to connect to debugger on localhost:8172
    at editor.debugging.mobdebug$connect_BANG_$fn.invoke(mobdebug.clj:342)
    at clojure.lang.AFn.run(AFn.java:22)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
    at java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.lang.Thread.run(Thread.java:829)
```

**Comment by jcbk101** [comment]
I finally got it to work continuously. Only on on device so far, and using USB tethering with a cable.

**Comment by britzl** [comment]
Good to hear that you got it working!
