### ISSUE TITLE
Editor, 1.4.2, build error

### ISSUE THREAD

**Issue by ekharkunov-ms** [defold/defold#7334]
### Expected behaviour
No error during building
### Actual behaviour
During project build appears an error.
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2023-01-30T11:00:44.874019</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>ed9e6dc4ee7f8a8c12219f2e7689f744c119b419</td></tr>
<tr><td>Defold engine sha</td><td>8cd3a634b13f4db51a37607bf32bf3a3b362c8e6</td></tr>
<tr><td>Defold version</td><td>1.4.2</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"feb17c49b0e8402fbd9a93903bcd4fdf"'>feb17c49b0e8402fbd9a93903bcd4fdf</a></td></tr>
<tr><td>GPU</td><td>AMD Radeon Pro 5500M OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 ATI-4.8.101</td></tr>
<tr><td>Java version</td><td>11.0.15+10-LTS</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>12.5.1</td></tr>
<table>

P.S. If use editor from beta channel 8cd3a634b13f4db51a37607bf32bf3a3b362c8e6 - no error appears.

**Comment by vlaaad** [comment]
```
java.util.concurrent.FutureTask.report.class java.util.concurrent.ExecutionException: java.lang.NullPointerException
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:191)
    at clojure.core$deref_future.invokeStatic(core.clj:2300)
    at clojure.core$future_call$reify.deref(core.clj:6974)
    at clojure.core$deref.invokeStatic(core.clj:2320)
    at clojure.core$pmap$step__8452$fn.invoke(core.clj:7025)
    at clojure.lang.LazySeq.sval(LazySeq.java:42)
    at clojure.lang.LazySeq.seq(LazySeq.java:51)
    at clojure.lang.RT.seq(RT.java:531)
    at clojure.core$seq__5387.invokeStatic(core.clj:137)
    at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:24)
    at clojure.core.protocols$fn.invokeStatic(protocols.clj:75)
    at clojure.core.protocols$fn.invoke(protocols.clj:75)
    at clojure.core.protocols$fn$G__8068__8086.invoke(protocols.clj:13)
    at clojure.core$reduce.invokeStatic(core.clj:6824)
    at editor.build$batched_pmap.invokeStatic(build.clj:23)
    at editor.build$build_project_BANG_.invokeStatic(build.clj:52)
    at editor.app_view$build_project_BANG_.invokeStatic(app_view.clj:811)
    at editor.app_view$async_build_BANG_$phase_3_build_project_BANG___57446$run_project_build_on_background_thread_BANG___57447.invoke(app_view.clj:944)
    at editor.app_view$async_build_BANG_$run_on_background_thread_BANG___57426$fn.invoke(app_view.clj:871)
    at clojure.core$binding_conveyor_fn$fn.invoke(core.clj:2030)
    at clojure.lang.AFn.call(AFn.java:18)
    at java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.lang.Thread.run(Thread.java:829)

clojure.lang.RT.longCast.class java.lang.NullPointerException: null
    at clojure.lang.RT.longCast(RT.java:1280)
    at internal.graph.MultigraphBasis.node_by_id_at(graph.clj:871)
    at dynamo.graph$node_instance_QMARK_.invokeStatic(graph.clj:952)
    at editor.gui$node__GT_node_tree.invokeStatic(gui.clj:397)
    at editor.gui$node__GT_gui_scene.invokeStatic(gui.clj:410)
    at editor.gui$node__GT_gui_scene.invoke(gui.clj:401)
    at editor.gui$node__GT_gui_scene.invokeStatic(gui.clj:403)
    at editor.gui$fn.invokeStatic(gui.clj:785)
    at editor.gui$fn.invoke(gui.clj:785)
    at clojure.lang.AFn.applyToHelper(AFn.java:154)
    at clojure.lang.AFn.applyTo(AFn.java:144)
    at clojure.lang.AFunction$1.doInvoke(AFunction.java:31)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at clojure.lang.Var.invoke(Var.java:384)
    at editor.spineguiext$SpineNode$behavior$gui_scene$fn.invoke
    at internal.node$trace_expr$fn.invoke(node.clj:38)
    at internal.node$trace_expr.invokeStatic(node.clj:38)
    at internal.node$trace_expr.invoke(node.clj:34)
    at editor.spineguiext$SpineNode$behavior$gui_scene.invokeStatic
    at editor.spineguiext$SpineNode$behavior$gui_scene.invoke
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.OverrideNode.produce_value(node.clj:1649)
    at editor.spineguiext$SpineNode$behavior$spine_anim_ids$fn.invoke
    at internal.node$trace_expr$fn.invoke(node.clj:38)
    at internal.node$trace_expr.invokeStatic(node.clj:38)
    at internal.node$trace_expr.invoke(node.clj:34)
    at editor.spineguiext$SpineNode$behavior$spine_anim_ids.invokeStatic
    at editor.spineguiext$SpineNode$behavior$spine_anim_ids.invoke
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.OverrideNode.produce_value(node.clj:1649)
    at editor.spineguiext$SpineNode$behavior$own_build_errors$fn.invoke
    at internal.node$trace_expr$fn.invoke(node.clj:38)
    at internal.node$trace_expr.invokeStatic(node.clj:38)
    at internal.node$trace_expr.invoke(node.clj:34)
    at editor.spineguiext$SpineNode$behavior$own_build_errors.invokeStatic
    at editor.spineguiext$SpineNode$behavior$own_build_errors.invoke
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.OverrideNode.produce_value(node.clj:1649)
    at editor.spineguiext$SpineNode$behavior$build_errors$fn.invoke
    at internal.node$trace_expr$fn.invoke(node.clj:38)
    at internal.node$trace_expr.invokeStatic(node.clj:38)
    at internal.node$trace_expr.invoke(node.clj:34)
    at editor.spineguiext$SpineNode$behavior$build_errors.invokeStatic
    at editor.spineguiext$SpineNode$behavior$build_errors.invoke
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.OverrideNode.produce_value(node.clj:1649)
    at internal.node$pull_input_values$fn.invoke(node.clj:1188)
    at clojure.core$mapv$fn.invoke(core.clj:6912)
    at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
    at clojure.core$reduce.invokeStatic(core.clj:6827)
    at clojure.core$mapv.invokeStatic(core.clj:6903)
    at internal.node$pull_input_values.invokeStatic(node.clj:1189)
    at editor.gui$BoxNode$behavior$build_errors$fn.invoke(gui.clj:948)
    at internal.node$trace_expr$fn.invoke(node.clj:38)
    at internal.node$trace_expr.invokeStatic(node.clj:38)
    at editor.gui$BoxNode$behavior$build_errors.invokeStatic(gui.clj:948)
    at editor.gui$BoxNode$behavior$build_errors.invoke(gui.clj:948)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.OverrideNode.produce_value(node.clj:1649)
    at internal.node$pull_input_values$fn.invoke(node.clj:1188)
    at clojure.core$mapv$fn.invoke(core.clj:6912)
    at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
    at clojure.core$reduce.invokeStatic(core.clj:6827)
    at clojure.core$mapv.invokeStatic(core.clj:6903)
    at internal.node$pull_input_values.invokeStatic(node.clj:1189)
    at editor.gui$BoxNode$behavior$build_errors$fn.invoke(gui.clj:948)
    at internal.node$trace_expr$fn.invoke(node.clj:38)
    at internal.node$trace_expr.invokeStatic(node.clj:38)
    at editor.gui$BoxNode$behavior$build_errors.invokeStatic(gui.clj:948)
    at editor.gui$BoxNode$behavior$build_errors.invoke(gui.clj:948)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.OverrideNode.produce_value(node.clj:1649)
    at internal.node$pull_input_values$fn.invoke(node.clj:1188)
    at clojure.core$mapv$fn.invoke(core.clj:6912)
    at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
    at clojure.core$reduce.invokeStatic(core.clj:6827)
    at clojure.core$mapv.invokeStatic(core.clj:6903)
    at internal.node$pull_input_values.invokeStatic(node.clj:1189)
    at editor.gui$BoxNode$behavior$build_errors$fn.invoke(gui.clj:948)
    at internal.node$trace_expr$fn.invoke(node.clj:38)
    at internal.node$trace_expr.invokeStatic(node.clj:38)
    at editor.gui$BoxNode$behavior$build_errors.invokeStatic(gui.clj:948)
    at editor.gui$BoxNode$behavior$build_errors.invoke(gui.clj:948)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.OverrideNode.produce_value(node.clj:1649)
    at internal.node$pull_input_values$fn.invoke(node.clj:1188)
    at clojure.core$mapv$fn.invoke(core.clj:6912)
    at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
    at clojure.core$reduce.invokeStatic(core.clj:6827)
    at clojure.core$mapv.invokeStatic(core.clj:6903)
    at internal.node$pull_input_values.invokeStatic(node.clj:1189)
    at editor.gui$NodeTree$behavior$build_errors$fn.invoke(gui.clj:1793)
    at internal.node$trace_expr$fn.invoke(node.clj:38)
    at internal.node$trace_expr.invokeStatic(node.clj:38)
    at editor.gui$NodeTree$behavior$build_errors.invokeStatic(gui.clj:1793)
    at editor.gui$NodeTree$behavior$build_errors.invoke(gui.clj:1793)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.OverrideNode.produce_value(node.clj:1649)
    at internal.node$pull_input_values$fn.invoke(node.clj:1188)
    at clojure.core$mapv$fn.invoke(core.clj:6912)
    at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
    at clojure.core$reduce.invokeStatic(core.clj:6827)
    at clojure.core$mapv.invokeStatic(core.clj:6903)
    at internal.node$pull_input_values.invokeStatic(node.clj:1189)
    at editor.gui$GuiSceneNode$behavior$build_errors$fn.invoke(gui.clj:2260)
    at internal.node$trace_expr$fn.invoke(node.clj:38)
    at internal.node$trace_expr.invokeStatic(node.clj:38)
    at editor.gui$GuiSceneNode$behavior$build_errors.invokeStatic(gui.clj:2260)
    at editor.gui$GuiSceneNode$behavior$build_errors.invoke(gui.clj:2260)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.OverrideNode.produce_value(node.clj:1649)
    at editor.gui$GuiSceneNode$behavior$build_targets$fn.invoke(gui.clj:2260)
    at internal.node$trace_expr$fn.invoke(node.clj:38)
    at internal.node$trace_expr.invokeStatic(node.clj:38)
    at editor.gui$GuiSceneNode$behavior$build_targets.invokeStatic(gui.clj:2260)
    at editor.gui$GuiSceneNode$behavior$build_targets.invoke(gui.clj:2260)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.OverrideNode.produce_value(node.clj:1649)
    at internal.node$node_value.invokeStatic(node.clj:454)
    at internal.system$node_value.invokeStatic(system.clj:354)
    at dynamo.graph$do_node_value.invokeStatic(graph.clj:815)
    at dynamo.graph$node_value.invokeStatic(graph.clj:818)
    at editor.build$build_project_BANG_$fn.invoke(build.clj:53)
    at clojure.core$map$fn.invoke(core.clj:2755)
    at clojure.lang.LazySeq.sval(LazySeq.java:42)
    at clojure.lang.LazySeq.seq(LazySeq.java:51)
    at clojure.lang.Cons.next(Cons.java:39)
    at clojure.lang.RT.next(RT.java:709)
    at clojure.core$next__5371.invokeStatic(core.clj:64)
    at clojure.core$dorun.invokeStatic(core.clj:3142)
    at clojure.core$doall.invokeStatic(core.clj:3148)
    at editor.build$batched_pmap$fn.invoke(build.clj:25)
    at clojure.core$pmap$fn$fn.invoke(core.clj:7022)
    at clojure.core$binding_conveyor_fn$fn.invoke(core.clj:2030)
    at clojure.lang.AFn.call(AFn.java:18)
    at java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.lang.Thread.run(Thread.java:829)
```

**Comment by ekharkunov-ms** [comment]
I tried to update binaries in spine extension but error is still occurred.

**Comment by matgis** [comment]
A fix has been merged, and an update to the editor should be available shortly. Thanks for reporting! ❤️
