### ISSUE TITLE
Report a better error when Android build is too large

### ISSUE THREAD

**Issue by subsoap** [defold/defold#7344]
When Android build fails for being too large the error is not helpful 

```
ERROR: unspecified:-1: 'com.dynamo.bob.CompileExceptionError: Failed creating AAB base.zip'

Failed creating AAB base.zip
Cause: java.lang.NegativeArraySizeException: -1905306680
```

Would be better to give a clearer error if possible that the size is the issue / maybe suggest enabling more aggressive texture profiles.

**Comment by britzl** [comment]
Did the output also include a stack trace? I wonder which part of the process throws this exception?

**Comment by britzl** [comment]
I'm guessing this happens while writing to the zip file. A zip file has a 4GB size limit and a maximum of 65k entries.

**Comment by subsoap** [comment]
@britzl Size was like 2.3GB when texture profiles were properly enabled and size much lower it worked again. @JCash said " I'm not sure if the zip uses an int32 or an uint32. in the int32 case I'd expect the 2.3gb be an overflow."

**Comment by britzl** [comment]
Ok, we'll see if we can create a simple repro case and add a size check. Or at least catch the error and return a helpful message.

**Comment by britzl** [comment]
Using enough large atlases (or other files) to generate a really large archive will result in this error:

```
Cause: java.lang.NegativeArraySizeException: -1533047734
com.dynamo.bob.CompileExceptionError: Failed creating AAB base.zip
	at com.dynamo.bob.bundle.AndroidBundler.createAppBundleBaseZip(AndroidBundler.java:601)
	at com.dynamo.bob.bundle.AndroidBundler.createAAB(AndroidBundler.java:735)
	at com.dynamo.bob.bundle.AndroidBundler.bundleApplication(AndroidBundler.java:898)
	at com.dynamo.bob.Project.bundle(Project.java:814)
	at com.dynamo.bob.Project.doBuild(Project.java:1306)
	at com.dynamo.bob.Project.build(Project.java:658)
	at com.dynamo.bob.Bob.mainInternal(Bob.java:824)
	at com.dynamo.bob.Bob.main(Bob.java:890)
```

Note that while testing I also ran into an issue when creating really large textures:

```
ERROR assets/atlas4.atlas:0 -2147483648
  java.lang.NegativeArraySizeException: -2147483648
  java.desktop/java.awt.image.DataBufferByte.<init>(DataBufferByte.java:76)
  java.desktop/java.awt.image.Raster.createInterleavedRaster(Raster.java:310)
  java.desktop/java.awt.image.BufferedImage.<init>(BufferedImage.java:391)
  com.dynamo.bob.textureset.TextureSetGenerator.composite(TextureSetGenerator.java:483)
  com.dynamo.bob.textureset.TextureSetGenerator.generate(TextureSetGenerator.java:421)
  com.dynamo.bob.pipeline.AtlasUtil.generateTextureSet(AtlasUtil.java:230)
  com.dynamo.bob.pipeline.AtlasBuilder.build(AtlasBuilder.java:66)
  com.dynamo.bob.Project.runTasks(Project.java:1463)
  com.dynamo.bob.Project.doBuild(Project.java:1244)
  com.dynamo.bob.Project.build(Project.java:658)
  com.dynamo.bob.Bob.mainInternal(Bob.java:824)
  com.dynamo.bob.Bob.main(Bob.java:890)
```

**Comment by britzl** [comment]
After solving the issue in com.dynamo.bob.bundle.ZipUtil and writing the large ZipEntry in increments of 16kb bytes instead of a single large byte array the Android bundletool fails with:

```
Caused by: java.io.IOException: Exception in thread "main" java.lang.OutOfMemoryError: Requested array size exceeds VM limit
	at java.base/java.io.ByteArrayOutputStream.<init>(ByteArrayOutputStream.java:81)
	at com.google.common.io.ByteStreams.toByteArray(ByteStreams.java:165)
	at com.android.tools.build.bundletool.io.ZipBuilder.writeTo(ZipBuilder.java:92)
	at com.android.tools.build.bundletool.io.ApkSetBuilderFactory$ApkSetArchiveBuilder.writeTo(ApkSetBuilderFactory.java:173)
	at com.android.tools.build.bundletool.commands.BuildApksManager.executeWithZip(BuildApksManager.java:261)
	at com.android.tools.build.bundletool.commands.BuildApksManager.execute(BuildApksManager.java:123)
	at com.android.tools.build.bundletool.commands.BuildApksCommand.execute(BuildApksCommand.java:523)
	at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:75)
	at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:47)

	at com.dynamo.bob.bundle.AndroidBundler.createUniversalApks(AndroidBundler.java:790)
```

**Comment by britzl** [comment]
Later versions of bundletool seems to have solved this by not loading the entire file into a byte array. Testing with Bundletool 1.14.

**Comment by britzl** [comment]
Nope, that didn't help:

```
Caused by: java.io.IOException: [BT:1.14.0] Error: integer overflow
java.lang.ArithmeticException: integer overflow
	at java.base/java.lang.Math.toIntExact(Math.java:1135)
	at com.android.zipflinger.Location.compareTo(Location.java:71)
	at com.android.zipflinger.Location.compareTo(Location.java:21)
	at java.base/java.util.ComparableTimSort.countRunAndMakeAscending(ComparableTimSort.java:325)
	at java.base/java.util.ComparableTimSort.sort(ComparableTimSort.java:188)
	at java.base/java.util.Arrays.sort(Arrays.java:1107)
	at java.base/java.util.Arrays.sort(Arrays.java:1301)
	at java.base/java.util.ArrayList.sort(ArrayList.java:1721)
	at java.base/java.util.Collections.sort(Collections.java:145)
	at com.android.zipflinger.FreeStore.<init>(FreeStore.java:72)
	at com.android.zipflinger.ZipArchive.<init>(ZipArchive.java:57)
	at com.android.zipflinger.ZipArchive.<init>(ZipArchive.java:42)
	at com.android.tools.build.bundletool.io.ModuleEntriesPack.mergeWith(ModuleEntriesPack.java:143)
	at com.android.tools.build.bundletool.io.ModuleSplitSerializer.serialize(ModuleSplitSerializer.java:150)
	at com.android.tools.build.bundletool.io.ApkSerializerManager.serializeApks(ApkSerializerManager.java:284)
	at com.android.tools.build.bundletool.io.ApkSerializerManager.serializeApkSetContent(ApkSerializerManager.java:189)
	at com.android.tools.build.bundletool.io.ApkSerializerManager.serializeApkSet(ApkSerializerManager.java:133)
	at com.android.tools.build.bundletool.commands.BuildApksManager.execute(BuildApksManager.java:222)
	at com.android.tools.build.bundletool.commands.BuildApksCommand.execute(BuildApksCommand.java:923)
	at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:83)
	at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:55)

	at com.dynamo.bob.bundle.AndroidBundler.createUniversalApks(AndroidBundler.java:790)
	... 7 more
```
