### ISSUE TITLE
got this error on creating a new project

### ISSUE THREAD

**Issue by BungeeGon** [defold/defold#7597]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2023-04-19T13:12:03.141790</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>bdae563e8b0edd929b7d41a566e37f79dce80f6b</td></tr>
<tr><td>Defold engine sha</td><td>f5e114aaebe25c5242db5f0066af2f5189c09f99</td></tr>
<tr><td>Defold version</td><td>1.4.4</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"a1e711d1305d432084d83382507f5deb"'>a1e711d1305d432084d83382507f5deb</a></td></tr>
<tr><td>GPU</td><td>Intel(R) UHD Graphics</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 - Build 26.20.100.7926</td></tr>
<tr><td>Java version</td><td>11.0.15+10-LTS</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by britzl** [comment]
```
sun.nio.ch.Net.connect0.class java.net.ConnectException: Connection timed out: connect
    at sun.nio.ch.Net.connect0(Net.java)
    at sun.nio.ch.Net.connect(Net.java:483)
    at sun.nio.ch.Net.connect(Net.java:472)
    at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:692)
    at java.nio.channels.SocketChannel.open(SocketChannel.java:194)
    at sun.nio.ch.PipeImpl$Initializer$LoopbackConnector.run(PipeImpl.java:127)
    at sun.nio.ch.PipeImpl$Initializer.run(PipeImpl.java:76)
    at sun.nio.ch.PipeImpl$Initializer.run(PipeImpl.java:61)
    at java.security.AccessController.doPrivileged(AccessController.java)
    at sun.nio.ch.PipeImpl.<init>(PipeImpl.java:171)
    at sun.nio.ch.SelectorProviderImpl.openPipe(SelectorProviderImpl.java:50)
    at java.nio.channels.Pipe.open(Pipe.java:155)
    at sun.nio.ch.WindowsSelectorImpl.<init>(WindowsSelectorImpl.java:142)
    at sun.nio.ch.WindowsSelectorProvider.openSelector(WindowsSelectorProvider.java:44)
    at java.nio.channels.Selector.open(Selector.java:295)
    at sun.net.httpserver.ServerImpl.<init>(ServerImpl.java:104)
    at sun.net.httpserver.HttpServerImpl.<init>(HttpServerImpl.java:50)
    at sun.net.httpserver.DefaultHttpServerProvider.createHttpServer(DefaultHttpServerProvider.java:35)
    at com.sun.net.httpserver.HttpServer.create(HttpServer.java:137)
    at util.http_server$__GT_server.invokeStatic(http_server.clj:77)
    at editor.boot_open_project$load_stage_BANG_.invokeStatic(boot_open_project.clj:195)
    at editor.boot_open_project$open_project_BANG_$fn.invoke(boot_open_project.clj:407)
    at editor.ui$do_run_now$fn.invoke(ui.clj:307)

```

**Comment by britzl** [comment]
It seems like a network connectivity error when loading the project. @BungeeGon was this when opening a blank project? Does it happen all the time?

**Comment by AGulev** [comment]
no action/answer from the reporter
