### ISSUE TITLE
Cannot close defold

### ISSUE THREAD

**Issue by Guest0814** [defold/defold#7629]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2023-04-27T18:27:39.031779</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>a57710afd396e91c0f512d09762fd1c6543f992f</td></tr>
<tr><td>Defold engine sha</td><td>3dbbf1dbebd3a8146f6a917d101882a61f56afdc</td></tr>
<tr><td>Defold version</td><td>1.4.5</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"63ce0a8a50374df4840de3a8cd153713"'>63ce0a8a50374df4840de3a8cd153713</a></td></tr>
<tr><td>GPU</td><td>Intel(R) HD Graphics 4000</td></tr>
<tr><td>GPU Driver</td><td>4.0.0 - Build 9.17.10.2932</td></tr>
<tr><td>Java version</td><td>11.0.15+10-LTS</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 7</td></tr>
<tr><td>OS version</td><td>6.1</td></tr>
<table>

**Comment by britzl** [comment]
```
internal.node$update_in_production.invokeStatic.class clojure.lang.ExceptionInfo: Cycle detected on node
    at internal.node$update_in_production.invokeStatic(node.clj:1389)
    at internal.node$update_in_production.invoke(node.clj:1388)
    at clojure.core$update.invokeStatic(core.clj:6198)
    at internal.node$mark_in_production.invokeStatic(node.clj:1397)
    at editor.tile_source$TileSourceNode$behavior$size.invokeStatic(tile_source.clj:556)
    at editor.tile_source$TileSourceNode$behavior$size.invoke(tile_source.clj:556)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:295)
    at internal.node$pull_first_input_value.invokeStatic(node.clj:1181)
    at editor.tile_source$TileSourceNode$behavior$size$fn.invoke(tile_source.clj:556)
    at internal.node$trace_expr.invokeStatic(node.clj:44)
    at editor.tile_source$TileSourceNode$behavior$size.invokeStatic(tile_source.clj:556)
    at editor.tile_source$TileSourceNode$behavior$size.invoke(tile_source.clj:556)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:295)
    at internal.node$pull_first_input_value.invokeStatic(node.clj:1181)
    at editor.tile_source$TileSourceNode$behavior$tile_source_attributes$fn.invoke(tile_source.clj:556)
    at internal.node$trace_expr.invokeStatic(node.clj:44)
    at editor.tile_source$TileSourceNode$behavior$tile_source_attributes.invokeStatic(tile_source.clj:556)
    at editor.tile_source$TileSourceNode$behavior$tile_source_attributes.invoke(tile_source.clj:556)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:295)
    at editor.tile_source$TileSourceNode$behavior$convex_hull_points$fn.invoke(tile_source.clj:556)
    at internal.node$trace_expr.invokeStatic(node.clj:44)
    at editor.tile_source$TileSourceNode$behavior$convex_hull_points.invokeStatic(tile_source.clj:556)
    at editor.tile_source$TileSourceNode$behavior$convex_hull_points.invoke(tile_source.clj:556)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:295)
    at editor.tile_source$TileSourceNode$behavior$convex_hulls$fn.invoke(tile_source.clj:556)
```

**Comment by AGulev** [comment]
not enough info
