### ISSUE TITLE
tutorials wont load

### ISSUE THREAD

**Issue by slmaoo** [defold/defold#7756]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2023-06-19T12:40:34.311080</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>94b853c671eb5264895b206dc427071978277cfa</td></tr>
<tr><td>Defold engine sha</td><td>7a608d3ce6ed895d484956c1e76110ed8b78422a</td></tr>
<tr><td>Defold version</td><td>1.4.7</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"76cc22b75971419eb50616fa4f655da5"'>76cc22b75971419eb50616fa4f655da5</a></td></tr>
<tr><td>GPU</td><td>Intel(R) UHD Graphics 620</td></tr>
<tr><td>GPU Driver</td><td>4.5.0 - Build 25.20.100.6472</td></tr>
<tr><td>Java version</td><td>11.0.15+10-LTS</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by britzl** [comment]
```
java.util.zip.InflaterInputStream.fill.class java.io.EOFException: Unexpected end of ZLIB input stream
    at java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:245)
    at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:159)
    at java.util.zip.ZipInputStream.read(ZipInputStream.java:197)
    at java.io.FilterInputStream.read(FilterInputStream.java:107)
    at clojure.java.io$fn.invokeStatic(io.clj:305)
    at clojure.java.io$fn.invoke(io.clj:302)
    at clojure.lang.MultiFn.invoke(MultiFn.java:239)
    at clojure.java.io$copy.invokeStatic(io.clj:406)
    at clojure.java.io$copy.doInvoke(io.clj:391)
    at clojure.lang.RestFn.invoke(RestFn.java:425)
    at editor.welcome$expand_proj_zip_BANG_$fn.invoke(welcome.clj:253)
    at editor.welcome$expand_proj_zip_BANG_.invokeStatic(welcome.clj:252)
    at editor.welcome$show_welcome_dialog_BANG_$download_template_BANG___103322$fn.invoke(welcome.clj:628)
    at clojure.core$binding_conveyor_fn$fn.invoke(core.clj:2030)
    at clojure.lang.AFn.call(AFn.java:18)
    at java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.lang.Thread.run(Thread.java:829)
```

**Comment by AGulev** [comment]
no action/answer from the reporter
