### ISSUE TITLE
Steam version can't update

### ISSUE THREAD

**Issue by JustAPotota** [defold/defold#7804]
**Describe the bug (REQUIRED)**
A fresh install of Defold through Steam is unable to update to the latest version.

**To Reproduce (REQUIRED)**
1. Install via Steam
2. Click `Update Available`

**Expected behavior (REQUIRED)**
It should update to the latest version.

**Defold version (REQUIRED):**
1.3.3

**Platforms (REQUIRED):**
Linux (Fedora Silverblue 38)

**Logs (OPTIONAL):**
```
2023-07-15 11:39:08.614 INFO  default    editor.updater - {:line 299, :message "Checking for updates", :url "https://d.defold.com/editor2/channels/beta/update-v3.json"}
2023-07-15 11:39:08.878 INFO  default    editor.updater - {:line 305, :message "New version found", :sha1 "905234d8da2e642f1075c73aaa1bfb72e49199e3"}
2023-07-15 11:40:17.467 INFO  default    editor.updater - {:line 124, :message "Downloading update", :url "https://d.defold.com/archive/905234d8da2e642f1075c73aaa1bfb72e49199e3/beta/editor2/Defold-x86_64-linux.zip", :file "/tmp/defold-update3648075572369148121.zip"}
moved permanently 'https://d.defold.com/archive/905234d8da2e642f1075c73aaa1bfb72e49199e3/beta/editor2/Defold-x86_64-linux.zip' -> 'http://d.defold.com/archive/beta/905234d8da2e642f1075c73aaa1bfb72e49199e3/beta/editor2/Defold-x86_64-linux.zip'
2023-07-15 11:40:17.827 INFO  default    editor.updater - {:line 213, :message "Update download failed"}
java.lang.IllegalArgumentException: No matching clause: 404
	at util.net$download_BANG_.invokeStatic(net.clj:48)
	at util.net$download_BANG_.doInvoke(net.clj:32)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at util.net$download_BANG_.invokeStatic(net.clj:48)
	at editor.updater$download_BANG_.invokeStatic(updater.clj:129)
	at editor.updater$download_and_extract_BANG_$fn__73266.invoke(updater.clj:205)
	at clojure.core$binding_conveyor_fn$fn__5739.invoke(core.clj:2030)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Workaround (OPTIONAL):**
Download the latest version from GitHub and replace the Steam version with it.

**Additional context (OPTIONAL):**
Seems like the issue is that https://d.defold.com/editor2/channels/beta/update-v3.json points to an old version (1.3.6) which is no longer served. I think the easiest solution is to just update the Steam version to the latest that uses `update-v4.json` (1.4.7 or 1.4.8 when that releases as stable). It's also odd that it defaults to the beta branch instead of stable.

**Comment by britzl** [comment]
> I think the easiest solution is to just update the Steam version to the latest

We've done this recently. We have also added Steam releases to our release checklist: https://github.com/defold/defold/blob/dev/RELEASE.md#release-to-steam

**Comment by JustAPotota** [comment]
A fresh install (Linux) still shows 1.3.3:

![Screenshot from 2023-09-03 22-14-35](https://github.com/defold/defold/assets/43710172/dd1f36b9-d9b8-4988-a48f-f48218961f77)
[SteamDB](https://steamdb.info/app/1365760/) says Defold got updated 2 weeks ago, but the depots for [macOS](https://steamdb.info/depot/1365761/), [Windows](https://steamdb.info/depot/1365762/), and [Linux](https://steamdb.info/depot/1365763/) say the last update was in 2022.

**Comment by britzl** [comment]
I did an upload of 1.5.0 and pushed it live

**Comment by JustAPotota** [comment]
Awesome, thanks!

![Screenshot from 2023-09-04 12-04-56](https://github.com/defold/defold/assets/43710172/d00f792f-53c8-44d2-8916-42f2717d08fa)
