### ISSUE TITLE
On drag and drop

### ISSUE THREAD

**Issue by SibGent** [defold/defold#7811]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2023-05-22T08:45:22.706391</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>c846a0013bf8606ea55e8fea4f6b3df809e2a1fa</td></tr>
<tr><td>Defold engine sha</td><td>cb8b34230bd42a5e0b68c12441657f06485562a6</td></tr>
<tr><td>Defold version</td><td>1.4.6</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"6dcb1ab178cc4902b1aee5c337656a12"'>6dcb1ab178cc4902b1aee5c337656a12</a></td></tr>
<tr><td>GPU</td><td>AMD Radeon Vega 11 Graphics (raven, LLVM 15.0.7, DRM 3.47, 5.19.0-46-generic)</td></tr>
<tr><td>GPU Driver</td><td>4.6 (Compatibility Profile) Mesa 22.2.5-0ubuntu0.1~22.04.3</td></tr>
<tr><td>Java version</td><td>11.0.15+10-LTS</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>5.19.0-46-generic</td></tr>
<table>

**Comment by britzl** [comment]
```
javafx.scene.Scene$DropTargetListener.drop.class java.lang.NullPointerException: null
    at javafx.scene.Scene$DropTargetListener.drop(Scene.java:3001)
    at com.sun.javafx.tk.quantum.GlassSceneDnDEventHandler.lambda$handleDragDrop$2(GlassSceneDnDEventHandler.java:111)
    at java.security.AccessController.doPrivileged(AccessController.java)
    at com.sun.javafx.tk.quantum.GlassSceneDnDEventHandler.handleDragDrop(GlassSceneDnDEventHandler.java:107)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleDragDrop$11(GlassViewEventHandler.java:772)
    at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:424)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleDragDrop(GlassViewEventHandler.java:771)
    at com.sun.glass.ui.View.handleDragDrop(View.java:708)
    at com.sun.glass.ui.View.notifyDragDrop(View.java:1037)
    at com.sun.glass.ui.gtk.GtkApplication._runLoop(GtkApplication.java)
    at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:316)
    at java.lang.Thread.run(Thread.java:829)
```

**Comment by Jhonnyg** [comment]
Isn't this fixed in 1.4.8? This report is from 1.4.6

**Comment by britzl** [comment]
Possibly. Although I think this is a different issue. @SibGent could you please try Defold 1.4.8?

**Comment by SibGent** [comment]
Defold 1.4.8 works fine!

**Comment by AGulev** [comment]
> Defold 1.4.8 works fine!

Great to hear that Defold 1.4.8 works fine for you!
