### ISSUE TITLE
I got this error when I double clicked on a Particle FX inside a Game Object

### ISSUE THREAD

**Issue by hamidrezakhaki** [defold/defold#7826]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2023-06-08T06:51:04.421732</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>bd9d5a1025768a9f6b7acaaa73c874385e7c35e4</td></tr>
<tr><td>Defold engine sha</td><td>cb8b34230bd42a5e0b68c12441657f06485562a6</td></tr>
<tr><td>Defold version</td><td>1.4.6</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"5bafbea896394c66b8b36ef0a23e6fb6"'>5bafbea896394c66b8b36ef0a23e6fb6</a></td></tr>
<tr><td>GPU</td><td>Intel(R) UHD Graphics 630</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 - Build 30.0.101.1273</td></tr>
<tr><td>Java version</td><td>11.0.15+10-LTS</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by britzl** [comment]
```
jogamp.opengl.windows.wgl.WindowsWGLContext.createImpl.class com.jogamp.opengl.GLException: Unable to create temp OpenGL context for device context 0x670124a6
    at jogamp.opengl.windows.wgl.WindowsWGLContext.createImpl(WindowsWGLContext.java:352)
    at jogamp.opengl.GLContextImpl.makeCurrentWithinLock(GLContextImpl.java:770)
    at jogamp.opengl.GLContextImpl.makeCurrent(GLContextImpl.java:653)
    at jogamp.opengl.GLContextImpl.makeCurrent(GLContextImpl.java:591)
    at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1279)
    at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1147)
    at jogamp.opengl.GLAutoDrawableBase.defaultDisplay(GLAutoDrawableBase.java:476)
    at com.jogamp.opengl.GLAutoDrawableDelegate.display(GLAutoDrawableDelegate.java:190)
    at jogamp.opengl.GLAutoDrawableBase.defaultWindowResizedOp(GLAutoDrawableBase.java:260)
    at jogamp.opengl.GLOffscreenAutoDrawableImpl.setSurfaceSize(GLOffscreenAutoDrawableImpl.java:61)
    at editor.scene$make_gl_pane_BANG_$fn$fn.invoke(scene.clj:1291)
    at editor.scene$make_gl_pane_BANG_$fn.invoke(scene.clj:1281)
    at editor.scene.proxy$com.defold.control.Region$ff19274a.layoutChildren
    at javafx.scene.Parent.layout(Parent.java:1207)
    at javafx.scene.Parent.layout(Parent.java:1214)
    at javafx.scene.Parent.layout(Parent.java:1214)
    at javafx.scene.Parent.layout(Parent.java:1214)
    at javafx.scene.Parent.layout(Parent.java:1214)
    at javafx.scene.Parent.layout(Parent.java:1214)
```

**Comment by britzl** [comment]
It seems like a driver issue. Is your graphics card driver up to date?

**Comment by hamidrezakhaki** [comment]
No, my graphics card driver is not up to date

**Comment by britzl** [comment]
> No, my graphics card driver is not up to date

It is unfortunate that it crashes and perhaps we can fail gracefully, but is your problem solved if you update the drivers?

**Comment by AGulev** [comment]
no extra info provided
