### ISSUE TITLE
Can not save file with lazygit open

### ISSUE THREAD

**Issue by Jerakin** [defold/defold#7918]
I can not save files when the project is open in [LazyGit](https://github.com/jesseduffield/lazygit). Lazygit does not prevent any other software from saving files.

### Expected behaviour
Saves the file

### Actual behaviour
Error dialog. 

### Steps to reproduce
Open the project in lazy git and try to save a changed file within defold

<hr/>

<table>
<tr><td>Build time</td><td>2023-08-07T11:36:43.216595</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>34db77fa587e44fb60bc0da0192075054def3f72</td></tr>
<tr><td>Defold engine sha</td><td>504de7800fa81847bfc2e26a21973899db9dd747</td></tr>
<tr><td>Defold version</td><td>1.4.8</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"55dbdbd0d89d48e9b2dbc6b411443b4d"'>55dbdbd0d89d48e9b2dbc6b411443b4d</a></td></tr>
<tr><td>GPU</td><td>AMD Radeon RX 7900 XT</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 Compatibility Profile Context 23.4.2.230412</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by britzl** [comment]
```
java.io.FileOutputStream.open0.class java.io.FileNotFoundException: H:\projects\repositories\mana-counter\main\app\total_view\total_view.gui_script (The requested operation cannot be performed on a file with a user-mapped section open)
    at java.io.FileOutputStream.open0(FileOutputStream.java)
    at java.io.FileOutputStream.open(FileOutputStream.java:293)
    at java.io.FileOutputStream.<init>(FileOutputStream.java:235)
    at clojure.java.io$fn.invokeStatic(io.clj:230)
    at clojure.java.io$fn.invoke(io.clj:230)
    at clojure.java.io$fn$G__11374__11412.invoke(io.clj:69)
    at editor.resource.FileResource.make_output_stream(resource.clj:174)
    at editor.resource.FileResource.make_writer(resource.clj:175)
    at clojure.java.io$writer.invokeStatic(io.clj:119)
    at clojure.java.io$writer.doInvoke(io.clj:104)
    at clojure.lang.RestFn.invoke(RestFn.java:410)
    at clojure.lang.AFn.applyToHelper(AFn.java:154)
    at clojure.lang.RestFn.applyTo(RestFn.java:132)
    at clojure.core$apply.invokeStatic(core.clj:667)
    at clojure.core$spit.invokeStatic(core.clj:6954)
    at clojure.core$spit.doInvoke(core.clj:6954)
    at clojure.lang.RestFn.invoke(RestFn.java:425)
    at editor.defold_project$write_save_data_to_disk_BANG_$fn.invoke(defold_project.clj:346)
```

**Comment by britzl** [comment]
It seems like LazyGit keeps files open: https://github.com/jesseduffield/lazygit/issues/1888

It is likely that this is only a project in a git project with a relatively large amount of file.
