### ISSUE TITLE
Reset template size cause error

### ISSUE THREAD

**Issue by Jerakin** [defold/defold#7919]
### Expected behaviour
Reset template over writes should set it to default

### Actual behaviour
error message

### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2023-08-07T11:36:43.216595</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>34db77fa587e44fb60bc0da0192075054def3f72</td></tr>
<tr><td>Defold engine sha</td><td>504de7800fa81847bfc2e26a21973899db9dd747</td></tr>
<tr><td>Defold version</td><td>1.4.8</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"890df9655a494aa6b5b8d2c72b42dac6"'>890df9655a494aa6b5b8d2c72b42dac6</a></td></tr>
<tr><td>GPU</td><td>AMD Radeon RX 7900 XT</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 Compatibility Profile Context 23.4.2.230412</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by Jerakin** [comment]
![image](https://github.com/defold/defold/assets/5273682/2eb6e6e8-ca7b-4920-af91-198cece7f5f0)


After a restart the template says it has over rides (is blue) but there are no reset buttons

**Comment by Jerakin** [comment]
![image](https://github.com/defold/defold/assets/5273682/e03cce6a-2eb6-4a22-975c-40231ee457a2)

standard values on the template

**Comment by Jerakin** [comment]
Still relevant.

1. Create gui "template"
2. Open "template" add a box
3. Create gui "test"
4. Open "test" add "template" as a template
5. On the template box, 
    * Change to -> Size Mode: Manual
    * Change to -> Size X: 300
6. Click the reset arrow on the Size.

<table>
<tr><td>Build time</td><td>2024-02-28T08:46:35.883246</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>fde3b9ca14f2629b143173ba41b580c6191317f4</td></tr>
<tr><td>Defold engine sha</td><td>fcec9500fd438e365d4e4f6cec24b99afb907247</td></tr>
<tr><td>Defold version</td><td>1.6.4</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"cc862a34af354acfb016e5c53cce7af8"'>cc862a34af354acfb016e5c53cce7af8</a></td></tr>
<tr><td>GPU</td><td>AMD Radeon RX 7900 XT</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 Compatibility Profile Context 23.9.1.230821</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by AGulev** [comment]
```
editor.handler$invoke_fnk.invokeStatic.class clojure.lang.ExceptionInfo: handler ':hide-toggle-selected' in context ':workbench' failed at ':enabled?' with message 'Cannot invoke "java.lang.Number.doubleValue()" because "x" is null'
    at editor.handler$invoke_fnk.invokeStatic(handler.clj:262)
    at editor.handler$enabled_QMARK_.invokeStatic(handler.clj:296)
    at editor.ui$refresh_menu_item_state.invokeStatic(ui.clj:1681)
    at editor.ui$refresh_menu_item_state.invoke(ui.clj:1657)
    at editor.ui$refresh_menu_item_state.invokeStatic(ui.clj:1663)
    at editor.ui$refresh_menubar_state.invokeStatic(ui.clj:1694)
    at editor.ui$refresh_menus_BANG_.invokeStatic(ui.clj:1844)
    at editor.ui$refresh.invokeStatic(ui.clj:1865)
    at editor.app_view$refresh_menus_and_toolbars_BANG_.invokeStatic(app_view.clj:1801)
    at editor.app_view$make_app_view$fn.invoke(app_view.clj:1925)
    at editor.ui$__GT_timer$fn$fn.invoke(ui.clj:1968)
    at clojure.lang.AFn.run(AFn.java:22)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:456)
    at java.security.AccessController.doPrivileged(AccessController.java:399)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:455)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
    at com.sun.glass.ui.win.WinApplication._runLoop(WinApplication.java)
    at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:184)
    at java.lang.Thread.run(Thread.java:833)
clojure.lang.RT.uncheckedDoubleCast.class java.lang.NullPointerException: Cannot invoke "java.lang.Number.doubleValue()" because "x" is null
    at clojure.lang.RT.uncheckedDoubleCast(RT.java:1559)
    at editor.slice9$vertex_data.invokeStatic(slice9.clj:220)
    at editor.gui$fn.invokeStatic(gui.clj:1012)
    at editor.gui$fn.invoke(gui.clj:1012)
    at clojure.lang.AFn.applyToHelper(AFn.java:154)
    at clojure.lang.AFn.applyTo(AFn.java:144)
    at clojure.lang.AFunction$1.doInvoke(AFunction.java:31)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at clojure.lang.Var.invoke(Var.java:384)
    at editor.gui$BoxNode$behavior$scene_renderable_user_data$fn.invoke(gui.clj:998)
    at internal.node$trace_expr.invokeStatic(node.clj:44)
    at editor.gui$BoxNode$behavior$scene_renderable_user_data.invokeStatic(gui.clj:998)
    at editor.gui$BoxNode$behavior$scene_renderable_user_data.invoke(gui.clj:998)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.OverrideNode.produce_value(node.clj:1710)
    at editor.gui$BoxNode$behavior$scene_outline_renderable$fn.invoke(gui.clj:998)
    at internal.node$trace_expr.invokeStatic(node.clj:44)
    at editor.gui$BoxNode$behavior$scene_outline_renderable.invokeStatic(gui.clj:998)
    at editor.gui$BoxNode$behavior$scene_outline_renderable.invoke(gui.clj:998)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.OverrideNode.produce_value(node.clj:1710)
    at editor.gui$BoxNode$behavior$scene$fn.invoke(gui.clj:998)
    at internal.node$trace_expr.invokeStatic(node.clj:44)
    at editor.gui$BoxNode$behavior$scene.invokeStatic(gui.clj:998)
    at editor.gui$BoxNode$behavior$scene.invoke(gui.clj:998)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.OverrideNode.produce_value(node.clj:1710)
    at internal.node$pull_input_values$fn.invoke(node.clj:1208)
    at clojure.core$mapv$fn.invoke(core.clj:6912)
    at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
    at clojure.core$reduce.invokeStatic(core.clj:6827)
    at clojure.core$mapv.invokeStatic(core.clj:6903)
    at internal.node$pull_input_values.invokeStatic(node.clj:1209)
    at editor.gui$NodeTree$behavior$child_scenes$fn.invoke(gui.clj:1893)
    at internal.node$trace_expr.invokeStatic(node.clj:44)
    at editor.gui$NodeTree$behavior$child_scenes.invokeStatic(gui.clj:1893)
    at editor.gui$NodeTree$behavior$child_scenes.invoke(gui.clj:1893)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.OverrideNode.produce_value(node.clj:1710)
    at editor.gui$NodeTree$behavior$scene$fn.invoke(gui.clj:1893)
    at internal.node$trace_expr.invokeStatic(node.clj:44)
    at editor.gui$NodeTree$behavior$scene.invokeStatic(gui.clj:1893)
    at editor.gui$NodeTree$behavior$scene.invoke(gui.clj:1893)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.OverrideNode.produce_value(node.clj:1710)
    at internal.node$pull_first_input_value.invokeStatic(node.clj:1192)
    at editor.gui$GuiSceneNode$behavior$child_scenes$fn.invoke(gui.clj:2483)
    at internal.node$trace_expr.invokeStatic(node.clj:44)
    at editor.gui$GuiSceneNode$behavior$child_scenes.invokeStatic(gui.clj:2483)
    at editor.gui$GuiSceneNode$behavior$child_scenes.invoke(gui.clj:2483)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.OverrideNode.produce_value(node.clj:1710)
    at editor.gui$GuiSceneNode$behavior$scene$fn.invoke(gui.clj:2483)
    at internal.node$trace_expr.invokeStatic(node.clj:44)
    at editor.gui$GuiSceneNode$behavior$scene.invokeStatic(gui.clj:2483)
    at editor.gui$GuiSceneNode$behavior$scene.invoke(gui.clj:2483)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.OverrideNode.produce_value(node.clj:1710)
    at internal.node$pull_first_input_value.invokeStatic(node.clj:1192)
    at editor.gui$TemplateNode$behavior$scene_children$fn.invoke(gui.clj:1278)
    at internal.node$trace_expr.invokeStatic(node.clj:44)
    at editor.gui$TemplateNode$behavior$scene_children.invokeStatic(gui.clj:1278)
    at editor.gui$TemplateNode$behavior$scene_children.invoke(gui.clj:1278)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:295)
    at editor.gui$TemplateNode$behavior$scene$fn.invoke(gui.clj:1278)
    at internal.node$trace_expr.invokeStatic(node.clj:44)
    at editor.gui$TemplateNode$behavior$scene.invokeStatic(gui.clj:1278)
    at editor.gui$TemplateNode$behavior$scene.invoke(gui.clj:1278)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:295)
    at internal.node$pull_input_values$fn.invoke(node.clj:1208)
    at clojure.core$mapv$fn.invoke(core.clj:6912)
    at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
    at clojure.core$reduce.invokeStatic(core.clj:6827)
    at clojure.core$mapv.invokeStatic(core.clj:6903)
    at internal.node$pull_input_values.invokeStatic(node.clj:1209)
    at editor.gui$BoxNode$behavior$scene_children$fn.invoke(gui.clj:998)
    at internal.node$trace_expr.invokeStatic(node.clj:44)
    at editor.gui$BoxNode$behavior$scene_children.invokeStatic(gui.clj:998)
    at editor.gui$BoxNode$behavior$scene_children.invoke(gui.clj:998)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:295)
    at editor.gui$BoxNode$behavior$scene$fn.invoke(gui.clj:998)
    at internal.node$trace_expr.invokeStatic(node.clj:44)
    at editor.gui$BoxNode$behavior$scene.invokeStatic(gui.clj:998)
    at editor.gui$BoxNode$behavior$scene.invoke(gui.clj:998)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:295)
    at internal.node$pull_input_values$fn.invoke(node.clj:1208)
    at clojure.core$mapv$fn.invoke(core.clj:6912)
    at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
    at clojure.core$reduce.invokeStatic(core.clj:6827)
    at clojure.core$mapv.invokeStatic(core.clj:6903)
    at internal.node$pull_input_values.invokeStatic(node.clj:1209)
    at editor.gui$NodeTree$behavior$child_scenes$fn.invoke(gui.clj:1893)
    at internal.node$trace_expr.invokeStatic(node.clj:44)
    at editor.gui$NodeTree$behavior$child_scenes.invokeStatic(gui.clj:1893)
    at editor.gui$NodeTree$behavior$child_scenes.invoke(gui.clj:1893)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:295)
    at editor.gui$NodeTree$behavior$scene$fn.invoke(gui.clj:1893)
    at internal.node$trace_expr.invokeStatic(node.clj:44)
    at editor.gui$NodeTree$behavior$scene.invokeStatic(gui.clj:1893)
    at editor.gui$NodeTree$behavior$scene.invoke(gui.clj:1893)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:295)
    at internal.node$pull_first_input_value.invokeStatic(node.clj:1192)
    at editor.gui$GuiSceneNode$behavior$child_scenes$fn.invoke(gui.clj:2483)
    at internal.node$trace_expr.invokeStatic(node.clj:44)
    at editor.gui$GuiSceneNode$behavior$child_scenes.invokeStatic(gui.clj:2483)
    at editor.gui$GuiSceneNode$behavior$child_scenes.invoke(gui.clj:2483)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:295)
    at editor.gui$GuiSceneNode$behavior$scene$fn.invoke(gui.clj:2483)
    at internal.node$trace_expr.invokeStatic(node.clj:44)
    at editor.gui$GuiSceneNode$behavior$scene.invokeStatic(gui.clj:2483)
    at editor.gui$GuiSceneNode$behavior$scene.invoke(gui.clj:2483)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:295)
    at internal.node$pull_first_input_value.invokeStatic(node.clj:1192)
    at editor.app_view$AppView$behavior$active_scene$fn.invoke(app_view.clj:330)
    at internal.node$trace_expr.invokeStatic(node.clj:44)
    at editor.app_view$AppView$behavior$active_scene.invokeStatic(app_view.clj:330)
    at editor.app_view$AppView$behavior$active_scene.invoke(app_view.clj:330)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:295)
    at internal.node$pull_first_input_value.invokeStatic(node.clj:1192)
    at editor.scene_visibility$SceneVisibilityNode$behavior$outline_name_paths_by_selection_state$fn.invoke(scene_visibility.clj:117)
    at internal.node$trace_expr.invokeStatic(node.clj:44)
    at editor.scene_visibility$SceneVisibilityNode$behavior$outline_name_paths_by_selection_state.invokeStatic(scene_visibility.clj:117)
    at editor.scene_visibility$SceneVisibilityNode$behavior$outline_name_paths_by_selection_state.invoke(scene_visibility.clj:117)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:295)
    at editor.scene_visibility$SceneVisibilityNode$behavior$selected_outline_name_paths$fn.invoke(scene_visibility.clj:117)
    at internal.node$trace_expr.invokeStatic(node.clj:44)
    at editor.scene_visibility$SceneVisibilityNode$behavior$selected_outline_name_paths.invokeStatic(scene_visibility.clj:117)
    at editor.scene_visibility$SceneVisibilityNode$behavior$selected_outline_name_paths.invoke(scene_visibility.clj:117)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:295)
    at editor.scene_visibility$SceneVisibilityNode$behavior$selected_hideable_outline_name_paths$fn.invoke(scene_visibility.clj:117)
    at internal.node$trace_expr.invokeStatic(node.clj:44)
    at editor.scene_visibility$SceneVisibilityNode$behavior$selected_hideable_outline_name_paths.invokeStatic(scene_visibility.clj:117)
    at editor.scene_visibility$SceneVisibilityNode$behavior$selected_hideable_outline_name_paths.invoke(scene_visibility.clj:117)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:295)
    at internal.node$node_value.invokeStatic(node.clj:454)
    at internal.system$node_value.invokeStatic(system.clj:354)
    at dynamo.graph$do_node_value.invokeStatic(graph.clj:830)
    at dynamo.graph$node_value.invokeStatic(graph.clj:833)
    at editor.scene_visibility$fn$fnk56489_positional__56493.invoke(scene_visibility.clj:243)
    at editor.scene_visibility$fn$fnk56489__56505$fn.invoke(scene_visibility.clj:243)
    at editor.scene_visibility$fn$fnk56489__56505.invoke(scene_visibility.clj:243)
    at clojure.lang.AFn.applyToHelper(AFn.java:154)
    at clojure.lang.AFn.applyTo(AFn.java:144)
    at clojure.lang.AFunction$1.doInvoke(AFunction.java:31)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at editor.handler$invoke_fnk.invokeStatic(handler.clj:256)
    at editor.handler$enabled_QMARK_.invokeStatic(handler.clj:296)
    at editor.ui$refresh_menu_item_state.invokeStatic(ui.clj:1681)
    at editor.ui$refresh_menu_item_state.invoke(ui.clj:1657)
    at editor.ui$refresh_menu_item_state.invokeStatic(ui.clj:1663)
    at editor.ui$refresh_menubar_state.invokeStatic(ui.clj:1694)
    at editor.ui$refresh_menus_BANG_.invokeStatic(ui.clj:1844)
    at editor.ui$refresh.invokeStatic(ui.clj:1865)
    at editor.app_view$refresh_menus_and_toolbars_BANG_.invokeStatic(app_view.clj:1801)
    at editor.app_view$make_app_view$fn.invoke(app_view.clj:1925)
    at editor.ui$__GT_timer$fn$fn.invoke(ui.clj:1968)
    at clojure.lang.AFn.run(AFn.java:22)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:456)
    at java.security.AccessController.doPrivileged(AccessController.java:399)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:455)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
    at com.sun.glass.ui.win.WinApplication._runLoop(WinApplication.java)
    at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:184)
    at java.lang.Thread.run(Thread.java:833)
```

**Comment by AGulev** [comment]
it seems like this is the same issue here: https://github.com/defold/defold/issues/8546
