### ISSUE TITLE
Error when connecting debuggger

### ISSUE THREAD

**Issue by DarkMoon2003** [defold/defold#7954]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2023-09-04T08:33:29.754337</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>3dc2224fcf3af8f69cd4369ee34979db0977c6dc</td></tr>
<tr><td>Defold engine sha</td><td>57b34efdf44a922acc6f21d285b207029b53927d</td></tr>
<tr><td>Defold version</td><td>1.5.0</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"cf5eeac72a1b4f0c8fd8f32bb8d6ef87"'>cf5eeac72a1b4f0c8fd8f32bb8d6ef87</a></td></tr>
<tr><td>GPU</td><td>GDI Generic</td></tr>
<tr><td>GPU Driver</td><td>1.1.0</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by britzl** [comment]
```
editor.debugging.mobdebug$connect_BANG_$fn__58833.invoke.class clojure.lang.ExceptionInfo: Failed to connect to debugger on localhost:8172
    at editor.debugging.mobdebug$connect_BANG_$fn.invoke(mobdebug.clj:159)
    at clojure.lang.AFn.run(AFn.java:22)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
    at java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    at java.lang.Thread.run(Thread.java:833)
```

@DarkMoon2003 does this happen all the time or just once?

**Comment by AGulev** [comment]
no extra info provided
