### ISSUE TITLE
1

### ISSUE THREAD

**Issue by EvGrizli** [defold/defold#7995]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2023-08-29T08:57:01.796097</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>57b34efdf44a922acc6f21d285b207029b53927d</td></tr>
<tr><td>Defold engine sha</td><td>57b34efdf44a922acc6f21d285b207029b53927d</td></tr>
<tr><td>Defold version</td><td>1.5.0</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"878818e1cd7042bda4ee7f04097de714"'>878818e1cd7042bda4ee7f04097de714</a></td></tr>
<tr><td>GPU</td><td>Mesa DRI Intel(R) Ivybridge Mobile </td></tr>
<tr><td>GPU Driver</td><td>3.0 Mesa 18.3.6</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>4.19.0-25-amd64</td></tr>
<table>

**Comment by britzl** [comment]
```
java.util.concurrent.FutureTask.report.class java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: Unable to load library 'texc_shared':
/lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/10177784657621623408/x86_64-linux/libtexc_shared.so)
/lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/10177784657621623408/x86_64-linux/libtexc_shared.so)
Native library (linux-x86-64/libtexc_shared.so) not found in resource path (/home/evgrizli/.local/share/Steam/steamapps/common/Defold/packages/defold-57b34efdf44a922acc6f21d285b207029b53927d.jar)
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:191)
    at clojure.core$deref_future.invokeStatic(core.clj:2300)
    at clojure.core$future_call$reify.deref(core.clj:6974)
    at clojure.core$deref.invokeStatic(core.clj:2320)
    at clojure.core$deref.invoke(core.clj:2306)
    at clojure.core$map$fn.invoke(core.clj:2755)
    at clojure.lang.LazySeq.sval(LazySeq.java:42)
    at clojure.lang.LazySeq.seq(LazySeq.java:58)
    at clojure.lang.RT.seq(RT.java:531)
    at clojure.core$seq__5387.invokeStatic(core.clj:137)
    at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:24)
    at clojure.core.protocols$fn.invokeStatic(protocols.clj:75)
    at clojure.core.protocols$fn.invoke(protocols.clj:75)
    at clojure.core.protocols$fn$G__8068__8086.invoke(protocols.clj:13)
    at clojure.core$reduce.invokeStatic(core.clj:6824)
    at editor.pipeline$batched_pmap.invokeStatic(pipeline.clj:174)
    at editor.pipeline$build_BANG_.invokeStatic(pipeline.clj:189)
    at editor.build$build_project_BANG_.invokeStatic(build.clj:59)
    at editor.app_view$build_project_BANG_.invokeStatic(app_view.clj:816)
    at editor.app_view$async_build_BANG_$phase_3_build_project_BANG___61771$run_project_build_on_background_thread_BANG___61772.invoke(app_view.clj:1044)
    at editor.app_view$async_build_BANG_$run_on_background_thread_BANG___61724$fn.invoke(app_view.clj:928)
    at clojure.core$binding_conveyor_fn$fn.invoke(core.clj:2030)
    at clojure.lang.AFn.call(AFn.java:18)
    at java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    at java.lang.Thread.run(Thread.java:833)
```

**Comment by britzl** [comment]
It seems like your version of glibc is lower than 2.29? Could you please confirm this?

**Comment by AGulev** [comment]
I see two ways to solve it:
1. build our libs with static linking
2. bundle needed GCLIB all together with the other libs
