### ISSUE TITLE
When creating my first ever Defold project (mobile game template)

### ISSUE THREAD

**Issue by FelipeSuarezPlazas** [defold/defold#8006]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2023-09-12T14:40:57.163828</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>b32617a800e88bcf42d70520d07c277e48d2b38a</td></tr>
<tr><td>Defold engine sha</td><td>e0073d0f7156b733e97a53c46924355fbf60dc77</td></tr>
<tr><td>Defold version</td><td>1.5.0</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"624b9e8ea0e64e7187c9198fc446b4aa"'>624b9e8ea0e64e7187c9198fc446b4aa</a></td></tr>
<tr><td>GPU</td><td>Apple M1</td></tr>
<tr><td>GPU Driver</td><td>2.1 Metal - 83.1</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>aarch64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>13.4.1</td></tr>
<table>

**Comment by FelipeSuarezPlazas** [comment]
(SOLVED) 
I had /Library/Java/JavaVirtualMachines/teterin11 (java jdk version 11) because I was using Godot before.
So the only thing I did was to remove this old version of Java JDK and install a newer: jdk-20.jdk

**Comment by britzl** [comment]
```
java.util.zip.InflaterInputStream.fill.class java.io.EOFException: Unexpected end of ZLIB input stream
    at java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:244)
    at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
    at java.util.zip.ZipInputStream.read(ZipInputStream.java:196)
    at java.io.FilterInputStream.read(FilterInputStream.java:106)
    at clojure.java.io$fn.invokeStatic(io.clj:305)
    at clojure.java.io$fn.invoke(io.clj:302)
    at clojure.lang.MultiFn.invoke(MultiFn.java:239)
    at clojure.java.io$copy.invokeStatic(io.clj:406)
    at clojure.java.io$copy.doInvoke(io.clj:391)
    at clojure.lang.RestFn.invoke(RestFn.java:425)
    at editor.welcome$expand_proj_zip_BANG_$fn.invoke(welcome.clj:253)
    at editor.welcome$expand_proj_zip_BANG_.invokeStatic(welcome.clj:252)
    at editor.welcome$show_welcome_dialog_BANG_$download_template_BANG___104987$fn.invoke(welcome.clj:628)
    at clojure.core$binding_conveyor_fn$fn.invoke(core.clj:2030)
    at clojure.lang.AFn.call(AFn.java:18)
    at java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    at java.lang.Thread.run(Thread.java:833)
```

**Comment by britzl** [comment]
This is a bit surprising since the editor comes bundled with a JDK. Your local JDK should not matter. @vlaaad and @matgis what do you make of this?

**Comment by vlaaad** [comment]
I think jdk reinstall is a red herring, the error seems to be related to unpacking the template zip, maybe download got corrupted.

**Comment by AGulev** [comment]
That would be awesome if the editor just re-download zip if see it is corrupted as I suggested here (maybe with some limitation for max 3 attempts or something like that):
https://github.com/defold/defold/issues/7933

**Comment by matgis** [comment]
Closing this since we now have a separate ticket for implementing a retry.
