### ISSUE TITLE
i don't know how i can not add component file

### ISSUE THREAD

**Issue by gdducnguyen** [defold/defold#8053]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2023-09-26T10:26:06.112848</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>669c99dd8041c1d35a21b6d4c518848efb2dfdf5</td></tr>
<tr><td>Defold engine sha</td><td>d9e9c49ab946c058f29a8b688c862d70f30e9c43</td></tr>
<tr><td>Defold version</td><td>1.6.0</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"f938a9384f064423bf131919fe2a6267"'>f938a9384f064423bf131919fe2a6267</a></td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce GTX 1650/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 531.79</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by britzl** [comment]
```
cljfx.coerce$fail.invokeStatic.class clojure.lang.ExceptionInfo: Don't know how to coerce
    at cljfx.coerce$fail.invokeStatic(coerce.clj:42)
    at cljfx.coerce$image.invokeStatic(coerce.clj:85)
    at cljfx.coerce$image.invoke(coerce.clj:84)
    at cljfx.mutator$setter$fn.invoke(mutator.clj:29)
    at cljfx.mutator$fn$G__1676__1740.invoke(mutator.clj:14)
    at cljfx.prop$assign_BANG_.invokeStatic(prop.clj:36)
    at cljfx.composite$create_composite_component.invokeStatic(composite.clj:39)
    at cljfx.composite$create_composite_component.invoke(composite.clj:26)
    at cljfx.lifecycle$fn$G__2449__2488.invoke(lifecycle.clj:17)
    at cljfx.lifecycle$create_dynamic_component.invokeStatic(lifecycle.clj:35)
    at cljfx.lifecycle$reify.create(lifecycle.clj:39)
    at cljfx.lifecycle$wrap_dynamic_fn$fn.invoke(lifecycle.clj:79)
    at cljfx.lifecycle$fn$G__2449__2488.invoke(lifecycle.clj:17)
    at cljfx.lifecycle$create_dynamic_component.invokeStatic(lifecycle.clj:35)
    at cljfx.lifecycle$reify.create(lifecycle.clj:39)
    at cljfx.lifecycle$wrap_extra_props$fn.invoke(lifecycle.clj:351)
    at cljfx.lifecycle$fn$G__2449__2488.invoke(lifecycle.clj:17)
    at cljfx.lifecycle$wrap_many$fn$fn$fn.invoke(lifecycle.clj:282)
    at clojure.core$update.invokeStatic(core.clj:6196)
    at cljfx.lifecycle$wrap_many$fn$fn.invoke(lifecycle.clj:281)
    at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
    at clojure.core$reduce.invokeStatic(core.clj:6827)
    at cljfx.lifecycle$wrap_many$fn.invoke(lifecycle.clj:280)
    at cljfx.lifecycle$fn$G__2449__2488.invoke(lifecycle.clj:17)
    at cljfx.composite$create_props$fn.invoke(composite.clj:22)
    at clojure.core$fn$fn.invoke(core.clj:6840)
    at clojure.core.protocols$iter_reduce.invokeStatic(protocols.clj:49)
    at clojure.core.protocols$fn.invokeStatic(protocols.clj:75)
    at clojure.core.protocols$fn.invoke(protocols.clj:75)
    at clojure.core.protocols$fn$G__8068__8086.invoke(protocols.clj:13)
    at clojure.core$reduce.invokeStatic(core.clj:6828)
    at clojure.core$fn.invokeStatic(core.clj:6830)
    at clojure.core$fn.invoke(core.clj:6830)
    at clojure.core.protocols$fn$G__8147__8161.invoke(protocols.clj:175)
    at clojure.core$reduce_kv.invokeStatic(core.clj:6856)
    at cljfx.composite$create_props.invokeStatic(composite.clj:16)
    at cljfx.composite$create_composite_component.invokeStatic(composite.clj:28)
    at cljfx.composite$create_composite_component.invoke(composite.clj:26)
    ...
```

**Comment by britzl** [comment]
When does this happen @gdducnguyen ? Can you reproduce it?

**Comment by britzl** [comment]
Hmm, ok. What if you download and open extension-spine as a Defold project in Defold 1.6.0?

https://github.com/defold/extension-spine/archive/refs/tags/2.12.0.zip

**Comment by gdducnguyen** [comment]
i using this version of spine extension. may be i install not true. can you note to me for step by step install extension? @britzl

**Comment by britzl** [comment]
The Spine extension should be added as a library dependency. Add it to Dependencies in game.project and then restart Defold*

https://defold.com/manuals/libraries/#setting-up-library-dependencies

* normally it is enough to add a dependency and select Fetch Libraries menu option to use a dependency, but the Spine extension is a bit special since it also has adds new functionality to the editor, thus a restart of the editor is required.

**Comment by gdducnguyen** [comment]
https://defold.com/manuals/libraries/#setting-up-library-dependencies
yes. it work done ! thanks sir ! i fetch extension with dependencies and it work  !
