### ISSUE TITLE
Deleting a UVmap outside the editor and saving a new PNG outside the editor but into the same Defold project folder creates error

### ISSUE THREAD

**Issue by QuarterMillion-games** [defold/defold#8090]
Deleting a UVmap outside the editor and saving a new PNG outside the editor but into the same Defold project folder creates error
### Expected behaviour
project runs no errors.
![blackmnMeshNew](https://github.com/defold/defold/assets/146807897/4633d3a0-5624-4e31-9241-52d7a797e6e1)

### Actual behaviour
Get a javascript fail error because it can't find the deleted file.
### Steps to reproduce

Create a new RGB color profiled PNG file. 
Directly save it into the Defold project's images folder instead of using drag and drop.
Delete a prior existing UV map sRGB PNG file (in this case blackmnMeshNew) in the same folder but not directly in the Defold project. Instead delete it outside of the Defold editor. Then SaveAll and then Build.
<hr/>

<table>
<tr><td>Build time</td><td>2023-09-24T10:14:54.165179</td></tr>
<tr><td>Defold channel</td><td>beta</td></tr>
<tr><td>Defold editor sha</td><td>0c82b0d465fc3fa12afe7b67f65f3f1c7c221182</td></tr>
<tr><td>Defold engine sha</td><td>0c82b0d465fc3fa12afe7b67f65f3f1c7c221182</td></tr>
<tr><td>Defold version</td><td>1.6.0</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"d40b6057b6394eab9dfa95ed11428a7a"'>d40b6057b6394eab9dfa95ed11428a7a</a></td></tr>
<tr><td>GPU</td><td>AMD Radeon(TM) R4 Graphics</td></tr>
<tr><td>GPU Driver</td><td>4.5.14009 Compatibility Profile Context 21.19.144.1281</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by britzl** [comment]
```
java.util.concurrent.FutureTask.report.class java.util.concurrent.ExecutionException: java.io.FileNotFoundException: F:\DefoldArcade\Empty3D\assets\images\blkhumanMesh.png (The system cannot find the file specified)
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:191)
    at clojure.core$deref_future.invokeStatic(core.clj:2300)
    at clojure.core$future_call$reify.deref(core.clj:6974)
    at clojure.core$deref.invokeStatic(core.clj:2320)
    at clojure.core$deref.invoke(core.clj:2306)
    at clojure.core$map$fn.invoke(core.clj:2755)
    at clojure.lang.LazySeq.sval(LazySeq.java:42)
    at clojure.lang.LazySeq.seq(LazySeq.java:58)
    at clojure.lang.RT.seq(RT.java:531)
    at clojure.core$seq__5387.invokeStatic(core.clj:137)
    at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:24)
    at clojure.core.protocols$fn.invokeStatic(protocols.clj:75)
    at clojure.core.protocols$fn.invoke(protocols.clj:75)
    at clojure.core.protocols$fn$G__8068__8086.invoke(protocols.clj:13)
    at clojure.core$reduce.invokeStatic(core.clj:6824)
    at editor.build$batched_pmap.invokeStatic(build.clj:23)
    at editor.build$build_project_BANG_.invokeStatic(build.clj:52)
    at editor.app_view$build_project_BANG_.invokeStatic(app_view.clj:816)
    at editor.app_view$async_build_BANG_$phase_3_build_project_BANG___61859$run_project_build_on_background_thread_BANG___61860.invoke(app_view.clj:1044)
    at editor.app_view$async_build_BANG_$run_on_background_thread_BANG___61812$fn.invoke(app_view.clj:928)
    at clojure.core$binding_conveyor_fn$fn.invoke(core.clj:2030)
    at clojure.lang.AFn.call(AFn.java:18)
    at java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    at java.lang.Thread.run(Thread.java:833)
```

**Comment by britzl** [comment]
> Delete a prior existing UV map sRGB PNG file (in this case blackmnMeshNew) in the same folder but not directly in the Defold project. Instead delete it outside of the Defold editor.

Is the file references in the project?

**Comment by QuarterMillion-games** [comment]
I thought I attached the files with the report

**Comment by AGulev** [comment]
I can't reproduce the issue, please provide a minimal reproduction case (a minimal project where it is possible to reproduce the issue)

**Comment by AGulev** [comment]
Feel free to reopen the issue if you are able to provide the requested information.
