### ISSUE TITLE
.spinescene error

### ISSUE THREAD

**Issue by labiozzza** [defold/defold#8176]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2023-10-09T13:06:39.373206</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>dba9e0dc85a404a10ff07cfe2d3f4c7d93ee5d8f</td></tr>
<tr><td>Defold engine sha</td><td>d9e9c49ab946c058f29a8b688c862d70f30e9c43</td></tr>
<tr><td>Defold version</td><td>1.6.0</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"4fdd58c26afb4e489ac32cc9e92a2e3d"'>4fdd58c26afb4e489ac32cc9e92a2e3d</a></td></tr>
<tr><td>GPU</td><td>Apple M2</td></tr>
<tr><td>GPU Driver</td><td>2.1 Metal - 83</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>aarch64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>13.0.1</td></tr>
<table>

**Comment by britzl** [comment]
```
editor.spineext$SpineSceneNode$behavior$atlas.invokeStatic.class java.lang.NoClassDefFoundError: Could not initialize class editor.spineext$SpineSceneNode$behavior$atlas$fn__2037
    at editor.spineext$SpineSceneNode$behavior$atlas.invokeStatic
    at editor.spineext$SpineSceneNode$behavior$atlas.invoke
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:295)
    at editor.spineext$SpineSceneNode$behavior$spine_scene_pb$fn.invoke
    at internal.node$trace_expr.invokeStatic(node.clj:44)
    at internal.node$trace_expr.invoke(node.clj:34)
    at editor.spineext$SpineSceneNode$behavior$spine_scene_pb.invokeStatic
    at editor.spineext$SpineSceneNode$behavior$spine_scene_pb.invoke
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:295)
    at editor.spineext$SpineSceneNode$behavior$main_scene$fn.invoke
    at internal.node$trace_expr.invokeStatic(node.clj:44)
    at internal.node$trace_expr.invoke(node.clj:34)
    at editor.spineext$SpineSceneNode$behavior$main_scene.invokeStatic
    at editor.spineext$SpineSceneNode$behavior$main_scene.invoke
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:295)
    at editor.spineext$SpineSceneNode$behavior$scene$fn.invoke
    at internal.node$trace_expr.invokeStatic(node.clj:44)
    at internal.node$trace_expr.invoke(node.clj:34)
    at editor.spineext$SpineSceneNode$behavior$scene.invokeStatic
    at editor.spineext$SpineSceneNode$behavior$scene.invoke
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:295)
    at internal.node$pull_first_input_value.invokeStatic(node.clj:1181)
    at editor.scene$SceneView$behavior$scene_aabb$fn.invoke(scene.clj:798)
    at internal.node$trace_expr.invokeStatic(node.clj:44)
    at editor.scene$SceneView$behavior$scene_aabb.invokeStatic(scene.clj:798)
```

**Comment by britzl** [comment]
@labiozzza which version of the Spine extension are you using?

**Comment by britzl** [comment]
Closing. Not enough information.
