### ISSUE TITLE
Trying to build first tutorial project in Bunsen labs Linux

### ISSUE THREAD

**Issue by MrDudeIII** [defold/defold#8263]
### Expected behaviour
I press build and it should run the game right?
### Actual behaviour
The initial project manager window renders at an unhelpful resolution (maybe 128x128?) and is unresizable. I loaded a tutorial blind, but then the editor seems to render correctly. When I try to build the tutorial project to run the game, it throws the reported error and the build fails + it doesn't run.
### Steps to reproduce
Download Defold.
Load side scroller tutorial
Build game

<hr/>

<table>
<tr><td>Build time</td><td>2023-11-23T07:58:52.984970</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>32c7a7f321c3ed0b1ce848fa9e7b500e09a7d311</td></tr>
<tr><td>Defold engine sha</td><td>4e156b7cf37a380122aada30dacbf2b590ead76b</td></tr>
<tr><td>Defold version</td><td>1.6.2</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"baa5c12cb1a0480fb6cc64af008a83c8"'>baa5c12cb1a0480fb6cc64af008a83c8</a></td></tr>
<tr><td>GPU</td><td>Mesa DRI Intel(R) HD Graphics 5500 (Broadwell GT2) </td></tr>
<tr><td>GPU Driver</td><td>3.0 Mesa 18.3.6</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>4.19.0-21-amd64</td></tr>
<table>

**Comment by britzl** [comment]
```
java.util.concurrent.FutureTask.report.class java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: Could not initialize class com.dynamo.bob.TexcLibrary
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:191)
    at clojure.core$deref_future.invokeStatic(core.clj:2300)
    at clojure.core$future_call$reify.deref(core.clj:6974)
    at clojure.core$deref.invokeStatic(core.clj:2320)
    at clojure.core$deref.invoke(core.clj:2306)
    at clojure.core$map$fn.invoke(core.clj:2755)
    at clojure.lang.LazySeq.sval(LazySeq.java:42)
    at clojure.lang.LazySeq.seq(LazySeq.java:51)
    at clojure.lang.Cons.next(Cons.java:39)
    at clojure.lang.RT.next(RT.java:709)
    at clojure.core$next__5371.invokeStatic(core.clj:64)
    at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:27)
    at clojure.core.protocols$fn.invokeStatic(protocols.clj:75)
    at clojure.core.protocols$fn.invoke(protocols.clj:75)
    at clojure.core.protocols$fn$G__8068__8086.invoke(protocols.clj:13)
    at clojure.core$reduce.invokeStatic(core.clj:6824)
    at editor.pipeline$batched_pmap.invokeStatic(pipeline.clj:174)
    at editor.pipeline$build_BANG_.invokeStatic(pipeline.clj:189)
    at editor.build$build_project_BANG_.invokeStatic(build.clj:59)
    at editor.app_view$build_project_BANG_.invokeStatic(app_view.clj:905)
    at editor.app_view$async_build_BANG_$phase_3_build_project_BANG___62875$run_project_build_on_background_thread_BANG___62876.invoke(app_view.clj:1133)
    at editor.app_view$async_build_BANG_$run_on_background_thread_BANG___62828$fn.invoke(app_view.clj:1017)
    at clojure.core$binding_conveyor_fn$fn.invoke(core.clj:2030)
    at clojure.lang.AFn.call(AFn.java:18)
    at java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    at java.lang.Thread.run(Thread.java:833)
```

**Comment by britzl** [comment]
I wonder if the super-small window size is related to this FAQ entry?

https://defold.com/manuals/linux/#q-why-is-the-defold-editor-super-small-when-run-on-a-4k-or-hidpi-monitor-when-using-gnome

**Comment by MrDudeIII** [comment]
Hey thanks for responding! It's not every screen that is super small, just the project manager. On further digging, it is likely something I can resolve by upgrading my distro to the current release. I tried a few versions of Defold backwards and found that I could get the demo projects to build with 1.2*, but mouse/keyboard inputs weren't registering. I will try to swing back around and update here if the upgrade resolves the issue.

**Comment by MrDudeIII** [comment]
For the people of the future, doing a full upgrade on the OS (bunsenlabs linux) resolved the issue. The project manager is still too small to read anything but I've got a poor temporary workaround.
