### ISSUE TITLE
Error when trying to restart after update

### ISSUE THREAD

**Issue by jamma** [defold/defold#8281]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2023-11-23T08:02:18.242359</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>32c7a7f321c3ed0b1ce848fa9e7b500e09a7d311</td></tr>
<tr><td>Defold engine sha</td><td>4e156b7cf37a380122aada30dacbf2b590ead76b</td></tr>
<tr><td>Defold version</td><td>1.6.2</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"1dd0687afed149eda1d433a8dec1c6ed"'>1dd0687afed149eda1d433a8dec1c6ed</a></td></tr>
<tr><td>GPU</td><td>AMD Radeon Pro 580 OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 ATI-4.14.1</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>13.6.1</td></tr>
<table>

**Comment by jamma** [comment]
Not sure exactly what happened. Defold keeps telling me that I need to restart to update, but when I click the "Restart to Update" text button it crashes. Closing and reopening Defold seems to solve the issue.

**Comment by britzl** [comment]
```
com.dynamo.bob.ClassLoaderScanner.scanLoader.class java.lang.RuntimeException: java.nio.file.NoSuchFileException: /Applications/Defold.app/Contents/Resources/packages/defold-32c7a7f321c3ed0b1ce848fa9e7b500e09a7d311.jar
    at com.dynamo.bob.ClassLoaderScanner.scanLoader(ClassLoaderScanner.java:122)
    at com.dynamo.bob.ClassLoaderScanner.scanClassLoader(ClassLoaderScanner.java:129)
    at editor.code.preprocessors$try_initialize_lua_preprocessors.invokeStatic(preprocessors.clj:108)
    at editor.code.preprocessors$reload_lua_preprocessors_BANG_.invokeStatic(preprocessors.clj:152)
    at editor.workspace$load_java_editor_plugins_BANG_.invokeStatic(workspace.clj:494)
    at editor.workspace$reload_plugins_BANG_.invokeStatic(workspace.clj:628)
    at editor.disk$start_save_job_BANG_$fn.invoke(disk.clj:165)
    at clojure.core$binding_conveyor_fn$fn.invoke(core.clj:2030)
    at clojure.lang.AFn.call(AFn.java:18)
    at java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    at java.lang.Thread.run(Thread.java:833)
```

**Comment by vlaaad** [comment]
@jamma Do you use https://github.com/defold/extension-lua-preprocessor?

**Comment by jamma** [comment]
Not that I know of. I'm very new to Defold but according to the lua-preprocessr github page I'd have to set this up under game.project -> Project -> Dependencies. That property is currently empty, I have no installed editor extensions outside of what may come with a default Defold installation.

**Comment by britzl** [comment]
We've changed the way we unpack files. Old issue. Closing.
