### ISSUE TITLE
Error on every symbol typed in lua extension file when lua language server running

### ISSUE THREAD

**Issue by vbif1** [defold/defold#8354]
### Expected behaviour
Expected typing without interruptions

### Actual behaviour
Got error dialog after every symbol being typed

### Steps to reproduce
Add lua-language-server extension to project
Add any extension with lua files - druid for example
Fetch libraries
Open lua file from extension and start typing.

<hr/>

<table>
<tr><td>Build time</td><td>2023-12-14T13:30:50.887403</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>acef72c1b65ebf1d91d22ec52e055e262d0e1888</td></tr>
<tr><td>Defold engine sha</td><td>4e156b7cf37a380122aada30dacbf2b590ead76b</td></tr>
<tr><td>Defold version</td><td>1.6.2</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"4a66019d7ff04960bcb7272eee6bb824"'>4a66019d7ff04960bcb7272eee6bb824</a></td></tr>
<tr><td>GPU</td><td>Apple M1 Max</td></tr>
<tr><td>GPU Driver</td><td>2.1 Metal - 83.1</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>13.4.1</td></tr>
<table>

**Comment by vlaaad** [comment]
```
java.net.URI$Parser.fail.class java.net.URISyntaxException: Expected authority at index 7: file://
    at java.net.URI$Parser.fail(URI.java:2974)
    at java.net.URI$Parser.failExpecting(URI.java:2980)
    at java.net.URI$Parser.parseHierarchical(URI.java:3224)
    at java.net.URI$Parser.parse(URI.java:3175)
    at java.net.URI.<init>(URI.java:708)
    at java.net.URI.<init>(URI.java:809)
    at editor.lsp.server$make_uri_string.invokeStatic(server.clj:113)
    at editor.lsp.server$resource_uri.invokeStatic(server.clj:119)
    at editor.lsp.server$completion.invokeStatic(server.clj:553)
    at editor.lsp$request_completions_BANG_$fn$fn.invoke(lsp.clj:860)
    at editor.lsp$send_requests_BANG_$fn.invoke(lsp.clj:712)
    at clojure.core$map$fn$fn.invoke(core.clj:2742)
    at clojure.core.protocols$iter_reduce.invokeStatic(protocols.clj:49)
    at clojure.core.protocols$fn.invokeStatic(protocols.clj:75)
    at clojure.core.protocols$fn.invoke(protocols.clj:75)
    at clojure.core.protocols$fn$G__8068__8086.invoke(protocols.clj:13)
    at clojure.core$transduce.invokeStatic(core.clj:6884)
    at clojure.core.Eduction.reduce(core.clj:7682)
    at clojure.core$reduce.invokeStatic(core.clj:6827)
    at internal.util$group_into.invokeStatic(util.clj:142)
    at editor.lsp$send_requests_BANG_.invokeStatic(lsp.clj:704)
    at editor.lsp$request_completions_BANG_$fn.invoke(lsp.clj:847)
    at clojure.lang.AFn.applyToHelper(AFn.java:154)
    at clojure.lang.AFn.applyTo(AFn.java:144)
    at clojure.core$apply.invokeStatic(core.clj:665)
    at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1973)
    at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1973)
    at clojure.lang.RestFn.applyTo(RestFn.java:142)
    at clojure.core$apply.invokeStatic(core.clj:669)
    at clojure.core$bound_fn_STAR_$fn.doInvoke(core.clj:2003)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at editor.lsp$make$fn$state_machine__19599__auto____30617$fn.invoke(lsp.clj:466)
    at editor.lsp$make$fn$state_machine__19599__auto____30617.invoke(lsp.clj:466)
    at clojure.core.async.impl.ioc_macros$run_state_machine.invokeStatic(ioc_macros.clj:978)
    at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invokeStatic(ioc_macros.clj:980)
    at clojure.core.async$ioc_alts_BANG_$fn.invoke(async.clj:419)
    at clojure.core.async$do_alts$fn$fn.invoke(async.clj:288)
    at clojure.core.async.impl.channels.ManyToManyChannel$fn$fn.invoke(channels.clj:99)
    at clojure.lang.AFn.run(AFn.java:22)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    at clojure.core.async.impl.concurrent$counted_thread_factory$reify$fn.invoke(concurrent.clj:29)
    at clojure.lang.AFn.run(AFn.java:22)
    at java.lang.Thread.run(Thread.java:833)
```

**Comment by vlaaad** [comment]
We shouldn't send completion requests for library lua files...
