### ISSUE TITLE
Failed editor update on Mac

### ISSUE THREAD

**Issue by osov** [defold/defold#8482]
After installing the version for "Apple Silicon Mac" from the official website, version 1.6.2 is installed, a button appears indicating that an update is available, when clicked it downloads, but during installation it gives an error:
"an error occurred during update installation"
Reinstalling does not solve the problem.

**Comment by britzl** [comment]
What does the editor log say?

https://defold.com/manuals/editor/#editor-logs

**Comment by osov** [comment]
```2024-02-13 00:18:28.224 283687985 [Timer-1] INFO  editor.updater - {:line 303, :message "Checking for updates", :url "https://d.defold.com/editor2/channels/editor-alpha/update-v4.json"}
2024-02-13 00:18:29.168 283688929 [Timer-1] INFO  editor.updater - {:line 309, :message "New version found", :sha1 "7c193bc6d45628afead4a26615ce5a9d52ca5bec"}
2024-02-13 02:40:31.694 292211455 [Timer-1] INFO  editor.updater - {:line 303, :message "Checking for updates", :url "https://d.defold.com/editor2/channels/editor-alpha/update-v4.json"}
2024-02-13 02:40:32.413 292212174 [Timer-1] INFO  editor.updater - {:line 309, :message "New version found", :sha1 "7c193bc6d45628afead4a26615ce5a9d52ca5bec"}
2024-02-13 05:56:57.750 303997511 [Timer-1] INFO  editor.updater - {:line 303, :message "Checking for updates", :url "https://d.defold.com/editor2/channels/editor-alpha/update-v4.json"}
2024-02-13 05:56:58.630 303998391 [Timer-1] INFO  editor.updater - {:line 309, :message "New version found", :sha1 "7c193bc6d45628afead4a26615ce5a9d52ca5bec"}
2024-02-13 11:23:59.597 323619358 [Timer-1] INFO  editor.updater - {:line 303, :message "Checking for updates", :url "https://d.defold.com/editor2/channels/editor-alpha/update-v4.json"}
2024-02-13 11:24:00.371 323620132 [Timer-1] INFO  editor.updater - {:line 309, :message "New version found", :sha1 "7c193bc6d45628afead4a26615ce5a9d52ca5bec"}
2024-02-13 13:32:41.218 331340979 [JavaFX Application Thread] INFO  editor.updater - {:line 264, :message "Installing update"}
2024-02-13 13:32:41.229 331340990 [JavaFX Application Thread] INFO  editor.ui.updater - {:line 38, :message "Update failed"}
java.nio.file.FileSystemException: /Volumes/Defold/Defold.app/Contents/_CodeSignature/CodeResources: Read-only file system
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:100)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixCopyFile.move(UnixCopyFile.java:467)
	at java.base/sun.nio.fs.UnixFileSystemProvider.move(UnixFileSystemProvider.java:266)
	at java.base/java.nio.file.Files.move(Files.java:1432)
	at editor.updater$move_file_BANG_.invokeStatic(updater.clj:222)
	at editor.updater$install_unix_file_BANG_.invokeStatic(updater.clj:228)
	at editor.updater$install_file_BANG_.invokeStatic(updater.clj:244)
	at editor.updater$install_BANG_.invokeStatic(updater.clj:269)
	at editor.ui.updater$install_BANG_.invokeStatic(updater.clj:33)
	at editor.ui.updater$init_BANG_$fn__106006.invoke(updater.clj:51)
	at editor.ui$fn__15205$fn__15206.invoke(ui.clj:2023)
	at editor.ui$chain_handler$reify__15169.handle(ui.clj:2009)
	at editor.ui$chain_handler$reify__15169.handle(ui.clj:2011)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:232)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:189)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at com.sun.javafx.stage.WindowPeerListener.closing(WindowPeerListener.java:100)
	at com.sun.javafx.tk.quantum.GlassWindowEventHandler.run(GlassWindowEventHandler.java:147)
	at com.sun.javafx.tk.quantum.GlassWindowEventHandler.run(GlassWindowEventHandler.java:40)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at com.sun.javafx.tk.quantum.GlassWindowEventHandler.lambda$handleWindowEvent$4(GlassWindowEventHandler.java:178)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:424)
	at com.sun.javafx.tk.quantum.GlassWindowEventHandler.handleWindowEvent(GlassWindowEventHandler.java:176)
	at com.sun.glass.ui.Window.handleWindowEvent(Window.java:1259)
	at com.sun.glass.ui.Window.notifyClose(Window.java:1164)
2024-02-13 13:33:45.774 96   [JavaFX-Launcher] WARN  javafx - Unsupported JavaFX configuration: classes were loaded from 'unnamed module @9251832'
2024-02-13 13:33:46.631 953  [Thread-4] INFO  com.defold.libs.ResourceUnpacker - deleting old unpack dirs from /Users/sov/Library/Application Support/Defold/unpack
2024-02-13 13:33:46.637 959  [Thread-4] INFO  com.defold.libs.ResourceUnpacker - Already unpacked for the editor version acef72c1b65ebf1d91d22ec52e055e262d0e1888
2024-02-13 13:33:46.640 962  [Thread-4] INFO  com.defold.libs.ResourceUnpacker - defold.unpack.path=/Users/sov/Library/Application Support/Defold/unpack/acef72c1b65ebf1d91d22ec52e055e262d0e1888
2024-02-13 13:33:48.949 3271 [Timer-1] INFO  editor.updater - {:line 303, :message "Checking for updates", :url "https://d.defold.com/editor2/channels/editor-alpha/update-v4.json"}
2024-02-13 13:33:49.229 3551 [Timer-1] INFO  editor.updater - {:line 309, :message "New version found", :sha1 "7c193bc6d45628afead4a26615ce5a9d52ca5bec"}
2024-02-13 13:33:52.585 6907 [clojure-agent-send-off-pool-6] INFO  editor.updater - {:line 126, :message "Downloading update", :url "https://d.defold.com/archive/7c193bc6d45628afead4a26615ce5a9d52ca5bec/editor-alpha/editor2/Defold-arm64-macos.zip", :file "/private/var/folders/71/1strms6d0lzfd8ghwjbgjhh00000gn/T/defold-update13128838275536819699.zip"}
2024-02-13 13:34:20.363 34685 [clojure-agent-send-off-pool-6] INFO  editor.updater - {:line 149, :message "Removing previously downloaded update"}
2024-02-13 13:34:20.405 34727 [clojure-agent-send-off-pool-6] INFO  editor.updater - {:line 153, :message "Extracting update", :dir "/Users/sov/Library/Application Support/Defold/update"}
2024-02-13 13:34:21.252 35574 [clojure-agent-send-off-pool-6] INFO  editor.updater - {:line 182, :message "Update extracted"}
2024-02-13 13:34:32.533 46855 [JavaFX Application Thread] INFO  editor.updater - {:line 264, :message "Installing update"}
2024-02-13 13:34:32.544 46866 [JavaFX Application Thread] INFO  editor.ui.updater - {:line 38, :message "Update failed"}
java.nio.file.FileSystemException: /Volumes/Defold/Defold.app/Contents/_CodeSignature/CodeResources: Read-only file system
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:100)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixCopyFile.move(UnixCopyFile.java:467)
	at java.base/sun.nio.fs.UnixFileSystemProvider.move(UnixFileSystemProvider.java:266)
	at java.base/java.nio.file.Files.move(Files.java:1432)
	at editor.updater$move_file_BANG_.invokeStatic(updater.clj:222)
	at editor.updater$install_unix_file_BANG_.invokeStatic(updater.clj:228)
	at editor.updater$install_file_BANG_.invokeStatic(updater.clj:244)
	at editor.updater$install_BANG_.invokeStatic(updater.clj:269)
	at editor.ui.updater$install_BANG_.invokeStatic(updater.clj:33)
	at editor.ui.updater$install_and_restart_BANG_.invokeStatic(updater.clj:43)
	at editor.welcome$init_pending_update_indicator_BANG_$install_and_restart_BANG___106222.invoke(welcome.clj:542)
	at editor.ui.updater$init_BANG_$fn__106008.invoke(updater.clj:84)
	at editor.ui$fn$reify__14216.handle(ui.clj:879)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:232)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:189)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Node.fireEvent(Node.java:8889)
	at javafx.scene.control.Hyperlink.fire(Hyperlink.java:156)
	at com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(ButtonBehavior.java:207)
	at com.sun.javafx.scene.control.inputmap.InputMap.handle(InputMap.java:274)
	at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:247)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:232)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:189)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Scene$MouseHandler.process(Scene.java:3984)
	at javafx.scene.Scene.processMouseEvent(Scene.java:1890)
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2708)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:411)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:301)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:450)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:424)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:449)
	at com.sun.glass.ui.View.handleMouseEvent(View.java:551)
	at com.sun.glass.ui.View.notifyMouse(View.java:937)
	at com.sun.glass.ui.mac.MacView.notifyMouse(MacView.java:127)
```

**Comment by ekharkunov** [comment]
It seems that you run Defold from mounted .dmg.
You should copy Defold from .dmg to any other location at you local disk.

**Comment by osov** [comment]
Thanks, this helped. Finally updated.
