### ISSUE TITLE
Clicking reset button on changed gui template properties makes editor blow up

### ISSUE THREAD

**Issue by Temeez** [defold/defold#8546]
### Expected behaviour
Changed gui property (e.g. size) of a template node resets to the template defaults.

### Actual behaviour
Spits three errors. Requires editor restart.

### Steps to reproduce
1. New mobile project
2. Create main.gui and template.gui
3. Open template.gui and add box. Set size to manual (64x64)
4. Open main.gui, add template and set the Template to template.gui
5. Edit template/box size to something else from 64x64 and click away to make sure the change is applied
6. Click the reset button where you changed the values -> Error

<hr/>

<table>
<tr><td>Build time</td><td>2024-02-15T08:54:48.112358</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>7bafadda047312e68a7094c2928e5a403ebf90d8</td></tr>
<tr><td>Defold engine sha</td><td>fcec9500fd438e365d4e4f6cec24b99afb907247</td></tr>
<tr><td>Defold version</td><td>1.6.4</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"a850d8d521b24561b1a288d2bbf773d9"'>a850d8d521b24561b1a288d2bbf773d9</a></td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce GTX 1070/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 531.79</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by britzl** [comment]
```
clojure.lang.RT.uncheckedDoubleCast.class java.lang.NullPointerException: Cannot invoke "java.lang.Number.doubleValue()" because "x" is null
    at clojure.lang.RT.uncheckedDoubleCast(RT.java:1559)
    at editor.slice9$vertex_data.invokeStatic(slice9.clj:220)
    at editor.gui$fn.invokeStatic(gui.clj:1012)
    at editor.gui$fn.invoke(gui.clj:1012)
    at clojure.lang.AFn.applyToHelper(AFn.java:154)
    at clojure.lang.AFn.applyTo(AFn.java:144)
    at clojure.lang.AFunction$1.doInvoke(AFunction.java:31)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at clojure.lang.Var.invoke(Var.java:384)
    at editor.gui$BoxNode$behavior$scene_renderable_user_data$fn.invoke(gui.clj:998)
    at internal.node$trace_expr.invokeStatic(node.clj:44)
```
