### ISSUE TITLE
Error and black screen when i edit collection file

### ISSUE THREAD

**Issue by d954mas** [defold/defold#8558]
### Expected behaviour
I have no idea what and why happened. I edit .collection files. Then i open another collection file

After few minutes, after error i get black screen and need reboot pc.

Mb is was something with my drivers or mb you do something wrong)

Please look on it
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2024-02-16T08:36:38.395220</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>842ff043cad46c2b6d944bd7fb091943a462f03f</td></tr>
<tr><td>Defold engine sha</td><td>fcec9500fd438e365d4e4f6cec24b99afb907247</td></tr>
<tr><td>Defold version</td><td>1.6.4</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"e1e8abc4ad304e4eae44c2c0ea66a1f6"'>e1e8abc4ad304e4eae44c2c0ea66a1f6</a></td></tr>
<tr><td>GPU</td><td>AMD Radeon(TM) Graphics</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 Compatibility Profile Context 23.5.2.230523</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by britzl** [comment]
```
jogamp.opengl.windows.wgl.WindowsWGLContext.createImpl.class com.jogamp.opengl.GLException: Error making temp context current: 0x0x200cf, werr: 126
    at jogamp.opengl.windows.wgl.WindowsWGLContext.createImpl(WindowsWGLContext.java:355)
    at jogamp.opengl.GLContextImpl.makeCurrentWithinLock(GLContextImpl.java:793)
    at jogamp.opengl.GLContextImpl.makeCurrent(GLContextImpl.java:676)
    at jogamp.opengl.GLContextImpl.makeCurrent(GLContextImpl.java:614)
    at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1279)
    at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1147)
    at jogamp.opengl.GLAutoDrawableBase.defaultDisplay(GLAutoDrawableBase.java:476)
    at com.jogamp.opengl.GLAutoDrawableDelegate.display(GLAutoDrawableDelegate.java:190)
    at jogamp.opengl.GLAutoDrawableBase.defaultWindowResizedOp(GLAutoDrawableBase.java:260)
    at jogamp.opengl.GLOffscreenAutoDrawableImpl.setSurfaceSize(GLOffscreenAutoDrawableImpl.java:61)
    at editor.scene$make_gl_pane_BANG_$fn$fn.invoke(scene.clj:1296)
    at editor.scene$make_gl_pane_BANG_$fn.invoke(scene.clj:1286)
    at editor.scene.proxy$com.defold.control.Region$ff19274a.layoutChildren
    at javafx.scene.Parent.layout(Parent.java:1208)
    at javafx.scene.Parent.layout(Parent.java:1215)
    at javafx.scene.Parent.layout(Parent.java:1215)
    at javafx.scene.Parent.layout(Parent.java:1215)
    at javafx.scene.Parent.layout(Parent.java:1215)
    at javafx.scene.Parent.layout(Parent.java:1215)
    at javafx.scene.Parent.layout(Parent.java:1215)
    at javafx.scene.Parent.layout(Parent.java:1215)
    at javafx.scene.Parent.layout(Parent.java:1215)
    at javafx.scene.Parent.layout(Parent.java:1215)
    at javafx.scene.Parent.layout(Parent.java:1215)
    at javafx.scene.Parent.layout(Parent.java:1215)
    at javafx.scene.Parent.layout(Parent.java:1215)
    at javafx.scene.Parent.layout(Parent.java:1215)
    at javafx.scene.Parent.layout(Parent.java:1215)
    at javafx.scene.Parent.layout(Parent.java:1215)
    at javafx.scene.Parent.layout(Parent.java:1215)
    at javafx.scene.Parent.layout(Parent.java:1215)
    at javafx.scene.Scene.doLayoutPass(Scene.java:596)
    at javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2603)
    at com.sun.javafx.tk.Toolkit.lambda$runPulse$2(Toolkit.java:401)
    at java.security.AccessController.doPrivileged(AccessController.java:399)
    at com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:400)
    at com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:430)
    at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:598)
    at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:578)
    at com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(QuantumToolkit.java:571)
    at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(QuantumToolkit.java:352)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
    at com.sun.glass.ui.win.WinApplication._runLoop(WinApplication.java)
    at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:184)
    at java.lang.Thread.run(Thread.java:833)
```

**Comment by AGulev** [comment]
looks like driver failure, not much we can do about it (expecially if there is no a repro)
