### ISSUE TITLE
Error when creating double quote in gui_script

### ISSUE THREAD

**Issue by Jerakin** [defold/defold#8615]
### Steps to reproduce
I only created  a new gui_script. Tried to write `local manager = require "main.game.manager` and on the next `"` the crash happened.

SWE Keyboard.

<hr/>

<table>
<tr><td>Build time</td><td>2024-02-28T08:46:35.883246</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>fde3b9ca14f2629b143173ba41b580c6191317f4</td></tr>
<tr><td>Defold engine sha</td><td>fcec9500fd438e365d4e4f6cec24b99afb907247</td></tr>
<tr><td>Defold version</td><td>1.6.4</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"afe1580756ae4f418321bbc9ace810d4"'>afe1580756ae4f418321bbc9ace810d4</a></td></tr>
<tr><td>GPU</td><td>AMD Radeon RX 7900 XT</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 Compatibility Profile Context 23.9.1.230821</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by Jerakin** [comment]
If I rename the file that should be imported it works, if I then change the name back on the file I get an error. But after the error is gone I can continue to work.

**Comment by britzl** [comment]
```
internal.transaction$assert_type_compatible.invokeStatic.class java.lang.AssertionError: Assert failed: Attempting to connect 72057594037928273 (a editor.placeholder-resource/PlaceholderResourceNode) :completion-info to 72057594037928274 (a editor.code.script/ScriptNode) :module-completion-infos, but editor.placeholder-resource/PlaceholderResourceNode does not have an output or property named :completion-info
output-valtype
    at internal.transaction$assert_type_compatible.invokeStatic(transaction.clj:699)
    at internal.transaction$ctx_connect.invokeStatic(transaction.clj:713)
    at internal.transaction$fn.invokeStatic(transaction.clj:726)
    at internal.transaction$fn.invoke(transaction.clj:726)
    at clojure.lang.MultiFn.invoke(MultiFn.java:234)
    at internal.transaction$apply_tx$fn.invoke(transaction.clj:814)
    at internal.transaction$apply_tx.invokeStatic(transaction.clj:812)
    at internal.transaction$apply_tx.invoke(transaction.clj:804)
    at internal.transaction$apply_tx.invokeStatic(transaction.clj:811)
    at internal.transaction$apply_tx.invoke(transaction.clj:804)
    at internal.transaction$apply_tx.invokeStatic(transaction.clj:811)
    at internal.transaction$apply_tx.invoke(transaction.clj:804)
    at internal.transaction$invoke_setter.invokeStatic(transaction.clj:570)
    at internal.transaction$fn.invokeStatic(transaction.clj:623)
    at internal.transaction$fn.invoke(transaction.clj:611)
    at clojure.lang.MultiFn.invoke(MultiFn.java:234)
    at internal.transaction$apply_tx$fn.invoke(transaction.clj:814)
    at internal.transaction$apply_tx.invokeStatic(transaction.clj:812)
    at internal.transaction$apply_tx.invoke(transaction.clj:804)
    at internal.transaction$invoke_setter.invokeStatic(transaction.clj:570)
    at internal.transaction$fn.invokeStatic(transaction.clj:623)
    at internal.transaction$fn.invoke(transaction.clj:611)
    at clojure.lang.MultiFn.invoke(MultiFn.java:234)
    at internal.transaction$apply_tx$fn.invoke(transaction.clj:814)
    at internal.transaction$apply_tx.invokeStatic(transaction.clj:812)
    at internal.transaction$transact_STAR_.invokeStatic(transaction.clj:895)
    at dynamo.graph$transact.invokeStatic(graph.clj:169)
    at dynamo.graph$transact.invoke(graph.clj:146)
    at dynamo.graph$transact.invokeStatic(graph.clj:160)
    at editor.code.view$set_properties_BANG_.invokeStatic(view.clj:1175)
    at editor.code.view$insert_text_BANG_.invokeStatic(view.clj:2149)
    at editor.code.view$handle_key_typed_BANG_.invokeStatic(view.clj:2199)
    at editor.code.view$make_view_BANG_$reify.handle(view.clj:3596)
    at editor.code.view$wrap_disallow_diaeresis_after_tilde$reify.handle(view.clj:3323)
    at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:247)
    at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:232)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:189)
    at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
    at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
    at javafx.event.Event.fireEvent(Event.java:198)
    at javafx.scene.Scene.processKeyEvent(Scene.java:2197)
    at javafx.scene.Scene$ScenePeerListener.keyEvent(Scene.java:2718)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(GlassViewEventHandler.java:218)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(GlassViewEventHandler.java:150)
    at java.security.AccessController.doPrivileged(AccessController.java:399)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleKeyEvent$1(GlassViewEventHandler.java:250)
    at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:430)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleKeyEvent(GlassViewEventHandler.java:249)
    at com.sun.glass.ui.View.handleKeyEvent(View.java:542)
    at com.sun.glass.ui.View.notifyKey(View.java:966)
    at com.sun.glass.ui.win.WinApplication._runLoop(WinApplication.java)
    at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:184)
    at java.lang.Thread.run(Thread.java:833)
```

**Comment by matgis** [comment]
I was unable to reproduce this issue in a new project. Are you able to provide a minimal repro case?

**Comment by Jerakin** [comment]
Tried to follow the exact setup I did (was in a new project) but I couldn't reproduce it, nor does it happen in the project again. Feel free to close it.

When it was happening my gut feeling says it had something to do with the content of `main.game.manager` however I am fairly certain that there was only boilerplate in it, so most likely my gut was wrong.

Quite literally this.
```lua
local M = {}


local M.save()

end


local M.load()

end

local M.start()

end


return M
```

**Comment by matgis** [comment]
Ok, thanks! Please feel free to reopen the issue if you happen upon it again!

**Comment by vlaaad** [comment]
hmm, could it be you used an extension like "Lua" instead of "lua" when creating the file?

**Comment by vlaaad** [comment]
I see that the OS is Windows, and that the error hints that the editor somehow was able to resolve a resource `/main/game/manager.lua`, but treated it as unknown type, so, just a guess...
