### ISSUE TITLE
error

### ISSUE THREAD

**Issue by n123b** [defold/defold#8625]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2023-11-28T14:48:43.723551</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>834267d4fb458e1326ff7dc696015f5da5f41d27</td></tr>
<tr><td>Defold engine sha</td><td>4e156b7cf37a380122aada30dacbf2b590ead76b</td></tr>
<tr><td>Defold version</td><td>1.6.2</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"6525cdb89b3941b6bac38a19ce7e422f"'>6525cdb89b3941b6bac38a19ce7e422f</a></td></tr>
<tr><td>GPU</td><td>Intel(R) UHD Graphics 617</td></tr>
<tr><td>GPU Driver</td><td>2.1 INTEL-22.1.29</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>14.2.1</td></tr>
<table>

**Comment by AGulev** [comment]
Please provide info when it's happening
What did you do before it appears?

```
editor.resource_watch$make_directory_snapshot.invokeStatic.class java.lang.AssertionError: Assert failed: (and root (.isDirectory root))
    at editor.resource_watch$make_directory_snapshot.invokeStatic(resource_watch.clj:141)
    at editor.resource_watch$make_snapshot_info.invokeStatic(resource_watch.clj:184)
    at editor.workspace$make_snapshot_info.invokeStatic(workspace.clj:454)
    at editor.disk$start_reload_job_BANG_$fn.invoke(disk.clj:83)
    at clojure.core$binding_conveyor_fn$fn.invoke(core.clj:2030)
    at clojure.lang.AFn.call(AFn.java:18)
    at java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    at java.lang.Thread.run(Thread.java:833)
    ```

**Comment by n123b** [comment]
I think I clicked at to many things at once so its just started loading and
then the error came up.

**Comment by AGulev** [comment]
not enough info to be able to reproduce or fix the issue
