### ISSUE TITLE
Editor Java error: When opening a collection

### ISSUE THREAD

**Issue by FlexYourBrain** [defold/defold#8673]
### Expected behavior
Opening a collect without error's and displaying the collection view.

### Actual behavior
 In the editor when opening main,collection in this specific [project](https://github.com/JCash/stencilfade/archive/refs/heads/master.zip)  I am receiving a java error:
```
java.lang.NullPointerException: Cannot invoke "java.lang.Number.doubleValue()" because "x" is null
```
The scene view does not render.

### Steps to reproduce
 in the linked repro and on win10 load the project then open the main.collect located(/main/main.collection)
#### Repro: https://github.com/JCash/stencilfade/archive/refs/heads/master.zip

<hr/>
<table>
<tr><td>Build time</td><td>2024-03-12T10:26:40.890206</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>9ad2d7834a6adfaedcd902a8e6f9997ed5cbb507</td></tr>
<tr><td>Defold engine sha</td><td>bf4dc66ab5fbbafd4294d32c2797c08b630c0be5</td></tr>
<tr><td>Defold version</td><td>1.7.0</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"87dc4188b0f24fd8aa9deac600ff97c7"'>87dc4188b0f24fd8aa9deac600ff97c7</a></td></tr>
<tr><td>GPU</td><td>Intel(R) HD Graphics 630</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 - Build 31.0.101.2111</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

![screenfade_error](https://github.com/defold/defold/assets/28400489/7a1ad017-3ece-4854-90c4-afce73d7528d)

**Comment by britzl** [comment]
```
clojure.lang.RT.doubleCast.class java.lang.NullPointerException: Cannot invoke "java.lang.Number.doubleValue()" because "x" is null
    at clojure.lang.RT.doubleCast(RT.java:1351)
    at editor.material$constant__GT_val.invokeStatic(material.clj:176)
    at editor.material$fn$fn.invoke(material.clj:212)
    at clojure.core$map$fn$fn.invoke(core.clj:2742)
    at clojure.lang.ArrayChunk.reduce(ArrayChunk.java:63)
    at clojure.core.protocols$fn.invokeStatic(protocols.clj:136)
    at clojure.core.protocols$fn.invoke(protocols.clj:124)
    at clojure.core.protocols$fn$G__8094__8108.invoke(protocols.clj:19)
    at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:31)
    at clojure.core.protocols$fn.invokeStatic(protocols.clj:75)
    at clojure.core.protocols$fn.invoke(protocols.clj:75)
    at clojure.core.protocols$fn$G__8068__8086.invoke(protocols.clj:13)
    at clojure.core$transduce.invokeStatic(core.clj:6884)
    at clojure.core$into.invokeStatic(core.clj:6899)
    at editor.material$fn.invokeStatic(material.clj:208)
    at editor.material$fn.invoke(material.clj:193)
    at clojure.lang.AFn.applyToHelper(AFn.java:154)
    at clojure.lang.AFn.applyTo(AFn.java:144)
    at clojure.lang.AFunction$1.doInvoke(AFunction.java:31)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at clojure.lang.Var.invoke(Var.java:384)
    at editor.material$MaterialNode$behavior$shader$fn.invoke(material.clj:503)
    at internal.node$trace_expr.invokeStatic(node.clj:44)
    at editor.material$MaterialNode$behavior$shader.invokeStatic(material.clj:503)
    at editor.material$MaterialNode$behavior$shader.invoke(material.clj:503)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:295)
    at internal.node$pull_first_input_value.invokeStatic(node.clj:1192)
    at editor.model$MaterialBinding$behavior$material_scene_info$fn.invoke(model.clj:303)
    at internal.node$trace_expr.invokeStatic(node.clj:44)
    at editor.model$MaterialBinding$behavior$material_scene_info.invokeStatic(model.clj:303)
    at editor.model$MaterialBinding$behavior$material_scene_info.invoke(model.clj:303)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:295)
    at internal.node$pull_input_values$fn.invoke(node.clj:1208)
    at clojure.core$mapv$fn.invoke(core.clj:6912)
    at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
    at clojure.core$reduce.invokeStatic(core.clj:6827)
    at clojure.core$mapv.invokeStatic(core.clj:6903)
    at internal.node$pull_input_values.invokeStatic(node.clj:1209)
    at editor.model$ModelNode$behavior$scene$fn.invoke(model.clj:497)
    at internal.node$trace_expr.invokeStatic(node.clj:44)
    at editor.model$ModelNode$behavior$scene.invokeStatic(model.clj:497)
    at editor.model$ModelNode$behavior$scene.invoke(model.clj:497)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:295)
    at internal.node$pull_first_input_value.invokeStatic(node.clj:1192)
    at editor.game_object$EmbeddedComponent$behavior$scene$fn.invoke(game_object.clj:217)
    at internal.node$trace_expr.invokeStatic(node.clj:44)
    at editor.game_object$EmbeddedComponent$behavior$scene.invokeStatic(game_object.clj:217)
    at editor.game_object$EmbeddedComponent$behavior$scene.invoke(game_object.clj:217)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:295)
    at internal.node$pull_input_values$fn.invoke(node.clj:1208)
    at clojure.core$mapv$fn.invoke(core.clj:6912)
    at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
    at clojure.core$reduce.invokeStatic(core.clj:6827)
    at clojure.core$mapv.invokeStatic(core.clj:6903)
    at internal.node$pull_input_values.invokeStatic(node.clj:1209)
    at editor.game_object$GameObjectNode$behavior$scene$fn.invoke(game_object.clj:421)
    at internal.node$trace_expr.invokeStatic(node.clj:44)
    at editor.game_object$GameObjectNode$behavior$scene.invokeStatic(game_object.clj:421)
    at editor.game_object$GameObjectNode$behavior$scene.invoke(game_object.clj:421)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:295)
    at internal.node$pull_first_input_value.invokeStatic(node.clj:1192)
    at editor.collection$EmbeddedGOInstanceNode$behavior$scene$fn.invoke(collection.clj:229)
    at internal.node$trace_expr.invokeStatic(node.clj:44)
    at editor.collection$EmbeddedGOInstanceNode$behavior$scene.invokeStatic(collection.clj:229)
    at editor.collection$EmbeddedGOInstanceNode$behavior$scene.invoke(collection.clj:229)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:295)
    at internal.node$pull_input_values$fn.invoke(node.clj:1208)
    at clojure.core$mapv$fn.invoke(core.clj:6912)
    at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
    at clojure.core$reduce.invokeStatic(core.clj:6827)
    at clojure.core$mapv.invokeStatic(core.clj:6903)
    at internal.node$pull_input_values.invokeStatic(node.clj:1209)
    at editor.collection$CollectionNode$behavior$scene$fn.invoke(collection.clj:430)
    at internal.node$trace_expr.invokeStatic(node.clj:44)
    at editor.collection$CollectionNode$behavior$scene.invokeStatic(collection.clj:430)
    at editor.collection$CollectionNode$behavior$scene.invoke(collection.clj:430)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:295)
    at internal.node$pull_first_input_value.invokeStatic(node.clj:1192)
    at editor.scene$SceneView$behavior$scene_aabb$fn.invoke(scene.clj:798)
    at internal.node$trace_expr.invokeStatic(node.clj:44)
    at editor.scene$SceneView$behavior$scene_aabb.invokeStatic(scene.clj:798)
    at editor.scene$SceneView$behavior$scene_aabb.invoke(scene.clj:798)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:295)
    at internal.node$pull_first_input_value.invokeStatic(node.clj:1192)
    at editor.camera$CameraController$behavior$camera$fn.invoke(camera.clj:658)
    at internal.node$trace_expr.invokeStatic(node.clj:44)
    at editor.camera$CameraController$behavior$camera.invokeStatic(camera.clj:658)
    at editor.camera$CameraController$behavior$camera.invoke(camera.clj:658)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:295)
    at internal.node$pull_first_input_value.invokeStatic(node.clj:1192)
    at editor.scene$SceneView$behavior$scene_render_data$fn.invoke(scene.clj:798)
    at internal.node$trace_expr.invokeStatic(node.clj:44)
    at editor.scene$SceneView$behavior$scene_render_data.invokeStatic(scene.clj:798)
    at editor.scene$SceneView$behavior$scene_render_data.invoke(scene.clj:798)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:295)
    at editor.scene$SceneView$behavior$selected_aabb$fn.invoke(scene.clj:798)
    at internal.node$trace_expr.invokeStatic(node.clj:44)
    at editor.scene$SceneView$behavior$selected_aabb.invokeStatic(scene.clj:798)
    at editor.scene$SceneView$behavior$selected_aabb.invoke(scene.clj:798)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:295)
    at internal.node$node_value.invokeStatic(node.clj:454)
    at internal.system$node_value.invokeStatic(system.clj:354)
    at dynamo.graph$do_node_value.invokeStatic(graph.clj:830)
    at dynamo.graph$node_value.invokeStatic(graph.clj:833)
    at editor.scene$frame_selection.invokeStatic(scene.clj:986)
    at editor.scene$make_gl_pane_BANG_$fn$fn.invoke(scene.clj:1303)
    at editor.scene$make_gl_pane_BANG_$fn.invoke(scene.clj:1286)
    at editor.scene.proxy$com.defold.control.Region$ff19274a.layoutChildren
    at javafx.scene.Parent.layout(Parent.java:1208)
    at javafx.scene.Parent.layout(Parent.java:1215)
    at javafx.scene.Parent.layout(Parent.java:1215)
    at javafx.scene.Parent.layout(Parent.java:1215)
    at javafx.scene.Parent.layout(Parent.java:1215)
    at javafx.scene.Parent.layout(Parent.java:1215)
    at javafx.scene.Parent.layout(Parent.java:1215)
    at javafx.scene.Parent.layout(Parent.java:1215)
    at javafx.scene.Parent.layout(Parent.java:1215)
    at javafx.scene.Parent.layout(Parent.java:1215)
    at javafx.scene.Parent.layout(Parent.java:1215)
    at javafx.scene.Parent.layout(Parent.java:1215)
    at javafx.scene.Parent.layout(Parent.java:1215)
    at javafx.scene.Parent.layout(Parent.java:1215)
    at javafx.scene.Parent.layout(Parent.java:1215)
    at javafx.scene.Parent.layout(Parent.java:1215)
    at javafx.scene.Parent.layout(Parent.java:1215)
    at javafx.scene.Parent.layout(Parent.java:1215)
    at javafx.scene.Node.doLayoutPass(Node.java:2101)
    at javafx.scene.Node.doCSSLayoutSyncForSnapshot(Node.java:2108)
    at javafx.scene.Node$1.layoutNodeForPrinting(Node.java:563)
    at com.sun.javafx.scene.NodeHelper.layoutNodeForPrinting(NodeHelper.java:268)
    at editor.app_view$open_resource.invokeStatic(app_view.clj:2053)
    at editor.app_view$open_resource.invoke(app_view.clj:1991)
    at editor.app_view$open_resource.invokeStatic(app_view.clj:1993)
    at editor.app_view$fn$fnk65445_positional__65453.invoke(app_view.clj:2075)
    at editor.app_view$fn$fnk65445__65470$fn.invoke(app_view.clj:2071)
    at editor.app_view$fn$fnk65445__65470.invoke(app_view.clj:2071)
    at clojure.lang.AFn.applyToHelper(AFn.java:154)
    at clojure.lang.AFn.applyTo(AFn.java:144)
    at clojure.lang.AFunction$1.doInvoke(AFunction.java:31)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at editor.handler$invoke_fnk.invokeStatic(handler.clj:256)
    at editor.handler$run.invokeStatic(handler.clj:289)
    at editor.ui$execute_handler_ctx.invokeStatic(ui.clj:1192)
    at editor.ui$execute_command.invokeStatic(ui.clj:1200)
    at editor.ui$run_command.invokeStatic(ui.clj:1440)
    at editor.ui$bind_double_click_BANG_$reify.handle(ui.clj:1472)
    at com.sun.javafx.event.CompositeEventHandler$NormalEventFilterRecord.handleCapturingEvent(CompositeEventHandler.java:321)
    at com.sun.javafx.event.CompositeEventHandler.dispatchCapturingEvent(CompositeEventHandler.java:98)
    at com.sun.javafx.event.EventHandlerManager.dispatchCapturingEvent(EventHandlerManager.java:219)
    at com.sun.javafx.event.EventHandlerManager.dispatchCapturingEvent(EventHandlerManager.java:178)
    at com.sun.javafx.event.CompositeEventDispatcher.dispatchCapturingEvent(CompositeEventDispatcher.java:43)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:52)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
    at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
    at javafx.event.Event.fireEvent(Event.java:198)
    at javafx.scene.Scene$ClickGenerator.postProcess(Scene.java:3691)
    at javafx.scene.Scene$MouseHandler.process(Scene.java:3996)
    at javafx.scene.Scene.processMouseEvent(Scene.java:1893)
    at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2711)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:411)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:301)
    at java.security.AccessController.doPrivileged(AccessController.java:399)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:450)
    at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:430)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:449)
    at com.sun.glass.ui.View.handleMouseEvent(View.java:551)
    at com.sun.glass.ui.View.notifyMouse(View.java:937)
    at com.sun.glass.ui.win.WinApplication._runLoop(WinApplication.java)
    at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:184)
    at java.lang.Thread.run(Thread.java:833)

```

**Comment by vlaaad** [comment]
Hey, I can reproduce the issue. The workaround is to open the `screenfade.material` and add a value to the `offset` fragment constant (double click on the value cell).

**Comment by FlexYourBrain** [comment]
>The workaround is to open the `screenfade.material` and add a value to the `offset` fragment constant (double click on the value cell).

Can confirm the workaround does work.

**Comment by FlexYourBrain** [comment]
Tested in Defold 1.10.4 the bug is no lomger reproducible for me. The `screenfade.material` offset constant has values without editing needed. 

*`screenfade.material` - `offset` constant has no values but is populated in the editor with 0.0's so the error no longer occurs. Note the material constant itself is not populated with values automatically only after adding new values to each constant component in the editor or manually by text.

I consider this issue fixed and I am closing it.
