### ISSUE TITLE
What does this mean :(((((

### ISSUE THREAD

**Issue by Tarameow** [defold/defold#8745]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2023-09-05T11:49:42.911000</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>1a550a6444d2a2e20404087f4247f66394d5aab7</td></tr>
<tr><td>Defold engine sha</td><td>57b34efdf44a922acc6f21d285b207029b53927d</td></tr>
<tr><td>Defold version</td><td>1.5.0</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"b55242aba30641cdaae2f36e7be46ff8"'>b55242aba30641cdaae2f36e7be46ff8</a></td></tr>
<tr><td>GPU</td><td>Apple M1</td></tr>
<tr><td>GPU Driver</td><td>2.1 Metal - 88</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>aarch64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>14.1.1</td></tr>
<table>

**Comment by AGulev** [comment]
>java.io.FileInputStream.open0.class java.io.FileNotFoundException: /var/folders/bg/7dqzdc85729dppcpzpw0ynmr0000gn/T/defold-unpack-1a550a6444d2a2e20404087f4247f66394d5aab7192491995143271768/builtins/builtins.zip (No such file or directory)
    at java.io.FileInputStream.open0(FileInputStream.java)
    at java.io.FileInputStream.open(FileInputStream.java:216)
    at java.io.FileInputStream.<init>(FileInputStream.java:157)
    at clojure.java.io$fn.invokeStatic(io.clj:229)
    at clojure.java.io$fn.invoke(io.clj:229)
    at clojure.java.io$fn$G__11372__11386.invoke(io.clj:69)
    at clojure.java.io$input_stream.invokeStatic(io.clj:136)
    at clojure.java.io$input_stream.doInvoke(io.clj:121)
    at clojure.lang.RestFn.invoke(RestFn.java:410)
    at editor.resource$load_zip.invokeStatic(resource.clj:329)
    at editor.resource$load_zip_resources.invokeStatic(resource.clj:349)
    at editor.resource$load_zip_resources.invoke(resource.clj:349)
    at editor.resource$load_zip_resources.invokeStatic(resource.clj:351)
    at editor.resource_watch$make_builtins_snapshot.invokeStatic(resource_watch.clj:93)
    at editor.resource_watch$make_snapshot_info.invokeStatic(resource_watch.clj:184)
    at editor.workspace$make_snapshot_info.invokeStatic(workspace.clj:454)
    at editor.disk$start_reload_job_BANG_$fn.invoke(disk.clj:83)
    at clojure.core$binding_conveyor_fn$fn.invoke(core.clj:2030)
    at clojure.lang.AFn.call(AFn.java:18)
    at java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    at java.lang.Thread.run(Thread.java:833)

**Comment by vlaaad** [comment]
We used to unpack editor files into temporary directory, which caused issues on mac, since it clears the temporary directories after a while. We fixed this issue awhile ago, so all you need to do to fix it is update to the newer version of Defold :)
