### ISSUE TITLE
Can't open `readme.md`

### ISSUE THREAD

**Issue by alexis-tg** [defold/defold#8746]
### Expected behaviour 
 readme.md открывается нормально.

### Actual behaviour
при попытке открыть readme.md выпадает баг. 
вчера обновился на новую версию дефолда. но вроде работало все.

### Steps to reproduce
запустить проект. даблклик по  readme.md 

<hr/>

<table>
<tr><td>Build time</td><td>2024-03-27T13:04:35.655564</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>d0338d13ad7c5ccd2be3208788805ef5010bf00b</td></tr>
<tr><td>Defold engine sha</td><td>bf4dc66ab5fbbafd4294d32c2797c08b630c0be5</td></tr>
<tr><td>Defold version</td><td>1.7.0</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"54109b2de9d44316ae65e9e0f6eef6bd"'>54109b2de9d44316ae65e9e0f6eef6bd</a></td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce GTX 1650/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 546.33</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by AGulev** [comment]
```
java.lang.ClassLoader.loadLibrary.class java.lang.UnsatisfiedLinkError: no jfxwebkit in java.library.path: C:\Users\alexey_chestnykh\Desktop\Defold\packages\jdk-17.0.5+8\bin;C:\WINDOWS\Sun\Java\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\Program Files (x86)\SCE\ORBIS\Tools\Publishing Tools\bin;D:\Oculus\Support\oculus-runtime;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\SCE\Prospero\Tools\Publishing Tools\bin;C:\Program Files (x86)\SCE\ORBIS\Tools\Target Manager Server\bin;C:\Program Files (x86)\SCE\ORBIS SDKs\5.000\host_tools\bin;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Git\cmd;C:\Program Files\dotnet\;C:\Program Files\TortoiseSVN\bin;C:\Program Files (x86)\Gpg4win\..\GnuPG\bin;C:\Users\alexey_chestnykh\AppData\Local\Microsoft\WindowsApps;C:\Users\alexey_chestnykh\AppData\Local\GitHubDesktop\bin;.
    at java.lang.ClassLoader.loadLibrary(ClassLoader.java:2429)
    at java.lang.Runtime.loadLibrary0(Runtime.java:818)
    at java.lang.System.loadLibrary(System.java:1989)
    at com.sun.glass.utils.NativeLibLoader.loadLibraryInternal(NativeLibLoader.java:170)
    at com.sun.glass.utils.NativeLibLoader.loadLibrary(NativeLibLoader.java:58)
    at com.sun.webkit.WebPage.lambda$static$1(WebPage.java:139)
    at java.security.AccessController.doPrivileged(AccessController.java:318)
    at com.sun.webkit.WebPage.<clinit>(WebPage.java:138)
    at javafx.scene.web.WebEngine.<init>(WebEngine.java:854)
    at javafx.scene.web.WebEngine.<init>(WebEngine.java:839)
    at javafx.scene.web.WebView.<init>(WebView.java:275)
    at editor.html_view$make_web_view.invokeStatic(html_view.clj:224)
    at editor.html_view$make_view.invokeStatic(html_view.clj:272)
    at editor.html_view$make_view.invoke(html_view.clj:270)
    at editor.app_view$make_tab_BANG_.invokeStatic(app_view.clj:1954)
    at editor.app_view$open_resource.invokeStatic(app_view.clj:2041)
    at editor.app_view$open_resource.invoke(app_view.clj:1991)
    at editor.app_view$open_resource.invokeStatic(app_view.clj:1993)
    at editor.app_view$fn$fnk65508_positional__65516.invoke(app_view.clj:2075)
    at editor.app_view$fn$fnk65508__65533$fn.invoke(app_view.clj:2071)
    at editor.app_view$fn$fnk65508__65533.invoke(app_view.clj:2071)
    at clojure.lang.AFn.applyToHelper(AFn.java:154)
    at clojure.lang.AFn.applyTo(AFn.java:144)
    at clojure.lang.AFunction$1.doInvoke(AFunction.java:31)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at editor.handler$invoke_fnk.invokeStatic(handler.clj:256)
    at editor.handler$run.invokeStatic(handler.clj:289)
    at editor.ui$execute_handler_ctx.invokeStatic(ui.clj:1192)
    at editor.ui$execute_command.invokeStatic(ui.clj:1200)
    at editor.ui$run_command.invokeStatic(ui.clj:1440)
    at editor.ui$bind_double_click_BANG_$reify.handle(ui.clj:1472)
    at com.sun.javafx.event.CompositeEventHandler$NormalEventFilterRecord.handleCapturingEvent(CompositeEventHandler.java:321)
    at com.sun.javafx.event.CompositeEventHandler.dispatchCapturingEvent(CompositeEventHandler.java:98)
    at com.sun.javafx.event.EventHandlerManager.dispatchCapturingEvent(EventHandlerManager.java:219)
    at com.sun.javafx.event.EventHandlerManager.dispatchCapturingEvent(EventHandlerManager.java:178)
    at com.sun.javafx.event.CompositeEventDispatcher.dispatchCapturingEvent(CompositeEventDispatcher.java:43)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:52)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
    at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
    at javafx.event.Event.fireEvent(Event.java:198)
    at javafx.scene.Scene$ClickGenerator.postProcess(Scene.java:3691)
    at javafx.scene.Scene$MouseHandler.process(Scene.java:3996)
    at javafx.scene.Scene.processMouseEvent(Scene.java:1893)
    at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2711)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:411)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:301)
    at java.security.AccessController.doPrivileged(AccessController.java:399)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:450)
    at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:430)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:449)
    at com.sun.glass.ui.View.handleMouseEvent(View.java:551)
    at com.sun.glass.ui.View.notifyMouse(View.java:937)
    at com.sun.glass.ui.win.WinApplication._runLoop(WinApplication.java)
    at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:184)
    at java.lang.Thread.run(Thread.java:833)
    ```

**Comment by vlaaad** [comment]
I can't reproduce the issue on this Defold version. Does it happen every time? Does it happen only with a particular game?

**Comment by AGulev** [comment]
Could you pls re-test using Defold 1.9.6?
