### ISSUE TITLE
Error when trying to remove material from model

### ISSUE THREAD

**Issue by joseneto** [defold/defold#8777]
### Steps to reproduce

1 - Add a material
2 - Click in the box and press enter to remove

<hr/>

<table>
<tr><td>Build time</td><td>2024-03-27T13:13:27.496662</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>d0338d13ad7c5ccd2be3208788805ef5010bf00b</td></tr>
<tr><td>Defold engine sha</td><td>bf4dc66ab5fbbafd4294d32c2797c08b630c0be5</td></tr>
<tr><td>Defold version</td><td>1.7.0</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"6230bd5431dc433fb6bf6aad19f3c6d3"'>6230bd5431dc433fb6bf6aad19f3c6d3</a></td></tr>
<tr><td>GPU</td><td>Apple M1 Pro</td></tr>
<tr><td>GPU Driver</td><td>2.1 Metal - 83.1</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>aarch64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>13.6.4</td></tr>
<table>

**Comment by britzl** [comment]
```
editor.model_scene$augment_mesh_scene.invokeStatic.class java.lang.AssertionError: Assert failed: (shader/shader-lifecycle? shader)
    at editor.model_scene$augment_mesh_scene.invokeStatic(model_scene.clj:378)
    at editor.model_scene$augment_model_scene$fn.invoke(model_scene.clj:400)
    at clojure.core$mapv$fn.invoke(core.clj:6912)
    at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
    at clojure.core$reduce.invokeStatic(core.clj:6827)
    at clojure.core$mapv.invokeStatic(core.clj:6903)
    at editor.model_scene$augment_model_scene.invokeStatic(model_scene.clj:398)
    at editor.model_scene$augment_scene$fn.invoke(model_scene.clj:411)
    at clojure.core$mapv$fn.invoke(core.clj:6912)
    at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
    at clojure.core$reduce.invokeStatic(core.clj:6827)
    at clojure.core$mapv.invokeStatic(core.clj:6903)
    at editor.model_scene$augment_scene.invokeStatic(model_scene.clj:407)
    at editor.model$fn.invokeStatic(model.clj:222)
    at editor.model$fn.invoke(model.clj:221)
    at clojure.lang.AFn.applyToHelper(AFn.java:154)
    at clojure.lang.AFn.applyTo(AFn.java:144)
    at clojure.lang.AFunction$1.doInvoke(AFunction.java:31)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at clojure.lang.Var.invoke(Var.java:384)
    at editor.model$ModelNode$behavior$scene$fn.invoke(model.clj:457)
    at internal.node$trace_expr.invokeStatic(node.clj:44)
    at editor.model$ModelNode$behavior$scene.invokeStatic(model.clj:457)
    at editor.model$ModelNode$behavior$scene.invoke(model.clj:457)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:295)
    at internal.node$pull_first_input_value.invokeStatic(node.clj:1204)
    at editor.game_object$EmbeddedComponent$behavior$scene$fn.invoke(game_object.clj:217)
    at internal.node$trace_expr.invokeStatic(node.clj:44)
    at editor.game_object$EmbeddedComponent$behavior$scene.invokeStatic(game_object.clj:217)
    at editor.game_object$EmbeddedComponent$behavior$scene.invoke(game_object.clj:217)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:295)
    at internal.node$pull_input_values$fn.invoke(node.clj:1220)
    at clojure.core$mapv$fn.invoke(core.clj:6912)
    at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
    at clojure.core$reduce.invokeStatic(core.clj:6827)
    at clojure.core$mapv.invokeStatic(core.clj:6903)
    at internal.node$pull_input_values.invokeStatic(node.clj:1221)
    at editor.game_object$GameObjectNode$behavior$scene$fn.invoke(game_object.clj:421)
    at internal.node$trace_expr.invokeStatic(node.clj:44)
    at editor.game_object$GameObjectNode$behavior$scene.invokeStatic(game_object.clj:421)
    at editor.game_object$GameObjectNode$behavior$scene.invoke(game_object.clj:421)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:295)
    at internal.node$pull_first_input_value.invokeStatic(node.clj:1204)
    at editor.collection$EmbeddedGOInstanceNode$behavior$scene$fn.invoke(collection.clj:229)
    at internal.node$trace_expr.invokeStatic(node.clj:44)
    at editor.collection$EmbeddedGOInstanceNode$behavior$scene.invokeStatic(collection.clj:229)
    at editor.collection$EmbeddedGOInstanceNode$behavior$scene.invoke(collection.clj:229)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:295)
    at internal.node$pull_input_values$fn.invoke(node.clj:1220)
    at clojure.core$mapv$fn.invoke(core.clj:6912)
    at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
    at clojure.core$reduce.invokeStatic(core.clj:6827)
    at clojure.core$mapv.invokeStatic(core.clj:6903)
    at internal.node$pull_input_values.invokeStatic(node.clj:1221)
    at editor.collection$CollectionNode$behavior$scene$fn.invoke(collection.clj:430)
    at internal.node$trace_expr.invokeStatic(node.clj:44)
    at editor.collection$CollectionNode$behavior$scene.invokeStatic(collection.clj:430)
    at editor.collection$CollectionNode$behavior$scene.invoke(collection.clj:430)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:295)
    at internal.node$pull_first_input_value.invokeStatic(node.clj:1204)
    at editor.app_view$AppView$behavior$active_scene$fn.invoke(app_view.clj:330)
    at internal.node$trace_expr.invokeStatic(node.clj:44)
    at editor.app_view$AppView$behavior$active_scene.invokeStatic(app_view.clj:330)
    at editor.app_view$AppView$behavior$active_scene.invoke(app_view.clj:330)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:295)
    at internal.node$pull_first_input_value.invokeStatic(node.clj:1204)
    at editor.scene_visibility$SceneVisibilityNode$behavior$outline_name_paths_by_selection_state$fn.invoke(scene_visibility.clj:117)
    at internal.node$trace_expr.invokeStatic(node.clj:44)
    at editor.scene_visibility$SceneVisibilityNode$behavior$outline_name_paths_by_selection_state.invokeStatic(scene_visibility.clj:117)
    at editor.scene_visibility$SceneVisibilityNode$behavior$outline_name_paths_by_selection_state.invoke(scene_visibility.clj:117)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:295)
    at editor.scene_visibility$SceneVisibilityNode$behavior$selected_outline_name_paths$fn.invoke(scene_visibility.clj:117)
    at internal.node$trace_expr.invokeStatic(node.clj:44)
    at editor.scene_visibility$SceneVisibilityNode$behavior$selected_outline_name_paths.invokeStatic(scene_visibility.clj:117)
    at editor.scene_visibility$SceneVisibilityNode$behavior$selected_outline_name_paths.invoke(scene_visibility.clj:117)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:295)
    at editor.scene_visibility$SceneVisibilityNode$behavior$selected_hideable_outline_name_paths$fn.invoke(scene_visibility.clj:117)
    at internal.node$trace_expr.invokeStatic(node.clj:44)
    at editor.scene_visibility$SceneVisibilityNode$behavior$selected_hideable_outline_name_paths.invokeStatic(scene_visibility.clj:117)
    at editor.scene_visibility$SceneVisibilityNode$behavior$selected_hideable_outline_name_paths.invoke(scene_visibility.clj:117)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:295)
    at internal.node$node_value.invokeStatic(node.clj:454)
    at internal.system$node_value.invokeStatic(system.clj:354)
    at dynamo.graph$do_node_value.invokeStatic(graph.clj:830)
    at dynamo.graph$node_value.invokeStatic(graph.clj:833)
    at editor.scene_visibility$fn$fnk57123_positional__57127.invoke(scene_visibility.clj:243)
    at editor.scene_visibility$fn$fnk57123__57139$fn.invoke(scene_visibility.clj:243)
    at editor.scene_visibility$fn$fnk57123__57139.invoke(scene_visibility.clj:243)
    at clojure.lang.AFn.applyToHelper(AFn.java:154)
    at clojure.lang.AFn.applyTo(AFn.java:144)
    at clojure.lang.AFunction$1.doInvoke(AFunction.java:31)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at editor.handler$invoke_fnk.invokeStatic(handler.clj:256)
    at editor.handler$enabled_QMARK_.invokeStatic(handler.clj:296)
    at editor.ui$make_menu_item.invokeStatic(ui.clj:1337)
    at editor.ui$make_menu_items$fn.invoke(ui.clj:1353)
    at clojure.core$keep$fn$fn.invoke(core.clj:7325)
    at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
    at clojure.core$transduce.invokeStatic(core.clj:6883)
    at clojure.core$into.invokeStatic(core.clj:6899)
    at editor.ui$make_menu_items.invokeStatic(ui.clj:1351)
    at editor.ui$make_menu_items.invoke(ui.clj:1351)
    at editor.ui$make_menu_item.invokeStatic(ui.clj:1329)
    at editor.ui$make_menu_items$fn.invoke(ui.clj:1353)
    at clojure.core$keep$fn$fn.invoke(core.clj:7325)
    at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
    at clojure.core$transduce.invokeStatic(core.clj:6883)
    at clojure.core$into.invokeStatic(core.clj:6899)
    at editor.ui$make_menu_items.invokeStatic(ui.clj:1351)
    at editor.ui$refresh_menubar_BANG_.invokeStatic(ui.clj:1571)
    at editor.ui$refresh_menus_BANG_.invokeStatic(ui.clj:1844)
    at editor.ui$refresh.invokeStatic(ui.clj:1865)
    at editor.app_view$refresh_menus_and_toolbars_BANG_.invokeStatic(app_view.clj:1801)
    at editor.app_view$make_app_view$fn.invoke(app_view.clj:1925)
    at editor.ui$__GT_timer$fn$fn.invoke(ui.clj:1968)
    at clojure.lang.AFn.run(AFn.java:22)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:456)
    at java.security.AccessController.doPrivileged(AccessController.java:399)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:455)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
```

**Comment by matgis** [comment]
Duplicate of #9261?

**Comment by AGulev** [comment]
I can't reproduce it.
Also: 


## Summary

Removing a material assignment from a model in the editor could trigger an assertion in `editor.model_scene/augment-mesh-scene`, where the scene code expected a fully formed shader-backed material scene info. The issue report reproduces this by clearing the material field and pressing Enter, and the linked stack trace shows the crash at `editor/src/clj/editor/model_scene.clj` during shader validation.

## Status

Possibly outdated/fixed

## Evidence

- The issue is still open on GitHub, but a later commit in this repository appears to address the same failure mode: `045d37f38aff91d15f6b462114cf95d900be17c5` (`Editor: Don’t apply Model material assignments unless fully-formed (#10610)`).
- Current code in `editor/src/clj/editor/model_scene.clj:648` introduces `make-material-name->material-scene-info`, which filters out material scene infos unless both `:shader` and `:vertex-space` are present before they can be applied to the scene.
- Current code in `editor/src/clj/editor/model.clj:455` now routes model material scene lookup through that filtering helper instead of directly using raw `material-scene-infos`.
- The original crash comment on issue #8777 shows `Assert failed: (shader/shader-lifecycle? shader)` in `editor.model_scene$augment_mesh_scene`, which is exactly the kind of incomplete material scene info the current filtering code avoids.
- A later comment on the issue says `Duplicate of #9261?`, suggesting maintainers also considered it part of a broader editor-model editing problem rather than a distinct still-unfixed bug.

## Why this looks already fixed

The current implementation explicitly prevents partially constructed model material assignments from being applied in scene augmentation, which directly matches the assertion seen in #8777. Since the reported failure depended on `augment-mesh-scene` receiving a material scene info without a valid shader, and the present code now rejects such entries before augmentation, the bug appears likely fixed in current `dev` even though the GitHub issue remains open.
