### ISSUE TITLE
Error alert when switching back to Defold editor

### ISSUE THREAD

**Issue by andrew-flick** [defold/defold#8806]
### Expected behaviour
Not throwing up an error alert when switching windows.

### Actual behaviour

ERROR: java.lang.ArrayIndexOutOfBoundsException: Index 16 out of bounds for length 16

shown after building, running game and command tabbing back to Defold editor.

### Steps to reproduce

Switch to the Defold editor after doing anything and this error now comes up.

I recently started using a sym link to some lua modules but don't think this is related.

<hr/>

<table>
<tr><td>Build time</td><td>2024-04-09T14:46:02.417652</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>ecdec42bff4ffde46635964bd0b16561b9498216</td></tr>
<tr><td>Defold engine sha</td><td>bf4dc66ab5fbbafd4294d32c2797c08b630c0be5</td></tr>
<tr><td>Defold version</td><td>1.7.0</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"7c8d6cf05d4f4bfab559323aa73fbf75"'>7c8d6cf05d4f4bfab559323aa73fbf75</a></td></tr>
<tr><td>GPU</td><td>Apple M1 Max</td></tr>
<tr><td>GPU Driver</td><td>2.1 Metal - 88</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>aarch64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>14.4.1</td></tr>
<table>

**Comment by AGulev** [comment]
```
org.eclipse.jgit.dircache.DirCacheTree.namecmp.class java.lang.ArrayIndexOutOfBoundsException: Index 16 out of bounds for length 16
    at org.eclipse.jgit.dircache.DirCacheTree.namecmp(DirCacheTree.java:545)
    at org.eclipse.jgit.dircache.DirCacheTree.validate(DirCacheTree.java:454)
    at org.eclipse.jgit.dircache.DirCacheTree.validate(DirCacheTree.java:482)
    at org.eclipse.jgit.dircache.DirCacheTree.validate(DirCacheTree.java:482)
    at org.eclipse.jgit.dircache.DirCache.getCacheTree(DirCache.java:946)
    at org.eclipse.jgit.dircache.DirCacheIterator.<init>(DirCacheIterator.java:118)
    at org.eclipse.jgit.lib.IndexDiff.diff(IndexDiff.java:414)
    at org.eclipse.jgit.lib.IndexDiff.diff(IndexDiff.java:377)
    at org.eclipse.jgit.api.StatusCommand.call(StatusCommand.java:148)
    at editor.git$status.invokeStatic(git.clj:197)
    at editor.git$unified_status.invokeStatic(git.clj:229)
    at editor.changes_view$refresh_BANG_$fn.invoke(changes_view.clj:57)
    at clojure.core$binding_conveyor_fn$fn.invoke(core.clj:2030)
    at clojure.lang.AFn.call(AFn.java:18)
    at java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    at java.lang.Thread.run(Thread.java:833)

**Comment by AGulev** [comment]
this bug fixed in defold 1.12.4
