### ISSUE TITLE
Error creating new mobile game

### ISSUE THREAD

**Issue by kd8plc** [defold/defold#8814]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2024-04-09T14:42:42.138847</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>ecdec42bff4ffde46635964bd0b16561b9498216</td></tr>
<tr><td>Defold engine sha</td><td>bf4dc66ab5fbbafd4294d32c2797c08b630c0be5</td></tr>
<tr><td>Defold version</td><td>1.7.0</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"5f6b788ce8a94240bed6db166895b0bb"'>5f6b788ce8a94240bed6db166895b0bb</a></td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce RTX 2070 with Max-Q Design/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 546.26</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 11</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by AGulev** [comment]
```
java.io.FileOutputStream.open0.class java.io.FileNotFoundException: C:\Users\Bryant\Adventure: A Love Story\.gitattributes (The filename, directory name, or volume label syntax is incorrect)
    at java.io.FileOutputStream.open0(FileOutputStream.java)
    at java.io.FileOutputStream.open(FileOutputStream.java:293)
    at java.io.FileOutputStream.<init>(FileOutputStream.java:235)
    at java.io.FileOutputStream.<init>(FileOutputStream.java:184)
    at editor.welcome$expand_proj_zip_BANG_.invokeStatic(welcome.clj:250)
    at editor.welcome$show_welcome_dialog_BANG_$download_template_BANG___107047$fn.invoke(welcome.clj:647)
    at clojure.core$binding_conveyor_fn$fn.invoke(core.clj:2030)
    at clojure.lang.AFn.call(AFn.java:18)
    at java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    at java.lang.Thread.run(Thread.java:833)

**Comment by matgis** [comment]
I think there might be an issue with unexpected characters in the project directory path.

Could you try renaming the project directory so that it does not contain spaces or the color character? I think the color character, specifically, can be troublesome on Windows. It is listed as a reserved character here: https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file#naming-conventions
