### ISSUE TITLE
Pasting lines longer than 2210 characters into a script causes a crash

### ISSUE THREAD

**Issue by mattpwest** [defold/defold#8815]
### Expected behaviour
Pasting code from another project should work smoothly.

### Actual behaviour
It crashes with `java.lang.StackOverflowError: Unknown` for one of the 8 files I am importing from an old PICO-8 project as reference.

### Steps to reproduce
I narrowed it down to the `spell_data=` line in the snippet below and determined the precise length at which it breaks to be > 2210 characters:
```
-- this crashes the editor
spell_data=split("disbelieve,100,4,9,0,1,0,0,1,0,dispels illusions.,-10;lightning,70,5,4,6,1,0,2,200,0,call the the thunder!,5;fireball,70,3,4,6,1,0,2,100,0,crisp an enemy.,5;justice,40,7,6,9,3,0,5,299,0,kills up to 3 enemies.,15;revenge,40,1,6,9,3,0,5,199,0,kills up to 3 enemies.,15;magic missiles,80,4,4,6,1,0,2,99,0,deadly balls of energy.,15;mayhem,80,3,0,0,1,1,1,102,0,chaos through mayhem!,6;cursed dagger,80,3,0,0,1,1,1,105,0,a double-edged dagger...,9;zombie,70,3,1,0,1,0,2,104,1,it wants brains!,9;bat,70,3,1,0,1,0,2,106,1,it flaps in the night...,11;shadow form,60,3,0,0,1,1,3,109,0,become darkness.,9;skeleton,60,3,1,0,1,0,3,107,1,old bones. old javelins...,17;dark wood,50,2,5,0,5,0,4,108,0,these trees want blood!,7;ghost,50,2,1,0,1,0,4,111,1,it's not friendly!,18;dark tower,40,1,1,0,1,0,5,113,0,safe haven (with library).,18;wraith,40,1,1,0,1,0,5,114,1,a powerful ghost.,20;vampire,30,1,1,0,1,0,6,115,1,a blood-hungry vampire.,25;gooey blob,30,1,5,0,1,0,6,112,0,danger!!! do not use!,27;rats,80,4,1,0,2,0,1,101,1,bringers of plague...,6;magic shield,80,4,0,0,1,1,1,7,0,it protects you from harm.,7;raven,80,4,1,0,1,0,1,8,1,messengers of the gods.,9;wild dog,70,4,1,0,1,0,2,2,1,best in a pack.,5;wall,70,4,4,0,4,0,2,4,0,a sturdy obstacle.,5;horse,70,4,1,0,1,0,2,9,1,an amazing mount!,11;catapult,60,4,1,0,1,0,3,10,1,a powerful siege engine.,22;warrior,60,4,1,0,1,0,3,3,1,strong. dumb. useful.,7;lion,60,4,1,0,1,0,3,203,1,the king of the jungle.,7;magic sword,60,4,0,0,1,1,3,10,0,it's extremely sharp!,10;magic bow,60,4,0,0,1,1,3,13,0,kill from afar.,16;castle,60,4,1,0,1,0,3,12,0,the best defence...,16;steel gorilla,50,4,1,0,1,0,4,6,1,a fearsome magic golem.,15;serpent,50,4,1,0,1,0,4,201,1,very poisonous!,8;order staff,80,5,0,0,1,1,1,201,0,symbol of an order mage.,10;law,80,5,0,0,1,1,1,202,0,order through law!,6;eagle,70,5,1,0,1,0,2,204,1,freedom soars!,12;elf,70,5,1,0,1,0,2,205,1,protectors of the forest.,16;angel wings,60,5,0,0,1,1,3,11,0,ride the winds!,12;pegasus,60,6,1,0,1,0,3,207,1,ride like the wind!,19;paladin,50,6,1,0,1,0,4,116,1,a holy knight.,13;magic forest,50,6,6,0,6,0,4,206,0,wise old trees.,15;light tower,40,7,1,0,1,0,5,12,0,a bastion of light!,17;unicorn,40,7,1,0,1,0,5,208,1,guardian of the forest.,20;holy flames,30,7,5,0,1,0,6,215,0,the all-consuming fire!,9;dragon,30,7,1,0,1,0,6,209,1,a fire-breathing dragon.,36",";")

-- This is OK
spell_data=split("disbelieve,100,4,9,0,1,0,0,1,0,dispels illusions.,-10;lightning,70,5,4,6,1,0,2,200,0,call the the thunder!,5;fireball,70,3,4,6,1,0,2,100,0,crisp an enemy.,5;justice,40,7,6,9,3,0,5,299,0,kills up to 3 enemies.,15;revenge,40,1,6,9,3,0,5,199,0,kills up to 3 enemies.,15;magic missiles,80,4,4,6,1,0,2,99,0,deadly balls of energy.,15;mayhem,80,3,0,0,1,1,1,102,0,chaos through mayhem!,6;cursed dagger,80,3,0,0,1,1,1,105,0,a double-edged dagger...,9;zombie,70,3,1,0,1,0,2,104,1,it wants brains!,9;bat,70,3,1,0,1,0,2,106,1,it flaps in the night...,11;shadow form,60,3,0,0,1,1,3,109,0,become darkness.,9;skeleton,60,3,1,0,1,0,3,107,1,old bones. old javelins...,17;dark wood,50,2,5,0,5,0,4,108,0,these trees want blood!,7;ghost,50,2,1,0,1,0,4,111,1,it's not friendly!,18;dark tower,40,1,1,0,1,0,5,113,0,safe haven (with library).,18;wraith,40,1,1,0,1,0,5,114,1,a powerful ghost.,20;vampire,30,1,1,0,1,0,6,115,1,a blood-hungry vampire.,25;gooey blob,30,1,5,0,1,0,6,112,0,danger!!! do not use!,27;rats,80,4,1,0,2,0,1,101,1,bringers of plague...,6;magic shield,80,4,0,0,1,1,1,7,0,it protects you from harm.,7;raven,80,4,1,0,1,0,1,8,1,messengers of the gods.,9;wild dog,70,4,1,0,1,0,2,2,1,best in a pack.,5;wall,70,4,4,0,4,0,2,4,0,a sturdy obstacle.,5;horse,70,4,1,0,1,0,2,9,1,an amazing mount!,11;catapult,60,4,1,0,1,0,3,10,1,a powerful siege engine.,22;warrior,60,4,1,0,1,0,3,3,1,strong. dumb. useful.,7;lion,60,4,1,0,1,0,3,203,1,the king of the jungle.,7;magic sword,60,4,0,0,1,1,3,10,0,it's extremely sharp!,10;magic bow,60,4,0,0,1,1,3,13,0,kill from afar.,16;castle,60,4,1,0,1,0,3,12,0,the best defence...,16;steel gorilla,50,4,1,0,1,0,4,6,1,a fearsome magic golem.,15;serpent,50,4,1,0,1,0,4,201,1,very poisonous!,8;order staff,80,5,0,0,1,1,1,201,0,symbol of an order mage.,10;law,80,5,0,0,1,1,1,202,0,order through law!,6;eagle,70,5,1,0,1,0,2,204,1,freedom soars!,12;elf,70,5,1,0,1,0,2,205,1,protectors of the forest.,16;angel wings,60,5,0,0,1,1,3,11,0,ride the winds!,12;pegasus,60,6,1,0,1,0,3,207,1,ride like the wind!,19;paladin,50,6,1,0,1,0,4,116,1,a holy knight.,13;magic forest,50,6,6,0,6,0,4,206,0,wise old trees.,15;light tower,40,7,1,0,1,0,5,12,0,a bastion of light!,17;unicorn,40,7,1,0,1,0,
```

<hr/>

<table>
<tr><td>Build time</td><td>2024-04-09T14:42:42.138847</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>ecdec42bff4ffde46635964bd0b16561b9498216</td></tr>
<tr><td>Defold engine sha</td><td>bf4dc66ab5fbbafd4294d32c2797c08b630c0be5</td></tr>
<tr><td>Defold version</td><td>1.7.0</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"099eac2b49fb4b408c921ab482d6dcfa"'>099eac2b49fb4b408c921ab482d6dcfa</a></td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce RTX 2070/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 552.22</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by AGulev** [comment]
```
java.util.regex.Pattern$GroupTail.match.class java.lang.StackOverflowError: null
    at java.util.regex.Pattern$GroupTail.match(Pattern.java:4820)
    at java.util.regex.Pattern$BranchConn.match(Pattern.java:4698)
    at java.util.regex.Pattern$CharProperty.match(Pattern.java:3931)
    at java.util.regex.Pattern$Branch.match(Pattern.java:4734)
    at java.util.regex.Pattern$GroupHead.match(Pattern.java:4789)
    at java.util.regex.Pattern$Loop.match(Pattern.java:4898)
    at java.util.regex.Pattern$GroupTail.match(Pattern.java:4820)
    at java.util.regex.Pattern$BranchConn.match(Pattern.java:4698)
    at java.util.regex.Pattern$CharProperty.match(Pattern.java:3931)
    at java.util.regex.Pattern$Branch.match(Pattern.java:4734)
    at java.util.regex.Pattern$GroupHead.match(Pattern.java:4789)
    at java.util.regex.Pattern$Loop.match(Pattern.java:4898)
    at java.util.regex.Pattern$GroupTail.match(Pattern.java:4820)
    at java.util.regex.Pattern$BranchConn.match(Pattern.java:4698)
    at java.util.regex.Pattern$CharProperty.match(Pattern.java:3931)
    at java.util.regex.Pattern$Branch.match(Pattern.java:4734)
    at java.util.regex.Pattern$GroupHead.match(Pattern.java:4789)
    at java.util.regex.Pattern$Loop.match(Pattern.java:4898)
    at java.util.regex.Pattern$GroupTail.match(Pattern.java:4820)
    at java.util.regex.Pattern$BranchConn.match(Pattern.java:4698)
    at java.util.regex.Pattern$CharProperty.match(Pattern.java:3931)
    at java.util.regex.Pattern$Branch.match(Pattern.java:4734)
    at java.util.regex.Pattern$GroupHead.match(Pattern.java:4789)
    at java.util.regex.Pattern$Loop.match(Pattern.java:4898)
    at java.util.regex.Pattern$GroupTail.match(Pattern.java:4820)
    at java.util.regex.Pattern$BranchConn.match(Pattern.java:4698)
    at java.util.regex.Pattern$CharProperty.match(Pattern.java:3931)
    at java.util.regex.Pattern$Branch.match(Pattern.java:4734)
    at java.util.regex.Pattern$GroupHead.match(Pattern.java:4789)
    at java.util.regex.Pattern$Loop.match(Pattern.java:4898)
    at java.util.regex.Pattern$GroupTail.match(Pattern.java:4820)
    at java.util.regex.Pattern$BranchConn.match(Pattern.java:4698)
    at java.util.regex.Pattern$CharProperty.match(Pattern.java:3931)
    at java.util.regex.Pattern$Branch.match(Pattern.java:4734)
    at java.util.regex.Pattern$GroupHead.match(Pattern.java:4789)
    at java.util.regex.Pattern$Loop.match(Pattern.java:4898)
    at java.util.regex.Pattern$GroupTail.match(Pattern.java:4820)
    at java.util.regex.Pattern$BranchConn.match(Pattern.java:4698)
    at java.util.regex.Pattern$CharProperty.match(Pattern.java:3931)
    at java.util.regex.Pattern$Branch.match(Pattern.java:4734)
    at java.util.regex.Pattern$GroupHead.match(Pattern.java:4789)
    at java.util.regex.Pattern$Loop.match(Pattern.java:4898)
    at java.util.regex.Pattern$GroupTail.match(Pattern.java:4820)
    at java.util.regex.Pattern$BranchConn.match(Pattern.java:4698)
    at java.util.regex.Pattern$CharProperty.match(Pattern.java:3931)
    at java.util.regex.Pattern$Branch.match(Pattern.java:4734)
    at java.util.regex.Pattern$GroupHead.match(Pattern.java:4789)
    at java.util.regex.Pattern$Loop.match(Pattern.java:4898)
    at java.util.regex.Pattern$GroupTail.match(Pattern.java:4820)
    at java.util.regex.Pattern$BranchConn.match(Pattern.java:4698)
    at java.util.regex.Pattern$CharProperty.match(Pattern.java:3931)
    at java.util.regex.Pattern$Branch.match(Pattern.java:4734)
    at java.util.regex.Pattern$GroupHead.match(Pattern.java:4789)
    at java.util.regex.Pattern$Loop.match(Pattern.java:4898)
    at java.util.regex.Pattern$GroupTail.match(Pattern.java:4820)
    at java.util.regex.Pattern$BranchConn.match(Pattern.java:4698)
    at java.util.regex.Pattern$CharProperty.match(Pattern.java:3931)
    at java.util.regex.Pattern$Branch.match(Pattern.java:4734)
    at java.util.regex.Pattern$GroupHead.match(Pattern.java:4789)
    at java.util.regex.Pattern$Loop.match(Pattern.java:4898)
    at java.util.regex.Pattern$GroupTail.match(Pattern.java:4820)
    at java.util.regex.Pattern$BranchConn.match(Pattern.java:4698)
    at java.util.regex.Pattern$CharProperty.match(Pattern.java:3931)
    at java.util.regex.Pattern$Branch.match(Pattern.java:4734)
    at java.util.regex.Pattern$GroupHead.match(Pattern.java:4789)
    at java.util.regex.Pattern$Loop.match(Pattern.java:4898)
    at java.util.regex.Pattern$GroupTail.match(Pattern.java:4820)
    at java.util.regex.Pattern$BranchConn.match(Pattern.java:4698)
    at java.util.regex.Pattern$CharProperty.match(Pattern.java:3931)
    at java.util.regex.Pattern$Branch.match(Pattern.java:4734)
    at java.util.regex.Pattern$GroupHead.match(Pattern.java:4789)
    at java.util.regex.Pattern$Loop.match(Pattern.java:4898)
    at java.util.regex.Pattern$GroupTail.match(Pattern.java:4820)
    at java.util.regex.Pattern$BranchConn.match(Pattern.java:4698)
    at java.util.regex.Pattern$CharProperty.match(Pattern.java:3931)
    at java.util.regex.Pattern$Branch.match(Pattern.java:4734)
    at java.util.regex.Pattern$GroupHead.match(Pattern.java:4789)
    at java.util.regex.Pattern$Loop.match(Pattern.java:4898)
    at java.util.regex.Pattern$GroupTail.match(Pattern.java:4820)
    at java.util.regex.Pattern$BranchConn.match(Pattern.java:4698)
    at java.util.regex.Pattern$CharProperty.match(Pattern.java:3931)
    at java.util.regex.Pattern$Branch.match(Pattern.java:4734)
    at java.util.regex.Pattern$GroupHead.match(Pattern.java:4789)
    at java.util.regex.Pattern$Loop.match(Pattern.java:4898)
    at java.util.regex.Pattern$GroupTail.match(Pattern.java:4820)
    at java.util.regex.Pattern$BranchConn.match(Pattern.java:4698)
    at java.util.regex.Pattern$CharProperty.match(Pattern.java:3931)
    at java.util.regex.Pattern$Branch.match(Pattern.java:4734)
    at java.util.regex.Pattern$GroupHead.match(Pattern.java:4789)
    at java.util.regex.Pattern$Loop.match(Pattern.java:4898)
    at java.util.regex.Pattern$GroupTail.match(Pattern.java:4820)
    at java.util.regex.Pattern$BranchConn.match(Pattern.java:4698)
    at java.util.regex.Pattern$CharProperty.match(Pattern.java:3931)
    at java.util.regex.Pattern$Branch.match(Pattern.java:4734)
    at java.util.regex.Pattern$GroupHead.match(Pattern.java:4789)
    at java.util.regex.Pattern$Loop.match(Pattern.java:4898)
    at java.util.regex.Pattern$GroupTail.match(Pattern.java:4820)
    at java.util.regex.Pattern$BranchConn.match(Pattern.java:4698)
    at java.util.regex.Pattern$CharProperty.match(Pattern.java:3931)
    at java.util.regex.Pattern$Branch.match(Pattern.java:4734)
    at java.util.regex.Pattern$GroupHead.match(Pattern.java:4789)
    at java.util.regex.Pattern$Loop.match(Pattern.java:4898)
    at java.util.regex.Pattern$GroupTail.match(Pattern.java:4820)
    at java.util.regex.Pattern$BranchConn.match(Pattern.java:4698)
    at java.util.regex.Pattern$CharProperty.match(Pattern.java:3931)
    at java.util.regex.Pattern$Branch.match(Pattern.java:4734)
    at java.util.regex.Pattern$GroupHead.match(Pattern.java:4789)
    at java.util.regex.Pattern$Loop.match(Pattern.java:4898)
    at java.util.regex.Pattern$GroupTail.match(Pattern.java:4820)
    at java.util.regex.Pattern$BranchConn.match(Pattern.java:4698)
    at java.util.regex.Pattern$CharProperty.match(Pattern.java:3931)
    at java.util.regex.Pattern$Branch.match(Pattern.java:4734)
    at java.util.regex.Pattern$GroupHead.match(Pattern.java:4789)
    at java.util.regex.Pattern$Loop.match(Pattern.java:4898)
    at java.util.regex.Pattern$GroupTail.match(Pattern.java:4820)
    at java.util.regex.Pattern$BranchConn.match(Pattern.java:4698)
    at java.util.regex.Pattern$CharProperty.match(Pattern.java:3931)
    at java.util.regex.Pattern$Branch.match(Pattern.java:4734)
    at java.util.regex.Pattern$GroupHead.match(Pattern.java:4789)
    at java.util.regex.Pattern$Loop.match(Pattern.java:4898)
    at java.util.regex.Pattern$GroupTail.match(Pattern.java:4820)
    at java.util.regex.Pattern$BranchConn.match(Pattern.java:4698)
    at java.util.regex.Pattern$CharProperty.match(Pattern.java:3931)
    at java.util.regex.Pattern$Branch.match(Pattern.java:4734)
    at java.util.regex.Pattern$GroupHead.match(Pattern.java:4789)
    at java.util.regex.Pattern$Loop.match(Pattern.java:4898)
    at java.util.regex.Pattern$GroupTail.match(Pattern.java:4820)
    at java.util.regex.Pattern$BranchConn.match(Pattern.java:4698)
    at java.util.regex.Pattern$CharProperty.match(Pattern.java:3931)
    at java.util.regex.Pattern$Branch.match(Pattern.java:4734)
    at java.util.regex.Pattern$GroupHead.match(Pattern.java:4789)
    at java.util.regex.Pattern$Loop.match(Pattern.java:4898)
    at java.util.regex.Pattern$GroupTail.match(Pattern.java:4820)
    at java.util.regex.Pattern$BranchConn.match(Pattern.java:4698)
    at java.util.regex.Pattern$CharProperty.match(Pattern.java:3931)
    at java.util.regex.Pattern$Branch.match(Pattern.java:4734)
    at java.util.regex.Pattern$GroupHead.match(Pattern.java:4789)
    at java.util.regex.Pattern$Loop.match(Pattern.java:4898)
    at java.util.regex.Pattern$GroupTail.match(Pattern.java:4820)
    at java.util.regex.Pattern$BranchConn.match(Pattern.java:4698)
    at java.util.regex.Pattern$CharProperty.match(Pattern.java:3931)
    at java.util.regex.Pattern$Branch.match(Pattern.java:4734)
    at java.util.regex.Pattern$GroupHead.match(Pattern.java:4789)
    at java.util.regex.Pattern$Loop.match(Pattern.java:4898)
    at java.util.regex.Pattern$GroupTail.match(Pattern.java:4820)
    at java.util.regex.Pattern$BranchConn.match(Pattern.java:4698)
    at java.util.regex.Pattern$CharProperty.match(Pattern.java:3931)
    at java.util.regex.Pattern$Branch.match(Pattern.java:4734)
    at java.util.regex.Pattern$GroupHead.match(Pattern.java:4789)
    at java.util.regex.Pattern$Loop.match(Pattern.java:4898)
    at java.util.regex.Pattern$GroupTail.match(Pattern.java:4820)
    at java.util.regex.Pattern$BranchConn.match(Pattern.java:4698)
    at java.util.regex.Pattern$CharProperty.match(Pattern.java:3931)
    at java.util.regex.Pattern$Branch.match(Pattern.java:4734)
    at java.util.regex.Pattern$GroupHead.match(Pattern.java:4789)
    at java.util.regex.Pattern$Loop.match(Pattern.java:4898)
    at java.util.regex.Pattern$GroupTail.match(Pattern.java:4820)
    at java.util.regex.Pattern$BranchConn.match(Pattern.java:4698)
    at java.util.regex.Pattern$CharProperty.match(Pattern.java:3931)
    at java.util.regex.Pattern$Branch.match(Pattern.java:4734)
    at java.util.regex.Pattern$GroupHead.match(Pattern.java:4789)
    at java.util.regex.Pattern$Loop.match(Pattern.java:4898)
    at java.util.regex.Pattern$GroupTail.match(Pattern.java:4820)
    at java.util.regex.Pattern$BranchConn.match(Pattern.java:4698)
    at java.util.regex.Pattern$CharProperty.match(Pattern.java:3931)
    at java.util.regex.Pattern$Branch.match(Pattern.java:4734)
    at java.util.regex.Pattern$GroupHead.match(Pattern.java:4789)
    at java.util.regex.Pattern$Loop.match(Pattern.java:4898)
    at java.util.regex.Pattern$GroupTail.match(Pattern.java:4820)
    at java.util.regex.Pattern$BranchConn.match(Pattern.java:4698)
    at java.util.regex.Pattern$CharProperty.match(Pattern.java:3931)
    at java.util.regex.Pattern$Branch.match(Pattern.java:4734)
    at java.util.regex.Pattern$GroupHead.match(Pattern.java:4789)
    at java.util.regex.Pattern$Loop.match(Pattern.java:4898)
    at java.util.regex.Pattern$GroupTail.match(Pattern.java:4820)
    at java.util.regex.Pattern$BranchConn.match(Pattern.java:4698)
    at java.util.regex.Pattern$CharProperty.match(Pattern.java:3931)
    at java.util.regex.Pattern$Branch.match(Pattern.java:4734)
    at java.util.regex.Pattern$GroupHead.match(Pattern.java:4789)
    at java.util.regex.Pattern$Loop.match(Pattern.java:4898)
    at java.util.regex.Pattern$GroupTail.match(Pattern.java:4820)
    at java.util.regex.Pattern$BranchConn.match(Pattern.java:4698)
    at java.util.regex.Pattern$CharProperty.match(Pattern.java:3931)
    at java.util.regex.Pattern$Branch.match(Pattern.java:4734)
    at java.util.regex.Pattern$GroupHead.match(Pattern.java:4789)
    at java.util.regex.Pattern$Loop.match(Pattern.java:4898)
    at java.util.regex.Pattern$GroupTail.match(Pattern.java:4820)
    at java.util.regex.Pattern$BranchConn.match(Pattern.java:4698)
    at java.util.regex.Pattern$CharProperty.match(Pattern.java:3931)
    at java.util.regex.Pattern$Branch.match(Pattern.java:4734)
    at java.util.regex.Pattern$GroupHead.match(Pattern.java:4789)
    at java.util.regex.Pattern$Loop.match(Pattern.java:4898)
    at java.util.regex.Pattern$GroupTail.match(Pattern.java:4820)
    at java.util.regex.Pattern$BranchConn.match(Pattern.java:4698)
    at java.util.regex.Pattern$CharProperty.match(Pattern.java:3931)
    at java.util.regex.Pattern$Branch.match(Pattern.java:4734)
    at java.util.regex.Pattern$GroupHead.match(Pattern.java:4789)
    at java.util.regex.Pattern$Loop.match(Pattern.java:4898)
    at java.util.regex.Pattern$GroupTail.match(Pattern.java:4820)
    at java.util.regex.Pattern$BranchConn.match(Pattern.java:4698)
    at java.util.regex.Pattern$CharProperty.match(Pattern.java:3931)
    at java.util.regex.Pattern$Branch.match(Pattern.java:4734)
    at java.util.regex.Pattern$GroupHead.match(Pattern.java:4789)
    at java.util.regex.Pattern$Loop.match(Pattern.java:4898)
    at java.util.regex.Pattern$GroupTail.match(Pattern.java:4820)
    at java.util.regex.Pattern$BranchConn.match(Pattern.java:4698)
    at java.util.regex.Pattern$CharProperty.match(Pattern.java:3931)
    at java.util.regex.Pattern$Branch.match(Pattern.java:4734)
    at java.util.regex.Pattern$GroupHead.match(Pattern.java:4789)
    at java.util.regex.Pattern$Loop.match(Pattern.java:4898)
    at java.util.regex.Pattern$GroupTail.match(Pattern.java:4820)
    at java.util.regex.Pattern$BranchConn.match(Pattern.java:4698)
    at java.util.regex.Pattern$CharProperty.match(Pattern.java:3931)
    at java.util.regex.Pattern$Branch.match(Pattern.java:4734)
    at java.util.regex.Pattern$GroupHead.match(Pattern.java:4789)
    at java.util.regex.Pattern$Loop.match(Pattern.java:4898)
    at java.util.regex.Pattern$GroupTail.match(Pattern.java:4820)
    at java.util.regex.Pattern$BranchConn.match(Pattern.java:4698)
    at java.util.regex.Pattern$CharProperty.match(Pattern.java:3931)
    at java.util.regex.Pattern$Branch.match(Pattern.java:4734)
    at java.util.regex.Pattern$GroupHead.match(Pattern.java:4789)
    at java.util.regex.Pattern$Loop.match(Pattern.java:4898)
    at java.util.regex.Pattern$GroupTail.match(Pattern.java:4820)
    at java.util.regex.Pattern$BranchConn.match(Pattern.java:4698)
    at java.util.regex.Pattern$CharProperty.match(Pattern.java:3931)
    at java.util.regex.Pattern$Branch.match(Pattern.java:4734)
    at java.util.regex.Pattern$GroupHead.match(Pattern.java:4789)
    at java.util.regex.Pattern$Loop.match(Pattern.java:4898)
    at java.util.regex.Pattern$GroupTail.match(Pattern.java:4820)
    at java.util.regex.Pattern$BranchConn.match(Pattern.java:4698)
    at java.util.regex.Pattern$CharProperty.match(Pattern.java:3931)
    at java.util.regex.Pattern$Branch.match(Pattern.java:4734)
    at java.util.regex.Pattern$GroupHead.match(Pattern.java:4789)
    at java.util.regex.Pattern$Loop.match(Pattern.java:4898)
    at java.util.regex.Pattern$GroupTail.match(Pattern.java:4820)
    at java.util.regex.Pattern$BranchConn.match(Pattern.java:4698)
    at java.util.regex.Pattern$CharProperty.match(Pattern.java:3931)
    at java.util.regex.Pattern$Branch.match(Pattern.java:4734)
    at java.util.regex.Pattern$GroupHead.match(Pattern.java:4789)
    at java.util.regex.Pattern$Loop.match(Pattern.java:4898)
    at java.util.regex.Pattern$GroupTail.match(Pattern.java:4820)
    at java.util.regex.Pattern$BranchConn.match(Pattern.java:4698)
    at java.util.regex.Pattern$CharProperty.match(Pattern.java:3931)
    at java.util.regex.Pattern$Branch.match(Pattern.java:4734)
    at java.util.regex.Pattern$GroupHead.match(Pattern.java:4789)
    at java.util.regex.Pattern$Loop.match(Pattern.java:4898)
    at java.util.regex.Pattern$GroupTail.match(Pattern.java:4820)
    at java.util.regex.Pattern$BranchConn.match(Pattern.java:4698)
    at java.util.regex.Pattern$CharProperty.match(Pattern.java:3931)
    at java.util.regex.Pattern$Branch.match(Pattern.java:4734)
    ```

**Comment by mattpwest** [comment]
Hi there, I'm brand new to Defold, I'd never heard of it until 2-3 days ago, now I'm jumping in with both feet because it seems like the ideal engine for porting a game a built in PICO-8 years ago that got too big for PICO-8. Very impressed so far by your engine!

Didn't even realize at first that the editor is written in Java. I'm a Java developer by day (mostly back-end / web), but if you could point me at roughly where in the code this regex is being triggered, I might be able to go figure out how to prevent the failure (or at least handle it more gracefully).
