### ISSUE TITLE
Random editor error

### ISSUE THREAD

**Issue by jcbk101** [defold/defold#8834]
I do not know what's happening. I clicked open the editor from a minimized stated and an error dialog box appeared more than once.

### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2024-04-16T09:38:37.528376</td></tr>
<tr><td>Defold channel</td><td>beta</td></tr>
<tr><td>Defold editor sha</td><td>ee98012b77a481568425be40f17ae74874fd4da8</td></tr>
<tr><td>Defold engine sha</td><td>ee98012b77a481568425be40f17ae74874fd4da8</td></tr>
<tr><td>Defold version</td><td>1.8.0</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"3e279f0df6e64477a8911f505898c5b3"'>3e279f0df6e64477a8911f505898c5b3</a></td></tr>
<tr><td>GPU</td><td>GeForce GT 730/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 456.71</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by AGulev** [comment]
```
editor.git$unified_status.invokeStatic.class java.lang.NullPointerException: Cannot invoke "org.eclipse.jgit.revwalk.RevCommit.getTree()" because the return value of "editor.git$get_commit.invokeStatic(Object, Object)" is null
    at editor.git$unified_status.invokeStatic(git.clj:239)
    at editor.git$unified_status.invoke(git.clj:225)
    at editor.git$unified_status.invokeStatic(git.clj:229)
    at editor.changes_view$refresh_BANG_$fn.invoke(changes_view.clj:57)
    at clojure.core$binding_conveyor_fn$fn.invoke(core.clj:2030)
    at clojure.lang.AFn.call(AFn.java:18)
    at java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    at java.lang.Thread.run(Thread.java:833)
    ```

**Comment by vlaaad** [comment]
Hi!
The error seems to be related to git, more specifically, to commits. Can you describe what was the git repo state when you get the error?

**Comment by jcbk101** [comment]
Hello,

I am not sure if git was running atcthe time or not. I believe I must have ceated a new repository externally for the project.


________________________________

**Comment by AGulev** [comment]
Most git/sync related functionality was removed from the editor. I'm closing it for now, but feel free to reopen or open a new ticket it it will happen again using new version of Defold
