### ISSUE TITLE
java.util.MissingFormatArgumentException: Format specifier '%s'

### ISSUE THREAD

**Issue by zendorx** [defold/defold#8873]
### Expected behaviour
No error after property type changing

### Actual behaviour
Error appears while saving file with changed property and file stays not saved

### Steps to reproduce
1) Create property with vector3 `go.property("ambient_color", vmath.vector3(1.0, 1.0, 1.0))`
2) Save/Run
3) rename `vector3` to `vector4` and add fourth parameter
4) Press save (cmd+s) and error appears

<hr/>

<table>
<tr><td>Build time</td><td>2024-04-25T16:30:24.874132</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>6ff357fdf05b853e628ba6200e076fa87b0f8318</td></tr>
<tr><td>Defold engine sha</td><td>fd3b8c652df601220d8651f581fa2fada8205237</td></tr>
<tr><td>Defold version</td><td>1.8.0</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"c88569bfbf294755910438be8b409f20"'>c88569bfbf294755910438be8b409f20</a></td></tr>
<tr><td>GPU</td><td>AMD Radeon Pro 560X OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 ATI-4.9.48</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>13.0</td></tr>
<table>

**Comment by AGulev** [comment]
```
java.util.Formatter.format.class java.util.MissingFormatArgumentException: Format specifier '%s'
    at java.util.Formatter.format(Formatter.java:2688)
    at java.util.Formatter.format(Formatter.java:2625)
    at java.lang.String.format(String.java:4143)
    at clojure.core$format.invokeStatic(core.clj:5744)
    at clojure.core$format.doInvoke(core.clj:5738)
    at clojure.lang.RestFn.applyTo(RestFn.java:139)
    at clojure.core$apply.invokeStatic(core.clj:667)
    at editor.properties$clj_value__GT_go_prop_value.invokeStatic(properties.clj:216)
    at editor.properties$property_entry__GT_go_prop.invokeStatic(properties.clj:626)
    at editor.properties$property_entry__GT_go_prop.invoke(properties.clj:623)
    at clojure.core$keep$fn$fn.invoke(core.clj:7325)
    at clojure.lang.ArraySeq.reduce(ArraySeq.java:111)
    at clojure.core$transduce.invokeStatic(core.clj:6883)
    at clojure.core$into.invokeStatic(core.clj:6899)
    at editor.game_object$fn.invokeStatic(game_object.clj:333)
    at editor.game_object$fn.invoke(game_object.clj:329)
    at clojure.lang.AFn.applyToHelper(AFn.java:154)
    at clojure.lang.AFn.applyTo(AFn.java:144)
    at clojure.lang.AFunction$1.doInvoke(AFunction.java:31)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at clojure.lang.Var.invoke(Var.java:384)
    at editor.game_object$ReferencedComponent$behavior$ddf_properties$fn.invoke(game_object.clj:257)
    at internal.node$trace_expr$fn.invoke(node.clj:38)
    at internal.node$trace_expr.invokeStatic(node.clj:38)
    at editor.game_object$ReferencedComponent$behavior$ddf_properties.invokeStatic(game_object.clj:257)
    at editor.game_object$ReferencedComponent$behavior$ddf_properties.invoke(game_object.clj:257)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:295)
    at editor.game_object$ReferencedComponent$behavior$ddf_message$fn.invoke(game_object.clj:257)
    at internal.node$trace_expr$fn.invoke(node.clj:38)
    at internal.node$trace_expr.invokeStatic(node.clj:38)
    at editor.game_object$ReferencedComponent$behavior$ddf_message.invokeStatic(game_object.clj:257)
    at editor.game_object$ReferencedComponent$behavior$ddf_message.invoke(game_object.clj:257)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:295)
    at editor.game_object$ReferencedComponent$behavior$build_targets$fn.invoke(game_object.clj:257)
    at internal.node$trace_expr$fn.invoke(node.clj:38)
    at internal.node$trace_expr.invokeStatic(node.clj:38)
    at editor.game_object$ReferencedComponent$behavior$build_targets.invokeStatic(game_object.clj:257)
    at editor.game_object$ReferencedComponent$behavior$build_targets.invoke(game_object.clj:257)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:295)
    at internal.node$node_value.invokeStatic(node.clj:454)
    at internal.system$node_value.invokeStatic(system.clj:354)
    at dynamo.graph$do_node_value.invokeStatic(graph.clj:830)
    at dynamo.graph$node_value.invokeStatic(graph.clj:833)
    at editor.build$build_project_BANG_$fn.invoke(build.clj:52)
    at editor.build$build_project_BANG_.invokeStatic(build.clj:52)
    at editor.app_view$build_project_BANG_.invokeStatic(app_view.clj:905)
    at editor.app_view$async_build_BANG_$phase_3_build_project_BANG___64163$run_project_build_on_background_thread_BANG___64164.invoke(app_view.clj:1133)
    at editor.app_view$async_build_BANG_$run_on_background_thread_BANG___64116$fn.invoke(app_view.clj:1017)
    at clojure.core$binding_conveyor_fn$fn.invoke(core.clj:2030)
    at clojure.lang.AFn.call(AFn.java:18)
    at java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    at java.lang.Thread.run(Thread.java:833)

**Comment by AGulev** [comment]
this issue closed as duplicate of https://github.com/defold/defold/issues/7716
