### ISSUE TITLE
Unable to build due to debugger exception

### ISSUE THREAD

**Issue by VitheMPN** [defold/defold#8885]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2024-05-02T15:10:02.194956</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>acf09db558d18f7ccbbaa02c09333932f7cc8d4a</td></tr>
<tr><td>Defold engine sha</td><td>9141d9d3605e3f5d51c71293116d769da2613d39</td></tr>
<tr><td>Defold version</td><td>1.8.0</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"a753ca32306e49a9b2aca4acdac93236"'>a753ca32306e49a9b2aca4acdac93236</a></td></tr>
<tr><td>GPU</td><td>Intel(R) HD Graphics</td></tr>
<tr><td>GPU Driver</td><td>3.1.0 - Build 9.17.10.4459</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by AGulev** [comment]
```
editor.debugging.mobdebug$connect_BANG_$fn__61076.invoke.class clojure.lang.ExceptionInfo: Failed to connect to debugger on localhost:8172
    at editor.debugging.mobdebug$connect_BANG_$fn.invoke(mobdebug.clj:159)
    at clojure.lang.AFn.run(AFn.java:22)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
    at java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    at java.lang.Thread.run(Thread.java:833)
```

**Comment by britzl** [comment]
Can you reproduce this? Does it happen with all projects?

**Comment by britzl** [comment]
We should show a more user friendly error popup when the debugger fails to connect.
