### ISSUE TITLE
Renaming a copied script fails

### ISSUE THREAD

**Issue by zahlman** [defold/defold#8908]
### Expected behaviour
The script should be renamed

### Actual behaviour
A dialog box warns: `java.lang.AssertionError: Assert failed: (rename? resources)` and the file name is unchanged

### Steps to reproduce
* Copy a logic script via right-click -> copy, right-click -> paste
* right-click the new script, choose Rename and supply a new name

<hr/>

<table>
<tr><td>Build time</td><td>2024-05-07T07:12:29.922058</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>a617f67bfd39462a74837babfe9724375a9697d3</td></tr>
<tr><td>Defold engine sha</td><td>9141d9d3605e3f5d51c71293116d769da2613d39</td></tr>
<tr><td>Defold version</td><td>1.8.0</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"377ca3c28bea40d68ad7bffb2a328549"'>377ca3c28bea40d68ad7bffb2a328549</a></td></tr>
<tr><td>GPU</td><td>AMD OLAND (DRM 2.50.0, 5.4.0-181-generic, LLVM 12.0.0)</td></tr>
<tr><td>GPU Driver</td><td>4.5 (Compatibility Profile) Mesa 21.2.6</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>5.4.0-181-generic</td></tr>
<table>

**Comment by britzl** [comment]
```
editor.asset_browser$rename.invokeStatic.class java.lang.AssertionError: Assert failed: (rename? resources)
    at editor.asset_browser$rename.invokeStatic(asset_browser.clj:376)
    at editor.asset_browser$fn$fnk107505_positional__107509.invoke(asset_browser.clj:427)
    at editor.asset_browser$fn$fnk107505__107525$fn.invoke(asset_browser.clj:416)
    at editor.asset_browser$fn$fnk107505__107525.invoke(asset_browser.clj:416)
    at clojure.lang.AFn.applyToHelper(AFn.java:154)
    at clojure.lang.AFn.applyTo(AFn.java:144)
    at clojure.lang.AFunction$1.doInvoke(AFunction.java:31)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at editor.handler$invoke_fnk.invokeStatic(handler.clj:256)
    at editor.handler$run.invokeStatic(handler.clj:289)
    at editor.ui$execute_handler_ctx.invokeStatic(ui.clj:1192)
    at editor.ui$execute_command.invokeStatic(ui.clj:1200)
    at editor.ui$invoke_handler.invokeStatic(ui.clj:1231)
    at editor.ui$make_menu_command$reify.handle(ui.clj:1312)
    at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:232)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:189)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
    at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
    at javafx.event.Event.fireEvent(Event.java:198)
    at javafx.scene.control.MenuItem.fire(MenuItem.java:459)
    at com.sun.javafx.scene.control.ContextMenuContent$MenuItemContainer.doSelect(ContextMenuContent.java:1415)
    at com.sun.javafx.scene.control.ContextMenuContent$MenuItemContainer.lambda$createChildren$12(ContextMenuContent.java:1368)
    at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:247)
    at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:232)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:189)
    at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
    at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
    at javafx.event.Event.fireEvent(Event.java:198)
    at javafx.scene.Scene$MouseHandler.process(Scene.java:3987)
    at javafx.scene.Scene.processMouseEvent(Scene.java:1893)
    at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2711)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:411)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:301)
    at java.security.AccessController.doPrivileged(AccessController.java:399)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:450)
    at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:430)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:449)
    at com.sun.glass.ui.View.handleMouseEvent(View.java:551)
    at com.sun.glass.ui.View.notifyMouse(View.java:937)
    at com.sun.glass.ui.gtk.GtkApplication._runLoop(GtkApplication.java)
    at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$10(GtkApplication.java:264)
    at java.lang.Thread.run(Thread.java:833)
```

**Comment by vlaaad** [comment]
Hi, I tried reproducing your issue by copy-pasting a script and then renaming it, but I didn't get an error. Can you reproduce it consistently? Maybe you could make a screen recording showing how do you do it?

**Comment by vlaaad** [comment]
Yeah I think it's somehow caused by that change, but the assert should really not be happening since we disable the rename menu item if the same condition is false. That's why I'm asking for a reproducible example/video, since I can't reproduce it myself and don't see the bug in the code

**Comment by vlaaad** [comment]
I now saw your comment in the other issue, thanks!

**Comment by zahlman** [comment]
I don't have screen recording software set up, and I tossed off a quick bug report because I was in the middle of a game jam and didn't want to think about it any further until afterward. But I can confirm I'm seeing the same thing as in the other issue, so this should be considered a duplicate.
