### ISSUE TITLE
Rotating my 3D object crashed defold.

### ISSUE THREAD

**Issue by schlista** [defold/defold#8978]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2024-05-24T10:50:33.105437</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>8dfb2825db0d62dfc910fdcf8c271a005d5edb99</td></tr>
<tr><td>Defold engine sha</td><td>9141d9d3605e3f5d51c71293116d769da2613d39</td></tr>
<tr><td>Defold version</td><td>1.8.0</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"7c62d87d15ca43a8b43854c31f8b3e41"'>7c62d87d15ca43a8b43854c31f8b3e41</a></td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce RTX 3080 Ti/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 552.22</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 11</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by AGulev** [comment]
```
editor.math$plane_from_points.invokeStatic.class java.lang.ArithmeticException: A plane cannot be found since all three points are on a line.
    at editor.math$plane_from_points.invokeStatic(math.clj:268)
    at editor.geom$fn$corners__GT_frustum__38424$fn.invoke(geom.clj:438)
    at editor.geom$fn$corners__GT_frustum__38424.invoke(geom.clj:438)
    at editor.camera$fn$screen_rect_frustum__41405$fn.invoke(camera.clj:348)
    at editor.camera$fn$screen_rect_frustum__41405.invoke(camera.clj:331)
    at editor.scene$fn.invokeStatic(scene.clj:716)
    at editor.scene$fn.invoke(scene.clj:711)
    at clojure.lang.AFn.applyToHelper(AFn.java:154)
    at clojure.lang.AFn.applyTo(AFn.java:144)
    at clojure.lang.AFunction$1.doInvoke(AFunction.java:31)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at clojure.lang.Var.invoke(Var.java:384)
    at editor.scene$SceneView$behavior$picking_selection$fn.invoke(scene.clj:806)
    at internal.node$trace_expr.invokeStatic(node.clj:44)
    at editor.scene$SceneView$behavior$picking_selection.invokeStatic(scene.clj:806)
    at editor.scene$SceneView$behavior$picking_selection.invoke(scene.clj:806)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:295)
    at internal.node$pull_first_input_value.invokeStatic(node.clj:1204)
    at internal.node$pull_first_input_value.invoke(node.clj:1199)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:295)
    at internal.node$node_value.invokeStatic(node.clj:454)
    at internal.system$node_value.invokeStatic(system.clj:354)
    at dynamo.graph$do_node_value.invokeStatic(graph.clj:830)
    at dynamo.graph$node_value.invokeStatic(graph.clj:833)
    at editor.scene_selection$select.invokeStatic(scene_selection.clj:90)
    at editor.scene_selection$handle_selection_input.invokeStatic(scene_selection.clj:155)
    at editor.scene_selection$handle_selection_input.invoke(scene_selection.clj:118)
    at editor.scene$dispatch_input$fn.invoke(scene.clj:1136)
    at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
    at clojure.core$reduce.invokeStatic(core.clj:6827)
    at editor.scene$dispatch_input.invokeStatic(scene.clj:1133)
    at editor.scene$update_image_view_BANG_$fn.invoke(scene.clj:1174)
    at editor.scene$update_image_view_BANG_.invokeStatic(scene.clj:1172)
    at editor.scene$update_image_view_BANG_.invoke(scene.clj:1151)
    at editor.scene$refresh_scene_view_BANG_.invokeStatic(scene.clj:868)
    at editor.app_view$refresh_scene_views_BANG_$fn.invoke(app_view.clj:1813)
    at editor.app_view$refresh_scene_views_BANG_.invokeStatic(app_view.clj:1813)
    at editor.app_view$make_app_view$fn.invoke(app_view.clj:1925)
    at editor.ui$__GT_timer$fn$fn.invoke(ui.clj:1968)
    at clojure.lang.AFn.run(AFn.java:22)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:456)
    at java.security.AccessController.doPrivileged(AccessController.java:399)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:455)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
    at com.sun.glass.ui.win.WinApplication._runLoop(WinApplication.java)
    at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:184)
    at java.lang.Thread.run(Thread.java:833)
    ```

**Comment by Jhonnyg** [comment]
Could you share something more about what you are trying to rotate? Or the project itself?

**Comment by schlista** [comment]
If I remember correctly, it was main.collection for a 3D scene with a topdown camera.
[cid:0bb02ea5-cc41-484b-b1a7-76c0b0379beb]
________________________________

**Comment by Jhonnyg** [comment]
Closing this for now since there's not enough information to do anything about this. Feel free to re-open it if you have a repro case or more information how we could reproduce this issue!

**Comment by JosephFerano** [comment]
```
java.lang.ArithmeticException: A plane cannot be found since all three points are on a line.
	at editor.math$plane_from_points.invokeStatic(math.clj:417)
	at editor.math$plane_from_points.invoke(math.clj:407)
	at editor.geom$eval45512$corners__GT_frustum__45517$fn__45518.invoke(geom.clj:465)
	at editor.geom$eval45512$corners__GT_frustum__45517.invoke(geom.clj:456)
	at editor.camera$screen_rect_frustum.invokeStatic(camera.clj:376)
	at editor.camera$screen_rect_frustum.invoke(camera.clj:357)
	at editor.scene$fn__97111.invokeStatic(scene.clj:1196)
	at editor.scene$fn__97111.invoke(scene.clj:1191)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.lang.AFunction$1.doInvoke(AFunction.java:33)
	at clojure.lang.RestFn.invoke(RestFn.java:411)
	at clojure.lang.Var.invoke(Var.java:386)
	at editor.scene$SceneView$behavior$picking_selection$fn__97949.invoke(scene.clj:1296)
	at internal.node$trace_expr.invokeStatic(node.clj:53)
	at internal.node$trace_expr.invoke(node.clj:42)
	at editor.scene$SceneView$behavior$picking_selection.invokeStatic(scene.clj:1296)
	at editor.scene$SceneView$behavior$picking_selection.invoke(scene.clj:1296)
	at clojure.lang.Var.invoke(Var.java:395)
	at internal.node.NodeImpl.produce_value(node.clj:404)
	at internal.node$pull_first_input_value.invokeStatic(node.clj:1358)
	at internal.node$pull_first_input_value.invoke(node.clj:1353)
	at clojure.lang.Var.invoke(Var.java:395)
	at internal.node.NodeImpl.produce_value(node.clj:404)
	at internal.node$node_value.invokeStatic(node.clj:524)
	at internal.node$node_value.invoke(node.clj:515)
	at dynamo.graph$node_value.invokeStatic(graph.clj:1333)
	at dynamo.graph$node_value.invoke(graph.clj:1308)
	at dynamo.graph$node_value.invokeStatic(graph.clj:1328)
	at dynamo.graph$node_value.invoke(graph.clj:1308)
	at editor.scene_selection$select.invokeStatic(scene_selection.clj:93)
	at editor.scene_selection$select.invoke(scene_selection.clj:91)
	at editor.scene_selection$handle_selection_input.invokeStatic(scene_selection.clj:226)
	at editor.scene_selection$handle_selection_input.invoke(scene_selection.clj:167)
	at editor.scene$dispatch_input$fn__99498.invoke(scene.clj:1745)
	at clojure.lang.PersistentVector.reduce(PersistentVector.java:418)
	at clojure.core$reduce.invokeStatic(core.clj:6964)
	at clojure.core$reduce.invoke(core.clj:6947)
	at editor.scene$dispatch_input.invokeStatic(scene.clj:1743)
	at editor.scene$dispatch_input.invoke(scene.clj:1742)
	at editor.scene$dispatch_input_action.invokeStatic(scene.clj:1763)
	at editor.scene$dispatch_input_action.invoke(scene.clj:1754)
	at clojure.core$partial$fn__5927.invoke(core.clj:2642)
	at clojure.lang.PersistentVector.reduce(PersistentVector.java:418)
	at clojure.core$reduce.invokeStatic(core.clj:6964)
	at clojure.core$reduce.invoke(core.clj:6947)
	at editor.scene$update_image_view_BANG_$fn__99531.invoke(scene.clj:1810)
	at editor.scene$update_image_view_BANG_.invokeStatic(scene.clj:1807)
	at editor.scene$update_image_view_BANG_.invoke(scene.clj:1787)
	at editor.scene$refresh_scene_view_BANG_.invokeStatic(scene.clj:1401)
	at editor.scene$refresh_scene_view_BANG_.invoke(scene.clj:1392)
	at editor.app_view$refresh_scene_view_BANG_.invokeStatic(app_view.clj:2271)
	at editor.app_view$refresh_scene_view_BANG_.invoke(app_view.clj:2269)
	at editor.app_view$refresh_scene_views_BANG_.invokeStatic(app_view.clj:2279)
	at editor.app_view$refresh_scene_views_BANG_.invoke(app_view.clj:2275)
	at editor.app_view$make_app_view$fn__111700.invoke(app_view.clj:2438)
	at editor.ui$__GT_timer$fn__49448$fn__49449.invoke(ui.clj:2601)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1990)
	at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1990)
	at clojure.lang.RestFn.invoke(RestFn.java:428)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.RestFn.applyTo(RestFn.java:135)
	at clojure.core$apply.invokeStatic(core.clj:671)
	at clojure.core$bound_fn_STAR_$fn__5837.doInvoke(core.clj:2020)
	at clojure.lang.RestFn.invoke(RestFn.java:400)
	at clojure.lang.AFn.run(AFn.java:22)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$0(PlatformImpl.java:424)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$0(GtkApplication.java:240)
	at java.base/java.lang.Thread.run(Thread.java:1474)

```

Reopening cause I just ran into it. I just did a random click when trying to resize the editor panes, I had an atlas resource open, and I got htis exception, and the agent found some info so I'll leave it here for further investigation. 

> corners->frustum builds the near plane from near-tl/near-bl/near-br. Those go collinear when the screen rect has zero width or height, so the cross product is zero and plane-from-points throws.
> 
> Source: scene.clj:1194. box-selection? tests the unclamped rect, but picking-rect->clamped-view-rect (scene.clj:1014) clamps each edge independently — if the box's span on one axis sits entirely past a viewport edge, both edges clamp to the same bound and that dimension collapses to 0. The rect still passes box-selection? on the other axis. Nothing revalidates in between.
> 
> The stack is the refresh timer replaying queued input, so the viewport at frustum-build time isn't the one from when the drag points were recorded — a pane resize mid-drag fits.
> 
> Fix:
> 
> (let [clamped-view-rect (picking-rect->clamped-view-rect viewport picking-rect)]
>   (when-not (geom/rect-empty? clamped-view-rect)
>     ...))
> 
> Zero area selects nothing, so nil is the right answer.
> 
> Separate latent hole: a 0×0 viewport (SceneView's default, scene.clj:1302) makes screen->clip divide by zero — NaN planes, silently, no throw.

**Comment by JosephFerano** [comment]
I'll assign myself since this seems to be general to the editor
