### ISSUE TITLE
I put txt files in Resource URI and try to debug, it says "Unable to load bootstrap data" and crashes.

### ISSUE THREAD

**Issue by shokomint** [defold/defold#9001]
_Is it a private platform, and a platform specific issue? (i.e. would it break your NDA?)<br>
Then please report your issue in the corresponding extension repository!_

**Describe the bug (REQUIRED)**

I put txt files in Resource URI and try to debug, it says "Unable to load bootstrap data" and crashes.
In the error box, it says "clojure.lang.ExceptionInfo: Failed to connect to debugger on localhost:8172".
If I don't put anything, it works as usual.

**To Reproduce (REQUIRED)**

As above.

**Expected behavior (REQUIRED)**

It should work without crashing.

**Defold version (REQUIRED):**
  - Version [e.g. 1.2.155]
  
1.8.1

**Platforms (REQUIRED):**
 - Platforms: [e.g. iOS, Android, Windows, macOS, Linux, HTML5]
 Windows
 - OS: [e.g. iOS8.1, Windows 10, High Sierra]
 Windows 11

**Minimal repro case project (OPTIONAL):**
Please attach a minimal project where the bug is reproduced. This will greatly help the person trying to investigate and fix the bug.

**Logs (OPTIONAL):**
Please provide relevant logs from engine, editor or build server. Learn where the logs are stored [here](https://defold.com/manuals/getting-help/#log-files).

2024-05-29 21:17:16.332 670649 [JavaFX Application Thread] INFO  editor.defold-project - {:line 966, :message "Cached save data in system cache.", :total 253, :retained 106, :unretained 147, :limit 20000}
2024-05-29 21:17:53.009 707326 [JavaFX Application Thread] INFO  editor.defold-project - {:line 966, :message "Cached build targets in system cache.", :total 279, :retained 104, :unretained 175, :limit 20000}
2024-05-29 21:18:03.649 717966 [pool-3-thread-6] ERROR editor.error-reporting - {:line 115, :ex-data {:address "localhost", :port 8172}}
clojure.lang.ExceptionInfo: Failed to connect to debugger on localhost:8172
	at editor.debugging.mobdebug$connect_BANG_$fn__62203.invoke(mobdebug.clj:159)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
2024-05-29 21:28:32.602 1346919 [JavaFX Application Thread] INFO  editor.defold-project - {:line 966, :message "Cached build targets in system cache.", :total 274, :retained 104, :unretained 170, :limit 20000}
2024-05-29 21:28:43.382 1357699 [pool-3-thread-7] ERROR editor.error-reporting - {:line 115, :ex-data {:address "localhost", :port 8172}}
clojure.lang.ExceptionInfo: Failed to connect to debugger on localhost:8172
	at editor.debugging.mobdebug$connect_BANG_$fn__62203.invoke(mobdebug.clj:159)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Workaround (OPTIONAL):**
If there is a workaround, please describe it here.

**Screenshots (OPTIONAL):**

**Additional context (OPTIONAL):**

Thanks!

**Comment by AGulev** [comment]
What is `Resource URI` ? Could you provide a minimal project where issue reproducible. 
Inability to connect to the debugger isn't an issue itself, in 1.9.2 the error message was replaced with a notification.

**Comment by britzl** [comment]
> What is `Resource URI` ?

I assume it is the game.project setting in the Resource section? Putting the path to a txt file there is not the purpose of that field though.

**Comment by shokomint** [comment]
Hi, yes it is in the resource section.
Yes, I was told in the community that a text file is not to be in the section, and it was solved.
I posted this before I posted it in the community to realize it is not for a text file and I didn't delete this post.
Thanks!
