### ISSUE TITLE
Error occurs when trying to rename a Game Object

### ISSUE THREAD

**Issue by HyperAlch** [defold/defold#9007]
### Expected behaviour
Should be able to rename a Game Object asset using `Right click > Rename` or `F2`
### Actual behaviour
The Defold editor fails to rename the Game Object and an error pops up
### Steps to reproduce
Use `Right click > Rename` or `F2` to try and rename a Game Object in the `Assets` panel
<hr/>

<table>
<tr><td>Build time</td><td>2024-05-28T14:18:57.094314</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>7247f038fba6f40cda23c5ea2e38e9fde69a2ea6</td></tr>
<tr><td>Defold engine sha</td><td>fd1ad4c17bfdcd890ea7176f2672c35102384419</td></tr>
<tr><td>Defold version</td><td>1.8.1</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"47a642381fa7499db81aad40c28bd561"'>47a642381fa7499db81aad40c28bd561</a></td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce GTX 1070 Ti/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 525.147.05</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux, Debian 12, Gnome, X11</td></tr>
<tr><td>OS version</td><td>6.1.0-21-amd64</td></tr>
<table>

**Comment by AGulev** [comment]
```
editor.asset_browser$rename.invokeStatic.class java.lang.AssertionError: Assert failed: (rename? resources)
    at editor.asset_browser$rename.invokeStatic(asset_browser.clj:376)
    at editor.asset_browser$fn$fnk108488_positional__108492.invoke(asset_browser.clj:427)
    at editor.asset_browser$fn$fnk108488__108508$fn.invoke(asset_browser.clj:416)
    at editor.asset_browser$fn$fnk108488__108508.invoke(asset_browser.clj:416)
    at clojure.lang.AFn.applyToHelper(AFn.java:154)
    at clojure.lang.AFn.applyTo(AFn.java:144)
    at clojure.lang.AFunction$1.doInvoke(AFunction.java:31)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at editor.handler$invoke_fnk.invokeStatic(handler.clj:256)
    at editor.handler$run.invokeStatic(handler.clj:289)
    at editor.ui$execute_handler_ctx.invokeStatic(ui.clj:1192)
    at editor.ui$execute_command.invokeStatic(ui.clj:1200)
    at editor.ui$run_command.invokeStatic(ui.clj:1440)
    at editor.ui$bind_key_commands_BANG_$reify.handle(ui.clj:1517)
    at com.sun.javafx.event.CompositeEventHandler$NormalEventFilterRecord.handleCapturingEvent(CompositeEventHandler.java:321)
    at com.sun.javafx.event.CompositeEventHandler.dispatchCapturingEvent(CompositeEventHandler.java:98)
    at com.sun.javafx.event.EventHandlerManager.dispatchCapturingEvent(EventHandlerManager.java:219)
    at com.sun.javafx.event.EventHandlerManager.dispatchCapturingEvent(EventHandlerManager.java:178)
    at com.sun.javafx.event.CompositeEventDispatcher.dispatchCapturingEvent(CompositeEventDispatcher.java:43)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:52)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
    at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
    at javafx.event.Event.fireEvent(Event.java:198)
    at javafx.scene.Scene.processKeyEvent(Scene.java:2197)
    at javafx.scene.Scene$ScenePeerListener.keyEvent(Scene.java:2718)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(GlassViewEventHandler.java:218)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(GlassViewEventHandler.java:150)
    at java.security.AccessController.doPrivileged(AccessController.java:399)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleKeyEvent$1(GlassViewEventHandler.java:250)
    at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:430)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleKeyEvent(GlassViewEventHandler.java:249)
    at com.sun.glass.ui.View.handleKeyEvent(View.java:542)
    at com.sun.glass.ui.View.notifyKey(View.java:966)
    at com.sun.glass.ui.gtk.GtkApplication._runLoop(GtkApplication.java)
    at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$10(GtkApplication.java:264)
    at java.lang.Thread.run(Thread.java:833)
    ```

**Comment by vlaaad** [comment]
Hi, thanks for your report. We are aware of the issue, feel free to follow it here: #8761
