### ISSUE TITLE
Cannot invoke "clojure.lang.IFn.invoke(Object)" because "settings" is null

### ISSUE THREAD

**Issue by gamedevshrimp** [defold/defold#9083]
**Describe the bug (REQUIRED)**
when I try to open an old defold project from a public repository, I faced with an error
https://gyazo.com/7bcbc443947c051ed67164103f2ca90d

### Expected behaviour
project starts and runs clean and fast

### Actual behaviour
project starts with an error https://gyazo.com/7bcbc443947c051ed67164103f2ca90d

### Steps to reproduce
- download the repo [from here](https://github.com/Dragosha/defold-sprite-repeat/tree/main)
- run the project file

<hr/>

<table>
<tr><td>Build time</td><td>2024-06-13T17:34:34.196429</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>669856aacd570b3e4daf3f75eb157f7d25de67fe</td></tr>
<tr><td>Defold engine sha</td><td>fd1ad4c17bfdcd890ea7176f2672c35102384419</td></tr>
<tr><td>Defold version</td><td>1.8.1</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"1ec7393feeda43e09a59be43c7fccdd4"'>1ec7393feeda43e09a59be43c7fccdd4</a></td></tr>
<tr><td>GPU</td><td>Apple M1 Pro</td></tr>
<tr><td>GPU Driver</td><td>2.1 Metal - 88</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>aarch64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>14.2.1</td></tr>
<table>

**Comment by AGulev** [comment]
```
editor.app_view$refresh_app_title_BANG_.invokeStatic.class java.lang.NullPointerException: Cannot invoke "clojure.lang.IFn.invoke(Object)" because "settings" is null
    at editor.app_view$refresh_app_title_BANG_.invokeStatic(app_view.clj:1795)
    at editor.app_view$make_app_view$fn.invoke(app_view.clj:1927)
    at editor.ui$__GT_timer$fn$fn.invoke(ui.clj:1968)
    at clojure.lang.AFn.run(AFn.java:22)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:456)
    at java.security.AccessController.doPrivileged(AccessController.java:399)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:455)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
    ```

**Comment by AGulev** [comment]
One more callstack form https://github.com/defold/defold/issues/9596 : 
```
editor.app_view$refresh_app_title_BANG_.invokeStatic.class java.lang.NullPointerException: Cannot invoke "clojure.lang.IFn.invoke(Object)" because "settings" is null
    at editor.app_view$refresh_app_title_BANG_.invokeStatic(app_view.clj:1793)
    at editor.app_view$make_app_view$fn.invoke(app_view.clj:1925)
    at editor.ui$__GT_timer$fn$fn.invoke(ui.clj:1959)
    at clojure.lang.AFn.run(AFn.java:22)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:456)
    at java.security.AccessController.doPrivileged(AccessController.java:399)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:455)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
    at com.sun.glass.ui.mac.MacApplication._enterNestedEventLoopImpl(MacApplication.java)
    at com.sun.glass.ui.mac.MacApplication._enterNestedEventLoop(MacApplication.java:168)
    at com.sun.glass.ui.Application.enterNestedEventLoop(Application.java:515)
    at com.sun.glass.ui.EventLoop.enter(EventLoop.java:107)
    at com.sun.javafx.tk.quantum.QuantumToolkit.enterNestedEventLoop(QuantumToolkit.java:650)
    at javafx.application.Platform.enterNestedEventLoop(Platform.java:307)
    at editor.fxui$mount_renderer_and_await_result_BANG_.invokeStatic(fxui.clj:323)
    at editor.fxui$show_dialog_and_await_result_BANG_.invokeStatic(fxui.clj:328)
    at editor.dialogs$make_unexpected_error_dialog.invokeStatic(dialogs.clj:391)
    at editor.boot$notify_user$fn.invoke(boot.clj:86)
    at editor.ui$do_run_now$fn.invoke(ui.clj:307)
    at clojure.lang.AFn.run(AFn.java:22)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:456)
    at java.security.AccessController.doPrivileged(AccessController.java:399)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:455)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
    ```

**Comment by gamedevshrimp** [comment]
Hello! I checked the problem in version 1.11.1 and looks like the problem is gone. I can't repeat it.

**Comment by britzl** [comment]
Please re-open if you figure out how to reproduce the issue
