### ISSUE TITLE
Defold error..

### ISSUE THREAD

**Issue by ec-lost00** [defold/defold#9117]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2024-05-28T13:22:19.138953</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>fd1ad4c17bfdcd890ea7176f2672c35102384419</td></tr>
<tr><td>Defold engine sha</td><td>fd1ad4c17bfdcd890ea7176f2672c35102384419</td></tr>
<tr><td>Defold version</td><td>1.8.1</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"d3301c2e9e174913a1e63020d9e1bc75"'>d3301c2e9e174913a1e63020d9e1bc75</a></td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce RTX 3060/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 555.99</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 11</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by AGulev** [comment]
```
java.io.FileOutputStream.open0.class java.io.FileNotFoundException: C:\Users\eduec\Desktop\Jump\Collect  Game\.gitattributes (The system cannot find the path specified)
    at java.io.FileOutputStream.open0(FileOutputStream.java)
    at java.io.FileOutputStream.open(FileOutputStream.java:293)
    at java.io.FileOutputStream.<init>(FileOutputStream.java:235)
    at java.io.FileOutputStream.<init>(FileOutputStream.java:184)
    at editor.welcome$expand_proj_zip_BANG_.invokeStatic(welcome.clj:250)
    at editor.welcome$show_welcome_dialog_BANG_$download_template_BANG___107605$fn.invoke(welcome.clj:647)
    at clojure.core$binding_conveyor_fn$fn.invoke(core.clj:2030)
    at clojure.lang.AFn.call(AFn.java:18)
    at java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    at java.lang.Thread.run(Thread.java:833)
    ```

**Comment by vlaaad** [comment]
Hi @ec-lost00!
It looks like the error happened when the editor was trying to extract the downloaded project template. Are you able to download the project template from the link?
<img width="790" alt="Screenshot 2024-06-24 at 09 23 27" src="https://github.com/defold/defold/assets/732554/cbfadb33-5d3a-4761-ab11-b15432a021db">

**Comment by ec-lost00** [comment]
So sorry for the confusion. It was the special characters in the file name ( / n _ )

**Comment by vlaaad** [comment]
Got it, no problem :)
