### ISSUE TITLE
Error when I pressed on "start" project. 

### ISSUE THREAD

**Issue by Dolbaeb777K** [defold/defold#9245]
### Expected behaviour
The project just will started.

### Actual behaviour
Error appeared.

### Steps to reproduce
1) Open defold project from NTFS disk;
2) Press on F5.

<hr/>

<table>
<tr><td>Build time</td><td>2024-07-29T13:01:19.674948</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>00373d5b9519a4950c3461a544b8ce0b18136504</td></tr>
<tr><td>Defold engine sha</td><td>691478c02875b80e76da65d2f5756394e7a906b1</td></tr>
<tr><td>Defold version</td><td>1.9.1</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"a3c793dee534487da8aab339b07229b6"'>a3c793dee534487da8aab339b07229b6</a></td></tr>
<tr><td>GPU</td><td>AMD Radeon RX 580 2048SP (polaris10, LLVM 15.0.7, DRM 3.42, 5.15.0-117-generic)</td></tr>
<tr><td>GPU Driver</td><td>4.6 (Compatibility Profile) Mesa 23.2.1-1ubuntu3.1~22.04.2</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>5.15.0-117-generic</td></tr>
<table>

**Comment by AGulev** [comment]
```
sun.nio.fs.UnixException.translateToIOException.class java.nio.file.FileSystemException: /media/hip/CE28069C280683A5/Defold_projects/Basic 3D project/build/default/_generated_8440cd1.rigscenec: Input/output error
    at sun.nio.fs.UnixException.translateToIOException(UnixException.java:100)
    at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
    at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
    at sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:248)
    at sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(AbstractFileSystemProvider.java:110)
    at java.nio.file.Files.deleteIfExists(Files.java:1191)
    at editor.fs$do_delete_file_BANG_.invokeStatic(fs.clj:170)
    at editor.fs$delete_file_BANG_.invokeStatic(fs.clj:183)
    at editor.fs$delete_BANG_.invokeStatic(fs.clj:238)
    at editor.fs$delete_BANG_.invoke(fs.clj:226)
    at editor.fs$delete_BANG_.invokeStatic(fs.clj:233)
    at editor.pipeline$prune_build_dir_BANG_.invokeStatic(pipeline.clj:174)
    at editor.pipeline$build_BANG_.invokeStatic(pipeline.clj:193)
    at editor.build$build_project_BANG_.invokeStatic(build.clj:178)
    at editor.app_view$build_project_BANG_.invokeStatic(app_view.clj:906)
    at editor.app_view$async_build_BANG_$phase_3_build_project_BANG___64072$run_project_build_on_background_thread_BANG___64073.invoke(app_view.clj:1136)
    at editor.app_view$async_build_BANG_$run_on_background_thread_BANG___64025$fn.invoke(app_view.clj:1021)
    at clojure.core$binding_conveyor_fn$fn.invoke(core.clj:2030)
    at clojure.lang.AFn.call(AFn.java:18)
    at java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    at java.lang.Thread.run(Thread.java:833)
    ```

**Comment by AGulev** [comment]
It's still the same NTFS on Linux issue. 
Please try another disk which is fully compatable with Linux (NTFS is NT File System, which refers to Windows NT file System)

**Comment by britzl** [comment]
I asked a few users on Discord to try using NTFS on Linux and it works for them:

https://discord.com/channels/250018174974689280/822548486755057735/1268975019908665464

> "I'm using Mint and I formatted my backup disk in Windows, so the file system is NTFS. I opened a tutorial project on my backup disk in Mint. It works."

> "I'm using Ubuntu 22.04 and have a Windows dual boot.
I tried: load into Win, download Defold example project from github, restart into Ubuntu, open project from NTFS Win drive - all ok."
