### ISSUE TITLE
File or The folder damaged. Read impossible

### ISSUE THREAD

**Issue by Dolbaeb777K** [defold/defold#9250]
### Expected behaviour
Start the game
### Actual behaviour
Error appear
### Steps to reproduce
1. Open the project in NTFS disk on windows system;
2. Tap F5.
<hr/>

<table>
<tr><td>Build time</td><td>2024-07-30T08:31:09.154106</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>075b790f01b4b3d2074a7fd9dcf04b20af309eb0</td></tr>
<tr><td>Defold engine sha</td><td>691478c02875b80e76da65d2f5756394e7a906b1</td></tr>
<tr><td>Defold version</td><td>1.9.1</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"6fe141a8a6a24deba5b01952cc8d5dcf"'>6fe141a8a6a24deba5b01952cc8d5dcf</a></td></tr>
<tr><td>GPU</td><td>AMD Radeon RX 580 2048SP</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 Compatibility Profile Context 24.1.1.231127</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by AGulev** [comment]
```
sun.nio.fs.WindowsException.translateToIOException.class java.nio.file.FileSystemException: D:\Defold_projects\Basic 3D project\build\default\_generated_5ab41032.meshsetc: Файл или папка повреждены. Чтение невозможно
    at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:92)
    at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
    at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
    at sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:275)
    at sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(AbstractFileSystemProvider.java:110)
    at java.nio.file.Files.deleteIfExists(Files.java:1191)
    at editor.fs$do_delete_file_BANG_.invokeStatic(fs.clj:170)
    at editor.fs$delete_file_BANG_.invokeStatic(fs.clj:183)
    at editor.fs$delete_BANG_.invokeStatic(fs.clj:238)
    at editor.fs$delete_BANG_.invoke(fs.clj:226)
    at editor.fs$delete_BANG_.invokeStatic(fs.clj:233)
    at editor.pipeline$prune_build_dir_BANG_.invokeStatic(pipeline.clj:174)
    at editor.pipeline$build_BANG_.invokeStatic(pipeline.clj:193)
    at editor.build$build_project_BANG_.invokeStatic(build.clj:178)
    at editor.app_view$build_project_BANG_.invokeStatic(app_view.clj:906)
    at editor.app_view$async_build_BANG_$phase_3_build_project_BANG___64078$run_project_build_on_background_thread_BANG___64079.invoke(app_view.clj:1136)
    at editor.app_view$async_build_BANG_$run_on_background_thread_BANG___64031$fn.invoke(app_view.clj:1021)
    at clojure.core$binding_conveyor_fn$fn.invoke(core.clj:2030)
    at clojure.lang.AFn.call(AFn.java:18)
    at java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    at java.lang.Thread.run(Thread.java:833)

**Comment by britzl** [comment]
> Файл или папка повреждены. Чтение невозможно

The file or folder is corrupted. Reading is not possible.

**Comment by britzl** [comment]
Please test if the problem goes away if the project is saved on a non-NTFS volume. Closing for now. Reopen if the problem persists on a different volume.

**Comment by britzl** [comment]
I asked a few users on Discord to try using NTFS on Linux and it works for them:

https://discord.com/channels/250018174974689280/822548486755057735/1268975019908665464

> "I'm using Mint and I formatted my backup disk in Windows, so the file system is NTFS. I opened a tutorial project on my backup disk in Mint. It works."

> "I'm using Ubuntu 22.04 and have a Windows dual boot.
I tried: load into Win, download Defold example project from github, restart into Ubuntu, open project from NTFS Win drive - all ok."
