### ISSUE TITLE
Cannot read field "dropped_line_count" because "layout" is null

### ISSUE THREAD

**Issue by mdewitt11** [defold/defold#9254]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2024-07-30T08:29:00.978889</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>075b790f01b4b3d2074a7fd9dcf04b20af309eb0</td></tr>
<tr><td>Defold engine sha</td><td>691478c02875b80e76da65d2f5756394e7a906b1</td></tr>
<tr><td>Defold version</td><td>1.9.1</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"b618d413a20c4f33adff8ca1a52d4547"'>b618d413a20c4f33adff8ca1a52d4547</a></td></tr>
<tr><td>GPU</td><td>Mesa Intel(R) Graphics (ADL GT2)</td></tr>
<tr><td>GPU Driver</td><td>4.6 (Compatibility Profile) Mesa 24.1.4</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>6.9.12-200.fc40.x86_64</td></tr>
<table>

**Comment by AGulev** [comment]
```
editor.code.data$last_visible_row.invokeStatic.class java.lang.NullPointerException: Cannot read field "dropped_line_count" because "layout" is null
    at editor.code.data$last_visible_row.invokeStatic(data.clj:1188)
    at editor.code.view$repaint_view_BANG_.invokeStatic(view.clj:3078)
    at editor.code.view$make_view_BANG_$fn.invoke(view.clj:3660)
    at clojure.lang.AFn.run(AFn.java:22)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:456)
    at java.security.AccessController.doPrivileged(AccessController.java:399)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:455)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
    at com.sun.glass.ui.gtk.GtkApplication._runLoop(GtkApplication.java)
    at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$10(GtkApplication.java:264)
    at java.lang.Thread.run(Thread.java:833)

**Comment by AGulev** [comment]
What is your Linux distr?

**Comment by vlaaad** [comment]
Hi, please check the editor for update, the issue is most probably resolved. Feel free to reopen if the issue returns :)

**Comment by mdewitt11** [comment]
fedora 40

**Comment by britzl** [comment]
> fedora 40

Thanks. Can you please confirm that the update has solved the problem for you?
