### ISSUE TITLE
Editor error when edition model

### ISSUE THREAD

**Issue by selimanac** [defold/defold#9261]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2024-08-03T06:55:40.226653</td></tr>
<tr><td>Defold channel</td><td>alpha</td></tr>
<tr><td>Defold editor sha</td><td>de8e81e893ced421e2a820eeeec70d78675f6212</td></tr>
<tr><td>Defold engine sha</td><td>de8e81e893ced421e2a820eeeec70d78675f6212</td></tr>
<tr><td>Defold version</td><td>1.9.2</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"3a794d45ec5643a2a959fa4dab3f5535"'>3a794d45ec5643a2a959fa4dab3f5535</a></td></tr>
<tr><td>GPU</td><td>Apple M2 Pro</td></tr>
<tr><td>GPU Driver</td><td>2.1 Metal - 88.1</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>aarch64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>14.6</td></tr>
<table>

**Comment by AGulev** [comment]
**1.9.2**
```
editor.model_scene$augment_mesh_scene.invokeStatic.class java.lang.AssertionError: Assert failed: (shader/shader-lifecycle? shader)
    at editor.model_scene$augment_mesh_scene.invokeStatic(model_scene.clj:385)
    at editor.model_scene$augment_model_scene$fn.invoke(model_scene.clj:407)
    at clojure.core$mapv$fn.invoke(core.clj:6912)
    at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
    at clojure.core$reduce.invokeStatic(core.clj:6827)
    at clojure.core$mapv.invokeStatic(core.clj:6903)
    at editor.model_scene$augment_model_scene.invokeStatic(model_scene.clj:405)
    at editor.model_scene$augment_scene$fn.invoke(model_scene.clj:418)
    at clojure.core$mapv$fn.invoke(core.clj:6912)
    at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
    at clojure.core$reduce.invokeStatic(core.clj:6827)
    at clojure.core$mapv.invokeStatic(core.clj:6903)
    at editor.model_scene$augment_scene.invokeStatic(model_scene.clj:414)
    at editor.model$fn.invokeStatic(model.clj:173)
    at editor.model$fn.invoke(model.clj:172)
    at clojure.lang.AFn.applyToHelper(AFn.java:154)
    at clojure.lang.AFn.applyTo(AFn.java:144)
    at clojure.lang.AFunction$1.doInvoke(AFunction.java:31)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at clojure.lang.Var.invoke(Var.java:384)
    at editor.model$ModelNode$behavior$scene$fn.invoke(model.clj:407)
    at internal.node$trace_expr.invokeStatic(node.clj:46)
    at editor.model$ModelNode$behavior$scene.invokeStatic(model.clj:407)
    at editor.model$ModelNode$behavior$scene.invoke(model.clj:407)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:313)
    at internal.node$pull_first_input_value.invokeStatic(node.clj:1224)
    at editor.game_object$EmbeddedComponent$behavior$scene$fn.invoke(game_object.clj:220)
    at internal.node$trace_expr.invokeStatic(node.clj:46)
    at editor.game_object$EmbeddedComponent$behavior$scene.invokeStatic(game_object.clj:220)
    at editor.game_object$EmbeddedComponent$behavior$scene.invoke(game_object.clj:220)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:313)
    at internal.node$pull_input_values$fn.invoke(node.clj:1240)
    at clojure.core$mapv$fn.invoke(core.clj:6912)
    at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
    at clojure.core$reduce.invokeStatic(core.clj:6827)
    at clojure.core$mapv.invokeStatic(core.clj:6903)
    at internal.node$pull_input_values.invokeStatic(node.clj:1241)
    at editor.game_object$GameObjectNode$behavior$scene$fn.invoke(game_object.clj:437)
    at internal.node$trace_expr.invokeStatic(node.clj:46)
    at editor.game_object$GameObjectNode$behavior$scene.invokeStatic(game_object.clj:437)
    at editor.game_object$GameObjectNode$behavior$scene.invoke(game_object.clj:437)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:313)
    at internal.node$pull_first_input_value.invokeStatic(node.clj:1224)
    at editor.collection$EmbeddedGOInstanceNode$behavior$scene$fn.invoke(collection.clj:229)
    at internal.node$trace_expr.invokeStatic(node.clj:46)
    at editor.collection$EmbeddedGOInstanceNode$behavior$scene.invokeStatic(collection.clj:229)
    at editor.collection$EmbeddedGOInstanceNode$behavior$scene.invoke(collection.clj:229)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:313)
    at internal.node$pull_input_values$fn.invoke(node.clj:1240)
    at clojure.core$mapv$fn.invoke(core.clj:6912)
    at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
    at clojure.core$reduce.invokeStatic(core.clj:6827)
    at clojure.core$mapv.invokeStatic(core.clj:6903)
    at internal.node$pull_input_values.invokeStatic(node.clj:1241)
    at editor.collection$CollectionNode$behavior$scene$fn.invoke(collection.clj:447)
    at internal.node$trace_expr.invokeStatic(node.clj:46)
    at editor.collection$CollectionNode$behavior$scene.invokeStatic(collection.clj:447)
    at editor.collection$CollectionNode$behavior$scene.invoke(collection.clj:447)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:313)
    at internal.node$pull_first_input_value.invokeStatic(node.clj:1224)
    at editor.scene$SceneView$behavior$scene_aabb$fn.invoke(scene.clj:834)
    at internal.node$trace_expr.invokeStatic(node.clj:46)
    at editor.scene$SceneView$behavior$scene_aabb.invokeStatic(scene.clj:834)
    at editor.scene$SceneView$behavior$scene_aabb.invoke(scene.clj:834)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:313)
    at internal.node$pull_first_input_value.invokeStatic(node.clj:1224)
    at editor.camera$CameraController$behavior$camera$fn.invoke(camera.clj:658)
    at internal.node$trace_expr.invokeStatic(node.clj:46)
    at editor.camera$CameraController$behavior$camera.invokeStatic(camera.clj:658)
    at editor.camera$CameraController$behavior$camera.invoke(camera.clj:658)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:313)
    at internal.node$pull_first_input_value.invokeStatic(node.clj:1224)
    at editor.scene$SceneView$behavior$scene_render_data$fn.invoke(scene.clj:834)
    at internal.node$trace_expr.invokeStatic(node.clj:46)
    at editor.scene$SceneView$behavior$scene_render_data.invokeStatic(scene.clj:834)
    at editor.scene$SceneView$behavior$scene_render_data.invoke(scene.clj:834)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:313)
    at editor.scene$SceneView$behavior$selected_aabb$fn.invoke(scene.clj:834)
    at internal.node$trace_expr.invokeStatic(node.clj:46)
    at editor.scene$SceneView$behavior$selected_aabb.invokeStatic(scene.clj:834)
    at editor.scene$SceneView$behavior$selected_aabb.invoke(scene.clj:834)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:313)
    at internal.node$node_value.invokeStatic(node.clj:474)
    at internal.system$node_value.invokeStatic(system.clj:388)
    at dynamo.graph$do_node_value.invokeStatic(graph.clj:889)
    at dynamo.graph$node_value.invokeStatic(graph.clj:892)
    at editor.scene$frame_selection.invokeStatic(scene.clj:1023)
    at editor.scene$make_gl_pane_BANG_$fn$fn.invoke(scene.clj:1355)
    at editor.scene$make_gl_pane_BANG_$fn.invoke(scene.clj:1338)
    at editor.scene.proxy$com.defold.control.Region$ff19274a.layoutChildren
    at javafx.scene.Parent.layout(Parent.java:1208)
    at javafx.scene.Parent.layout(Parent.java:1215)
    at javafx.scene.Parent.layout(Parent.java:1215)
    at javafx.scene.Parent.layout(Parent.java:1215)
    at javafx.scene.Parent.layout(Parent.java:1215)
    at javafx.scene.Parent.layout(Parent.java:1215)
    at javafx.scene.Parent.layout(Parent.java:1215)
    at javafx.scene.Parent.layout(Parent.java:1215)
    at javafx.scene.Parent.layout(Parent.java:1215)
    at javafx.scene.Parent.layout(Parent.java:1215)
    at javafx.scene.Parent.layout(Parent.java:1215)
    at javafx.scene.Parent.layout(Parent.java:1215)
    at javafx.scene.Parent.layout(Parent.java:1215)
    at javafx.scene.Parent.layout(Parent.java:1215)
    at javafx.scene.Parent.layout(Parent.java:1215)
    at javafx.scene.Parent.layout(Parent.java:1215)
    at javafx.scene.Parent.layout(Parent.java:1215)
    at javafx.scene.Parent.layout(Parent.java:1215)
    at javafx.scene.Node.doLayoutPass(Node.java:2101)
    at javafx.scene.Node.doCSSLayoutSyncForSnapshot(Node.java:2108)
    at javafx.scene.Node$1.layoutNodeForPrinting(Node.java:563)
    at com.sun.javafx.scene.NodeHelper.layoutNodeForPrinting(NodeHelper.java:268)
    at editor.app_view$open_resource.invokeStatic(app_view.clj:2064)
    at editor.app_view$open_resource.invoke(app_view.clj:2003)
    at editor.app_view$open_resource.invokeStatic(app_view.clj:2005)
    at editor.app_view$fn$fnk65411_positional__65419.invoke(app_view.clj:2086)
    at editor.app_view$fn$fnk65411__65436$fn.invoke(app_view.clj:2082)
    at editor.app_view$fn$fnk65411__65436.invoke(app_view.clj:2082)
    at clojure.lang.AFn.applyToHelper(AFn.java:154)
    at clojure.lang.AFn.applyTo(AFn.java:144)
    at clojure.lang.AFunction$1.doInvoke(AFunction.java:31)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at editor.handler$invoke_fnk.invokeStatic(handler.clj:256)
    at editor.handler$run.invokeStatic(handler.clj:289)
    at editor.ui$execute_handler_ctx.invokeStatic(ui.clj:1228)
    at editor.ui$execute_command.invokeStatic(ui.clj:1236)
    at editor.ui$run_command.invokeStatic(ui.clj:1476)
    at editor.ui$bind_double_click_BANG_$reify.handle(ui.clj:1508)
    at com.sun.javafx.event.CompositeEventHandler$NormalEventFilterRecord.handleCapturingEvent(CompositeEventHandler.java:321)
    at com.sun.javafx.event.CompositeEventHandler.dispatchCapturingEvent(CompositeEventHandler.java:98)
    at com.sun.javafx.event.EventHandlerManager.dispatchCapturingEvent(EventHandlerManager.java:219)
    at com.sun.javafx.event.EventHandlerManager.dispatchCapturingEvent(EventHandlerManager.java:178)
    at com.sun.javafx.event.CompositeEventDispatcher.dispatchCapturingEvent(CompositeEventDispatcher.java:43)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:52)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
    at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
    at javafx.event.Event.fireEvent(Event.java:198)
    at javafx.scene.Scene$ClickGenerator.postProcess(Scene.java:3691)
    at javafx.scene.Scene$MouseHandler.process(Scene.java:3996)
    at javafx.scene.Scene.processMouseEvent(Scene.java:1893)
    at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2711)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:411)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:301)
    at java.security.AccessController.doPrivileged(AccessController.java:399)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:450)
    at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:430)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:449)
    at com.sun.glass.ui.View.handleMouseEvent(View.java:551)
    at com.sun.glass.ui.View.notifyMouse(View.java:937)
    at com.sun.glass.ui.mac.MacView.notifyMouse(MacView.java:127)###

**Comment by Jhonnyg** [comment]
Do you have any more information on how to reproduce this? there's not enough info for me to to anything about this right now

**Comment by selimanac** [comment]
Sorry, it was a busy morning and I couldn't find time to write an explanation. It happens when I try to add the attached glb to the model component. I was just trying a few dummy models and this one is from Sketchfab, so it might be problematic. It is not very important to me, as I'm not going to use this model for production.

![Screenshot 2024-08-05 at 11 59 42](https://github.com/user-attachments/assets/0ca24433-86d7-4480-9e07-0603aa802120)

You can find the Blender and glb file attached below.
[lowpoly.zip](https://github.com/user-attachments/files/16493429/lowpoly.zip)

**Comment by selimanac** [comment]
Not for comparison, I'm just testing stuff on Godot and this glb model works fine with Godot.
![Screenshot 2024-08-05 at 12 14 14](https://github.com/user-attachments/assets/c130e3a2-af6b-45de-b627-ed9ff5573b6f)

**Comment by AGulev** [comment]
I can't reproduce it. Please provide a minimal project if you are still able to reproduce it in new Defold
