### ISSUE TITLE
Error renaming

### ISSUE THREAD

**Issue by padreputativo** [defold/defold#9275]
### Expected behaviour

Being able to rename files.

### Actual behaviour

When renaming, the error appears and the file is not renamed. 

### Steps to reproduce

This error occurs when you rename a file while it's open in the editor, when it appears in the tab.

If you close the file before renaming it, the error does not appear.

<hr/>

<table>
<tr><td>Build time</td><td>2024-08-06T12:14:06.237364</td></tr>
<tr><td>Defold channel</td><td>beta</td></tr>
<tr><td>Defold editor sha</td><td>bedb9de52d298c50db06329523bec00779b6ad90</td></tr>
<tr><td>Defold engine sha</td><td>bedb9de52d298c50db06329523bec00779b6ad90</td></tr>
<tr><td>Defold version</td><td>1.9.2</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"e30fd80859604b7ea9b2ba3d64eecbb9"'>e30fd80859604b7ea9b2ba3d64eecbb9</a></td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 535.183.01</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>6.8.0-40-generic</td></tr>
<table>

**Comment by padreputativo** [comment]
It seems that the issue of being able to rename files upon closing them does not occur in all cases. It’s as if they remain open from one session to another (which I assume is impossible?).

**Comment by padreputativo** [comment]
It seems that putting the focus on and off the text box several times fixes the issue... although now I'm not entirely sure.

**Comment by britzl** [comment]
```
editor.asset_browser$rename.invokeStatic.class java.lang.AssertionError: Assert failed: (rename? resources)
    at editor.asset_browser$rename.invokeStatic(asset_browser.clj:390)
    at editor.asset_browser$fn$fnk104818_positional__104822.invoke(asset_browser.clj:441)
    at editor.asset_browser$fn$fnk104818__104838$fn.invoke(asset_browser.clj:430)
    at editor.asset_browser$fn$fnk104818__104838.invoke(asset_browser.clj:430)
    at clojure.lang.AFn.applyToHelper(AFn.java:154)
    at clojure.lang.AFn.applyTo(AFn.java:144)
    at clojure.lang.AFunction$1.doInvoke(AFunction.java:31)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at editor.handler$invoke_fnk.invokeStatic(handler.clj:256)
    at editor.handler$run.invokeStatic(handler.clj:289)
    at editor.ui$execute_handler_ctx.invokeStatic(ui.clj:1228)
    at editor.ui$execute_command.invokeStatic(ui.clj:1236)
    at editor.ui$invoke_handler.invokeStatic(ui.clj:1267)
    at editor.ui$make_menu_command$reify.handle(ui.clj:1348)
    at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:232)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:189)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
    at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
    at javafx.event.Event.fireEvent(Event.java:198)
    at javafx.scene.control.MenuItem.fire(MenuItem.java:459)
    at com.sun.javafx.scene.control.ContextMenuContent$MenuItemContainer.doSelect(ContextMenuContent.java:1415)
    at com.sun.javafx.scene.control.ContextMenuContent$MenuItemContainer.lambda$createChildren$12(ContextMenuContent.java:1368)
    at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:247)
    at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:232)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:189)
    at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
    at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
    at javafx.event.Event.fireEvent(Event.java:198)
    at javafx.scene.Scene$MouseHandler.process(Scene.java:3987)
    at javafx.scene.Scene.processMouseEvent(Scene.java:1893)
    at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2711)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:411)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:301)
    at java.security.AccessController.doPrivileged(AccessController.java:399)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:450)
    at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:430)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:449)
    at com.sun.glass.ui.View.handleMouseEvent(View.java:551)
    at com.sun.glass.ui.View.notifyMouse(View.java:937)
    at com.sun.glass.ui.gtk.GtkApplication._runLoop(GtkApplication.java)
    at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$10(GtkApplication.java:264)
    at java.lang.Thread.run(Thread.java:833)
```

**Comment by vlaaad** [comment]
Hi, please check the editor for update, the issue should be resolved :)

**Comment by padreputativo** [comment]
Fixed, but if you press Enter, it still fails.

https://github.com/user-attachments/assets/c7887697-46f8-4dc2-8766-d740d982b0ab

**Comment by vlaaad** [comment]
Hmm, what's your editor SHA in Help ->About?

**Comment by vlaaad** [comment]
Ah, no, you are using `beta` channel. The fix is on the main editor channel that you get when you download the editor from the site. The SHA should be `7e106914636fe4f22c967d7e297f4e24a26e0198`

**Comment by padreputativo** [comment]
Solved!

https://github.com/user-attachments/assets/6106d0c5-7d43-469b-b0c9-13ea8a5dfcdc
