### ISSUE TITLE
Adding a file to project will not toggle a newly added file and display it - Cannot read field "dropped_line_count" because "layout" is null

### ISSUE THREAD

**Issue by ig-gh** [defold/defold#9278]
### Expected behavior
Adding new file to project will display it in **assets pane** and open it at **main pane**

### Actual behavior
Random success

Adding a file to project  will not toggle a newly added file and display it.
Adding another **new** fiie will trigger a refresh and priviously added file will appear in **assets pane**

### Steps to reproduce
https://github.com/user-attachments/assets/b74d25ac-3c11-479b-90c2-46a7cc8a3a13
<hr/>

<table>
<tr><td>Build time</td><td>2024-08-07T21:50:00.440108</td></tr>
<tr><td>Defold channel</td><td>beta</td></tr>
<tr><td>Defold editor sha</td><td>8201073966fb31fa605f443c28a886e5dde0c04d</td></tr>
<tr><td>Defold engine sha</td><td>8201073966fb31fa605f443c28a886e5dde0c04d</td></tr>
<tr><td>Defold version</td><td>1.9.2</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"62a1b7ecea414ed3af0ff9ad234b1b6b"'>62a1b7ecea414ed3af0ff9ad234b1b6b</a></td></tr>
<tr><td>GPU</td><td>Mesa Intel(R) HD Graphics 620 (KBL GT2)</td></tr>
<tr><td>GPU Driver</td><td>4.6 (Compatibility Profile) Mesa 24.1.3-2</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux (debian+X11(gnome))</td></tr>
<tr><td>OS version</td><td>6.7.12-amd64</td></tr>
<table>

````
java.lang.NullPointerException: Cannot read field "dropped_line_count" because "layout" is null
        at editor.code.data$last_visible_row.invokeStatic(data.clj:1188)
        at editor.code.view$repaint_view_BANG_.invokeStatic(view.clj:3078)
        at editor.code.view$make_view_BANG_$fn__52184.invoke(view.clj:3660)
        at clojure.lang.AFn.run(AFn.java:22)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:456)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:455)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
        at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
        at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$10(GtkApplication.java:264)
        at java.base/java.lang.Thread.run(Thread.java:833)
2024-08-09 19:44:48.783 ERROR default    editor.error-reporting - {:line 115, :ex-data {:handler {:command :cut, :context :code-view, :fns {:active? #object[clojure.lang.AFunction$1 0x374e2a5c "clojure.lang.AFunction$1@374e2a5c"], :run #object[clojure.lang.AFunction$1 0x26fe6bb7 "clojure.lang.AFunction$1@26fe6bb7"], :enabled? #object[clojure.lang.AFunction$1 0x2819271c "clojure.lang.AFunction$1@2819271c"]}}, :command-context #editor.handler.Context{:name :code-view, :env {:view-node 288230376151711744, :selection-provider nil, :replace-bar #object[javafx.scene.layout.GridPane 0x4f5973e6 "Grid hgap=6.0, vgap=0.0, alignment=TOP_LEFT"], :editable true, :open-resource-fn #object[clojure.core$partial$fn__5830 0x2c5c45c3 "clojure.core$partial$fn__5830@2c5c45c3"], :selection-context :code-view, :goto-line-bar #object[javafx.scene.layout.GridPane 0x6c359536 "Grid hgap=6.0, vgap=0.0, alignment=TOP_LEFT"], :user-data nil, :clipboard #object[javafx.scene.input.Clipboard 0x462da864 "javafx.scene.input.Clipboard@462da864"], :selection nil, :find-bar #object[javafx.scene.layout.GridPane 0x412ef458 "Grid hgap=6.0, vgap=0.0, alignment=TOP_LEFT"]}, :selection-provider nil, :dynamics {}, :adapters {}}}}
clojure.lang.ExceptionInfo: handler ':cut' in context ':code-view' failed at ':enabled?' with message 'class clojure.lang.MapEntry cannot be cast to class editor.code.data.CursorRange (clojure.lang.MapEntry and editor.code.data.CursorRange are in unnamed module of loader 'app')'
        at editor.handler$invoke_fnk.invokeStatic(handler.clj:262)
        at editor.handler$enabled_QMARK_.invokeStatic(handler.clj:296)
        at editor.ui$make_menu_item.invokeStatic(ui.clj:1373)
        at editor.ui$make_menu_items$fn__15107.invoke(ui.clj:1389)
        at clojure.core$keep$fn__8540$fn__8541.invoke(core.clj:7325)
        at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
        at clojure.core$transduce.invokeStatic(core.clj:6883)
        at clojure.core$into.invokeStatic(core.clj:6899)
        at editor.ui$make_menu_items.invokeStatic(ui.clj:1387)
        at editor.ui$make_menu_items.invoke(ui.clj:1387)
        at editor.ui$make_menu_item.invokeStatic(ui.clj:1365)
        at editor.ui$make_menu_items$fn__15107.invoke(ui.clj:1389)
        at clojure.core$keep$fn__8540$fn__8541.invoke(core.clj:7325)
        at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
        at clojure.core$transduce.invokeStatic(core.clj:6883)
        at clojure.core$into.invokeStatic(core.clj:6899)
        at editor.ui$make_menu_items.invokeStatic(ui.clj:1387)
        at editor.ui$refresh_menubar_BANG_.invokeStatic(ui.clj:1607)
        at editor.ui$refresh_menus_BANG_.invokeStatic(ui.clj:1880)
        at editor.ui$refresh.invokeStatic(ui.clj:1901)
        at editor.app_view$refresh_menus_and_toolbars_BANG_.invokeStatic(app_view.clj:1830)
        at editor.app_view$make_app_view$fn__65611.invoke(app_view.clj:1954)
        at editor.ui$__GT_timer$fn__15482$fn__15483.invoke(ui.clj:2004)
        at clojure.lang.AFn.run(AFn.java:22)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:456)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:455)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
        at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
        at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$10(GtkApplication.java:264)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ClassCastException: class clojure.lang.MapEntry cannot be cast to class editor.code.data.CursorRange (clojure.lang.MapEntry and editor.code.data.CursorRange are in unnamed module of loader 'app')
        at editor.code.data$cursor_range_empty_QMARK_.invokeStatic(data.clj:205)
        at editor.code.data$cursor_range_empty_QMARK_.invoke(data.clj:204)
        at clojure.core$every_QMARK_.invokeStatic(core.clj:2681)
        at clojure.core$every_QMARK_.invoke(core.clj:2672)
        at clojure.core$comp$fn__5792.invoke(core.clj:2570)
        at editor.code.view$has_selection_QMARK_.invokeStatic(view.clj:2341)
        at editor.code.view$fn__49944$fnk49941_positional__49945.invoke(view.clj:2381)
        at editor.code.view$fn__49944$fnk49941__49956$fn__49957.invoke(view.clj:2381)
        at editor.code.view$fn__49944$fnk49941__49956.invoke(view.clj:2381)
        at clojure.lang.AFn.applyToHelper(AFn.java:154)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.lang.AFunction$1.doInvoke(AFunction.java:31)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at editor.handler$invoke_fnk.invokeStatic(handler.clj:256)
        ... 30 common frames omitted
2024-08-09 19:44:48.794 ERROR default    editor.error-reporting - {:line 115, :ex-data {:handler {:command :sort-lines, :context :code-view, :fns {:active? #object[clojure.lang.AFunction$1 0x52161d69 "clojure.lang.AFunction$1@52161d69"], :run #object[clojure.lang.AFunction$1 0x4087ea3a "clojure.lang.AFunction$1@4087ea3a"], :enabled? #object[clojure.lang.AFunction$1 0x152b2f78 "clojure.lang.AFunction$1@152b2f78"]}}, :command-context #editor.handler.Context{:name :code-view, :env {:view-node 288230376151711744, :selection-provider nil, :replace-bar #object[javafx.scene.layout.GridPane 0x4f5973e6 "Grid hgap=6.0, vgap=0.0, alignment=TOP_LEFT"], :editable true, :open-resource-fn #object[clojure.core$partial$fn__5830 0x2c5c45c3 "clojure.core$partial$fn__5830@2c5c45c3"], :selection-context :code-view, :goto-line-bar #object[javafx.scene.layout.GridPane 0x6c359536 "Grid hgap=6.0, vgap=0.0, alignment=TOP_LEFT"], :user-data nil, :clipboard #object[javafx.scene.input.Clipboard 0x462da864 "javafx.scene.input.Clipboard@462da864"], :selection nil, :find-bar #object[javafx.scene.layout.GridPane 0x412ef458 "Grid hgap=6.0, vgap=0.0, alignment=TOP_LEFT"]}, :selection-provider nil, :dynamics {}, :adapters {}}}}
clojure.lang.ExceptionInfo: handler ':sort-lines' in context ':code-view' failed at ':enabled?' with message 'class clojure.lang.MapEntry cannot be cast to class editor.code.data.CursorRange (clojure.lang.MapEntry and editor.code.data.CursorRange are in unnamed module of loader 'app')'
        at editor.handler$invoke_fnk.invokeStatic(handler.clj:262)
        at editor.handler$enabled_QMARK_.invokeStatic(handler.clj:296)
        at editor.ui$make_menu_item.invokeStatic(ui.clj:1373)
        at editor.ui$make_menu_items$fn__15107.invoke(ui.clj:1389)
        at clojure.core$keep$fn__8540$fn__8541.invoke(core.clj:7325)
        at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
        at clojure.core$transduce.invokeStatic(core.clj:6883)
        at clojure.core$into.invokeStatic(core.clj:6899)
        at editor.ui$make_menu_items.invokeStatic(ui.clj:1387)
        at editor.ui$make_menu_items.invoke(ui.clj:1387)
        at editor.ui$make_menu_item.invokeStatic(ui.clj:1365)
        at editor.ui$make_menu_items$fn__15107.invoke(ui.clj:1389)
        at clojure.core$keep$fn__8540$fn__8541.invoke(core.clj:7325)
        at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
        at clojure.core$transduce.invokeStatic(core.clj:6883)
        at clojure.core$into.invokeStatic(core.clj:6899)
        at editor.ui$make_menu_items.invokeStatic(ui.clj:1387)
        at editor.ui$refresh_menubar_BANG_.invokeStatic(ui.clj:1607)
        at editor.ui$refresh_menus_BANG_.invokeStatic(ui.clj:1880)
        at editor.ui$refresh.invokeStatic(ui.clj:1901)
        at editor.app_view$refresh_menus_and_toolbars_BANG_.invokeStatic(app_view.clj:1830)
        at editor.app_view$make_app_view$fn__65611.invoke(app_view.clj:1954)
        at editor.ui$__GT_timer$fn__15482$fn__15483.invoke(ui.clj:2004)
        at clojure.lang.AFn.run(AFn.java:22)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:456)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:455)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
        at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
        at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$10(GtkApplication.java:264)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ClassCastException: class clojure.lang.MapEntry cannot be cast to class editor.code.data.CursorRange (clojure.lang.MapEntry and editor.code.data.CursorRange are in unnamed module of loader 'app')
        at editor.code.data$cursor_range_multi_line_QMARK_.invokeStatic(data.clj:208)
        at editor.code.data$cursor_range_multi_line_QMARK_.invoke(data.clj:207)
        at clojure.core$some.invokeStatic(core.clj:2701)
        at editor.code.view$can_sort_lines_QMARK_.invokeStatic(view.clj:2563)
        at editor.code.view$fn__50839$fnk50836_positional__50840.invoke(view.clj:2573)
        at editor.code.view$fn__50839$fnk50836__50851$fn__50852.invoke(view.clj:2573)
        at editor.code.view$fn__50839$fnk50836__50851.invoke(view.clj:2573)
        at clojure.lang.AFn.applyToHelper(AFn.java:154)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.lang.AFunction$1.doInvoke(AFunction.java:31)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at editor.handler$invoke_fnk.invokeStatic(handler.clj:256)
        ... 30 common frames omitted
2024-08-09 19:44:56.421 INFO  default    editor.defold-project - {:line 346, :message "Cached loaded save data in system cache.", :total 62, :retained 15, :unretained 47, :limit 20000}


`````

**Comment by vlaaad** [comment]
Hi, please check the editor for update, the issue is most probably resolved. Feel free to reopen if the issue returns :)
