### ISSUE TITLE
Problem when renaming files and creating script files on Ubuntu

### ISSUE THREAD

**Issue by septumca** [defold/defold#9279]
Hi, 

I have some issues when creating new script files or renaming game objects or component in Defold editor on Ubuntu. I'm not an expert in Linux and I can't really provide steps to reproduce since the issues are not present always (only most of the time). Also I'm not sure if I'm not doing something wrong, since when I run Defold as root, the both issues seems to be not present. However I didn't find any info what might be wrong in Defold Linux FAQ (https://defold.com/faq/faq/#linux)

I realize that there is probably not much you can do, but maybe you can guide me if there are any errors in setting up Defold on my end, or maybe guide me how can I provide more information?

This is my system info
![Screenshot from 2024-08-10 20-33-50](https://github.com/user-attachments/assets/a135b12c-820c-4239-be80-ecb17fd59797)

Thank you

### Expected behaviour
Renaming files work
Creating script files works without errors

### Actual behaviour
When renaming files, sometimes (90%) it fails with following error
![Screenshot from 2024-08-10 20-09-35](https://github.com/user-attachments/assets/4afd855a-dbf1-46fc-9e9d-c4d4bbf281c3)
```
2024-08-10 20:09:09.675 223326 [JavaFX Application Thread] ERROR editor.error-reporting - {:line 116}
java.lang.AssertionError: Assert failed: (rename? resources)
	at editor.asset_browser$rename.invokeStatic(asset_browser.clj:390)
	at editor.asset_browser$fn__104536$fnk104533_positional__104537.invoke(asset_browser.clj:441)
	at editor.asset_browser$fn__104536$fnk104533__104553$fn__104554.invoke(asset_browser.clj:430)
	at editor.asset_browser$fn__104536$fnk104533__104553.invoke(asset_browser.clj:430)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.lang.AFunction$1.doInvoke(AFunction.java:31)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at editor.handler$invoke_fnk.invokeStatic(handler.clj:256)
	at editor.handler$run.invokeStatic(handler.clj:289)
	at editor.ui$execute_handler_ctx.invokeStatic(ui.clj:1228)
	at editor.ui$execute_command.invokeStatic(ui.clj:1236)
	at editor.ui$invoke_handler.invokeStatic(ui.clj:1267)
	at editor.ui$make_menu_command$reify__15094.handle(ui.clj:1348)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:232)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:189)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.control.MenuItem.fire(MenuItem.java:459)
	at com.sun.javafx.scene.control.ContextMenuContent$MenuItemContainer.doSelect(ContextMenuContent.java:1415)
	at com.sun.javafx.scene.control.ContextMenuContent.lambda$selectMenuItem$5(ContextMenuContent.java:693)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at com.sun.javafx.scene.control.ContextMenuContent.selectMenuItem(ContextMenuContent.java:681)
	at com.sun.javafx.scene.control.ContextMenuContent$1.handle(ContextMenuContent.java:543)
	at com.sun.javafx.scene.control.ContextMenuContent$1.handle(ContextMenuContent.java:498)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:232)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:189)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
	at javafx.stage.PopupWindow$PopupEventRedirector.handleKeyEvent(PopupWindow.java:1012)
	at javafx.stage.PopupWindow$PopupEventRedirector.handleRedirectedEvent(PopupWindow.java:984)
	at com.sun.javafx.event.EventRedirector.dispatchCapturingEvent(EventRedirector.java:106)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchCapturingEvent(CompositeEventDispatcher.java:43)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:52)
	at com.sun.javafx.event.EventRedirector.redirectEvent(EventRedirector.java:124)
	at com.sun.javafx.event.EventRedirector.dispatchCapturingEvent(EventRedirector.java:103)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchCapturingEvent(CompositeEventDispatcher.java:43)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:52)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Scene.processKeyEvent(Scene.java:2197)
	at javafx.scene.Scene$ScenePeerListener.keyEvent(Scene.java:2718)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(GlassViewEventHandler.java:218)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(GlassViewEventHandler.java:150)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleKeyEvent$1(GlassViewEventHandler.java:250)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:430)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleKeyEvent(GlassViewEventHandler.java:249)
	at com.sun.glass.ui.View.handleKeyEvent(View.java:542)
	at com.sun.glass.ui.View.notifyKey(View.java:966)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$10(GtkApplication.java:264)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

When creating .script files, following errors are shown (sometimes only some of them are shown, sometimes all of them)
![Screenshot from 2024-08-10 20-10-07](https://github.com/user-attachments/assets/108d8b0c-5ad1-4ef6-a81d-080665e91607)
```
2024-08-10 20:10:28.608 302259 [JavaFX Application Thread] ERROR editor.error-reporting - {:line 116}
java.lang.NullPointerException: Cannot read field "dropped_line_count" because "layout" is null
	at editor.code.data$last_visible_row.invokeStatic(data.clj:1188)
	at editor.code.view$repaint_view_BANG_.invokeStatic(view.clj:3078)
	at editor.code.view$make_view_BANG_$fn__52120.invoke(view.clj:3660)
	at clojure.lang.AFn.run(AFn.java:22)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:456)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:455)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$10(GtkApplication.java:264)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

![Screenshot from 2024-08-10 20-10-53](https://github.com/user-attachments/assets/f681f93a-5fbf-4287-84c4-fea82e8370c7)
```
2024-08-10 20:10:28.624 302275 [JavaFX Application Thread] ERROR editor.error-reporting - {:line 115, :ex-data {:handler {:command :cut, :context :code-view, :fns {:active? #object[clojure.lang.AFunction$1 0x716bd0ef "clojure.lang.AFunction$1@716bd0ef"], :run #object[clojure.lang.AFunction$1 0x724d1df4 "clojure.lang.AFunction$1@724d1df4"], :enabled? #object[clojure.lang.AFunction$1 0x6907b1db "clojure.lang.AFunction$1@6907b1db"]}}, :command-context #editor.handler.Context{:name :code-view, :env {:view-node 288230376151711744, :selection-provider nil, :replace-bar #object[javafx.scene.layout.GridPane 0x17b2cf33 "Grid hgap=6.0, vgap=0.0, alignment=TOP_LEFT"], :editable true, :open-resource-fn #object[clojure.core$partial$fn__5830 0x31e5576e "clojure.core$partial$fn__5830@31e5576e"], :selection-context :code-view, :goto-line-bar #object[javafx.scene.layout.GridPane 0x29d5ca21 "Grid hgap=6.0, vgap=0.0, alignment=TOP_LEFT"], :user-data nil, :clipboard #object[javafx.scene.input.Clipboard 0x4e22ff7e "javafx.scene.input.Clipboard@4e22ff7e"], :selection nil, :find-bar #object[javafx.scene.layout.GridPane 0x78224914 "Grid hgap=6.0, vgap=0.0, alignment=TOP_LEFT"]}, :selection-provider nil, :dynamics {}, :adapters {}}}}
clojure.lang.ExceptionInfo: handler ':cut' in context ':code-view' failed at ':enabled?' with message 'class clojure.lang.MapEntry cannot be cast to class editor.code.data.CursorRange (clojure.lang.MapEntry and editor.code.data.CursorRange are in unnamed module of loader 'app')'
	at editor.handler$invoke_fnk.invokeStatic(handler.clj:262)
	at editor.handler$enabled_QMARK_.invokeStatic(handler.clj:296)
	at editor.ui$make_menu_item.invokeStatic(ui.clj:1373)
	at editor.ui$make_menu_items$fn__15107.invoke(ui.clj:1389)
	at clojure.core$keep$fn__8540$fn__8541.invoke(core.clj:7325)
	at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
	at clojure.core$transduce.invokeStatic(core.clj:6883)
	at clojure.core$into.invokeStatic(core.clj:6899)
	at editor.ui$make_menu_items.invokeStatic(ui.clj:1387)
	at editor.ui$make_menu_items.invoke(ui.clj:1387)
	at editor.ui$make_menu_item.invokeStatic(ui.clj:1365)
	at editor.ui$make_menu_items$fn__15107.invoke(ui.clj:1389)
	at clojure.core$keep$fn__8540$fn__8541.invoke(core.clj:7325)
	at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
	at clojure.core$transduce.invokeStatic(core.clj:6883)
	at clojure.core$into.invokeStatic(core.clj:6899)
	at editor.ui$make_menu_items.invokeStatic(ui.clj:1387)
	at editor.ui$refresh_menubar_BANG_.invokeStatic(ui.clj:1607)
	at editor.ui$refresh_menus_BANG_.invokeStatic(ui.clj:1880)
	at editor.ui$refresh.invokeStatic(ui.clj:1901)
	at editor.app_view$refresh_menus_and_toolbars_BANG_.invokeStatic(app_view.clj:1806)
	at editor.app_view$make_app_view$fn__65322.invoke(app_view.clj:1930)
	at editor.ui$__GT_timer$fn__15482$fn__15483.invoke(ui.clj:2004)
	at clojure.lang.AFn.run(AFn.java:22)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:456)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:455)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$10(GtkApplication.java:264)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ClassCastException: class clojure.lang.MapEntry cannot be cast to class editor.code.data.CursorRange (clojure.lang.MapEntry and editor.code.data.CursorRange are in unnamed module of loader 'app')
	at editor.code.data$cursor_range_empty_QMARK_.invokeStatic(data.clj:205)
	at editor.code.data$cursor_range_empty_QMARK_.invoke(data.clj:204)
	at clojure.core$every_QMARK_.invokeStatic(core.clj:2681)
	at clojure.core$every_QMARK_.invoke(core.clj:2672)
	at clojure.core$comp$fn__5792.invoke(core.clj:2570)
	at editor.code.view$has_selection_QMARK_.invokeStatic(view.clj:2341)
	at editor.code.view$fn__49880$fnk49877_positional__49881.invoke(view.clj:2381)
	at editor.code.view$fn__49880$fnk49877__49892$fn__49893.invoke(view.clj:2381)
	at editor.code.view$fn__49880$fnk49877__49892.invoke(view.clj:2381)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.lang.AFunction$1.doInvoke(AFunction.java:31)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at editor.handler$invoke_fnk.invokeStatic(handler.clj:256)
	... 30 common frames omitted
```
![Screenshot from 2024-08-10 20-11-04](https://github.com/user-attachments/assets/d6f48c0f-1f3a-497c-a4d6-8da6293f6986)
```
2024-08-10 20:10:28.633 302284 [JavaFX Application Thread] ERROR editor.error-reporting - {:line 115, :ex-data {:handler {:command :sort-lines, :context :code-view, :fns {:active? #object[clojure.lang.AFunction$1 0xa24d18f "clojure.lang.AFunction$1@a24d18f"], :run #object[clojure.lang.AFunction$1 0x53365e4a "clojure.lang.AFunction$1@53365e4a"], :enabled? #object[clojure.lang.AFunction$1 0xc2a4a77 "clojure.lang.AFunction$1@c2a4a77"]}}, :command-context #editor.handler.Context{:name :code-view, :env {:view-node 288230376151711744, :selection-provider nil, :replace-bar #object[javafx.scene.layout.GridPane 0x17b2cf33 "Grid hgap=6.0, vgap=0.0, alignment=TOP_LEFT"], :editable true, :open-resource-fn #object[clojure.core$partial$fn__5830 0x31e5576e "clojure.core$partial$fn__5830@31e5576e"], :selection-context :code-view, :goto-line-bar #object[javafx.scene.layout.GridPane 0x29d5ca21 "Grid hgap=6.0, vgap=0.0, alignment=TOP_LEFT"], :user-data nil, :clipboard #object[javafx.scene.input.Clipboard 0x4e22ff7e "javafx.scene.input.Clipboard@4e22ff7e"], :selection nil, :find-bar #object[javafx.scene.layout.GridPane 0x78224914 "Grid hgap=6.0, vgap=0.0, alignment=TOP_LEFT"]}, :selection-provider nil, :dynamics {}, :adapters {}}}}
clojure.lang.ExceptionInfo: handler ':sort-lines' in context ':code-view' failed at ':enabled?' with message 'class clojure.lang.MapEntry cannot be cast to class editor.code.data.CursorRange (clojure.lang.MapEntry and editor.code.data.CursorRange are in unnamed module of loader 'app')'
	at editor.handler$invoke_fnk.invokeStatic(handler.clj:262)
	at editor.handler$enabled_QMARK_.invokeStatic(handler.clj:296)
	at editor.ui$make_menu_item.invokeStatic(ui.clj:1373)
	at editor.ui$make_menu_items$fn__15107.invoke(ui.clj:1389)
	at clojure.core$keep$fn__8540$fn__8541.invoke(core.clj:7325)
	at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
	at clojure.core$transduce.invokeStatic(core.clj:6883)
	at clojure.core$into.invokeStatic(core.clj:6899)
	at editor.ui$make_menu_items.invokeStatic(ui.clj:1387)
	at editor.ui$make_menu_items.invoke(ui.clj:1387)
	at editor.ui$make_menu_item.invokeStatic(ui.clj:1365)
	at editor.ui$make_menu_items$fn__15107.invoke(ui.clj:1389)
	at clojure.core$keep$fn__8540$fn__8541.invoke(core.clj:7325)
	at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
	at clojure.core$transduce.invokeStatic(core.clj:6883)
	at clojure.core$into.invokeStatic(core.clj:6899)
	at editor.ui$make_menu_items.invokeStatic(ui.clj:1387)
	at editor.ui$refresh_menubar_BANG_.invokeStatic(ui.clj:1607)
	at editor.ui$refresh_menus_BANG_.invokeStatic(ui.clj:1880)
	at editor.ui$refresh.invokeStatic(ui.clj:1901)
	at editor.app_view$refresh_menus_and_toolbars_BANG_.invokeStatic(app_view.clj:1806)
	at editor.app_view$make_app_view$fn__65322.invoke(app_view.clj:1930)
	at editor.ui$__GT_timer$fn__15482$fn__15483.invoke(ui.clj:2004)
	at clojure.lang.AFn.run(AFn.java:22)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:456)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:455)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$10(GtkApplication.java:264)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ClassCastException: class clojure.lang.MapEntry cannot be cast to class editor.code.data.CursorRange (clojure.lang.MapEntry and editor.code.data.CursorRange are in unnamed module of loader 'app')
	at editor.code.data$cursor_range_multi_line_QMARK_.invokeStatic(data.clj:208)
	at editor.code.data$cursor_range_multi_line_QMARK_.invoke(data.clj:207)
	at clojure.core$some.invokeStatic(core.clj:2701)
	at editor.code.view$can_sort_lines_QMARK_.invokeStatic(view.clj:2563)
	at editor.code.view$fn__50775$fnk50772_positional__50776.invoke(view.clj:2573)
	at editor.code.view$fn__50775$fnk50772__50787$fn__50788.invoke(view.clj:2573)
	at editor.code.view$fn__50775$fnk50772__50787.invoke(view.clj:2573)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.lang.AFunction$1.doInvoke(AFunction.java:31)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at editor.handler$invoke_fnk.invokeStatic(handler.clj:256)
	... 30 common frames omitted
```

### Steps to reproduce
Either rename some file 
Create new script file

<hr/>

<table>
<tr><td>Build time</td><td>2024-08-06T08:03:31.339776</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>63810f43f612b9decad53c7f3bff62c5a23302ce</td></tr>
<tr><td>Defold engine sha</td><td>691478c02875b80e76da65d2f5756394e7a906b1</td></tr>
<tr><td>Defold version</td><td>1.9.1</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"3ac9c4d37317467192b1bfde2b729f30"'>3ac9c4d37317467192b1bfde2b729f30</a></td></tr>
<tr><td>GPU</td><td>Mesa Intel(R) Graphics (ADL-N)</td></tr>
<tr><td>GPU Driver</td><td>4.6 (Compatibility Profile) Mesa 24.0.9-0ubuntu0.1</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>6.8.0-39-generic</td></tr>
<table>

**Comment by septumca** [comment]
It seems to work after update, thank you :)
