### ISSUE TITLE
java.lang.AssertionError: Assert failed: source-id

### ISSUE THREAD

**Issue by MhadhbiXissam** [defold/defold#9289]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2024-06-25T16:24:14.962363</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>3642fa5b700b8d6e74e3f0595e75cd50eff54459</td></tr>
<tr><td>Defold engine sha</td><td>d6882f432beca85d460ec42497888157c356d058</td></tr>
<tr><td>Defold version</td><td>1.9.0</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"c1f65e0e862d44daa5ad99cd688be4be"'>c1f65e0e862d44daa5ad99cd688be4be</a></td></tr>
<tr><td>GPU</td><td>Mesa Intel(R) Xe Graphics (TGL GT2)</td></tr>
<tr><td>GPU Driver</td><td>4.6 (Compatibility Profile) Mesa 23.2.1-1ubuntu3.1~22.04.2</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>5.15.0-107-generic</td></tr>
<table>

**Comment by AGulev** [comment]
```
dynamo.graph$connect.invokeStatic.class java.lang.AssertionError: Assert failed: source-id
    at dynamo.graph$connect.invokeStatic(graph.clj:534)
    at editor.collection$child_go_go$iter__98468__98472$fn$fn.invoke(collection.clj:88)
    at editor.collection$child_go_go$iter__98468__98472$fn.invoke(collection.clj:88)
    at clojure.lang.LazySeq.sval(LazySeq.java:42)
    at clojure.lang.LazySeq.seq(LazySeq.java:51)
    at clojure.lang.RT.seq(RT.java:531)
    at clojure.core$seq__5387.invokeStatic(core.clj:137)
    at internal.transaction$apply_tx.invokeStatic(transaction.clj:809)
    at internal.transaction$apply_tx.invoke(transaction.clj:805)
    at internal.transaction$apply_tx.invokeStatic(transaction.clj:812)
    at internal.transaction$apply_tx.invoke(transaction.clj:805)
    at internal.transaction$apply_tx.invokeStatic(transaction.clj:812)
    at internal.transaction$apply_tx.invoke(transaction.clj:805)
    at internal.transaction$apply_tx.invokeStatic(transaction.clj:812)
    at internal.transaction$transact_STAR_.invokeStatic(transaction.clj:896)
    at dynamo.graph$transact.invokeStatic(graph.clj:169)
    at editor.defold_project$load_nodes_BANG_$fn.invoke(defold_project.clj:226)
    at editor.defold_project$load_nodes_BANG_.invokeStatic(defold_project.clj:226)
    at editor.defold_project$perform_resource_change_plan.invokeStatic(defold_project.clj:577)
    at editor.defold_project$handle_resource_changes.invokeStatic(defold_project.clj:693)
    at editor.defold_project.ProjectResourceListener.handle_changes(defold_project.clj:886)
    at editor.workspace$resource_sync_BANG_$fn.invoke(workspace.clj:757)
    at editor.workspace$resource_sync_BANG_.invokeStatic(workspace.clj:751)
    at editor.disk$start_reload_job_BANG_$fn$fn.invoke(disk.clj:89)
    at clojure.lang.AFn.run(AFn.java:22)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:456)
    at java.security.AccessController.doPrivileged(AccessController.java:399)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:455)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
    at com.sun.glass.ui.gtk.GtkApplication._runLoop(GtkApplication.java)
    at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$10(GtkApplication.java:264)
    at java.lang.Thread.run(Thread.java:833)

**Comment by britzl** [comment]
Can you reproduce this? If so, what are the steps to reproduce?

**Comment by AGulev** [comment]
The requested additional information wasn't provided. We are closing the issue for now, as it cannot be fixed without further context. 

Feel free to reopen the issue when you are able to provide the requested information.
