### ISSUE TITLE
Drag and Drop Acting Up Again

### ISSUE THREAD

**Issue by bar1tech** [defold/defold#9354]
### Expected behavior
When we drag images into the Project Assets Pane we expect no errors thrown.

### Actual behavior
When we drag images into the Project Assets Pane an error pop-up is thrown.

### Steps to reproduce
Drag images from the Desktop into the Project Assets Pane.  This is probably a macOS exclusive and we've reported it before.  However, it only happens intermittently.  This is more of a nuisance since the images are added to the Project Assets Pane.

<hr/>

<table>
<tr><td>Build time</td><td>2024-08-22T07:44:18.524313</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>8a536ed1046ca0190e22eb47f78cb59e840a92a7</td></tr>
<tr><td>Defold engine sha</td><td>3251ca82359cf238a1074e383281e3126547d50b</td></tr>
<tr><td>Defold version</td><td>1.9.2</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"e180bb15b8964d24acf4f9260d766435"'>e180bb15b8964d24acf4f9260d766435</a></td></tr>
<tr><td>GPU</td><td>Apple M1 Max</td></tr>
<tr><td>GPU Driver</td><td>2.1 Metal - 88.1</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>14.6.1</td></tr>
<table>

**Comment by AGulev** [comment]
Error:
```
com.sun.glass.ui.View$2.flush.class java.lang.UnsupportedOperationException: Flush is forbidden from target!
    at com.sun.glass.ui.View$2.flush(View.java:1017)
    at com.sun.javafx.tk.quantum.QuantumClipboard.flush(QuantumClipboard.java:275)
    at com.sun.javafx.tk.quantum.QuantumToolkit.startDrag(QuantumToolkit.java:1326)
    at javafx.scene.Scene$DnDGesture.dragDetectedProcessed(Scene.java:3171)
    at javafx.scene.Scene$DnDGesture.process(Scene.java:3240)
    at javafx.scene.Scene$MouseHandler.process(Scene.java:4003)
    at javafx.scene.Scene.processMouseEvent(Scene.java:1893)
    at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2711)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:411)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:301)
    at java.security.AccessController.doPrivileged(AccessController.java:399)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:450)
    at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:430)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:449)
    at com.sun.glass.ui.View.handleMouseEvent(View.java:551)
    at com.sun.glass.ui.View.notifyMouse(View.java:937)
    at com.sun.glass.ui.mac.MacView.notifyMouse(MacView.java:127)
