### ISSUE TITLE
Source file crashed editor after text delete attempt

### ISSUE THREAD

**Issue by jcbk101** [defold/defold#9372]
### Expected behaviour
Selected text gets deleted

### Actual behaviour
Editor crashes, now source file will not open without editor error dialog box.

### Steps to reproduce
After selecting a block of text, press delete key to erase text.
<hr/>

<table>
<tr><td>Build time</td><td>2024-07-22T09:24:02.748379</td></tr>
<tr><td>Defold channel</td><td>beta</td></tr>
<tr><td>Defold editor sha</td><td>3be87d89fd5a93a63f527351fbedb84f8a875812</td></tr>
<tr><td>Defold engine sha</td><td>3be87d89fd5a93a63f527351fbedb84f8a875812</td></tr>
<tr><td>Defold version</td><td>1.9.1</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"aae88253b4cc4551848244bdb915f8d8"'>aae88253b4cc4551848244bdb915f8d8</a></td></tr>
<tr><td>GPU</td><td>GeForce GT 730/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 456.71</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by britzl** [comment]
```
clojure.lang.PersistentVector.arrayFor.class java.lang.IndexOutOfBoundsException: null
    at clojure.lang.PersistentVector.arrayFor(PersistentVector.java:158)
    at clojure.lang.PersistentVector.nth(PersistentVector.java:162)
    at clojure.lang.APersistentVector.invoke(APersistentVector.java:293)
    at editor.code.data$text_start.invokeStatic(data.clj:1246)
    at editor.code.data$execution_marker.invokeStatic(data.clj:2293)
    at editor.code.view$fn$fn.invoke(view.clj:836)
    at clojure.core$map$fn$fn.invoke(core.clj:2742)
    at clojure.core$filter$fn$fn.invoke(core.clj:2806)
    at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
    at clojure.core$transduce.invokeStatic(core.clj:6883)
    at clojure.core$into.invokeStatic(core.clj:6899)
    at editor.code.view$fn.invokeStatic(view.clj:832)
    at editor.code.view$fn.invoke(view.clj:831)
    at clojure.lang.AFn.applyToHelper(AFn.java:154)
    at clojure.lang.AFn.applyTo(AFn.java:144)
    at clojure.lang.AFunction$1.doInvoke(AFunction.java:31)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at clojure.lang.Var.invoke(Var.java:384)
    at editor.code.view$CodeEditorView$behavior$execution_markers$fn.invoke(view.clj:1015)
    at internal.node$trace_expr.invokeStatic(node.clj:46)
    at editor.code.view$CodeEditorView$behavior$execution_markers.invokeStatic(view.clj:1015)
    at editor.code.view$CodeEditorView$behavior$execution_markers.invoke(view.clj:1015)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:313)
    at editor.code.view$CodeEditorView$behavior$canvas_repaint_info$fn.invoke(view.clj:1015)
    at internal.node$trace_expr.invokeStatic(node.clj:46)
    at editor.code.view$CodeEditorView$behavior$canvas_repaint_info.invokeStatic(view.clj:1015)
    at editor.code.view$CodeEditorView$behavior$canvas_repaint_info.invoke(view.clj:1015)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:313)
    at internal.node$node_value.invokeStatic(node.clj:474)
    at internal.system$node_value.invokeStatic(system.clj:388)
    at dynamo.graph$do_node_value.invokeStatic(graph.clj:889)
    at dynamo.graph$node_value.invokeStatic(graph.clj:892)
    at editor.code.view$repaint_view_BANG_.invokeStatic(view.clj:3057)
    at editor.code.view$make_view_BANG_$fn.invoke(view.clj:3660)
    at clojure.lang.AFn.run(AFn.java:22)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:456)
    at java.security.AccessController.doPrivileged(AccessController.java:399)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:455)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
    at com.sun.glass.ui.win.WinApplication._runLoop(WinApplication.java)
    at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:184)
    at java.lang.Thread.run(Thread.java:833)
```

**Comment by britzl** [comment]
Does this happen frequently? Can you share steps to reproduce?

**Comment by jcbk101** [comment]
This only happened once since I've been using defold and that was the first. Note, I keep my PC and Defold running for days at a time.

All I did was open the source in the editor, scrolled down, selected the text and attempted to delete it.


________________________________

**Comment by AGulev** [comment]
it's not enough info to be able to reproduce the issue and fix it. 
If you will find a way to reproduce it, feel free to reopen it
