### ISSUE TITLE
Editor Freezing on macOS when many code views are open

### ISSUE THREAD

**Issue by bar1tech** [defold/defold#9394]
### Expected behaviour

I can open any number of files in the editor without the editor freezing.

### Actual behaviour

With the latest Defold Patch I installed this morning, the editor freezes after I opened 8 script files. The last script I open appears blank.  If I try to open the Help > About window that appears pitch black, If I try to buildit builds but I don't get the blue progress bar in the lower corner. Once the editor freezes the finder menus appear but I can't open any other files.  Defold > Quit Defold does exit gracefully.  This is probably reported elsewhere so I'm just chiming in with my UX. 

### Steps to reproduce

Open the most recently patched version of Defold on an M1 macOS and then open as many files in the editor as it takes for the freeze.

<hr/>

<table>
<tr><td>Build time</td><td>2024-09-06T18:08:23.700242</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>5b1a5372e6c9111b4842fa191e193c666c6cc72e</td></tr>
<tr><td>Defold engine sha</td><td>3251ca82359cf238a1074e383281e3126547d50b</td></tr>
<tr><td>Defold version</td><td>1.9.2</td></tr>
<tr><td>GPU</td><td>Apple M1 Max</td></tr>
<tr><td>GPU Driver</td><td>2.1 Metal - 88.1</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>14.6.1</td></tr>
<table>

**Comment by bar1tech** [comment]
I opened the atlas, a collection, and a game object, then opened 8 script files and the last script file was blank.  I cannot switch tabs to other open files.  The build seems to take longer than expected.  All UI interactions are disabled.

**Comment by bar1tech** [comment]
[Screenshot 2024-09-07 at 11.00.46 AM.png.pdf](https://github.com/user-attachments/files/16918787/Screenshot.2024-09-07.at.11.00.46.AM.png.pdf)

**Comment by bar1tech** [comment]
https://github.com/user-attachments/assets/cff960d2-3d67-4bab-a62e-fdd380750b4f

**Comment by AGulev** [comment]
@bar1tech thank you! let me try to reproduce it again

**Comment by AGulev** [comment]
Here we go! 
I caught it with logs here:
[log.txt.zip](https://github.com/user-attachments/files/16918882/log.txt.zip)

```
java.lang.NullPointerException: Cannot invoke "com.sun.prism.RTTexture.createGraphics()" because "<local9>" is null
	at com.sun.javafx.sg.prism.NGCanvas$RenderBuf.validate(NGCanvas.java:214)
	at com.sun.javafx.sg.prism.NGCanvas.initCanvas(NGCanvas.java:644)
	at com.sun.javafx.sg.prism.NGCanvas.renderContent(NGCanvas.java:607)
	at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2074)
	at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1966)
	at com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:270)
	at com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:579)
	at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2074)
	at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1966)
	at com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:270)
	at com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:579)
	at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2074)
	at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1966)
	at com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:270)
	at com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:579)
	at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2074)
	at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1966)
	at com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:270)
	at com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:579)
	at com.sun.javafx.sg.prism.NGNode.renderForClip(NGNode.java:2315)
	at com.sun.javafx.sg.prism.NGNode.renderRectClip(NGNode.java:2209)
	at com.sun.javafx.sg.prism.NGNode.renderClip(NGNode.java:2235)
	at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2068)
	at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1966)
	at com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:270)
	at com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:579)
	at com.sun.javafx.sg.prism.NGNode.renderForClip(NGNode.java:2315)
	at com.sun.javafx.sg.prism.NGNode.renderRectClip(NGNode.java:2209)
	at com.sun.javafx.sg.prism.NGNode.renderClip(NGNode.java:2235)
	at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2068)
	at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1966)
	at com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:270)
	at com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:579)
	at com.sun.javafx.sg.prism.NGNode.renderForClip(NGNode.java:2315)
	at com.sun.javafx.sg.prism.NGNode.renderRectClip(NGNode.java:2209)
	at com.sun.javafx.sg.prism.NGNode.renderClip(NGNode.java:2235)
	at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2068)
	at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1966)
	at com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:270)
	at com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:579)
	at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2074)
	at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1966)
	at com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:270)
	at com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:579)
	at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2074)
	at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1966)
	at com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:270)
	at com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:579)
	at com.sun.javafx.sg.prism.NGNode.renderForClip(NGNode.java:2315)
	at com.sun.javafx.sg.prism.NGNode.renderRectClip(NGNode.java:2209)
	at com.sun.javafx.sg.prism.NGNode.renderClip(NGNode.java:2235)
	at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2068)
	at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1966)
	at com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:270)
	at com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:579)
	at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2074)
	at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1966)
	at com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:270)
	at com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:579)
	at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2074)
	at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1966)
	at com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:270)
	at com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:579)
	at com.sun.javafx.sg.prism.NGNode.renderForClip(NGNode.java:2315)
	at com.sun.javafx.sg.prism.NGNode.renderRectClip(NGNode.java:2209)
	at com.sun.javafx.sg.prism.NGNode.renderClip(NGNode.java:2235)
	at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2068)
	at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1966)
	at com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:270)
	at com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:579)
	at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2074)
	at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1966)
	at com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:270)
	at com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:579)
	at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2074)
	at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1966)
	at com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:270)
	at com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:579)
	at com.sun.javafx.sg.prism.NGNode.renderForClip(NGNode.java:2315)
	at com.sun.javafx.sg.prism.NGNode.renderRectClip(NGNode.java:2209)
	at com.sun.javafx.sg.prism.NGNode.renderClip(NGNode.java:2235)
	at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2068)
	at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1966)
	at com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:270)
	at com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:579)
	at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2074)
	at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1966)
	at com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:270)
	at com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:579)
	at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2074)
	at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1966)
	at com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:270)
	at com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:579)
	at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2074)
	at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1966)
	at com.sun.javafx.tk.quantum.ViewPainter.doPaint(ViewPainter.java:480)
	at com.sun.javafx.tk.quantum.ViewPainter.paintImpl(ViewPainter.java:321)
	at com.sun.javafx.tk.quantum.PresentingPainter.run(PresentingPainter.java:92)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at com.sun.javafx.tk.RenderJob.run(RenderJob.java:58)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:126)
	at java.base/java.lang.Thread.run(Thread.java:840)
	```
	
	Also, it's unrelated to the latest Defold update (I've just tested version before the latest changes and caught it as well)

**Comment by bar1tech** [comment]
So is it really a bug?  Typically I don't open files in rapid succession.  My normal workflow is to only open what I need and close what's not needed.  I usually work in tow tab panes and close what I don't need at the moment.  I think I was trying to get an idea of where most of the logic was in case I wanted to refactor.

**Comment by bar1tech** [comment]
In other words, my normal workflow doesn't freeze the editor.

**Comment by AGulev** [comment]
It is a bug.
I'm just saying that it's not related to the latest Defold update. I tested it on older Defold versions, and it happens there as well.
Since we haven't touched anything related to this area lately, I would assume it might be related to a macOS update. But I'm not sure right now, and we will investigate it further.

**Comment by AGulev** [comment]
Thank you for this report with all the additional info

**Comment by AGulev** [comment]
This JavaFx issue seems related https://bugs.openjdk.org/browse/JDK-8305654 (closed in favor of https://bugs.openjdk.org/browse/JDK-8296364)

**Comment by bar1tech** [comment]
Thank you for working on Saturday! The team seems to be 24/7 which is really something.  Have a great weekend if you can find time too and thanks for following up so quickly.

**Comment by AGulev** [comment]
More info about the problem:
https://chunky-dev.github.io/docs/support/troubleshooting/#javalangnullpointerexception-cannot-invoke-comsunprismrttexturecreategraphics-because-local9-is-null

https://stackoverflow.com/questions/65565209/nullpointers-in-javafx-when-using-a-large-canvas

**Comment by bar1tech** [comment]
So it is out of Defold's hands.

**Comment by britzl** [comment]
@bar1tech Are you using the Intel x86 version of the editor on your ARM mac?

**Comment by matgis** [comment]
It could be that JavaFX retains the VRAM allocated for each `Canvas`, even though the view is hidden? Maybe we need to destroy and recreate the `Canvas` views manually as they hide and show in the UI. 🤔

**Comment by bar1tech** [comment]
@britzl  I'm thinking yes, I just performed an update and grabbed this out of the file  editor2.2024-09-09.log:

`024-09-09 13:04:41.564 28490 [clojure-agent-send-off-pool-0] INFO  editor.updater - {:line 126, :message "Downloading update", :url "https://d.defold.com/archive/7b332ee8234aa1a5a7e4a54f36c4eae5c623d3d7/editor-alpha/editor2/Defold-x86_64-macos.zip", :file "/private/var/folders/6l/973q07z52h30_zhvfh4vp2lc0000gn/T/defold-update680842094520376036.zip"}`

The table at the beginning of this thread reads: OS arch | x86_64

If there is an arm64 where can I find that and apologies for not knowing at this point.  I've been updating the same version I started with from my initial site download (at least 15- 18 months or so).


[editor2.2024-09-09.log](https://github.com/user-attachments/files/16934015/editor2.2024-09-09.log)

<img width="498" alt="Screenshot 2024-09-09 at 1 06 11 PM" src="https://github.com/user-attachments/assets/45c9efa0-5210-4a80-99c7-a7f0f2fbc9c1">

**Comment by britzl** [comment]
> If there is an arm64 where can I find that and apologies for not knowing at this point

No worries. You can download an arm64 version from the download page (there is a drop-down on the macOS download button):

https://defold.com/download/

You can also download directly from GitHub:

https://github.com/defold/defold/releases/tag/1.9.2

**Comment by bar1tech** [comment]
> You can download an arm64 version from the download page...

Thanks, I reinstalled Defold using `Defold-arm64-macos.dmg`.  I had to delete the `Defold`  and `defoldlogs` folders in `Application Support` because Defold was hanging on launch. After that no problems.  

The editor freeze problem is still present in my arm64 installation.
