### ISSUE TITLE
Memory Issue?

### ISSUE THREAD

**Issue by xochitlhuicaci** [defold/defold#9399]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2024-08-30T12:43:21.963528</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>8a5478f8b67306dcc6b3e6ebf33e3b3114e430fd</td></tr>
<tr><td>Defold engine sha</td><td>3251ca82359cf238a1074e383281e3126547d50b</td></tr>
<tr><td>Defold version</td><td>1.9.2</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"c546f398e09b41a0976d46f545788029"'>c546f398e09b41a0976d46f545788029</a></td></tr>
<tr><td>GPU</td><td>AMD Radeon Pro 580 OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 ATI-4.14.1</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>13.6.7</td></tr>
<table>

**Comment by AGulev** [comment]
```
com.dynamo.bob.util.TextureUtil.extrudeBorders.class java.lang.OutOfMemoryError: Java heap space
    at com.dynamo.bob.util.TextureUtil.extrudeBorders(TextureUtil.java:141)
    at com.dynamo.bob.textureset.TextureSetGenerator.layoutImages(TextureSetGenerator.java:516)
    at editor.pipeline.texture_set_gen$layout_atlas_pages$fn.invoke(texture_set_gen.clj:80)
    at clojure.core$mapv$fn.invoke(core.clj:6912)
    at clojure.core.protocols$iter_reduce.invokeStatic(protocols.clj:49)
    at clojure.core.protocols$fn.invokeStatic(protocols.clj:75)
    at clojure.core.protocols$fn.invoke(protocols.clj:75)
    at clojure.core.protocols$fn$G__8068__8086.invoke(protocols.clj:13)
    at clojure.core$reduce.invokeStatic(core.clj:6828)
    at clojure.core$mapv.invokeStatic(core.clj:6903)
    at editor.pipeline.texture_set_gen$layout_atlas_pages.invokeStatic(texture_set_gen.clj:81)
    at editor.atlas$generate_packed_page_images.invokeStatic(atlas.clj:649)
    at editor.atlas$generate_packed_page_images.invoke(atlas.clj:641)
    at editor.atlas$call_generator.invokeStatic(atlas.clj:639)
    at editor.atlas$fn.invokeStatic(atlas.clj:829)
    at editor.atlas$fn.invoke(atlas.clj:829)
    at clojure.lang.AFn.applyToHelper(AFn.java:154)
    at clojure.lang.AFn.applyTo(AFn.java:144)
    at clojure.lang.AFunction$1.doInvoke(AFunction.java:31)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at clojure.lang.Var.invoke(Var.java:384)
    at editor.atlas$AtlasNode$behavior$packed_page_images$fn.invoke(atlas.clj:776)
    at internal.node$trace_expr.invokeStatic(node.clj:46)
    at editor.atlas$AtlasNode$behavior$packed_page_images.invokeStatic(atlas.clj:776)
    at editor.atlas$AtlasNode$behavior$packed_page_images.invoke(atlas.clj:776)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:313)
    at editor.atlas$AtlasNode$behavior$gpu_texture$fn.invoke(atlas.clj:776)
    at internal.node$trace_expr.invokeStatic(node.clj:46)
    at editor.atlas$AtlasNode$behavior$gpu_texture.invokeStatic(atlas.clj:776)
    at editor.atlas$AtlasNode$behavior$gpu_texture.invoke(atlas.clj:776)
    at clojure.lang.Var.invoke(Var.java:393)

**Comment by britzl** [comment]
Can you share a b it more about the setup? What is the size of the texture? Can you reproduce the error?

**Comment by xochitlhuicaci** [comment]
older computer, a mac.
2017.
3.8ghz quad intel core i5 processor
radeon pro 580, 8gb graphic
8gb 2400 mhz ddr4 memory

-the texture is about 4kx5.5k pixels, the atlases only get to be 20k pixels
before the error starts popping up.
so i've been making atlases that hold 3-5 images atm.
alongside that accessing or editing these files take 8+ seconds per
interaction.
So trying to make animations with them has been difficult.
New to this, so I likely am missing something or pulling some inefficiency.

**Comment by britzl** [comment]
> 8gb 2400 mhz ddr4 memory

This is on the lower end of the spectrum and if you are creating a very large atlas or tilesource it might not be enough. What is the size if the atlas that you are working with?

**Comment by xochitlhuicaci** [comment]
I'll try shrinking it down the assets and see if it helps with speed.
From a print/illustration background, so im used to working in 300+dpi
so i think i just need to adjust my perspective on filesize.

The atlases right now average around 16kx8k, and can only hold four or five
images.
Im going to cut the images to around 72dpi, try and work under 1500 pixels
per illustration, and see if that helps with speeds.
I'll report back if that solves my issue, thankyou for the help.

**Comment by britzl** [comment]
> The atlases right now average around 16kx8k

That's quite big!

16384x8192x4 = 536 870 912 bytes ... or half a gig of memory. You can add another 30% I think if you also enable mipmaps. And finally there will be a whole bunch of extra memory allocations if you resize or tweak any of the atlas settings.

How are you going to use the images? Do you really need such a large atlas? Could you split it into multiple atlases? Or load images at runtime?

**Comment by AGulev** [comment]
More likely related to https://github.com/defold/defold/issues/9605
