### ISSUE TITLE
<!-- NOTE! The information you specify will be publicly accessible. --> ### Expected behaviour

### ISSUE THREAD

**Issue by ezopsv** [defold/defold#9430]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2024-08-22T07:42:28.305676</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>8a536ed1046ca0190e22eb47f78cb59e840a92a7</td></tr>
<tr><td>Defold engine sha</td><td>3251ca82359cf238a1074e383281e3126547d50b</td></tr>
<tr><td>Defold version</td><td>1.9.2</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"7fddc47acf1b485aaf9bde2800f5e5b4"'>7fddc47acf1b485aaf9bde2800f5e5b4</a></td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce RTX 2060 SUPER/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 546.29</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by AGulev** [comment]
```
clojure.lang.PersistentVector.pop.class java.lang.IllegalStateException: Can't pop empty vector
    at clojure.lang.PersistentVector.pop(PersistentVector.java:470)
    at clojure.lang.PersistentVector.pop(PersistentVector.java:22)
    at clojure.lang.RT.pop(RT.java:751)
    at clojure.core$pop.invokeStatic(core.clj:1474)
    at editor.engine.build_errors$next_compilation_line$fn.invoke(build_errors.clj:284)
    at clojure.lang.ArraySeq.reduce(ArraySeq.java:111)
    at clojure.core$reduce.invokeStatic(core.clj:6827)
    at editor.engine.build_errors$next_compilation_line.invokeStatic(build_errors.clj:270)
    at editor.engine.build_errors$parse_compilation_log$fn.invoke(build_errors.clj:356)
    at editor.engine.build_errors$parse_compilation_log.invokeStatic(build_errors.clj:323)
    at editor.engine.build_errors$try_parse_compiler_error_causes.invokeStatic(build_errors.clj:404)
    at editor.engine.build_errors$build_error_causes.invokeStatic(build_errors.clj:477)
    at editor.engine.build_errors$exception__GT_error_value.invokeStatic(build_errors.clj:521)
    at editor.app_view$async_build_BANG_$phase_5_await_engine_build_BANG___64466$process_engine_build_results_on_ui_thread_BANG___64469.invoke(app_view.clj:1134)
    at editor.app_view$async_build_BANG_$run_on_background_thread_BANG___64432$fn$fn.invoke(app_view.clj:1060)
    at clojure.lang.AFn.run(AFn.java:22)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:456)
    at java.security.AccessController.doPrivileged(AccessController.java:399)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:455)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
    at com.sun.glass.ui.win.WinApplication._runLoop(WinApplication.java)
    at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:184)
    at java.lang.Thread.run(Thread.java:833)
    ```
