### ISSUE TITLE
game

### ISSUE THREAD

**Issue by alisultan759** [defold/defold#9431]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2024-09-16T09:12:12.178176</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>4bed75905b7e1ddc3d30907ad2c6e8fbce3741e3</td></tr>
<tr><td>Defold engine sha</td><td>e4aaff11f49c941fde1dd93883cf69c6b8abebe4</td></tr>
<tr><td>Defold version</td><td>1.9.3</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"3b563b4b56ac4faabe66e52e3405bbfa"'>3b563b4b56ac4faabe66e52e3405bbfa</a></td></tr>
<tr><td>GPU</td><td>Intel(R) HD Graphics 4000</td></tr>
<tr><td>GPU Driver</td><td>4.0.0 - Build 10.18.10.4252</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by AGulev** [comment]
```
java.io.FileOutputStream.open0.class java.io.FileNotFoundException: D:\Mobile game\.gitattributes (Системе не удается найти указанный путь)
    at java.io.FileOutputStream.open0(FileOutputStream.java)
    at java.io.FileOutputStream.open(FileOutputStream.java:293)
    at java.io.FileOutputStream.<init>(FileOutputStream.java:235)
    at java.io.FileOutputStream.<init>(FileOutputStream.java:184)
    at editor.welcome$expand_proj_zip_BANG_.invokeStatic(welcome.clj:250)
    at editor.welcome$show_welcome_dialog_BANG_$download_template_BANG___104534$fn.invoke(welcome.clj:649)
    at clojure.core$binding_conveyor_fn$fn.invoke(core.clj:2030)
    at clojure.lang.AFn.call(AFn.java:18)
    at java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    at java.lang.Thread.run(Thread.java:833)
    ```

**Comment by AGulev** [comment]
Closed as duplicate in fovor of https://github.com/defold/defold/issues/9449
