### ISSUE TITLE
Error choosing File | Search in Files

### ISSUE THREAD

**Issue by schlista** [defold/defold#9449]
### Expected behaviour
Search files
### Actual behaviour
Error pops up
### Steps to reproduce
Watch included video.

https://github.com/user-attachments/assets/8305613b-3ae5-4fb0-95d7-42f6e85a24a3

<hr/>

<table>
<tr><td>Build time</td><td>2024-09-18T06:37:05.372838</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>9c546b9847c68d50a21a8c6c5d7357ba1d9f32d1</td></tr>
<tr><td>Defold engine sha</td><td>e4aaff11f49c941fde1dd93883cf69c6b8abebe4</td></tr>
<tr><td>Defold version</td><td>1.9.3</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"6038f361d6ba49c38f641a3550b9f658"'>6038f361d6ba49c38f641a3550b9f658</a></td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce RTX 3080 Ti/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 561.09</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 11</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by AGulev** [comment]
Steps to reproduce:
1. open a project 
2. copy a file into the project, which can't be opened by the editor e.g. pdf
3. remove this file from the project
4. Open `Search in Files` menu

**Comment by AGulev** [comment]
```
java.io.FileInputStream.open0.class java.io.FileNotFoundException: D:\DefoldProjects\Rogue Craps\assets\images\Craps Table Pixel Art.png-autosave.kra (The system cannot find the file specified)
    at java.io.FileInputStream.open0(FileInputStream.java)
    at java.io.FileInputStream.open(FileInputStream.java:216)
    at java.io.FileInputStream.<init>(FileInputStream.java:157)
    at clojure.java.io$fn.invokeStatic(io.clj:229)
    at clojure.java.io$fn.invoke(io.clj:229)
    at clojure.java.io$fn$G__11372__11386.invoke(io.clj:69)
    at editor.resource.FileResource.make_input_stream(resource.clj:190)
    at editor.resource.FileResource.make_reader(resource.clj:191)
    at clojure.java.io$reader.invokeStatic(io.clj:102)
    at clojure.java.io$reader.doInvoke(io.clj:86)
    at clojure.lang.RestFn.invoke(RestFn.java:410)
    at util.text_util$binary_QMARK_.invokeStatic(text_util.clj:135)
    at util.text_util$binary_QMARK_.invoke(text_util.clj:125)
    at util.text_util$binary_QMARK_.invokeStatic(text_util.clj:131)
    at editor.resource$textual_QMARK_.invokeStatic(resource.clj:522)
    at editor.defold_project_search$make_search_data_future$fn$fn.invoke(defold_project_search.clj:46)
    at clojure.core$keep$fn$fn.invoke(core.clj:7325)
    at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
    at clojure.core$transduce.invokeStatic(core.clj:6883)
    at clojure.core$into.invokeStatic(core.clj:6899)
    at editor.defold_project_search$make_search_data_future$fn.invoke(defold_project_search.clj:35)
    at clojure.core$binding_conveyor_fn$fn.invoke(core.clj:2030)
    at clojure.lang.AFn.call(AFn.java:18)
    at java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    at java.lang.Thread.run(Thread.java:833)
    ```
