### ISSUE TITLE
i am getting error

### ISSUE THREAD

**Issue by ispirLee25** [defold/defold#9462]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2024-09-23T16:53:19.307053</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>c9a48ecb87fde211f84f8d7dff4fecedd628644a</td></tr>
<tr><td>Defold engine sha</td><td>e4aaff11f49c941fde1dd93883cf69c6b8abebe4</td></tr>
<tr><td>Defold version</td><td>1.9.3</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"f315d55577444c588642833ecb20d745"'>f315d55577444c588642833ecb20d745</a></td></tr>
<tr><td>GPU</td><td>Intel(R) HD Graphics 530</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 - Build 31.0.101.2111</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by AGulev** [comment]
```
editor.workspace$unpack_resource_BANG_.invokeStatic.class java.io.IOException: 
**Extension plugins needs updating.**
Please restart editor for these changes to take effect!
    at editor.workspace$unpack_resource_BANG_.invokeStatic(workspace.clj:645)
    at editor.workspace$unpack_resource_BANG_.invoke(workspace.clj:631)
    at editor.workspace$unpack_resource_BANG_.invokeStatic(workspace.clj:633)
    at editor.workspace$unpack_editor_plugins_BANG_$fn.invoke(workspace.clj:710)
    at clojure.core$run_BANG_$fn.invoke(core.clj:7715)
    at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
    at clojure.core$reduce.invokeStatic(core.clj:6827)
    at clojure.core$run_BANG_.invokeStatic(core.clj:7710)
    at editor.workspace$unpack_editor_plugins_BANG_.invokeStatic(workspace.clj:698)
    at editor.defold_project$reload_plugins_BANG_.invokeStatic(defold_project.clj:903)
    at editor.defold_project$handle_resource_changes.invokeStatic(defold_project.clj:914)
    at editor.defold_project.ProjectResourceListener.handle_changes(defold_project.clj:1128)
    at editor.workspace$resource_sync_BANG_$fn.invoke(workspace.clj:816)
    at editor.workspace$resource_sync_BANG_.invokeStatic(workspace.clj:810)
    at editor.disk$start_reload_job_BANG_$fn$fn.invoke(disk.clj:94)
    at clojure.lang.AFn.run(AFn.java:22)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:456)
    at java.security.AccessController.doPrivileged(AccessController.java:399)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:455)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
    at com.sun.glass.ui.win.WinApplication._runLoop(WinApplication.java)
    at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:184)
    at java.lang.Thread.run(Thread.java:833)
java.io.FileOutputStream.open0.class java.io.FileNotFoundException: C:\Users\MONSTER\Desktop\sample-runner-main\sample-runner-main\build\plugins\defold-spine\plugins\lib\x86_64-win32\libSpineExt.dll (Dosya başka bir işlem tarafından kullanıldığından bu işlem dosyaya erişemiyor)
    at java.io.FileOutputStream.open0(FileOutputStream.java)
    at java.io.FileOutputStream.open(FileOutputStream.java:293)
    at java.io.FileOutputStream.<init>(FileOutputStream.java:235)
    at java.io.FileOutputStream.<init>(FileOutputStream.java:184)
    at clojure.java.io$fn.invokeStatic(io.clj:319)
    at clojure.java.io$fn.invoke(io.clj:319)
    at clojure.lang.MultiFn.invoke(MultiFn.java:239)
    at clojure.java.io$copy.invokeStatic(io.clj:406)
    at clojure.java.io$copy.doInvoke(io.clj:391)
    at clojure.lang.RestFn.invoke(RestFn.java:425)
    at editor.workspace$unpack_resource_BANG_$fn.invoke(workspace.clj:640)
    at editor.workspace$unpack_resource_BANG_.invokeStatic(workspace.clj:639)
    at editor.workspace$unpack_resource_BANG_.invoke(workspace.clj:631)
    at editor.workspace$unpack_resource_BANG_.invokeStatic(workspace.clj:633)
    at editor.workspace$unpack_editor_plugins_BANG_$fn.invoke(workspace.clj:710)
    at clojure.core$run_BANG_$fn.invoke(core.clj:7715)
    at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
    at clojure.core$reduce.invokeStatic(core.clj:6827)
    at clojure.core$run_BANG_.invokeStatic(core.clj:7710)
    at editor.workspace$unpack_editor_plugins_BANG_.invokeStatic(workspace.clj:698)
    at editor.defold_project$reload_plugins_BANG_.invokeStatic(defold_project.clj:903)
    at editor.defold_project$handle_resource_changes.invokeStatic(defold_project.clj:914)
    at editor.defold_project.ProjectResourceListener.handle_changes(defold_project.clj:1128)
    at editor.workspace$resource_sync_BANG_$fn.invoke(workspace.clj:816)
    at editor.workspace$resource_sync_BANG_.invokeStatic(workspace.clj:810)
    at editor.disk$start_reload_job_BANG_$fn$fn.invoke(disk.clj:94)
    at clojure.lang.AFn.run(AFn.java:22)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:456)
    at java.security.AccessController.doPrivileged(AccessController.java:399)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:455)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
    at com.sun.glass.ui.win.WinApplication._runLoop(WinApplication.java)
    at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:184)
    at java.lang.Thread.run(Thread.java:833)
    ```

**Comment by JCash** [comment]
Re: C:\Users\MONSTER\Desktop\sample-runner-main\sample-runner-main\build\plugins\defold-spine\plugins\lib\x86_64-win32\libSpineExt.dll 

> Dosya başka bir işlem tarafından kullanıldığından bu işlem dosyaya erişemiyor

"This process cannot access the file because the file is being used by another process"

**Comment by AGulev** [comment]
Fixed in the latest version of the sample-runner: https://github.com/defold/sample-runner (spine extension and spine model updated to the latest version)
