### ISSUE TITLE
Shaders fail to compile in editor with new pipeline if certain conditions are met

### ISSUE THREAD

**Issue by Wolfe2x7** [defold/defold#9504]
**Describe the bug:**
When using the new shader pipeline, some particular conditions cause compilation to fail in the editor. It's unclear what exactly the error is, because there are no error messages for this.

**To Reproduce:**
I cannot describe the steps to reproduce the bug, because it affects different shaders in my project differently; I found no 100% consistent pattern. Maybe it involves `gl_FragCoord`? Maybe it involves `discard`? Maybe it involves ternaries? However, I was able to create a minimum reproduction project.

**Expected behavior:**
The material should be visible in the editor.

**Defold version:**
1.9.3 stable

**Platforms:**
Linux Mint 21.2 Cinnamon

**Minimal repro case project:**
[MinRepro-2024-9-28.zip](https://github.com/user-attachments/files/17173876/MinRepro-2024-9-28.zip)

**Comment by aglitchman** [comment]
There is an option to show editor logs to check what's wrong:
![image](https://github.com/user-attachments/assets/7d0cbf9d-537d-4b63-b3a8-439466e264f5)

I uncommented the last line in the .fp shader and the error is:
```
2024-09-30 00:07:47.900 93840 [JavaFX Application Thread] ERROR editor.scene - {:line 219, :pass #editor.gl.pass.RenderPass{:nm "opaque", :selection false, :model-transform true, :depth-clipping true}, :render-fn #object[editor.model_scene$render_mesh 0x3e200662 "editor.model_scene$render_mesh@3e200662"], :message "skipping renderable", :ex-data nil}
java.lang.ArithmeticException: Divide by zero
	at clojure.lang.Numbers.divide(Numbers.java:188)
	at clojure.lang.Numbers.divide(Numbers.java:3901)
	at editor.gl.vertex2.VertexBuffer.count(vertex2.clj:103)
	at clojure.lang.RT.count(RT.java:638)
	at editor.model_scene$render_mesh_opaque_impl.invokeStatic(model_scene.clj:223)
	at editor.model_scene$render_mesh_opaque.invokeStatic(model_scene.clj:229)
	at editor.model_scene$render_mesh.invokeStatic(model_scene.clj:240)
	at editor.model_scene$render_mesh.invoke(model_scene.clj:236)
	at editor.scene$render_nodes.invokeStatic(scene.clj:217)
	at editor.scene$batch_render.invokeStatic(scene.clj:245)
	at editor.scene$render_BANG_.invokeStatic(scene.clj:327)
	at editor.scene$update_image_view_BANG_$fn__61433.invoke(scene.clj:1215)
	at editor.scene$update_image_view_BANG_.invokeStatic(scene.clj:1212)
	at editor.scene$update_image_view_BANG_.invoke(scene.clj:1183)
	at editor.scene$refresh_scene_view_BANG_.invokeStatic(scene.clj:896)
	at editor.app_view$refresh_scene_views_BANG_$fn__67074.invoke(app_view.clj:1829)
	at editor.app_view$refresh_scene_views_BANG_.invokeStatic(app_view.clj:1829)
	at editor.app_view$make_app_view$fn__67114.invoke(app_view.clj:1948)
	at editor.ui$__GT_timer$fn__15688$fn__15689.invoke(ui.clj:2028)
	at clojure.lang.AFn.run(AFn.java:22)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:456)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:455)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:184)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by AGulev** [comment]
I've tested the provided example in 1.12.1 and it works now. If you'll be able to reproduce it again, please reopen this issue
