### ISSUE TITLE
Creating a project (First time)

### ISSUE THREAD

**Issue by fieldkim** [defold/defold#9507]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2024-07-22T11:01:54.608980</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>3be87d89fd5a93a63f527351fbedb84f8a875812</td></tr>
<tr><td>Defold engine sha</td><td>3be87d89fd5a93a63f527351fbedb84f8a875812</td></tr>
<tr><td>Defold version</td><td>1.9.1</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"93077313a83c4dd5bde4c6aa8545450a"'>93077313a83c4dd5bde4c6aa8545450a</a></td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce RTX 3070/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 561.09</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 11</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by AGulev** [comment]
```
java.io.FileOutputStream.open0.class java.io.FileNotFoundException: E:\DefoldGit\CardGame\ACardGame\.gitattributes (지정된 경로를 찾을 수 없습니다)
    at java.io.FileOutputStream.open0(FileOutputStream.java)
    at java.io.FileOutputStream.open(FileOutputStream.java:293)
    at java.io.FileOutputStream.<init>(FileOutputStream.java:235)
    at java.io.FileOutputStream.<init>(FileOutputStream.java:184)
    at editor.welcome$expand_proj_zip_BANG_.invokeStatic(welcome.clj:250)
    at editor.welcome$show_welcome_dialog_BANG_$download_template_BANG___104070$fn.invoke(welcome.clj:649)
    at clojure.core$binding_conveyor_fn$fn.invoke(core.clj:2030)
    at clojure.lang.AFn.call(AFn.java:18)
    at java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    at java.lang.Thread.run(Thread.java:833)
    ```

**Comment by britzl** [comment]
Are the rest of the files available in`E:\DefoldGit\CardGame\ACardGame` or is the folder empty? Do you have an antivirus which might prevent/block/delete dot files?

**Comment by AGulev** [comment]
Related: https://github.com/defold/defold/issues/5327

**Comment by AGulev** [comment]
Requested info wasn't provided. If you are able to provide more info, please feel free to reopen the issue
