### ISSUE TITLE
Impossible to add new gamepads from inside the editor itself on Linux

### ISSUE THREAD

**Issue by wfzyx** [defold/defold#9591]
### Expected behaviour

Being able to add new gamepads on the .gamepads form editor

### Actual behaviour

Not possible at all - it crashes as soon as you try adding a new one with the context menu `Add` option

### Steps to reproduce

- Open any gamepads file such as the builtin default.gamepads 
- Go into the gamepad list
- Right click to open the context menu
- Select Add
- Crash: clojure.lang.ExceptionInfo: Replace forbidden

<hr/>

<table>
<tr><td>Build time</td><td>2024-07-22T10:59:47.912057</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>3be87d89fd5a93a63f527351fbedb84f8a875812</td></tr>
<tr><td>Defold engine sha</td><td>3be87d89fd5a93a63f527351fbedb84f8a875812</td></tr>
<tr><td>Defold version</td><td>1.9.1</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"3101c084391d49beb83ac57d654c3657"'>3101c084391d49beb83ac57d654c3657</a></td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce RTX 2080 SUPER/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 560.35.03</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>6.11.2-201.fsync.fc40.x86_64</td></tr>
<table>

**Comment by britzl** [comment]
```
cljfx.mutator$fn__1821.invokeStatic.class clojure.lang.ExceptionInfo: Replace forbidden
    at cljfx.mutator$fn.invokeStatic(mutator.clj:108)
    at cljfx.mutator$fn.invoke(mutator.clj:107)
    at cljfx.mutator$fn$G__1678__1698.invoke(mutator.clj:14)
    at cljfx.prop$replace_BANG_.invokeStatic(prop.clj:40)
    at cljfx.composite$advance_composite_component$fn$fn.invoke(composite.clj:64)
    at clojure.core.protocols$iter_reduce.invokeStatic(protocols.clj:49)
    at clojure.core.protocols$fn.invokeStatic(protocols.clj:75)
    at clojure.core.protocols$fn.invoke(protocols.clj:75)
    at clojure.core.protocols$fn$G__8068__8086.invoke(protocols.clj:13)
    at clojure.core$reduce.invokeStatic(core.clj:6828)
    at cljfx.composite$advance_composite_component$fn.invoke(composite.clj:52)
    at clojure.core$update.invokeStatic(core.clj:6196)
    at cljfx.composite$advance_composite_component.invokeStatic(composite.clj:46)
    at cljfx.composite$advance_composite_component.invoke(composite.clj:43)
    at cljfx.lifecycle$fn$G__2451__2469.invoke(lifecycle.clj:17)
    at cljfx.lifecycle$reify$fn.invoke(lifecycle.clj:48)
    at clojure.core$update.invokeStatic(core.clj:6196)
    at cljfx.lifecycle$reify.advance(lifecycle.clj:46)
    at cljfx.lifecycle$if_desc$reify$fn.invoke(lifecycle.clj:656)
    at clojure.core$update.invokeStatic(core.clj:6196)
    at cljfx.lifecycle$if_desc$reify.advance(lifecycle.clj:655)
    at cljfx.composite$advance_composite_component$fn$fn.invoke(composite.clj:64)
    at clojure.core.protocols$iter_reduce.invokeStatic(protocols.clj:49)
    at clojure.core.protocols$fn.invokeStatic(protocols.clj:75)
    at clojure.core.protocols$fn.invoke(protocols.clj:75)
    at clojure.core.protocols$fn$G__8068__8086.invoke(protocols.clj:13)
    at clojure.core$reduce.invokeStatic(core.clj:6828)
    at cljfx.composite$advance_composite_component$fn.invoke(composite.clj:52)
    at clojure.core$update.invokeStatic(core.clj:6196)
    at cljfx.composite$advance_composite_component.invokeStatic(composite.clj:46)
    at cljfx.composite$advance_composite_component.invoke(composite.clj:43)
    at cljfx.lifecycle$fn$G__2451__2469.invoke(lifecycle.clj:17)
    at cljfx.lifecycle$reify$fn.invoke(lifecycle.clj:48)
    at clojure.core$update.invokeStatic(core.clj:6196)
    at cljfx.lifecycle$reify.advance(lifecycle.clj:46)
    at cljfx.lifecycle$wrap_dynamic_fn$fn$fn.invoke(lifecycle.clj:90)
    at clojure.core$update.invokeStatic(core.clj:6196)
    at cljfx.lifecycle$wrap_dynamic_fn$fn.invoke(lifecycle.clj:82)
    at cljfx.lifecycle$fn$G__2451__2469.invoke(lifecycle.clj:17)
    at cljfx.lifecycle$reify$fn.invoke(lifecycle.clj:48)
    at clojure.core$update.invokeStatic(core.clj:6196)
    at cljfx.lifecycle$reify.advance(lifecycle.clj:46)
    at cljfx.lifecycle$wrap_dynamic_fn$fn$fn.invoke(lifecycle.clj:90)
    at clojure.core$update.invokeStatic(core.clj:6196)
    at cljfx.lifecycle$wrap_dynamic_fn$fn.invoke(lifecycle.clj:82)
    at cljfx.lifecycle$fn$G__2451__2469.invoke(lifecycle.clj:17)
    at editor.fxui$fn.invokeStatic(fxui.clj:98)
    at editor.fxui$fn.invoke(fxui.clj:93)
    at cljfx.lifecycle$fn$G__2451__2469.invoke(lifecycle.clj:17)
    at cljfx.lifecycle$reify$fn.invoke(lifecycle.clj:48)
    at clojure.core$update.invokeStatic(core.clj:6196)
    at cljfx.lifecycle$reify.advance(lifecycle.clj:46)
    at cljfx.lifecycle$wrap_extra_props$fn.invoke(lifecycle.clj:372)
    at cljfx.lifecycle$fn$G__2451__2469.invoke(lifecycle.clj:17)
    at cljfx.lifecycle$wrap_many$fn$fn.invoke(lifecycle.clj:302)
    at clojure.core.protocols$iter_reduce.invokeStatic(protocols.clj:49)
    at clojure.core.protocols$fn.invokeStatic(protocols.clj:75)
    at clojure.core.protocols$fn.invoke(protocols.clj:75)
    at clojure.core.protocols$fn$G__8068__8086.invoke(protocols.clj:13)
    at clojure.core$reduce.invokeStatic(core.clj:6828)
    at cljfx.lifecycle$wrap_many$fn.invoke(lifecycle.clj:294)
    at cljfx.lifecycle$fn$G__2451__2469.invoke(lifecycle.clj:17)
    at cljfx.composite$advance_composite_component$fn$fn.invoke(composite.clj:64)
    at clojure.core.protocols$iter_reduce.invokeStatic(protocols.clj:49)
    at clojure.core.protocols$fn.invokeStatic(protocols.clj:75)
    at clojure.core.protocols$fn.invoke(protocols.clj:75)
    at clojure.core.protocols$fn$G__8068__8086.invoke(protocols.clj:13)
    at clojure.core$reduce.invokeStatic(core.clj:6828)
    at cljfx.composite$advance_composite_component$fn.invoke(composite.clj:52)
    at clojure.core$update.invokeStatic(core.clj:6196)
    at cljfx.composite$advance_composite_component.invokeStatic(composite.clj:46)
    at cljfx.composite$advance_composite_component.invoke(composite.clj:43)
    at cljfx.lifecycle$fn$G__2451__2469.invoke(lifecycle.clj:17)
    at cljfx.lifecycle$reify$fn.invoke(lifecycle.clj:48)
    at clojure.core$update.invokeStatic(core.clj:6196)
    at cljfx.lifecycle$reify.advance(lifecycle.clj:46)
    at cljfx.lifecycle$wrap_extra_props$fn.invoke(lifecycle.clj:372)
    at cljfx.lifecycle$fn$G__2451__2469.invoke(lifecycle.clj:17)
    at cljfx.lifecycle$wrap_many$fn$fn.invoke(lifecycle.clj:302)
    at clojure.core.protocols$iter_reduce.invokeStatic(protocols.clj:49)
    at clojure.core.protocols$fn.invokeStatic(protocols.clj:75)
    at clojure.core.protocols$fn.invoke(protocols.clj:75)
    at clojure.core.protocols$fn$G__8068__8086.invoke(protocols.clj:13)
    at clojure.core$reduce.invokeStatic(core.clj:6828)
    at cljfx.lifecycle$wrap_many$fn.invoke(lifecycle.clj:294)
    at cljfx.lifecycle$fn$G__2451__2469.invoke(lifecycle.clj:17)
    at cljfx.composite$advance_composite_component$fn$fn.invoke(composite.clj:64)
    at clojure.core.protocols$iter_reduce.invokeStatic(protocols.clj:49)
    at clojure.core.protocols$fn.invokeStatic(protocols.clj:75)
    at clojure.core.protocols$fn.invoke(protocols.clj:75)
    at clojure.core.protocols$fn$G__8068__8086.invoke(protocols.clj:13)
    at clojure.core$reduce.invokeStatic(core.clj:6828)
    at cljfx.composite$advance_composite_component$fn.invoke(composite.clj:52)
    at clojure.core$update.invokeStatic(core.clj:6196)
    at cljfx.composite$advance_composite_component.invokeStatic(composite.clj:46)
    at cljfx.composite$advance_composite_component.invoke(composite.clj:43)
    at cljfx.lifecycle$fn$G__2451__2469.invoke(lifecycle.clj:17)
    at cljfx.lifecycle$reify$fn.invoke(lifecycle.clj:48)
    at clojure.core$update.invokeStatic(core.clj:6196)
    at cljfx.lifecycle$reify.advance(lifecycle.clj:46)
    at cljfx.lifecycle$wrap_extra_props$fn.invoke(lifecycle.clj:372)
    at cljfx.lifecycle$fn$G__2451__2469.invoke(lifecycle.clj:17)
    at cljfx.lifecycle$wrap_many$fn$fn.invoke(lifecycle.clj:302)
    at clojure.core.protocols$iter_reduce.invokeStatic(protocols.clj:49)
    at clojure.core.protocols$fn.invokeStatic(protocols.clj:75)
    at clojure.core.protocols$fn.invoke(protocols.clj:75)
    at clojure.core.protocols$fn$G__8068__8086.invoke(protocols.clj:13)
    at clojure.core$reduce.invokeStatic(core.clj:6828)
    at cljfx.lifecycle$wrap_many$fn.invoke(lifecycle.clj:294)
    at cljfx.lifecycle$fn$G__2451__2469.invoke(lifecycle.clj:17)
    at cljfx.composite$advance_composite_component$fn$fn.invoke(composite.clj:64)
    at clojure.core.protocols$iter_reduce.invokeStatic(protocols.clj:49)
    at clojure.core.protocols$fn.invokeStatic(protocols.clj:75)
    at clojure.core.protocols$fn.invoke(protocols.clj:75)
    at clojure.core.protocols$fn$G__8068__8086.invoke(protocols.clj:13)
    at clojure.core$reduce.invokeStatic(core.clj:6828)
    at cljfx.composite$advance_composite_component$fn.invoke(composite.clj:52)
    at clojure.core$update.invokeStatic(core.clj:6196)
    at cljfx.composite$advance_composite_component.invokeStatic(composite.clj:46)
    at cljfx.composite$advance_composite_component.invoke(composite.clj:43)
    at cljfx.lifecycle$fn$G__2451__2469.invoke(lifecycle.clj:17)
    at cljfx.lifecycle$reify$fn.invoke(lifecycle.clj:48)
    at clojure.core$update.invokeStatic(core.clj:6196)
    at cljfx.lifecycle$reify.advance(lifecycle.clj:46)
    at cljfx.lifecycle$wrap_dynamic_fn$fn$fn.invoke(lifecycle.clj:90)
    at clojure.core$update.invokeStatic(core.clj:6196)
    at cljfx.lifecycle$wrap_dynamic_fn$fn.invoke(lifecycle.clj:82)
    at cljfx.lifecycle$fn$G__2451__2469.invoke(lifecycle.clj:17)
    at editor.fxui$fn.invokeStatic(fxui.clj:98)
    at editor.fxui$fn.invoke(fxui.clj:93)
    at cljfx.lifecycle$fn$G__2451__2469.invoke(lifecycle.clj:17)
    at cljfx.lifecycle$reify$fn.invoke(lifecycle.clj:48)
    at clojure.core$update.invokeStatic(core.clj:6196)
    at cljfx.lifecycle$reify.advance(lifecycle.clj:46)
    at cljfx.lifecycle$wrap_extra_props$fn.invoke(lifecycle.clj:372)
    at cljfx.lifecycle$fn$G__2451__2469.invoke(lifecycle.clj:17)
    at cljfx.lifecycle$wrap_many$fn$fn.invoke(lifecycle.clj:302)
    at clojure.core.protocols$iter_reduce.invokeStatic(protocols.clj:49)
    at clojure.core.protocols$fn.invokeStatic(protocols.clj:75)
    at clojure.core.protocols$fn.invoke(protocols.clj:75)
    at clojure.core.protocols$fn$G__8068__8086.invoke(protocols.clj:13)
    at clojure.core$reduce.invokeStatic(core.clj:6828)
    at cljfx.lifecycle$wrap_many$fn.invoke(lifecycle.clj:294)
    at cljfx.lifecycle$fn$G__2451__2469.invoke(lifecycle.clj:17)
    at cljfx.composite$advance_composite_component$fn$fn.invoke(composite.clj:64)
    at clojure.core.protocols$iter_reduce.invokeStatic(protocols.clj:49)
    at clojure.core.protocols$fn.invokeStatic(protocols.clj:75)
    at clojure.core.protocols$fn.invoke(protocols.clj:75)
    at clojure.core.protocols$fn$G__8068__8086.invoke(protocols.clj:13)
    at clojure.core$reduce.invokeStatic(core.clj:6828)
    at cljfx.composite$advance_composite_component$fn.invoke(composite.clj:52)
    at clojure.core$update.invokeStatic(core.clj:6196)
    at cljfx.composite$advance_composite_component.invokeStatic(composite.clj:46)
    at cljfx.composite$advance_composite_component.invoke(composite.clj:43)
    at cljfx.lifecycle$fn$G__2451__2469.invoke(lifecycle.clj:17)
    at cljfx.lifecycle$reify$fn.invoke(lifecycle.clj:48)
    at clojure.core$update.invokeStatic(core.clj:6196)
    at cljfx.lifecycle$reify.advance(lifecycle.clj:46)
    at cljfx.lifecycle$wrap_extra_props$fn.invoke(lifecycle.clj:372)
    at cljfx.lifecycle$fn$G__2451__2469.invoke(lifecycle.clj:17)
    at cljfx.lifecycle$wrap_many$fn$fn.invoke(lifecycle.clj:302)
    at clojure.core.protocols$iter_reduce.invokeStatic(protocols.clj:49)
    at clojure.core.protocols$fn.invokeStatic(protocols.clj:75)
    at clojure.core.protocols$fn.invoke(protocols.clj:75)
    at clojure.core.protocols$fn$G__8068__8086.invoke(protocols.clj:13)
    at clojure.core$reduce.invokeStatic(core.clj:6828)
    at cljfx.lifecycle$wrap_many$fn.invoke(lifecycle.clj:294)
    at cljfx.lifecycle$fn$G__2451__2469.invoke(lifecycle.clj:17)
    at cljfx.composite$advance_composite_component$fn$fn.invoke(composite.clj:64)
    at clojure.core.protocols$iter_reduce.invokeStatic(protocols.clj:49)
    at clojure.core.protocols$fn.invokeStatic(protocols.clj:75)
    at clojure.core.protocols$fn.invoke(protocols.clj:75)
    at clojure.core.protocols$fn$G__8068__8086.invoke(protocols.clj:13)
    at clojure.core$reduce.invokeStatic(core.clj:6828)
    at cljfx.composite$advance_composite_component$fn.invoke(composite.clj:52)
    at clojure.core$update.invokeStatic(core.clj:6196)
    at cljfx.composite$advance_composite_component.invokeStatic(composite.clj:46)
    at cljfx.composite$advance_composite_component.invoke(composite.clj:43)
    at cljfx.lifecycle$fn$G__2451__2469.invoke(lifecycle.clj:17)
    at cljfx.lifecycle$reify$fn.invoke(lifecycle.clj:48)
    at clojure.core$update.invokeStatic(core.clj:6196)
    at cljfx.lifecycle$reify.advance(lifecycle.clj:46)
    at cljfx.lifecycle$wrap_extra_props$fn.invoke(lifecycle.clj:372)
    at cljfx.lifecycle$fn$G__2451__2469.invoke(lifecycle.clj:17)
    at cljfx.lifecycle$wrap_many$fn$fn.invoke(lifecycle.clj:302)
    at clojure.core.protocols$iter_reduce.invokeStatic(protocols.clj:49)
    at clojure.core.protocols$fn.invokeStatic(protocols.clj:75)
    at clojure.core.protocols$fn.invoke(protocols.clj:75)
    at clojure.core.protocols$fn$G__8068__8086.invoke(protocols.clj:13)
    at clojure.core$reduce.invokeStatic(core.clj:6828)
    at cljfx.lifecycle$wrap_many$fn.invoke(lifecycle.clj:294)
    at cljfx.lifecycle$fn$G__2451__2469.invoke(lifecycle.clj:17)
    at cljfx.composite$advance_composite_component$fn$fn.invoke(composite.clj:64)
    at clojure.core.protocols$iter_reduce.invokeStatic(protocols.clj:49)
    at clojure.core.protocols$fn.invokeStatic(protocols.clj:75)
    at clojure.core.protocols$fn.invoke(protocols.clj:75)
    at clojure.core.protocols$fn$G__8068__8086.invoke(protocols.clj:13)
    at clojure.core$reduce.invokeStatic(core.clj:6828)
    at cljfx.composite$advance_composite_component$fn.invoke(composite.clj:52)
    at clojure.core$update.invokeStatic(core.clj:6196)
    at cljfx.lifecycle$fn$G__2451__2469.invoke(lifecycle.clj:17)
    at cljfx.lifecycle$wrap_many$fn$fn.invoke(lifecycle.clj:302)
    at clojure.core.protocols$iter_reduce.invokeStatic(protocols.clj:49)
    at clojure.core.protocols$fn.invokeStatic(protocols.clj:75)
    at clojure.core.protocols$fn.invoke(protocols.clj:75)
    at clojure.core.protocols$fn$G__8068__8086.invoke(protocols.clj:13)
    at clojure.core$reduce.invokeStatic(core.clj:6828)
    at cljfx.lifecycle$wrap_many$fn.invoke(lifecycle.clj:294)
    at cljfx.lifecycle$fn$G__2451__2469.invoke(lifecycle.clj:17)
    at cljfx.lifecycle$advance_prop_map$fn.invoke(lifecycle.clj:193)
    at clojure.core.protocols$iter_reduce.invokeStatic(protocols.clj:49)
    at clojure.core.protocols$fn.invokeStatic(protocols.clj:75)
    at clojure.core.protocols$fn.invoke(protocols.clj:75)
    at clojure.core.protocols$fn$G__8068__8086.invoke(protocols.clj:13)
    at clojure.core$reduce.invokeStatic(core.clj:6828)
    at cljfx.lifecycle$advance_prop_map.invokeStatic(lifecycle.clj:183)
    at cljfx.lifecycle$props_on$reify.advance(lifecycle.clj:391)
    at cljfx.lifecycle$make_ext_with_props$reify.advance(lifecycle.clj:424)
    at cljfx.lifecycle$reify$fn.invoke(lifecycle.clj:48)
    at clojure.core$update.invokeStatic(core.clj:6196)
    at cljfx.lifecycle$reify.advance(lifecycle.clj:46)
    at cljfx.lifecycle$wrap_dynamic_fn$fn$fn.invoke(lifecycle.clj:90)
    at clojure.core$update.invokeStatic(core.clj:6196)
    at cljfx.lifecycle$wrap_dynamic_fn$fn.invoke(lifecycle.clj:82)
    at cljfx.lifecycle$fn$G__2451__2469.invoke(lifecycle.clj:17)
    at cljfx.lifecycle$reify$fn.invoke(lifecycle.clj:48)
    at clojure.core$update.invokeStatic(core.clj:6196)
    at cljfx.lifecycle$reify.advance(lifecycle.clj:46)
    at cljfx.lifecycle$fn.invokeStatic(lifecycle.clj:64)
    at cljfx.lifecycle$fn.invoke(lifecycle.clj:62)
    at cljfx.lifecycle$fn$G__2451__2469.invoke(lifecycle.clj:17)
    at cljfx.lifecycle$wrap_map_desc$fn.invoke(lifecycle.clj:452)
    at cljfx.lifecycle$fn$G__2451__2469.invoke(lifecycle.clj:17)
    at editor.fxui$wrap_dedupe_desc$reify$fn.invoke(fxui.clj:286)
    at clojure.core$update.invokeStatic(core.clj:6196)
    at editor.fxui$wrap_dedupe_desc$reify.advance(fxui.clj:282)
    at cljfx.renderer$render_component.invokeStatic(renderer.clj:65)
    at cljfx.renderer$create$fn.invoke(renderer.clj:77)
    at cljfx.renderer$perform_render$fn.invoke(renderer.clj:23)
    at cljfx.renderer$perform_render.invokeStatic(renderer.clj:22)
    at cljfx.renderer$request_render$fn$fn.invoke(renderer.clj:46)
    at cljfx.renderer$request_render$fn.invoke(renderer.clj:46)
    at clojure.lang.AFn.run(AFn.java:22)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:456)
    at java.security.AccessController.doPrivileged(AccessController.java:399)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:455)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
    at com.sun.glass.ui.gtk.GtkApplication._runLoop(GtkApplication.java)
    at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$10(GtkApplication.java:264)
    at java.lang.Thread.run(Thread.java:833)
```

**Comment by vlaaad** [comment]
Fixed now, check for updates.
