### ISSUE TITLE
Cannot invoke "clojure.lang.IFn.invoke(Object)" because "settings" is null

### ISSUE THREAD

**Issue by DPelta-ms** [defold/defold#9596]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2024-07-29T18:23:25.696563</td></tr>
<tr><td>Defold channel</td><td>dev</td></tr>
<tr><td>Defold editor sha</td><td>d4994b939edd128407b3808160dd2decd9d31377</td></tr>
<tr><td>Defold engine sha</td><td>d4994b939edd128407b3808160dd2decd9d31377</td></tr>
<tr><td>Defold version</td><td>1.6.2</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"4b8b7a51d8104174a08f48641a32c1e7"'>4b8b7a51d8104174a08f48641a32c1e7</a></td></tr>
<tr><td>GPU</td><td>Apple M2 Max</td></tr>
<tr><td>GPU Driver</td><td>2.1 Metal - 88.1</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>aarch64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>14.6.1</td></tr>
<table>

**Comment by AGulev** [comment]
```
editor.app_view$refresh_app_title_BANG_.invokeStatic.class java.lang.NullPointerException: Cannot invoke "clojure.lang.IFn.invoke(Object)" because "settings" is null
    at editor.app_view$refresh_app_title_BANG_.invokeStatic(app_view.clj:1793)
    at editor.app_view$make_app_view$fn.invoke(app_view.clj:1925)
    at editor.ui$__GT_timer$fn$fn.invoke(ui.clj:1959)
    at clojure.lang.AFn.run(AFn.java:22)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:456)
    at java.security.AccessController.doPrivileged(AccessController.java:399)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:455)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
    at com.sun.glass.ui.mac.MacApplication._enterNestedEventLoopImpl(MacApplication.java)
    at com.sun.glass.ui.mac.MacApplication._enterNestedEventLoop(MacApplication.java:168)
    at com.sun.glass.ui.Application.enterNestedEventLoop(Application.java:515)
    at com.sun.glass.ui.EventLoop.enter(EventLoop.java:107)
    at com.sun.javafx.tk.quantum.QuantumToolkit.enterNestedEventLoop(QuantumToolkit.java:650)
    at javafx.application.Platform.enterNestedEventLoop(Platform.java:307)
    at editor.fxui$mount_renderer_and_await_result_BANG_.invokeStatic(fxui.clj:323)
    at editor.fxui$show_dialog_and_await_result_BANG_.invokeStatic(fxui.clj:328)
    at editor.dialogs$make_unexpected_error_dialog.invokeStatic(dialogs.clj:391)
    at editor.boot$notify_user$fn.invoke(boot.clj:86)
    at editor.ui$do_run_now$fn.invoke(ui.clj:307)
    at clojure.lang.AFn.run(AFn.java:22)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:456)
    at java.security.AccessController.doPrivileged(AccessController.java:399)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:455)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)

**Comment by AGulev** [comment]
It seems like duplicate of https://github.com/defold/defold/issues/9083 - more info here

**Comment by AGulev** [comment]
closed as duplicate of https://github.com/defold/defold/issues/9083 (because it has more info)
