### ISSUE TITLE
Fail to package and install emscripten SDK on Windows 10

### ISSUE THREAD

**Issue by redoak** [defold/defold#9621]
**Describe the bug (REQUIRED)**
With Defold tag 1.9.4, on Windows 10 in Git Bash, packaging and installing the emscripten SDK fails for two reasons:

- When running `$ ./scripts/package/package_emscripten.sh`
  The created tar.gz file gets the name emsdk-3.1.65-x86_64-mingw64_nt-10.0-19045.tar.gz. This is not what the `install_sdk` command expects, resulting in failure with "Could not find local file".
- When running `$ ./scripts/build.py install_sdk --platform=wasm-web` (after having manually renamed the above file to the expected emsdk-3.1.65-x86_64-win32.tar.gz)
  The script fails with "OSError: [WinError 193] %1 is not a valid Win32 application".

**To Reproduce (REQUIRED)**

1. Complete the Windows setup guide described in README_SETUP.md
2. In Git Bash, run `$ ./script/build.py shell`
3. Set DM_PACKAGES_URL, e.g. with `$ set DM_PACKAGES_URL=/c/dev/defold/local_sdks`
4. In Git Bash, run `$ ./scripts/package/package_emscripten.sh`
5. In Git Bash, run `$ ./scripts/build.py install_sdk --platform=wasm-web`
6. See error
7. Rename emsdk-3.1.65-x86_64-mingw64_nt-10.0-19045.tar.gz to emsdk-3.1.65-x86_64-win32.tar.gz
8. In Git Bash, run `$ ./scripts/build.py install_sdk --platform=wasm-web`
9. See error

**Expected behavior (REQUIRED)**
The package and install commands work out of the box.

**Defold version (REQUIRED):**
Defold 1.9.4 (commit 512763fd375633fd67197225e61fe90a5929166b)

**Platforms (REQUIRED):**
- OS: Windows 10, Version 10.0.19045
- Visual Studio 2022, Version 14.41.34120

**Logs (OPTIONAL):**
<details><summary>Output from ./scripts/package/package_emscripten.sh</summary>

```
$ ./scripts/package/package_emscripten.sh
/c/dev/defold/local_sdks/_tmpdir /c/dev/defold
--2024-10-21 19:08:37--  https://github.com/emscripten-core/emsdk/archive/3.1.65.tar.gz
Resolving github.com (github.com)... 4.225.11.194
Connecting to github.com (github.com)|4.225.11.194|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/emscripten-core/emsdk/tar.gz/refs/tags/3.1.65 [following]
--2024-10-21 19:08:37--  https://codeload.github.com/emscripten-core/emsdk/tar.gz/refs/tags/3.1.65
Resolving codeload.github.com (codeload.github.com)... 4.225.11.198
Connecting to codeload.github.com (codeload.github.com)|4.225.11.198|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 109082 (107K) [application/x-gzip]
Saving to: '3.1.65.tar.gz'

3.1.65.tar.gz                                                         100%[=========================================================================================================================================================================>] 106.53K  --.-KB/s    in 0.01s

2024-10-21 19:08:37 (10.3 MB/s) - '3.1.65.tar.gz' saved [109082/109082]

Resolving SDK alias 'latest' to '3.1.65'
Resolving SDK version '3.1.65' to 'sdk-releases-fdcf56c75a1d27fdff6525a7e03423595485ca19-64bit'
Installing SDK 'sdk-releases-fdcf56c75a1d27fdff6525a7e03423595485ca19-64bit'..
Installing tool 'node-18.20.3-64bit'..
Downloading: C:/dev/defold/local_sdks/_tmpdir/emsdk-3.1.65/downloads/node-v18.20.3-win-x64.zip from https://storage.googleapis.com/webassembly/emscripten-releases-builds/deps/node-v18.20.3-win-x64.zip, 30476796 Bytes
Unpacking 'C:/dev/defold/local_sdks/_tmpdir/emsdk-3.1.65/downloads/node-v18.20.3-win-x64.zip' to 'C:/dev/defold/local_sdks/_tmpdir/emsdk-3.1.65/node/18.20.3_64bit'
Done installing tool 'node-18.20.3-64bit'.
Installing tool 'python-3.9.2-nuget-64bit'..
Downloading: C:/dev/defold/local_sdks/_tmpdir/emsdk-3.1.65/downloads/python-3.9.2-4-amd64+pywin32.zip from https://storage.googleapis.com/webassembly/emscripten-releases-builds/deps/python-3.9.2-4-amd64+pywin32.zip, 14413267 Bytes
Unpacking 'C:/dev/defold/local_sdks/_tmpdir/emsdk-3.1.65/downloads/python-3.9.2-4-amd64+pywin32.zip' to 'C:/dev/defold/local_sdks/_tmpdir/emsdk-3.1.65/python/3.9.2-nuget_64bit'
Done installing tool 'python-3.9.2-nuget-64bit'.
Installing tool 'java-8.152-64bit'..
Downloading: C:/dev/defold/local_sdks/_tmpdir/emsdk-3.1.65/downloads/portable_jre_8_update_152_64bit.zip from https://storage.googleapis.com/webassembly/emscripten-releases-builds/deps/portable_jre_8_update_152_64bit.zip, 69241499 Bytes
Unpacking 'C:/dev/defold/local_sdks/_tmpdir/emsdk-3.1.65/downloads/portable_jre_8_update_152_64bit.zip' to 'C:/dev/defold/local_sdks/_tmpdir/emsdk-3.1.65/java/8.152_64bit'
Done installing tool 'java-8.152-64bit'.
Installing tool 'releases-fdcf56c75a1d27fdff6525a7e03423595485ca19-64bit'..
Downloading: C:/dev/defold/local_sdks/_tmpdir/emsdk-3.1.65/downloads/fdcf56c75a1d27fdff6525a7e03423595485ca19-wasm-binaries.zip from https://storage.googleapis.com/webassembly/emscripten-releases-builds/win/fdcf56c75a1d27fdff6525a7e03423595485ca19/wasm-binaries.zip, 523605271 Bytes
Unpacking 'C:/dev/defold/local_sdks/_tmpdir/emsdk-3.1.65/downloads/fdcf56c75a1d27fdff6525a7e03423595485ca19-wasm-binaries.zip' to 'C:/dev/defold/local_sdks/_tmpdir/emsdk-3.1.65/upstream'
[...]
Wrote /c/dev/defold/local_sdks/emsdk-3.1.65-x86_64-mingw64_nt-10.0-19045.tar.gz
```
</details>

<details><summary>Output from ./scripts/build.py install_sdk --platform=wasm-web</summary>

```
$ ./scripts/build.py install_sdk --platform=wasm-web
Couldn't find build_vendor.py. Skipping.
[exec] git remote get-url origin
Running 'install_sdk'
SDK already installed: C:\dev\defold\tmp\dynamo_home\ext\SDKs\Win32\WindowsKits\10
SDK already installed: C:\dev\defold\tmp\dynamo_home\ext\SDKs\Win32\MicrosoftVisualStudio14.0
Could not find local file: C:\dev\defold\local_sdks/emsdk-3.1.65-x86_64-win32.tar.gz
```
</details>

<details><summary>Output, after file rename, from ./scripts/build.py install_sdk --platform=wasm-web</summary>

```
$ ./scripts/build.py install_sdk --platform=wasm-web
Couldn't find build_vendor.py. Skipping.
[exec] git remote get-url origin
Running 'install_sdk'
SDK already installed: C:\dev\defold\tmp\dynamo_home\ext\SDKs\Win32\WindowsKits\10
SDK already installed: C:\dev\defold\tmp\dynamo_home\ext\SDKs\Win32\MicrosoftVisualStudio14.0
Extracting C:/dev/defold/local_sdks/emsdk-3.1.65-x86_64-win32.tar.gz to C:\dev\defold\tmp\dynamo_home\ext\SDKs\emsdk-3.1.65/
[exec] tar xfz C:/dev/defold/local_sdks/emsdk-3.1.65-x86_64-win32.tar.gz -C emsdk-3.1.65 --strip-components 1
Activating emsdk
[exec] C:\dev\defold\tmp\dynamo_home\ext\SDKs\emsdk-3.1.65\emsdk activate 3.1.65 --embedded
Traceback (most recent call last):
  File "C:\dev\defold\scripts\build.py", line 2525, in <module>
    f()
  File "C:\dev\defold\scripts\build.py", line 627, in install_sdk
    self._activate_ems(emsdk_folder, join(emsdk_folder, 'upstream', 'emscripten'), sdk.EMSCRIPTEN_VERSION_STR)
  File "C:\dev\defold\scripts\build.py", line 655, in _activate_ems
    run.env_command(self._form_env(), [join(emsdk, 'emsdk'), 'activate', version, '--embedded'])
  File "C:\dev\defold\build_tools\run.py", line 98, in env_command
    return _exec_command(args, shell = False, stdout = None, env = env, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\defold\build_tools\run.py", line 50, in _exec_command
    process = subprocess.Popen(arg_list, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eddie\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\eddie\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [WinError 193] %1 is not a valid Win32 application
```
</details>

**Comment by secondimpactrob** [comment]
This is one of the many issues I've run into trying to build Defold from source on a windows machine, it's clear that quite a few of the steps simply don't work.

On this particular issue, after renaming the file to fix the 'mingw' issue, the problem is that build.py is calling two different shell scripts as if they were windows programs. 'emsdk' and 'emcc'. It appears that the sdk provides equivalent .bat versions, and the process works if you change **scripts/build.py** to call these instead.

I.e.:

run.env_command(self.form_env(), [join(emsdk, '**emsdk**'), ....

becomes:

run.env_command(self.form_env(), [join(emsdk, '**emsdk.bat**'), ....

and likewise for the similar 'emcc' call a bit lower.


(Unrelated to the issue report, I had to make other edits to build.py to even get this stuff to run. I had to stop it trying to install the winsdk first, before the esmsdk, since that always fails due to version mismatches and causes the emsdk install to not even be attempted)

**Comment by paweljarosz** [comment]
Related: https://github.com/defold/defold/issues/9623
