### ISSUE TITLE
Editor displays error when script properties are overridden in collections

### ISSUE THREAD

**Issue by j-h-a** [defold/defold#9638]
`button.collection` has an object with button.script which has some script properties.
`room_x.collection` has one or more button collections embedded in it, some of the default button properties are overridden at this level
` level_x.collection` has the room_x collection plus some other objects, and overrides some button different properties at this level

Problem 1: When level is loaded, only the overrides from level.collection are applied - the ones in room_x are lost.
Problem 2: If you override the property again in level.collection, with the same value, then problem 1 goes away (it uses the overridden value) but now the editor behaves strangely, caching old versions of code changes and writing them back over source files even if you've edited them and saved elsewhere. It also pops up an error message sometimes (for example when editing an external source file and editor reloads it):
`clojure.lang.ExceptionInfo: Duplicate node key `affix_to_object` from :editor.code.script/ScriptPropertyNode`

<hr/>

<table>
<tr><td>Build time</td><td>2024-05-02T15:13:12.916151</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>acf09db558d18f7ccbbaa02c09333932f7cc8d4a</td></tr>
<tr><td>Defold engine sha</td><td>9141d9d3605e3f5d51c71293116d769da2613d39</td></tr>
<tr><td>Defold version</td><td>1.8.0</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"83f95adf3d944e4a880d83a5bf1ef21c"'>83f95adf3d944e4a880d83a5bf1ef21c</a></td></tr>
<tr><td>GPU</td><td>Apple M1 Pro</td></tr>
<tr><td>GPU Driver</td><td>2.1 Metal - 88.1</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>aarch64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>14.5</td></tr>
<table>

**Comment by AGulev** [comment]
please provide a minimal project where it's easy to see

**Comment by britzl** [comment]
```
dynamo.graph$collect_overridden_properties$fn__10571.invoke.class clojure.lang.ExceptionInfo: Duplicate node key `affix_to_object` from :editor.code.script/ScriptPropertyNode
    at dynamo.graph$collect_overridden_properties$fn.invoke(graph.clj:1415)
    at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
    at clojure.core$reduce.invokeStatic(core.clj:6827)
    at dynamo.graph$collect_overridden_properties.invokeStatic(graph.clj:1429)
    at editor.defold_project$perform_resource_change_plan$fn.invoke(defold_project.clj:502)
    at clojure.core$map$fn$fn.invoke(core.clj:2742)
    at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
    at clojure.core$transduce.invokeStatic(core.clj:6883)
    at clojure.core$into.invokeStatic(core.clj:6899)
    at editor.defold_project$perform_resource_change_plan.invokeStatic(defold_project.clj:506)
    at editor.defold_project$handle_resource_changes.invokeStatic(defold_project.clj:660)
    at editor.defold_project.ProjectResourceListener.handle_changes(defold_project.clj:853)
    at editor.workspace$resource_sync_BANG_$fn.invoke(workspace.clj:747)
    at editor.workspace$resource_sync_BANG_.invokeStatic(workspace.clj:737)
    at editor.disk$start_reload_job_BANG_$fn$fn.invoke(disk.clj:89)
    at clojure.lang.AFn.run(AFn.java:22)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:456)
    at java.security.AccessController.doPrivileged(AccessController.java:399)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:455)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
```

**Comment by AGulev** [comment]
Could you please provide a small project and steps how to reproduce this issue?
