### ISSUE TITLE
HTML5 build errors, Mustache related

### ISSUE THREAD

**Issue by 0xbeefbeef** [defold/defold#9639]
**Build errors (HTML5)**
From one day to another, my project stopped building HTML5 successfully. I tried going back to older commits, which I definitely know they worked. Same problem. Seems to be a problem related to Mustache, because i get the following build error:
> com.samskivert.mustache.MustacheException$Context: No method or field with name 'env' on line 1

Problems started when I first tried to change the Scale Mode in the game.project. From then on, I couldn't get my project to build HTML5 successfully. Other build targets work fine. Already deleted the build folder entirely, with no success :(

Any ideas are more then welcome :-)

**To Reproduce**
This is hard, I haven't found a way to reproduce this error in a minimal example. In other projects, with fewer dependencies, the error doesn't occur.  

**Expected behavior **
Successful HTML5 build 

**Defold version 1.7.0**
Because FMOD is unfortunately not working for Defold versions > 1.7.0, i have to stay at 1.7.0 for now.
In the game.project I have the following dependencies:
```
dependencies#0 = https://github.com/britzl/monarch/archive/refs/tags/5.1.1.zip
dependencies#1 = https://github.com/defold/extension-spine/archive/refs/tags/2.14.5.zip
dependencies#2 = https://github.com/britzl/defold-input/archive/master.zip
dependencies#3 = https://github.com/defold/extension-websocket/archive/3.0.0.zip
dependencies#4 = https://github.com/heroiclabs/nakama-defold/archive/refs/tags/v3.3.0.zip
dependencies#5 = https://github.com/subsoap/defsave/archive/master.zip
dependencies#6 = https://github.com/Melsoft-Games/defold-protobuf/archive/master.zip
dependencies#7 = https://github.com/dapetcu21/defold-fmod/archive/v2.6.1.zip
dependencies#8 = https://github.com/Insality/druid/archive/refs/tags/0.11.0.zip
dependencies#9 = https://github.com/subsoap/log/archive/master.zip
dependencies#10 = https://github.com/defold/extension-safearea/archive/master.zip
dependencies#11 = https://www.github.com/defold/extension-gpgs/archive/master.zip
dependencies#12 = https://github.com/britzl/defold-sharing/archive/refs/tags/4.3.1.zip
```
The html5 section is as follows:
```
splash_image = /assets/icon-512-maskable.png
show_console_banner = 0
wasm_streaming = 0
show_fullscreen_button = 0
show_made_with_defold = 0
heap_size = 512
htmlfile = /manifests/engine_template.html
cssfile = /builtins/manifests/web/dark_theme.css
```

**Platforms**
HTML5

**Logs**
```
com.samskivert.mustache.MustacheException$Context: No method or field with name 'env' on line 1
	at com.samskivert.mustache.Template.checkForMissing(Template.java:370)
	at com.samskivert.mustache.Template.getValue(Template.java:273)
	at com.samskivert.mustache.Template.getCompoundValue(Template.java:286)
	at com.samskivert.mustache.Template.getValue(Template.java:270)
	at com.samskivert.mustache.Template.getValueOrDefault(Template.java:318)
	at com.samskivert.mustache.Mustache$VariableSegment.execute(Mustache.java:1313)
	at com.samskivert.mustache.Template.executeSegs(Template.java:196)
	at com.samskivert.mustache.Template.execute(Template.java:139)
	at com.samskivert.mustache.Template.execute(Template.java:130)
	at com.defold.extender.TemplateExecutor.execute(TemplateExecutor.java:18)
	at com.defold.extender.Extender.<init>(Extender.java:268)
	at com.defold.extender.Extender.<init>(Extender.java:297)
	at com.defold.extender.AsyncBuilder.asyncBuildEngine(AsyncBuilder.java:102)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:355)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:113)
	at io.micrometer.context.ContextSnapshot.lambda$wrap$1(ContextSnapshot.java:106)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by ekharkunov** [comment]
Defold 1.7.0 uses Emscripten 2.0.11 for web build. It was removed from supported list with the last release (after update sdk we support old version only for 6 month).
So initial report is about "correct error message about unsupported version".
For your case you need to run Extender with Emscripten 2.0.11 yourself. You can use ready-to-use Docker image for that. Here is full path to pull image https://github.com/defold/extender/blob/dev/server/docker/docker-compose.yml#L59

**Comment by 0xbeefbeef** [comment]
Thanks for the fast reply! Unfortunatly, I don't fully understand how to get this running. I understand that I need to run that Extender as a docker container to get the Emscripten 2.0.11 support. But how do I have to build my project and use that container?

**Comment by ekharkunov** [comment]
> Thanks for the fast reply! Unfortunatly, I don't fully understand how to get this running. I understand that I need to run that Extender as a docker container to get the Emscripten 2.0.11 support. But how do I have to build my project and use that container?
> 
> Is this the right starting point:
> 
> https://defold.com/manuals/extender-local-setup/

Yes, it's a right instruction that you need. When you runs docker containers via `docker compose` you can go to Editor's settings and change build server url to `http://localhost:9000` (default url for locally run Extender)

**Comment by 0xbeefbeef** [comment]
Problem solved! Thank you so much, should have asked earlier ;-)

**Comment by 0xbeefbeef** [comment]
Problem solved! Thank you so much, should have asked earlier ;-)

**Comment by 0xbeefbeef** [comment]
Problem solved! Thank you so much, should have asked earlier ;-)
