### ISSUE TITLE
Error "Operation did not complete successfully because the file contains a virus or potentially unwanted software"

### ISSUE THREAD

**Issue by koushik0722** [defold/defold#9658]
`<!--` NOTE! The information you specify will be publicly accessible. -->
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2024-10-25T10:19:47.791131</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>182e33cbc33fc6db8a70a78f3648dd0fe5daf3a9</td></tr>
<tr><td>Defold engine sha</td><td>a9277779d1c23b0712a5959314b9508d2e802efb</td></tr>
<tr><td>Defold version</td><td>1.9.4</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"4dbf2d84c10c4d0285d0761e2923d406"'>4dbf2d84c10c4d0285d0761e2923d406</a></td></tr>
<tr><td>GPU</td><td>Intel(R) UHD Graphics</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 - Build 31.0.101.4502</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 11</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by britzl** [comment]
```
java.io.FileInputStream.open0.class java.io.FileNotFoundException: C:\Users\koush\AppData\Local\Temp\template-project1444792602913486489.zip (Operation did not complete successfully because the file contains a virus or potentially unwanted software)
    at java.io.FileInputStream.open0(FileInputStream.java)
    at java.io.FileInputStream.open(FileInputStream.java:216)
    at java.io.FileInputStream.<init>(FileInputStream.java:157)
    at clojure.java.io$fn.invokeStatic(io.clj:229)
    at clojure.java.io$fn.invoke(io.clj:229)
    at clojure.java.io$fn$G__11372__11386.invoke(io.clj:69)
    at clojure.java.io$input_stream.invokeStatic(io.clj:136)
    at clojure.java.io$input_stream.doInvoke(io.clj:121)
    at clojure.lang.RestFn.invoke(RestFn.java:410)
    at editor.welcome$expand_proj_zip_BANG_.invokeStatic(welcome.clj:228)
    at editor.welcome$show_welcome_dialog_BANG_$download_template_BANG___106228$fn.invoke(welcome.clj:635)
    at clojure.core$binding_conveyor_fn$fn.invoke(core.clj:2030)
    at clojure.lang.AFn.call(AFn.java:18)
    at java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    at java.lang.Thread.run(Thread.java:833)
```

**Comment by britzl** [comment]
It seems like your antivirus incorrectly prevents the editor from unpacking supporting files such as Lua compiler and shader compiler.

**Comment by FlexYourBrain** [comment]
Yesterday I had a user wanting to learn defold and they got to the point of creating a new project using the "desktop game template" then windows defender killed defold while creating the project from the downloaded temp project file.
![defold_template__desktop_win11](https://github.com/user-attachments/assets/dd12eead-d9f5-4892-9f6d-2288549d4081)

Had to workaround it by downloading the template from github directly then using that to create a project manually.

**Comment by britzl** [comment]
> We need to solve this by packaging the templates with Defold instead.

https://github.com/defold/defold/issues/3930
