### ISSUE TITLE
Building the engine sometimes fail on Windows 10, possibly related to MSVC vctip.exe process file locks

### ISSUE THREAD

**Issue by redoak** [defold/defold#9726]
**Describe the bug (REQUIRED)**

When building the Windows 10, seemingly by random, the build will fail. Building again right after will produce the same error. `distclean` and manual deletion of dynamo_home may fail as some files are locked by MSVC's vctip.exe. Waiting for ~10m and trying again may result in the same error in the same place, the same type of error but in another place, or a successful build.

**To Reproduce (REQUIRED)**

Run `./scripts/build.py build_engine`

Sometimes the error occurs. I was able to build without issue a number of times one day, but the next day I got this error multiple times.

**Expected behavior (REQUIRED)**

Deterministic build behavior.

**Defold version (REQUIRED):**

- Version: 1.9.5-alpha, 11/09/2024 09:24 AM, 4f13aa283b0964053981abb3d43d4569676304da

**Platforms (REQUIRED):**

- Platforms: Windows 10, 10.0.19045 Build 19045
- Microsoft Visual Studio Community 2022 17.11.4 (Compiler Version 19.41.34120)
- MSVC Build Tools 14.41.34120
- C++ Clang Compiler for Windows 17.0.3
- Python 3.12.6

**Logs (OPTIONAL):**

- [build_fail_log.txt](https://github.com/user-attachments/files/17715254/build_fail_log.txt) — Mostly complete log. The start is missing, as the terminal buffer wasn't large enough.
- [build_fail_log_2.txt](https://github.com/user-attachments/files/17715427/build_fail_log_2.txt) — After encountering the above error, a later retry got past the above error location but failed a bit later.
- [build_fail_log_3.txt](https://github.com/user-attachments/files/17715783/build_fail_log_3.txt) — After a retry resulting in a successful build, I later tried building again, and got this error only a handful of lines before the error shown in log_2.

Here's where the first one fails, which is the error location I've seen all but two times (the other two shown in log_2 and log_3):

```
test_gamesys.cpp
C:\dev\defold\tmp\dynamo_home\sdk\include\dmsdk\dlib\dalloca.h(33): warning C4005: 'alloca': macro redefinition
C:\Program Files (x86)\Windows Kits\10\include\10.0.20348.0\ucrt\malloc.h(176): note: see previous definition of 'alloca'

[569/569] Linking build\src\gamesys\test\test_gamesys.exe
LINK : warning LNK4044: unrecognized option '/O2'; ignored
   Creating library C:\dev\defold\engine\gamesys\build\src\gamesys\test\test_gamesys.lib and object C:\dev\defold\engine\gamesys\build\src\gamesys\test\test_gamesys.exp

Waf: Leaving directory `C:\dev\defold\engine\gamesys\build'
'build' finished successfully (18.603s)
Waf: Entering directory `C:\dev\defold\engine\gamesys\build'
Missing namespace definition in C:\dev\defold\engine\gamesys\src\dmsdk\gamesys\property.h
Missing namespace definition in C:\dev\defold\engine\gamesys\src\dmsdk\gamesys\components\comp_factory.h
Missing namespace definition in C:\dev\defold\engine\gamesys\src\dmsdk\gamesys\resources\res_font.h
[ 34/185] Compiling proto\gamesys\atlas_ddf.proto
+ install C:\dev\defold\tmp\dynamo_home\share\proto\gamesys\atlas_ddf.bproto (from build\proto\gamesys\atlas_ddf.bproto)
[...]
+ install C:\dev\defold\tmp\dynamo_home\lib\python\gamesys\__init__.py (from build\proto\gamesys\__init__.py)
Waf: Leaving directory `C:\dev\defold\engine\gamesys\build'
Build failed
Traceback (most recent call last):
  File "C:\dev\defold\tmp\dynamo_home\ext\bin\waf3-2.0.23-7dbdd0b348178777c338c9a31f6218a5\waflib\Build.py", line 598, in do_install
    self.copy_fun(src,tgt)
  File "C:\dev\defold\tmp\dynamo_home\ext\bin\waf3-2.0.23-7dbdd0b348178777c338c9a31f6218a5\waflib\Build.py", line 542, in copy_fun
    self.fix_perms(tgt)
  File "C:\dev\defold\tmp\dynamo_home\ext\bin\waf3-2.0.23-7dbdd0b348178777c338c9a31f6218a5\waflib\Build.py", line 612, in fix_perms
    os.chmod(tgt,self.chmod)
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\dev\\defold\\tmp\\dynamo_home\\lib\\python\\gamesys\\__init__.py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\dev\defold\tmp\dynamo_home\ext\bin\waf3-2.0.23-7dbdd0b348178777c338c9a31f6218a5\waflib\Task.py", line 180, in process
    ret=self.run()
        ^^^^^^^^^^
  File "C:\dev\defold\tmp\dynamo_home\ext\bin\waf3-2.0.23-7dbdd0b348178777c338c9a31f6218a5\waflib\Build.py", line 564, in run
    fun(x.abspath(),y.abspath(),x.path_from(launch_node))
  File "C:\dev\defold\tmp\dynamo_home\ext\bin\waf3-2.0.23-7dbdd0b348178777c338c9a31f6218a5\waflib\Build.py", line 604, in do_install
    raise Errors.WafError('Could not install the file %r'%tgt,e)
waflib.Errors.WafError: Could not install the file 'C:\\dev\\defold\\tmp\\dynamo_home\\lib\\python\\gamesys\\__init__.py'


[exec] python C:\dev\defold\tmp\dynamo_home/ext/bin/waf --prefix=C:\dev\defold\tmp\dynamo_home distclean configure build install --platform=x86_64-win32
Error:
Traceback (most recent call last):
  File "C:\dev\defold\scripts\build.py", line 2539, in <module>
    f()
  File "C:\dev\defold\scripts\build.py", line 1233, in build_engine
    self._build_engine_lib(args, lib, target_platform)
  File "C:\dev\defold\scripts\build.py", line 1165, in _build_engine_lib
    run.env_command(self._form_env(), args + plf_args + self.waf_options + skip_build_tests, cwd = cwd)
  File "C:\dev\defold\build_tools\run.py", line 98, in env_command
    return _exec_command(args, shell = False, stdout = None, env = env, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\defold\build_tools\run.py", line 75, in _exec_command
    raise e
run.ExecException: 1
```

**Workaround (OPTIONAL):**

Wait for ~10m and try again. It's also possible to kill any file locks, delete dynamo_home, and try again.

**Screenshots (OPTIONAL):**

These are the locked files:

![defold-vctip-lock](https://github.com/user-attachments/assets/5c799687-0c34-421d-b5a0-4377e0f797d6)

**Additional context (OPTIONAL):**

I'm running Extender with Docker locally as I'm building the engine. This has worked without issue.

**Comment by JCash** [comment]
It's likely a build race condition, not being correctly setup in one of the wscripts.

**Comment by AGulev** [comment]
This issue is outdated and we can't really fix it, since many changes have been made in the build system and the error log is now outdated, so we cannot reproduce the problem.

If you still experience this issue, please provide updated logs from a fresh branch and reopen the issue, or create a new one.

----

- The current proto Python packaging logic in `engine/ddf/src/waf_ddf.py:316` through `engine/ddf/src/waf_ddf.py:320` now tracks `install_py_proto_packages` and installs each package `__init__.py` only once per relative path.
- The current `gamesys` build still enables Python proto generation from multiple places (`engine/gamesys/src/gamesys/wscript:28`, `engine/gamesys/src/gamesys/wscript:43`, `engine/gamesys/src/gamesys/wscript:64`), which matches the original scenario where multiple install tasks could target the same `lib/python/gamesys/__init__.py` output.
- `git log` for `engine/ddf/src/waf_ddf.py` includes commit `9892435d8c4211f1a8cb9e09dabadb2772f1a280` with message `Fix  race between two install tasks targeting the same tmp/dynamo_home/lib/python/gamesys/__init__.py. (#11637)`.
- The diff for that commit shows the specific change: the build now deduplicates package install tasks before calling `install_files(...)`, which directly addresses the failure mode from issue #9726.

## Why it is possibly already fixed

The current code contains an explicit fix for the exact race described by the issue: multiple install tasks targeting `tmp/dynamo_home/lib/python/gamesys/__init__.py`. That race now appears guarded by `install_py_proto_packages`, so the duplicated install target that could non-deterministically fail on Windows should no longer be created. I did not find any newer code suggesting the same `gamesys/__init__.py` install race still exists in the current tree.
