### ISSUE TITLE
Issue that occurs when working with pycharm 

### ISSUE THREAD

**Issue by karol-wolonciej** [defold/defold#9793]
### Expected behaviour

When I have Defold open on right monitor (totally having 3) after some time after opening when I switch from middle or left monitor to Defold (clicking on editor for example) I get sometimes errors like this here. I think I didn't have them when working on laptop with no additional monitor. After this error there are further small problems with editor like non empty folders don't have arrow symbol signalizing they can be clicked in panels like "Assets" and Outline, sometimes after error I stop seeing "Properties" panel entirely and then I have to restart.

### Steps to reproduce
Having defold editor opened in one of three monitors and switching between programs on different monitors after some time give error when switching back to Defold.

<hr/>

<table>
<tr><td>Build time</td><td>2024-09-18T06:34:57.281998</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>9c546b9847c68d50a21a8c6c5d7357ba1d9f32d1</td></tr>
<tr><td>Defold engine sha</td><td>e4aaff11f49c941fde1dd93883cf69c6b8abebe4</td></tr>
<tr><td>Defold version</td><td>1.9.3</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"822cfbf3e0334fa684d971192ece665b"'>822cfbf3e0334fa684d971192ece665b</a></td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce RTX 4080/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 535.183.01</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>6.8.0-47-generic</td></tr>
<table>

**Comment by AGulev** [comment]
```
editor.defold_project$load_resource_node.invokeStatic.class clojure.lang.ExceptionInfo: Error when loading resource '/assets/modules/level_operations/createPencilSketch.lua~'
    at editor.defold_project$load_resource_node.invokeStatic(defold_project.clj:132)
    at editor.defold_project$node_load_info_tx_data.invokeStatic(defold_project.clj:240)
    at editor.defold_project$load_tx_data$iter__36585__36589$fn$fn.invoke(defold_project.clj:287)
    at editor.defold_project$load_tx_data$iter__36585__36589$fn.invoke(defold_project.clj:284)
    at clojure.lang.LazySeq.sval(LazySeq.java:42)
    at clojure.lang.LazySeq.seq(LazySeq.java:51)
    at clojure.lang.RT.seq(RT.java:531)
    at clojure.core$seq__5387.invokeStatic(core.clj:137)
    at clojure.core$dorun.invokeStatic(core.clj:3133)
    at clojure.core$doall.invokeStatic(core.clj:3148)
    at editor.defold_project$load_tx_data.invokeStatic(defold_project.clj:284)
    at editor.defold_project$load_nodes_into_graph_BANG_$fn.invoke(defold_project.clj:388)
    at editor.defold_project$load_nodes_into_graph_BANG_.invokeStatic(defold_project.clj:388)
    at editor.defold_project$load_nodes_BANG_.invokeStatic(defold_project.clj:417)
    at editor.defold_project$perform_resource_change_plan.invokeStatic(defold_project.clj:799)
    at editor.defold_project$handle_resource_changes.invokeStatic(defold_project.clj:915)
    at editor.defold_project.ProjectResourceListener.handle_changes(defold_project.clj:1128)
    at editor.workspace$resource_sync_BANG_$fn.invoke(workspace.clj:816)
    at editor.workspace$resource_sync_BANG_.invokeStatic(workspace.clj:810)
    at editor.disk$start_reload_job_BANG_$fn$fn.invoke(disk.clj:94)
    at clojure.lang.AFn.run(AFn.java:22)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:456)
    at java.security.AccessController.doPrivileged(AccessController.java:399)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:455)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
    at com.sun.glass.ui.gtk.GtkApplication._runLoop(GtkApplication.java)
    at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$10(GtkApplication.java:264)
    at java.lang.Thread.run(Thread.java:833)
editor.defold_project$load_resource_node.invokeStatic.class java.lang.AssertionError: Assert failed: (and (not= :folder (resource/source-type resource)) (resource/exists? resource))
    at editor.defold_project$load_resource_node.invokeStatic(defold_project.clj:105)
    at editor.defold_project$node_load_info_tx_data.invokeStatic(defold_project.clj:240)
    at editor.defold_project$load_tx_data$iter__36585__36589$fn$fn.invoke(defold_project.clj:287)
    at editor.defold_project$load_tx_data$iter__36585__36589$fn.invoke(defold_project.clj:284)
    at clojure.lang.LazySeq.sval(LazySeq.java:42)
    at clojure.lang.LazySeq.seq(LazySeq.java:51)
    at clojure.lang.RT.seq(RT.java:531)
    at clojure.core$seq__5387.invokeStatic(core.clj:137)
    at clojure.core$dorun.invokeStatic(core.clj:3133)
    at clojure.core$doall.invokeStatic(core.clj:3148)
    at editor.defold_project$load_tx_data.invokeStatic(defold_project.clj:284)
    at editor.defold_project$load_nodes_into_graph_BANG_$fn.invoke(defold_project.clj:388)
    at editor.defold_project$load_nodes_into_graph_BANG_.invokeStatic(defold_project.clj:388)
    at editor.defold_project$load_nodes_BANG_.invokeStatic(defold_project.clj:417)
    at editor.defold_project$perform_resource_change_plan.invokeStatic(defold_project.clj:799)
    at editor.defold_project$handle_resource_changes.invokeStatic(defold_project.clj:915)
    at editor.defold_project.ProjectResourceListener.handle_changes(defold_project.clj:1128)
    at editor.workspace$resource_sync_BANG_$fn.invoke(workspace.clj:816)
    at editor.workspace$resource_sync_BANG_.invokeStatic(workspace.clj:810)
    at editor.disk$start_reload_job_BANG_$fn$fn.invoke(disk.clj:94)
    at clojure.lang.AFn.run(AFn.java:22)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:456)
    at java.security.AccessController.doPrivileged(AccessController.java:399)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:455)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
    at com.sun.glass.ui.gtk.GtkApplication._runLoop(GtkApplication.java)
    at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$10(GtkApplication.java:264)
    at java.lang.Thread.run(Thread.java:833)
    ```

**Comment by karol-wolonciej** [comment]
Ok, thanks, I didn't see whole error, I will look next time more closely when something like this occurs.

**Comment by karol-wolonciej** [comment]
Unfortunately seems I still getting some errors when switching from external IDE to defold. My external ide is PyCharm 2024.2.1 (Community Edition). PyCharm with lua plugin is very effective due to its good navigations features like finding files by name or finding fragments of code.

**Comment by vlaaad** [comment]
What Defold editor version did you update to? Please share editor SHA (you can find it in `Help -> About`)

**Comment by karol-wolonciej** [comment]
editor SHA1: 2f84786d839dfe35f67eea803413597a9b459c6f
engine SHA1: 87b6907759f7b8dff830d54b2250b8d721bde291

defold version 1.9.5

**Comment by karol-wolonciej** [comment]
I think adding 

```
.idea/
*.pyc
__pycache__/
*.iml
```

to .gitignore seems to help and Defold is ignoring those problematic files

**Comment by vlaaad** [comment]
Hmm, the error you reported initially had this path: `/assets/modules/level_operations/createPencilSketch.lua~`. Your shared gitignore file does not cover the file that triggered the error...

**Comment by karol-wolonciej** [comment]
yes, I tried to what you said earlier - address unintended interaction between defold and pycharm but after some time I got this error again. Adding .idea and other pycharm specific files to .gitignore its a good idea but problem persist, so should I delete comment before?

**Comment by vlaaad** [comment]
Nah it's okay :) You could try turning of "safe write" feature in pycharm settings, see if it helps.

**Comment by AGulev** [comment]
duplicate of https://github.com/defold/defold/issues/10489
