### ISSUE TITLE
Assigning the "sprite" material to a model throws exceptions in the editor

### ISSUE THREAD

**Issue by Jhonnyg** [defold/defold#9859]
When I assign the sprite material from the builtins folder to a model, I get the following error in the terminal:

```
java.lang.NullPointerException: Cannot invoke "java.lang.Character.charValue()" because "x" is null
	at clojure.lang.RT.intCast(RT.java:1241)
	at editor.gl.texture$apply_params_BANG_.invokeStatic(texture.clj:81)
	at editor.gl.texture$apply_params_BANG_.invokePrim(texture.clj)
	at editor.gl.texture.TextureLifecycle.bind(texture.clj:120)
	at editor.gl$bind.invokeStatic(gl.clj:252)
	at editor.gl$bind.invoke(gl.clj:251)
	at editor.model_scene$render_mesh_opaque_impl.invokeStatic(model_scene.clj:233)
	at editor.model_scene$render_mesh_opaque_impl.invoke(model_scene.clj:196)
	at editor.model_scene$render_mesh_opaque.invokeStatic(model_scene.clj:245)
	at editor.model_scene$render_mesh_opaque.invoke(model_scene.clj:244)
	at editor.model_scene$render_mesh.invokeStatic(model_scene.clj:257)
	at editor.model_scene$render_mesh.invoke(model_scene.clj:251)
	at editor.scene$render_nodes.invokeStatic(scene.clj:217)
	.. rest of callstack
```

The reason this is happening is that the parameter values for :min-filter :mag-filter and :default-tex-params are nil, but we are trying to use it anyway. If I skip setting the texture filter value at (.glTexParameteri gl texture-target gl-param gl-value) when the value is nil, something renders (although it doesn't look correct!). 

This seems to be the case for 1.9.5, so it is not related to anything recent.

**Comment by AGulev** [comment]
looks similiar to :
https://github.com/defold/defold/issues/9596
https://github.com/defold/defold/issues/8673
and a couple of more issues
but maybe not related

**Comment by AGulev** [comment]
I can't reproduce it anymore 

<img width="2472" height="2044" alt="Image" src="https://github.com/user-attachments/assets/ca24ab83-dc92-42d7-b457-1184231f07f8" />

-----

## Status

Possibly outdated/fixed

## Evidence

- The built-in sprite material still declares `filter_min: FILTER_MODE_MIN_DEFAULT` and `filter_mag: FILTER_MODE_MAG_DEFAULT`, which matches the original bug trigger. See `engine/engine/content/builtins/materials/sprite.material:20`.
- Current editor code now normalizes material samplers before consumers see them: `produce-samplers` replaces `:filter-mode-min-default` / `:filter-mode-mag-default` with concrete values from `game.project`. See `editor/src/clj/editor/material.clj:236`.
- Material resources are wired to the project-level default sampler settings when loaded, so those default modes are available during sampler normalization. See `editor/src/clj/editor/material.clj:589`.
- Even if project defaults are absent, `filter-mode-min->gl` and `filter-mode-mag->gl` now fall back to OpenGL constants instead of returning `nil`, removing the direct cause of the `intCast` crash described in the issue. See `editor/src/clj/editor/material.clj:459`.
- The relevant history shows an explicit post-issue fix: commit `a5e253c202` (`Fixed models not rendering in the editor in some situations (#10580)`) includes `Editor: Inject project default texture filter modes into material samplers when requested`, which matches the failure mode from this issue.
- Model rendering still applies sampler params through `material/sampler->tex-params`, but with the current sampler normalization and fallback logic that path no longer appears able to produce the nil filter values reported in the stack trace. See `editor/src/clj/editor/model.clj:153`.

## Why this looks already fixed

The issue was opened against 1.9.5 in late 2024, but the current codebase contains a later editor fix specifically aimed at injecting project default texture filter modes into material samplers and at preventing nil filter values from propagating into OpenGL texture parameter application. That directly addresses the root cause described in the issue body: `FILTER_MODE_*_DEFAULT` samplers no longer depend on `default-tex-params` being present at the exact call site, because the material node resolves those defaults earlier and the GL conversion functions now have hard fallbacks. I did not find a dedicated regression test for assigning `sprite.material` to a model, so I am marking this as possibly outdated/fixed rather than definitively fixed.
