### ISSUE TITLE
Error loading GLTF model

### ISSUE THREAD

**Issue by schlista** [defold/defold#9879]
### Expected behaviour
No error and display the model.
### Actual behaviour
It gives the error and no model is displayed.  
### Steps to reproduce
Import this model.  I just exported it from blender so it may be a bad export, but still it shouldn't error out like this.
[craps_0.zip](https://github.com/user-attachments/files/17997785/craps_0.zip)

<hr/>

<table>
<tr><td>Build time</td><td>2024-12-02T13:30:54.865959</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>a646799c3eb767cc8ea8d3bbceee820839adc62c</td></tr>
<tr><td>Defold engine sha</td><td>d01194cf0fb576b516a1dca6af6f643e9e590051</td></tr>
<tr><td>Defold version</td><td>1.9.5</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"ac37021c2ce243d5abd14005de4e6c09"'>ac37021c2ce243d5abd14005de4e6c09</a></td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce RTX 3080 Ti/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 566.14</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 11</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by vlaaad** [comment]
```
clojure.lang.PersistentVector.arrayFor.class java.lang.IndexOutOfBoundsException: null
    at clojure.lang.PersistentVector.arrayFor(PersistentVector.java:158)
    at clojure.lang.PersistentVector.nth(PersistentVector.java:162)
    at clojure.lang.APersistentVector.invoke(APersistentVector.java:293)
    at clojure.core$mapv$fn.invoke(core.clj:6912)
    at clojure.core.protocols$fn.invokeStatic(protocols.clj:168)
    at clojure.core.protocols$fn.invoke(protocols.clj:124)
    at clojure.core.protocols$fn$G__8094__8108.invoke(protocols.clj:19)
    at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:31)
    at clojure.core.protocols$fn.invokeStatic(protocols.clj:75)
    at clojure.core.protocols$fn.invoke(protocols.clj:75)
    at clojure.core.protocols$fn$G__8068__8086.invoke(protocols.clj:13)
    at clojure.core$reduce.invokeStatic(core.clj:6828)
    at clojure.core$mapv.invokeStatic(core.clj:6903)
    at editor.model_scene$mesh__GT_renderable_data.invokeStatic(model_scene.clj:160)
    at editor.model_scene$make_renderable_mesh.invokeStatic(model_scene.clj:299)
    at editor.model_scene$make_renderable_model$fn.invoke(model_scene.clj:315)
    at clojure.core$mapv$fn.invoke(core.clj:6912)
    at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
    at clojure.core$reduce.invokeStatic(core.clj:6827)
    at clojure.core$mapv.invokeStatic(core.clj:6903)
    at editor.model_scene$make_renderable_model.invokeStatic(model_scene.clj:316)
    at editor.model_scene$make_renderable_mesh_set$fn.invoke(model_scene.clj:330)
    at clojure.core$mapv$fn.invoke(core.clj:6912)
    at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
    at clojure.core$reduce.invokeStatic(core.clj:6827)
    at clojure.core$mapv.invokeStatic(core.clj:6903)
    at editor.model_scene$make_renderable_mesh_set.invokeStatic(model_scene.clj:331)
    at editor.model_scene$fn.invokeStatic(model_scene.clj:347)
    at editor.model_scene$fn.invoke(model_scene.clj:343)
    at clojure.lang.AFn.applyToHelper(AFn.java:154)
    at clojure.lang.AFn.applyTo(AFn.java:144)
    at clojure.lang.AFunction$1.doInvoke(AFunction.java:31)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at clojure.lang.Var.invoke(Var.java:384)
    at editor.model_scene$ModelSceneNode$behavior$renderable_mesh_set$fn.invoke(model_scene.clj:436)
    at internal.node$trace_expr.invokeStatic(node.clj:46)
    at editor.model_scene$ModelSceneNode$behavior$renderable_mesh_set.invokeStatic(model_scene.clj:436)
    at editor.model_scene$ModelSceneNode$behavior$renderable_mesh_set.invoke(model_scene.clj:436)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:318)
    at editor.model_scene$ModelSceneNode$behavior$scene$fn.invoke(model_scene.clj:436)
    at internal.node$trace_expr.invokeStatic(node.clj:46)
    at editor.model_scene$ModelSceneNode$behavior$scene.invokeStatic(model_scene.clj:436)
    at editor.model_scene$ModelSceneNode$behavior$scene.invoke(model_scene.clj:436)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:318)
    at internal.node$pull_first_input_value.invokeStatic(node.clj:1226)
    at editor.model$ModelNode$behavior$scene$fn.invoke(model.clj:404)
    at internal.node$trace_expr.invokeStatic(node.clj:46)
    at editor.model$ModelNode$behavior$scene.invokeStatic(model.clj:404)
    at editor.model$ModelNode$behavior$scene.invoke(model.clj:404)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:318)
    at internal.node$pull_first_input_value.invokeStatic(node.clj:1226)
    at editor.game_object$EmbeddedComponent$behavior$scene$fn.invoke(game_object.clj:224)
    at internal.node$trace_expr.invokeStatic(node.clj:46)
    at editor.game_object$EmbeddedComponent$behavior$scene.invokeStatic(game_object.clj:224)
    at editor.game_object$EmbeddedComponent$behavior$scene.invoke(game_object.clj:224)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:318)
    at internal.node$pull_input_values$fn.invoke(node.clj:1242)
    at clojure.core$mapv$fn.invoke(core.clj:6912)
    at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
    at clojure.core$reduce.invokeStatic(core.clj:6827)
    at clojure.core$mapv.invokeStatic(core.clj:6903)
    at internal.node$pull_input_values.invokeStatic(node.clj:1243)
    at editor.game_object$GameObjectNode$behavior$scene$fn.invoke(game_object.clj:439)
    at internal.node$trace_expr.invokeStatic(node.clj:46)
    at editor.game_object$GameObjectNode$behavior$scene.invokeStatic(game_object.clj:439)
    at editor.game_object$GameObjectNode$behavior$scene.invoke(game_object.clj:439)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:318)
    at internal.node$pull_first_input_value.invokeStatic(node.clj:1226)
    at editor.collection$EmbeddedGOInstanceNode$behavior$scene$fn.invoke(collection.clj:247)
    at internal.node$trace_expr.invokeStatic(node.clj:46)
    at editor.collection$EmbeddedGOInstanceNode$behavior$scene.invokeStatic(collection.clj:247)
    at editor.collection$EmbeddedGOInstanceNode$behavior$scene.invoke(collection.clj:247)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:318)
    at internal.node$pull_input_values$fn.invoke(node.clj:1242)
    at clojure.core$mapv$fn.invoke(core.clj:6912)
    at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
    at clojure.core$reduce.invokeStatic(core.clj:6827)
    at clojure.core$mapv.invokeStatic(core.clj:6903)
    at internal.node$pull_input_values.invokeStatic(node.clj:1243)
    at editor.collection$CollectionNode$behavior$scene$fn.invoke(collection.clj:452)
    at internal.node$trace_expr.invokeStatic(node.clj:46)
    at editor.collection$CollectionNode$behavior$scene.invokeStatic(collection.clj:452)
    at editor.collection$CollectionNode$behavior$scene.invoke(collection.clj:452)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:318)
    at internal.node$pull_first_input_value.invokeStatic(node.clj:1226)
    at editor.scene$SceneView$behavior$scene_aabb$fn.invoke(scene.clj:834)
    at internal.node$trace_expr.invokeStatic(node.clj:46)
    at editor.scene$SceneView$behavior$scene_aabb.invokeStatic(scene.clj:834)
    at editor.scene$SceneView$behavior$scene_aabb.invoke(scene.clj:834)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:318)
    at internal.node$pull_first_input_value.invokeStatic(node.clj:1226)
    at editor.camera$CameraController$behavior$camera$fn.invoke(camera.clj:658)
    at internal.node$trace_expr.invokeStatic(node.clj:46)
    at editor.camera$CameraController$behavior$camera.invokeStatic(camera.clj:658)
    at editor.camera$CameraController$behavior$camera.invoke(camera.clj:658)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:318)
    at internal.node$pull_first_input_value.invokeStatic(node.clj:1226)
    at editor.scene$SceneView$behavior$scene_render_data$fn.invoke(scene.clj:834)
    at internal.node$trace_expr.invokeStatic(node.clj:46)
    at editor.scene$SceneView$behavior$scene_render_data.invokeStatic(scene.clj:834)
    at editor.scene$SceneView$behavior$scene_render_data.invoke(scene.clj:834)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:318)
    at editor.scene$SceneView$behavior$selected_aabb$fn.invoke(scene.clj:834)
    at internal.node$trace_expr.invokeStatic(node.clj:46)
    at editor.scene$SceneView$behavior$selected_aabb.invokeStatic(scene.clj:834)
    at editor.scene$SceneView$behavior$selected_aabb.invoke(scene.clj:834)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:318)
    at internal.node$node_value.invokeStatic(node.clj:476)
    at dynamo.graph$node_value.invokeStatic(graph.clj:913)
    at dynamo.graph$node_value.invoke(graph.clj:889)
    at dynamo.graph$node_value.invokeStatic(graph.clj:909)
    at editor.scene$frame_selection.invokeStatic(scene.clj:1023)
    at editor.scene$make_gl_pane_BANG_$fn$fn.invoke(scene.clj:1355)
    at editor.scene$make_gl_pane_BANG_$fn.invoke(scene.clj:1338)
    at editor.scene.proxy$com.defold.control.Region$ff19274a.layoutChildren
    at javafx.scene.Parent.layout(Parent.java:1208)
    at javafx.scene.Parent.layout(Parent.java:1215)
    at javafx.scene.Parent.layout(Parent.java:1215)
    at javafx.scene.Parent.layout(Parent.java:1215)
    at javafx.scene.Parent.layout(Parent.java:1215)
    at javafx.scene.Parent.layout(Parent.java:1215)
    at javafx.scene.Parent.layout(Parent.java:1215)
    at javafx.scene.Parent.layout(Parent.java:1215)
    at javafx.scene.Parent.layout(Parent.java:1215)
    at javafx.scene.Parent.layout(Parent.java:1215)
    at javafx.scene.Parent.layout(Parent.java:1215)
    at javafx.scene.Parent.layout(Parent.java:1215)
    at javafx.scene.Parent.layout(Parent.java:1215)
    at javafx.scene.Parent.layout(Parent.java:1215)
    at javafx.scene.Parent.layout(Parent.java:1215)
    at javafx.scene.Parent.layout(Parent.java:1215)
    at javafx.scene.Parent.layout(Parent.java:1215)
    at javafx.scene.Parent.layout(Parent.java:1215)
    at javafx.scene.Node.doLayoutPass(Node.java:2101)
    at javafx.scene.Node.doCSSLayoutSyncForSnapshot(Node.java:2108)
    at javafx.scene.Node$1.layoutNodeForPrinting(Node.java:563)
    at com.sun.javafx.scene.NodeHelper.layoutNodeForPrinting(NodeHelper.java:268)
    at editor.app_view$open_resource.invokeStatic(app_view.clj:2102)
    at editor.app_view$open_resource.invoke(app_view.clj:2039)
    at editor.app_view$open_resource.invokeStatic(app_view.clj:2041)
    at editor.app_view$fn$fnk67910_positional__67918.invoke(app_view.clj:2124)
    at editor.app_view$fn$fnk67910__67935$fn.invoke(app_view.clj:2120)
    at editor.app_view$fn$fnk67910__67935.invoke(app_view.clj:2120)
    at clojure.lang.AFn.applyToHelper(AFn.java:154)
    at clojure.lang.AFn.applyTo(AFn.java:144)
    at clojure.lang.AFunction$1.doInvoke(AFunction.java:31)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at editor.handler$invoke_fnk.invokeStatic(handler.clj:256)
    at editor.handler$run.invokeStatic(handler.clj:289)
    at editor.ui$execute_handler_ctx.invokeStatic(ui.clj:1254)
    at editor.ui$execute_command.invokeStatic(ui.clj:1262)
    at editor.ui$run_command.invokeStatic(ui.clj:1502)
    at editor.ui$bind_double_click_BANG_$reify.handle(ui.clj:1534)
    at com.sun.javafx.event.CompositeEventHandler$NormalEventFilterRecord.handleCapturingEvent(CompositeEventHandler.java:321)
    at com.sun.javafx.event.CompositeEventHandler.dispatchCapturingEvent(CompositeEventHandler.java:98)
    at com.sun.javafx.event.EventHandlerManager.dispatchCapturingEvent(EventHandlerManager.java:219)
    at com.sun.javafx.event.EventHandlerManager.dispatchCapturingEvent(EventHandlerManager.java:178)
    at com.sun.javafx.event.CompositeEventDispatcher.dispatchCapturingEvent(CompositeEventDispatcher.java:43)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:52)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
    at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
    at javafx.event.Event.fireEvent(Event.java:198)
    at javafx.scene.Scene$ClickGenerator.postProcess(Scene.java:3691)
    at javafx.scene.Scene$MouseHandler.process(Scene.java:3996)
    at javafx.scene.Scene.processMouseEvent(Scene.java:1893)
    at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2711)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:411)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:301)
    at java.security.AccessController.doPrivileged(AccessController.java:399)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:450)
    at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:430)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:449)
    at com.sun.glass.ui.View.handleMouseEvent(View.java:551)
    at com.sun.glass.ui.View.notifyMouse(View.java:937)
    at com.sun.glass.ui.win.WinApplication._runLoop(WinApplication.java)
    at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:184)
    at java.lang.Thread.run(Thread.java:833)
```

**Comment by JCash** [comment]
Minimal repro:
[issue-9879-repro.zip](https://github.com/user-attachments/files/18146963/issue-9879-repro.zip)
