### ISSUE TITLE
No sound on Android 14

### ISSUE THREAD

**Issue by hraytilakhealthcare** [defold/defold#9985]
_Is it a private platform, and a platform specific issue? (i.e. would it break your NDA?)<br>
Then please report your issue in the corresponding extension repository!_

**Describe the bug (REQUIRED)**
On Android 14, no sound is played when calling `sound.play(…)`

**To Reproduce (REQUIRED)**
1. Create a `sound` on the game object
2. Call `sound.play`
3. Hear no sound

**Expected behavior (REQUIRED)**
1. Create a `sound` on the game object
2. Call `sound.play`
3. Hear sound

**Defold version (REQUIRED):**
  - Version `1.9.6` editor `83536c65275c04366b704b2fd3f3d681c88b8267`, engine `11d2cd3a9be17b2fc5a2cb5cea59bbfb4af1ca96`.

**Platforms (REQUIRED):**
 - Platforms: Android
 - OS: `14`

**Minimal repro case project (OPTIONAL):**
[sfx_android_test.zip](https://github.com/user-attachments/files/18273668/sfx_android_test.zip)

**Logs (OPTIONAL):**

I noticed the following log when running the game on Android 14.

```log
defold.sound  E  App is missing the READ_PHONE_STATE permission. Audio will continue while phone call is active.
                         E  An exception occurred while retrieving system services
                         E  java.lang.SecurityException: getCallState: Neither user 10302 nor current process has android.permission.READ_PHONE
                            _STATE.
                         E      at android.os.Parcel.createExceptionOrNull(Parcel.java:3057)
                         E      at android.os.Parcel.createException(Parcel.java:3041)
                         E      at android.os.Parcel.readException(Parcel.java:3024)
                         E      at android.os.Parcel.readException(Parcel.java:2966)
                         E      at com.android.internal.telecom.ITelecomService$Stub$Proxy.getCallStateUsingPackage(ITelecomService.java:2114)
                         E      at android.telecom.TelecomManager.getCallState(TelecomManager.java:1883)
                         E      at android.telephony.TelephonyManager.getCallState(TelephonyManager.java:6188)
                         E      at com.defold.sound.SoundManager.<init>(SoundManager.java:75)
                         E  Caused by: android.os.RemoteException: Remote stack trace:
                         E      at android.app.ContextImpl.enforce(ContextImpl.java:2332)
                         E      at android.app.ContextImpl.enforceCallingOrSelfPermission(ContextImpl.java:2360)
                         E      at android.content.ContextWrapper.enforceCallingOrSelfPermission(ContextWrapper.java:982)
                         E      at com.android.server.telecom.TelecomServiceImpl.canReadPhoneState(TelecomServiceImpl.java:2895)
                         E      at com.android.server.telecom.TelecomServiceImpl.-$$Nest$mcanReadPhoneState(TelecomServiceImpl.java:0)
```

**Additional context (OPTIONAL):**
I had this issue on an Android `14`  device. I tried on an Android `13` and had no issue. I don't have that many devices lying around to test but I'll try to help as much as I can.

**Comment by ekharkunov** [comment]
Hello @hraytilakhealthcare !
I've looked into issue and tried to reproduce locally. I've tried run project on Samsung Galaxy S24(Android 15) and on Pixel 3A Emulator (Android 14). I used Defold 1.10.1 (but I think it doesn't matter). In both case sound played when I touched the screen.
Can you provide a bit more information about:
* what is the phone model
* full log from logcat without any filters
* what ABI phone supportes (armv7a + arm64?)

**Comment by britzl** [comment]
@hraytilakhealthcare I'm closing this issue for now. Please reopen the issue if you are able to provide the requested info.
